sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/Merchant_Pop_Up_Response__c.object-meta.xml
<CustomObject>
    <description>LEM-1979: Object to capture the Pop-Up responses of the Merchant before filling out Nintex based Use Case forms.</description>
    <label>Franchise Form Request</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Merchant Pop-Up Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Franchise Form Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>LEM-3214: It represents the approval status of the Nintex URL.</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Business_Account_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Account_Record_Type_Id__c</fullName>
    <description>LEM-2133: Used for Nintex to get the business account record type id</description>
    <label>Business Account Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Check_COO_Exception_Email_List_Updated__c.field-meta.xml
<CustomField>
    <fullName>Check_COO_Exception_Email_List_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-5305: It used to update the latest COO exception email list.</description>
    <label>Check COO Exception Email List Updated</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Mx_Corporate_Account__c.field-meta.xml
<CustomField>
    <fullName>Mx_Corporate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1979: Merchant Corporate Account.</description>
    <label>Mx Corporate Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Corporate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Merchant Pop-Up Responses</relationshipLabel>
    <relationshipName>Merchant_Pop_Up_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Payment_Account_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account_Record_Type_Id__c</fullName>
    <description>LEM-2133: Used for Nintex to get the payment account record type id</description>
    <label>Payment Account Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Select_the_Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Select_the_Franchise_Type__c</fullName>
    <description>LEM-2297: Captures franchise type</description>
    <label>Select the Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrated Franchise</fullName>
            </value>
            <value>
                <fullName>Drive Form - Franchise</fullName>
            </value>
            <value>
                <fullName>Drive - Amendment</fullName>
            </value>
            <value>
                <fullName>Withholding Opt-out</fullName>
            </value>
            <value>
                <fullName>Drive Amendment</fullName>
                <isActive>false</isActive>
                <label>Drive Amendment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Pop_Up_Response__c/fields/Store_Account_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Account_Record_Type_Id__c</fullName>
    <description>LEM-2133: Used for Nintex to get the store account record type id</description>
    <label>Store Account Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Payment_Account__c/recordTypes/Payments.recordType-meta.xml
<RecordType>
    <fullName>Payments</fullName>
    <active>true</active>
    <label>Payments</label>
</RecordType>

sfdx-source/force-app/tests/classes/unit/domains/MerchantPopUpResponsesTest.cls
/**
 * @author Deloitte
 * @date 20/08/2022
 * @description This class is used to test MerchantPopUpResponses
 */
@isTest(seeAllData=false)
private class MerchantPopUpResponsesTest {
    private static final String APPROVED = 'Approved';
    private static final String CONSTRUCTOR_ASSERT_MESSAGE = 'Unexpected result: The objects are matching';
    private static final String WITHHOLDING_OPT_OUT = System.Label.FranchiseType_Withholding_Opt_out;
    private static final String PENDING = 'Pending';
    /**
     * @description To test class instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenRun() {
        List<Merchant_Pop_Up_Response__c> responseList = new List<Merchant_Pop_Up_Response__c>();
        MerchantPopUpResponses.newInstance(responseList);
        MerchantPopUpResponses responsesObject = new MerchantPopUpResponses(responseList);
        MerchantPopUpResponses.Constructor constructorObject = new MerchantPopUpResponses.Constructor();
        constructorObject.construct(responseList);
        System.assertNotEquals(
            MerchantPopUpResponses.newInstance(responseList),
            responsesObject,
            CONSTRUCTOR_ASSERT_MESSAGE
        );
    }

    /**
     * @description This method is used to test if record type Id is getting stamped on Merchant Pop Up Response.
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenMerchantPopUpResponseGetInsertedThenStampRecordTypeId() {
        Id storeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Store')
            .getRecordTypeId();
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Id paymentsRecordTypeId = Schema.SObjectType.Payment_Account__c.getRecordTypeInfosByDeveloperName()
            .get('Payments')
            .getRecordTypeId();

        Merchant_Pop_Up_Response__c response = new Merchant_Pop_Up_Response__c(
            Id = fflib_IDGenerator.generate(Merchant_Pop_Up_Response__c.SObjectType)
        );

        MerchantPopUpResponses.newInstance(new List<Merchant_Pop_Up_Response__c>{ response })
            .updateRecordTypeIdsOnMerchantResponse();
        System.assertEquals(
            response.Business_Account_Record_Type_Id__c,
            businessRecordTypeId,
            'Business record type id is not matching'
        );
        System.assertEquals(
            response.Store_Account_Record_Type_Id__c,
            storeRecordTypeId,
            'Store record type id is not matching'
        );
        System.assertEquals(
            response.Payment_Account_Record_Type_Id__c,
            paymentsRecordTypeId,
            'Payment record type id is not matching '
        );
    }

    /**
     * @description This method is used to test if the latest coo exception mail list updated in franchise request records.
     */
    @isTest
    private static void testWhenCheckCOOExceptionEmailListUpdatedFieldToTrueThenUpdateLatestEmails() {
        Merchant_Pop_Up_Response__c response = new Merchant_Pop_Up_Response__c(
            Id = fflib_IDGenerator.generate(Merchant_Pop_Up_Response__c.SObjectType),
            Check_COO_Exception_Email_List_Updated__c = true
        );

        MerchantPopUpResponses.newInstance(new List<Merchant_Pop_Up_Response__c>{ response })
            .updateLatestCOOExceptionEmailListOnMerchantResponse();
        System.assertEquals(
            response.Check_COO_Exception_Email_List_Updated__c,
            false,
            'Unexpected Error: This value should be false'
        );
    }

    /**
     * @description It is used to validate that update to "Withholding Opt-out Expiry Date" field
     * on corporate account is initiated based on the passed approved franchise form requests.
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenApprovedWithholdingOptOutFranchiseFormsReceivedThenUpdateToStampWithholdingOptOutExpiryDateOnAccountInitiated() {
        Id franchiseFormRequestId = Fake.generateId(Merchant_Pop_Up_Response__c.class);
        Id corporateAccountId = Fake.generateId(Account.class);
        Merchant_Pop_Up_Response__c[] newFranchiseRequests = new List<Merchant_Pop_Up_Response__c>{
            new Merchant_Pop_Up_Response__c(
                Id = franchiseFormRequestId,
                Approval_Status__c = APPROVED,
                Mx_Corporate_Account__c = corporateAccountId,
                Select_the_Franchise_Type__c = WITHHOLDING_OPT_OUT
            )
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);

        IMerchantPopUpResponses merchantPopUpResponsesInstance = MerchantPopUpResponses.newInstance(
            newFranchiseRequests
        );
        merchantPopUpResponsesInstance.setWithholdingExpiryDateOnCorporateAccountsByEligibleFranchisFormRequests();
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description It is used to validate that update to "Withholding Opt-out Expiry Date" field on
     * corporate account is not initiated based on the passed pending franchise form requests.
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenPendingIntegratedFranchiseFormsReceivedThenUpdateToStampWithholdingOptOutExpiryDateOnAccountNotInitiated() {
        Id franchiseFormRequestId = Fake.generateId(Merchant_Pop_Up_Response__c.class);
        Id corporateAccountId = Fake.generateId(Account.class);
        Merchant_Pop_Up_Response__c[] newFranchiseRequests = new List<Merchant_Pop_Up_Response__c>{
            new Merchant_Pop_Up_Response__c(
                Id = franchiseFormRequestId,
                Approval_Status__c = PENDING,
                Mx_Corporate_Account__c = corporateAccountId,
                Select_the_Franchise_Type__c = WITHHOLDING_OPT_OUT
            )
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);

        IMerchantPopUpResponses merchantPopUpResponsesInstance = MerchantPopUpResponses.newInstance(
            newFranchiseRequests
        );
        merchantPopUpResponsesInstance.setWithholdingExpiryDateOnCorporateAccountsByEligibleFranchisFormRequests();
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 0)).commitWork();
    }
}