sfdx-source/force-app/main/default/objects/MX_Order__c/MX_Order__c.object-meta.xml
<CustomObject>
    <description>LEM-13509: Custom Order object for Vendor Integration</description>
    <label>Merchant Order</label>
    <nameField>
        <displayFormat>MX{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-13509: It is used to store the account associated to the current order.</description>
    <inlineHelpText>It is used to store the account associated to the current order.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MX_Order_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Order_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Status_Description__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13509: It is used to store the escalation/block reasons for executing the Order.</description>
    <label>Order Status Description</label>
    <length>103725</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13509: Merchant Order Status</description>
    <inlineHelpText>Merchant Order Status</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mx_Order_Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-13509: Select Type of order</description>
    <inlineHelpText>Select Type of order</inlineHelpText>
    <label>Type of Mx Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Type_Of_Request__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Request__c</fullName>
    <description>LEM-13509: It is used to store the type of tablet request.</description>
    <label>Type of Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net-New</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <description>LEM-13509: It is used to store the Vendor details for the Order.</description>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Denali</fullName>
            </value>
            <value>
                <fullName>Social Mobile</fullName>
            </value>
            <value>
                <fullName>OCUS</fullName>
            </value>
            <value>
                <fullName>Snappr</fullName>
            </value>
            <value>
                <fullName>Overture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Vendor_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Order_ID__c</fullName>
    <description>LEM-13509: It is used to store the unique  identifier for the Order.</description>
    <externalId>true</externalId>
    <label>Vendor Order ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Work_Order_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Sub_Type__c</fullName>
    <formula>TEXT(Work_Order__r.Sub_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Order Sub Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Mx_Order_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Order Created</fullName>
    </customValue>
    <customValue>
        <fullName>Shipped</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Sender</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <customValue>
        <fullName>Unsuccessful Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <description>LEM-13509 : Merchant Order Status</description>
    <masterLabel>Merchant Order Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/domains/MerchantOrdersTest.cls
/**
 * @author Deloitte
 * @date 06/20/2024
 * @description Test class for MerchantOrders class.
 */
@isTest(SeeAllData=false)
private class MerchantOrdersTest {
    private static final String FIELD_UPDATE_ASSERT_MESSAGE = 'Unexpected result: Field is not updated with expected value';
    private static final String MOCK_ORDER_STATUS_DESCRIPTION = 'MerchantOrdersTest Status Description';
    private static final String MOCK_VENDOR_ORDER_ID = 'MerchantOrdersTest0101';
    private static final String MX_ORDER_TYPE_TABLET = 'Tablet';
    private static final String MX_ORDER_NAME = 'MX-0001';
    private static final String MX_ORDER_VENDOR_DENALI = 'Denali';
    private static final String MX_ORDER_VENDOR_SOCIAL_MOBILE = 'Social Mobile';
    private static final String MX_ORDER_TYPE_OF_REQUEST = 'Return';
    private static final String MX_ORDER_STATUS_NOT_APPLICABLE = 'Not Applicable';
    private static final String MX_ORDER_TYPE_OF_REQUEST_REPLACEMENT = 'Replacement';
    private static final String STATUS_UPDATE_ASSERT_MESSAGE = 'Unexpected result: Status is not correct';
    private static final String WORK_STEP_NAME_DELIVER_RETURN_LABEL = 'Deliver Return Label';
    private static final String WORK_STEP_STATUS_COMPLETE = 'Complete';
    private static final String WORK_STEP_STATUS_DRAFT = 'Draft';

    /**
     * @description To test when the Mx Order vendor is Denali and the request type is Return
     * then the status should be updatd to Not Applicable.
     */
    @isTest
    private static void testWhenMxOrderVendorDenaliAndReturnRequestThenSetStatusNotApplicable() {
        Id mxOrderId = fflib_IDGenerator.generate(MX_Order__c.SObjectType);
        Id storeAccountId = fflib_IDGenerator.generate(Account.SObjectType);
        MX_Order__c mockMxOrder = (Mx_Order__c) new Fake(Mx_Order__c.class)
            .setField(MX_Order__c.Id, mxOrderId)
            .setField(MX_Order__c.Account__c, storeAccountId)
            .setField(MX_Order__c.Type__c, MX_ORDER_TYPE_TABLET)
            .setField(MX_Order__c.Name, MX_ORDER_NAME)
            .setField(MX_Order__c.Vendor__c, MX_ORDER_VENDOR_DENALI)
            .setField(MX_Order__c.Type_Of_Request__c, MX_ORDER_TYPE_OF_REQUEST)
            .setField(MX_Order__c.Work_Order_Sub_Type__c, MX_ORDER_TYPE_OF_REQUEST_REPLACEMENT)
            .toSObject();
        IMerchantOrders mxOrdersInstance = MerchantOrders.newInstance(
            new List<MX_Order__c>{ mockMxOrder }
        );
        mxOrdersInstance.updateMerchantOrderStatus(new List<MX_Order__c>{ mockMxOrder });
        system.assertEquals(
            MX_ORDER_STATUS_NOT_APPLICABLE,
            mockMxOrder.Status__c,
            STATUS_UPDATE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test when the Mx Order vendor is Social Mobile and the request type is Return
     * then the status should not be updatd to Not Applicable.
     */
    @isTest
    private static void testWhenMxOrderVendorSocialMobileAndReturnRequestThenDoNotSetStatusNotApplicable() {
        Id mxOrderId = fflib_IDGenerator.generate(MX_Order__c.SObjectType);
        Id storeAccountId = fflib_IDGenerator.generate(Account.SObjectType);
        MX_Order__c mockMxOrder = (Mx_Order__c) new Fake(Mx_Order__c.class)
            .setField(MX_Order__c.Id, mxOrderId)
            .setField(MX_Order__c.Account__c, storeAccountId)
            .setField(MX_Order__c.Type__c, MX_ORDER_TYPE_TABLET)
            .setField(MX_Order__c.Name, MX_ORDER_NAME)
            .setField(MX_Order__c.Vendor__c, MX_ORDER_VENDOR_SOCIAL_MOBILE)
            .setField(MX_Order__c.Type_Of_Request__c, MX_ORDER_TYPE_OF_REQUEST)
            .toSObject();
        IMerchantOrders mxOrdersInstance = MerchantOrders.newInstance(
            new List<MX_Order__c>{ mockMxOrder }
        );
        mxOrdersInstance.updateMerchantOrderStatus(new List<MX_Order__c>{ mockMxOrder });
        system.assertNotEquals(
            MX_ORDER_STATUS_NOT_APPLICABLE,
            mockMxOrder.Status__c,
            STATUS_UPDATE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test when the Mx Order Vendor is changed then update Mx Order fields.
     */
    @isTest
    private static void testWhenMxOrderVendorChangedThenUpdateMxOrderFields() {
        Id mxOrderId = fflib_IDGenerator.generate(MX_Order__c.SObjectType);
        Id storeAccountId = fflib_IDGenerator.generate(Account.SObjectType);
        Fake mockMxOrderFakeInstance = new Fake(Mx_Order__c.class)
            .setField(MX_Order__c.Id, mxOrderId)
            .setField(MX_Order__c.Account__c, storeAccountId)
            .setField(MX_Order__c.Name, MX_ORDER_NAME)
            .setField(MX_Order__c.Order_Status_Description__c, MOCK_ORDER_STATUS_DESCRIPTION)
            .setField(MX_Order__c.Status__c, MX_ORDER_STATUS_NOT_APPLICABLE)
            .setField(MX_Order__c.Type__c, MX_ORDER_TYPE_TABLET)
            .setField(MX_Order__c.Type_Of_Request__c, MX_ORDER_TYPE_OF_REQUEST)
            .setField(MX_Order__c.Vendor__c, MX_ORDER_VENDOR_SOCIAL_MOBILE)
            .setField(MX_Order__c.Vendor_Order_ID__c, MOCK_VENDOR_ORDER_ID);

        MX_Order__c mockMxOrder = (Mx_Order__c) mockMxOrderFakeInstance.toSObject();
        IMerchantOrders mxOrdersInstance = MerchantOrders.newInstance(
            new List<MX_Order__c>{ mockMxOrder }
        );
        mxOrdersInstance.resetMerchantOrdersOnVendorChange(new List<MX_Order__c>{ mockMxOrder });
        System.assertEquals(
            WORK_STEP_STATUS_DRAFT,
            mockMxOrder.Status__c,
            STATUS_UPDATE_ASSERT_MESSAGE
        );
        System.assertEquals(
            '',
            mockMxOrder.Order_Status_Description__c,
            FIELD_UPDATE_ASSERT_MESSAGE
        );
        System.assertEquals('', mockMxOrder.Vendor_Order_ID__c, FIELD_UPDATE_ASSERT_MESSAGE);
    }
}