sfdx-source/force-app/main/default/objects/Mx_Order_Product_Bundle__c/Mx_Order_Product_Bundle__c.object-meta.xml
<CustomObject>
    <description>LEM-14053: It is used to store all valid product bundles for Merchant Service Orders.</description>
    <label>Mx Order Product Bundle</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mx Order Product Bundles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Order_Product_Option__c/Mx_Order_Product_Option__c.object-meta.xml
<CustomObject>
    <description>LEM-14053: It is used to store options for all valid product bundles for Merchant Service Orders.</description>
    <label>Mx Order Product Option</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Order Product Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Order_Product_Option__c/fields/Assigned_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Vendor__c</fullName>
    <description>LEM-14053: It is used to store the possible vendors.</description>
    <label>Assigned Vendor</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Denali</fullName>
            </value>
            <value>
                <fullName>Social Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Order_Product_Option__c/fields/Mx_Order_Product_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Mx_Order_Product_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14053: It is used to map the Product bundle.</description>
    <label>Mx Order Product Bundle</label>
    <referenceTo>Mx_Order_Product_Bundle__c</referenceTo>
    <relationshipLabel>Mx Order Product Options</relationshipLabel>
    <relationshipName>Mx_Order_Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Order_Product_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14053: It is used to map the associated Product.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mx Order Product Options</relationshipLabel>
    <relationshipName>Mx_Order_Product_Option</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Order_Product_Option__c/fields/Product_Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Option_Name__c</fullName>
    <description>LEM-14053: It is used to store the Product Option name.</description>
    <label>Product Option Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product2/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>LEM-14053: It is used to store the language preference of the product bundle.</description>
    <label>Language</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/ProductOptionsSelector.cls
/**
 * @author Deloitte
 * @date 04/25/2024
 * @description Selector Class for Product Options
 */
public inherited sharing class ProductOptionsSelector extends fflib_SObjectSelector implements IProductOptionsSelector {
    /**
     * @description Default Constructor for the Product Options Selector Class
     * @return IProductOptionsSelector - Interface of IProductOptionsSelector
     */
    public static IProductOptionsSelector newInstance() {
        return (IProductOptionsSelector) Application.Selector.newInstance(
            Mx_Order_Product_Option__c.SObjectType
        );
    }

    /**
     * @description This method is used for getting fields on Product Options Object
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Mx_Order_Product_Option__c.Id,
            Mx_Order_Product_Option__c.Name,
            Mx_Order_Product_Option__c.Product__c,
            Mx_Order_Product_Option__c.Product_Option_Name__c,
            Mx_Order_Product_Option__c.Mx_Order_Product_Bundle__c
        };
    }

    /**
     * @description This method is used for getting Object Type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Mx_Order_Product_Option__c.SObjectType;
    }

    /**
     * @description This method is used for getting Product Options based on Id
     * @param setIds
     * @return list of Insight records
     */
    public List<Mx_Order_Product_Option__c> selectById(Set<Id> setIds) {
        return (List<Mx_Order_Product_Option__c>) selectSObjectsById(setIds);
    }

    /**
     * @description Query for all Product Options records present in the system
     * @param productBundleIds
     * @return List<Mx_Order_Product_Option__c>
     */
    public List<Mx_Order_Product_Option__c> selectProductOptionsByProductBundle(
        Set<Id> productBundleIds
    ) {
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Name');
        query.selectField('Product_Option_Name__c');
        query.selectField('Product__c');
        query.selectField('Product__r.Name');
        query.selectField('Mx_Order_Product_Bundle__c');
        query.selectField('Product__r.Family');
        query.selectField('Product__r.CurrencyIsoCode');
        query.selectField('Product__r.Language__c');
        query.selectfield('Assigned_Vendor__c');
        query.setCondition('Mx_Order_Product_Bundle__c IN :productBundleIds');
        return (List<Mx_Order_Product_Option__c>) Database.query(query.toSOQL());
    }
}