sfdx-source/force-app/main/default/objects/Interface_Transaction__c/Interface_Transaction__c.object-meta.xml
<CustomObject>
    <description>LEM-92: This Object is created for Integration retry mechanism</description>
    <label>Interface Transaction</label>
    <nameField>
        <displayFormat>IT-{00}</displayFormat>
        <label>Interface Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interface Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Interface_Transaction__c/fields/Interface_Transaction_Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Interface_Transaction_Configuration_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It stores the &apos;Interface Transaction Configuration&apos; custom metadata record name which contains the configurations specific to interface transaction record.</description>
    <label>Interface Transaction Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13506: It stores the record id of related record the payload/Interface Transaction corresponds to.</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-92: This field is to store the status of the re-executed class</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction_Configuration__mdt/Interface_Transaction_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>LEM-13778: It stores the configuration details related to each internal processes utilising interface transaction records.</description>
    <label>Interface Transaction Configuration</label>
    <pluralLabel>Interface Transaction Configurations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Interface_Transaction_Configuration__mdt/fields/Enable_Retry__c.field-meta.xml
<CustomField>
    <fullName>Enable_Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-13778: It indicates whether retry is enabled for failed interface transactions related to the current process.</description>
    <label>Enable Retry</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction_Configuration__mdt/fields/Interface_Transaction_Name__c.field-meta.xml
<CustomField>
    <fullName>Interface_Transaction_Name__c</fullName>
    <description>LEM-13778: It stores the transaction process name used in Interface Transaction record for identifying related configuration details.</description>
    <label>Interface Transaction Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction_Configuration__mdt/fields/Service_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Class_Name__c</fullName>
    <description>LEM-13378: It stores the service class name where the custom logic exists.</description>
    <label>Service Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/MX_Order__c.object-meta.xml
<CustomObject>
    <description>LEM-13509: Custom Order object for Vendor Integration</description>
    <label>Merchant Order</label>
    <nameField>
        <displayFormat>MX{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13509: Merchant Order Status</description>
    <inlineHelpText>Merchant Order Status</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mx_Order_Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Mx_Order_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Order Created</fullName>
    </customValue>
    <customValue>
        <fullName>Shipped</fullName>
    </customValue>
    <customValue>
        <fullName>Return to Sender</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <customValue>
        <fullName>Unsuccessful Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <description>LEM-13509 : Merchant Order Status</description>
    <masterLabel>Merchant Order Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/services/RetryableServiceBatch.cls
/**
 * @author Deloitte
 * @date 2/3/2022
 * @description Batch class for re-executing the failed Integration Classes
 */
public with sharing class RetryableServiceBatch implements System.Schedulable, Database.Batchable<SObject>, Database.AllowsCallouts {
    private static final String MX_ORDER_STATUS_INVALID = 'Invalid';
    private static final Set<String> MX_ORDER_STATUSES_INELIGIBLE_FOR_RETRY = new Set<String>{
        MX_ORDER_STATUS_INVALID
    };
    private static final String MX_ORDER_INTERFACE_TRANSACTION_CONFIG_TABLET = 'Tablet_Outbound_Integration';
    private static final String MX_ORDER_INTERFACE_TRANSACTION_CONFIG_PHOTOSHOOT = 'Photoshoot_Outbound_Integration';
    private static final Set<String> MX_ORDER_INTERFACE_TRANSACTION_CONFIG_NAMES = new Set<String>{
        MX_ORDER_INTERFACE_TRANSACTION_CONFIG_TABLET,
        MX_ORDER_INTERFACE_TRANSACTION_CONFIG_PHOTOSHOOT
    };
    Map<String, String> interfaceConfigNameToDetails;
    Map<Id, MX_Order__c> mxOrderIdToOrderStatus;
    Map<String, List<Interface_Transaction__c>> interfaceTransactionsForRetry;

    /**
     * @description Constructor to set interface name for batch retry.
     */
    public RetryableServiceBatch() {
        this.interfaceConfigNameToDetails = new Map<String, String>();
        this.interfaceTransactionsForRetry = new Map<String, List<Interface_Transaction__c>>();
        this.mxOrderIdToOrderStatus = new Map<Id, MX_Order__c>();
    }

    /**
     * @description Start method of Batch class
     * @param batchableContext - Database.BatchableContext
     * @return result- DML operation result
     */
    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        return new InterfaceTransactionSelector().queryLocatorReadyToRetry();
    }

    /**
     * @description Execute method to perform business logic
     * @param batchableContext - Database.BatchableContext
     * @param interfaceTransactions - Interface Transaction records
     */
    public void execute(
        Database.BatchableContext batchableContext,
        List<Interface_Transaction__c> interfaceTransactions
    ) {
        Set<Id> mxOrderIds = new Set<Id>();
        collectInterfaceTransactionConfigs();
        for (Interface_Transaction__c eachInterfaceTransactionRecord : interfaceTransactions) {
            if (
                eachInterfaceTransactionRecord.Interface_Transaction_Configuration_Name__c ==
                null ||
                !interfaceConfigNameToDetails.containsKey(
                    eachInterfaceTransactionRecord.Interface_Transaction_Configuration_Name__c
                )
            ) {
                continue;
            }
            if (
                MX_ORDER_INTERFACE_TRANSACTION_CONFIG_NAMES.contains(
                    eachInterfaceTransactionRecord.Interface_Transaction_Configuration_Name__c
                )
            ) {
                mxOrderIds.add(eachInterfaceTransactionRecord.Record_Id__c);
                continue;
            }
            collectInterfaceTransactionsByConfig(eachInterfaceTransactionRecord);
        }
        collectMxOrdersDetailsForRetry(mxOrderIds);
        MerchantOrdersService.retryPayloadGeneration(mxOrderIdToOrderStatus.values());
        for (
            Interface_Transaction__c eachInterfaceTransaction : InterfaceTransactionSelector.newInstance()
                .selectByOriginRecordIds(
                    (Set<String>) JSON.deserialize(JSON.serialize(mxOrderIds), Set<String>.class)
                )
        ) {
            collectInterfaceTransactionsByConfig(eachInterfaceTransaction);
        }
        for (String eachInterfaceTransactionsConfigName : interfaceTransactionsForRetry.keySet()) {
            retryService(
                interfaceTransactionsForRetry.get(eachInterfaceTransactionsConfigName),
                interfaceConfigNameToDetails.get(eachInterfaceTransactionsConfigName)
            );
        }
    }

    /**
     * @description schedulable method to execute batch class with size 1
     * @param schedulableContext - SchedulableContext
     */
    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(
            new RetryableServiceBatch(),
            Integer.valueof(System.Label.Retryable_Service_Batch_Size)
        );
    }

    /**
     * @description Finish method to perform logic after retry process completion.
     * @param batchableContext - Database.BatchableContext
     */
    @SuppressWarnings('PMD.EmptyStatementBlock')
    public void finish(Database.BatchableContext batchableContext) {
    }

    /**
     * @description It collects Interface Transaction configuration metadata records.
     */
    private void collectInterfaceTransactionConfigs() {
        for (
            Interface_Transaction_Configuration__mdt eachConfig : InterfaceTransactionConfigSelector.newInstance()
                .selectAllActiveInterfaceTransactionCongis()
        ) {
            if (eachConfig.Service_Class_Name__c != null && eachConfig.Enable_Retry__c) {
                interfaceConfigNameToDetails.put(
                    eachConfig.Interface_Transaction_Name__c,
                    eachConfig.Service_Class_Name__c
                );
            }
        }
    }

    /**
     * @description It collects Mx Order details related to Interface transactions for retry.
     * @param mxOrderIds
     */
    private void collectMxOrdersDetailsForRetry(Set<Id> mxOrderIds) {
        mxOrderIdToOrderStatus = new Map<Id, MX_Order__c>(
            MerchantOrdersSelector.newInstance().selectById(mxOrderIds)
        );
    }

    /**
     * @description It collects Mx Order details related to Interface transactions for retry.
     * @param interfaceTransactionDetails
     */
    private void collectInterfaceTransactionsByConfig(
        Interface_Transaction__c interfaceTransactionDetails
    ) {
        if (
            !interfaceTransactionsForRetry.containsKey(
                interfaceTransactionDetails.Interface_Transaction_Configuration_Name__c
            )
        ) {
            interfaceTransactionsForRetry.put(
                interfaceTransactionDetails.Interface_Transaction_Configuration_Name__c,
                new List<Interface_Transaction__c>()
            );
        }
        interfaceTransactionsForRetry.get(
                interfaceTransactionDetails.Interface_Transaction_Configuration_Name__c
            )
            .add(interfaceTransactionDetails);
    }

    /**
     * @description It passes the interface transaction records to spefied service class for retry.
     * @param interfaceTransactions
     * @param serviceClassName
     */
    private void retryService(
        List<Interface_Transaction__c> interfaceTransactions,
        String serviceClassName
    ) {
        //Filtering to remove interface transactions related to Mx Orders with 'Invalid' Status.
        Set<Interface_Transaction__c> filterInterfaceTransactions = new Set<Interface_Transaction__c>(
            interfaceTransactions
        );
        for (Interface_Transaction__c eachInterfaceTransaction : interfaceTransactions) {
            if (
                eachInterfaceTransaction.Record_Id__c != null &&
                mxOrderIdToOrderStatus.containsKey(eachInterfaceTransaction.Record_Id__c) &&
                MX_ORDER_STATUSES_INELIGIBLE_FOR_RETRY.contains(
                    mxOrderIdToOrderStatus.get(eachInterfaceTransaction.Record_Id__c).Status__c
                )
            ) {
                filterInterfaceTransactions.remove(eachInterfaceTransaction);
            }
        }
        try {
            IRetryableService retryClass = (IRetryableService) Application.SERVICE.newInstance(
                Type.forName(serviceClassName)
            );
            retryClass.retry(new List<Interface_Transaction__c>(filterInterfaceTransactions));
        } catch (Exception ex) {
            Logger.publish(LogEntry.newExceptionLog(ex, LogEntry.SeverityLevel.HIGH));
        }
    }
}