sfdx-source/force-app/main/default/objects/Interface_Transaction__c/Interface_Transaction__c.object-meta.xml
<CustomObject>
    <description>LEM-92: This Object is created for Integration retry mechanism</description>
    <label>Interface Transaction</label>
    <nameField>
        <displayFormat>IT-{00}</displayFormat>
        <label>Interface Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interface Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Interface_Transaction__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>LEM-92: This field is to capture the payload of the transaction</description>
    <label>Payload</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Interface_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-92: This field is to store the status of the re-executed class</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Onboarding_Link__c/Mx_Onboarding_Link__c.object-meta.xml
<CustomObject>
    <description>LEM-15116: It is used to store Mx onboarding links.</description>
    <label>Mx Onboarding Link</label>
    <nameField>
        <displayFormat>MOL-{0000}</displayFormat>
        <label>Mx Onboarding Link Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Onboarding Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Onboarding_Link__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15328: It stores the data required for processing.</description>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Onboarding_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15116: It stores status of Mx onboarding link.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/Onboarding_Activation__e.object-meta.xml
<CustomObject>
    <description>LEM-13303: It allows generic Platform Event schema and the trigger listener to act as dispatcher of the events for Merchant Services related functionality. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further processing.</description>
    <label>Onboarding &amp; Activation</label>
    <pluralLabel>Onboarding &amp; Activations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>LEM-13303: t stores the data required for processing by the service layer corresponding to the topic. The format may vary by use-case; it may store set of record ids or JSON string. The service layer will process the payload as needed.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-13303: It stores use-case for which event is fired. It is used for identifying service layer for further payload processing.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/MxOnboardingLinksServiceImpl.cls
/**
 * @author Deloitte
 * @date 26/06/2024
 * @description Service implementation class for Mx Onboarding Link related logic.
 */
public inherited sharing class MxOnboardingLinksServiceImpl implements IMxOnboardingLinksService {
    private static final String INITIATE_RELATED_OBJECTS_CREATION = 'INITIATE_RELATED_OBJECTS_CREATION';
    private static final String INTERFACE_TRANSACTION_STATUS_FAILURE = 'Failure';
    private static final String LOG_DOMAIN_MX_ONBOARDING_LINKS = 'Mx Onboarding Links';
    private static final String LOG_SERVICE_MX_ONBOARDING_LINKS_SERVICE = 'MxOnboardingLinksService';
    private enum EventTopics {
        EVENT_TOPIC_INITIATE_RELATED_OBJECTS_CREATION
    }
    private static final Map<String, EventTopics> EVENT_TOPIC_MAPPINGS = new Map<String, EventTopics>{
        INITIATE_RELATED_OBJECTS_CREATION => EventTopics.EVENT_TOPIC_INITIATE_RELATED_OBJECTS_CREATION
    };
    private enum ObjectTypes {
        MX_ONBOARDING_LINK,
        INTERFACE_TRANSACTION
    }
    private static final Map<Schema.SobjectType, ObjectTypes> SOBJECTTYPETOOBJECTTYPES = new Map<Schema.SobjectType, ObjectTypes>{
        Mx_Onboarding_Link__c.SObjectType => ObjectTypes.MX_ONBOARDING_LINK,
        Interface_Transaction__c.SObjectType => ObjectTypes.INTERFACE_TRANSACTION
    };

    Set<Id> interfaceTransactionIds;
    Set<Id> mxOnboardingLinkIds;
    fflib_ISObjectUnitOfWork uow;

    /**
     * @description default constructor
     */
    public MxOnboardingLinksServiceImpl() {
        this.interfaceTransactionIds = new Set<Id>();
        this.mxOnboardingLinkIds = new Set<Id>();
        this.uow = Application.UnitOfWork.newInstance();
    }

    /**
     * @description It is used to handle and route the published OnboardingActivationsEvents.
     * @param onboardingActivationsEvents List of platform events with payload.
     */
    public void handleOnboardingActivationsEvents(
        List<Onboarding_Activation__e> onboardingActivationsEvents
    ) {
        Set<Id> sObjectIds = new Set<Id>();
        Set<Id> recordIdsByPayload;
        for (Onboarding_Activation__e eachEvent : onboardingActivationsEvents) {
            switch on EVENT_TOPIC_MAPPINGS.get(eachEvent.Topic__c) {
                when EVENT_TOPIC_INITIATE_RELATED_OBJECTS_CREATION {
                    recordIdsByPayload = (Set<Id>) JSON.deserialize(
                        eachEvent.Payload__c,
                        Set<Id>.class
                    );
                    if (recordIdsByPayload == null) {
                        continue;
                    }
                    sObjectIds.addAll(recordIdsByPayload);
                }
            }
        }
        groupSobjectIdsBySObjectTypes(sObjectIds);
        try {
            MxOnboardingLinks.newInstance(new List<Mx_Onboarding_Link__c>{})
                .initiateStoreAgreementCreation(mxOnboardingLinkIds);
        } catch (Exception agreementCreationException) {
            updateInterfaceTransactionToFailure();
            createLogEntries(agreementCreationException);
        }
    }

    /**
     * @description It is used to create Log Entries.
     * @param agreementCreationException
     */
    public void createLogEntries(Exception agreementCreationException) {
        Set<String> recordIdsToLog = new Set<String>();
        recordIdsToLog.add(JSON.serialize(interfaceTransactionIds));
        recordIdsToLog.add(JSON.serialize(mxOnboardingLinkIds));
        Logger.publish(
            LogEntry.newExceptionLog(agreementCreationException, LogEntry.SeverityLevel.HIGH)
        );
        GenericLoggerService.publish(
            GenericLoggerService.createGenericLog(
                    LOG_SERVICE_MX_ONBOARDING_LINKS_SERVICE,
                    LOG_DOMAIN_MX_ONBOARDING_LINKS,
                    GenericLogEntry.SeverityLevel.HIGH
                )
                .logException(agreementCreationException)
                .logSFRecordId(recordIdsToLog)
        );
    }

    /**
     * @description It is used to group SObject Ids from Platform Event by SObject Types.
     * @param sObjectIds
     */
    private void groupSobjectIdsBySObjectTypes(Set<Id> sObjectIds) {
        for (Id eachId : sObjectIds) {
            Schema.SObjectType sobjectType = eachId.getSObjectType();
            switch on SOBJECTTYPETOOBJECTTYPES.get(sobjectType) {
                when MX_ONBOARDING_LINK {
                    mxOnboardingLinkIds.add(eachId);
                }
                when INTERFACE_TRANSACTION {
                    interfaceTransactionIds.add(eachId);
                }
            }
        }
    }

    /**
     * @description It is used to update Interface Transaction Status to Failure.
     */
    private void updateInterfaceTransactionToFailure() {
        for (Id eachInterfaceTransactionId : interfaceTransactionIds) {
            uow.registerDirty(
                new Interface_Transaction__c(
                    Id = eachInterfaceTransactionId,
                    Status__c = INTERFACE_TRANSACTION_STATUS_FAILURE
                )
            );
        }
        uow.commitWork();
    }
}