sfdx-source/force-app/main/default/objects/Work_Step_Status_Mapping__mdt/Work_Step_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1273: This configuration will be used in WorkStepsServiceImpl class for calculating the updated Status of Work Order and Work Plan on basis of Work Step Status.</description>
    <label>Work Step Status Mapping</label>
    <pluralLabel>Work Step Status Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Work_Step_Status_Mapping__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>LEM-1273: Indicates the operator which will be used for calculating Workorder/WorkPlan status.</description>
    <label>Operator</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Work_Step_Status_Mapping__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>LEM-1273: Indicates the sequence of the status for sorting the status mapping.</description>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Work_Step_Status_Mapping__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-1273: Indicates the status of sobject.</description>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Work_Step_Status_Mapping__mdt/fields/Status_To_Apply__c.field-meta.xml
<CustomField>
    <fullName>Status_To_Apply__c</fullName>
    <description>LEM-1273: Indicates the status value which will be used for calculating WorkOrder/WorkPlan new Status.</description>
    <label>Status To Apply</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/WorkStepStatusMappingsSelectorTest.cls
/**
 * @author Deloitte
 * @date 19/05/2022
 * @description Test class for WorkStepStatusMappingsSelector class.
 */
@isTest(seeAllData=false)
private class WorkStepStatusMappingsSelectorTest {
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: There is a mismatch in fields list.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: The object type must be Work Step Status Mapping Metadata.';
    private static final String METADATA_DEV_NAME = 'Complete';
    private static final String METADATA_MASTER_LABEL = 'Complete';
    private static final String METADATA_OPERATOR = 'equals';
    private static final Integer METADATA_SEQUENCE = 1;
    private static final String METADATA_STATUS_TO_APPLY = 'In Progress';
    private static final String METADATA_STATUS = 'Complete';

    /**
     * @description To test Work Step Status Mappings custom metadata fields.
     */
    @isTest
    private static void testWhenGetSObjectFieldListMethodCalledThenReturnFields() {
        List<Schema.SObjectField> sObjectFieldsMock = new List<Schema.SObjectField>{
            Work_Step_Status_Mapping__mdt.Sequence__c,
            Work_Step_Status_Mapping__mdt.Status__c,
            Work_Step_Status_Mapping__mdt.Operator__c,
            Work_Step_Status_Mapping__mdt.Status_To_Apply__c
        };
        Schema.SObjectType typeOfObject = WorkStepStatusMappingsSelector.newInstance()
            .SObjectType();
        List<Schema.SObjectField> sObjectFields = WorkStepStatusMappingsSelector.newInstance()
            .getSObjectFieldList();
        System.assertEquals(
            Work_Step_Status_Mapping__mdt.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            sObjectFieldsMock,
            sObjectFields,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }

    /**
     * @description To test Work Step Status Mappings custom metadata query.
     */
    @isTest
    private static void testWhenGetAllValuesMethodCalledThenReturnAllMetadataRecords() {
        List<Work_Step_Status_Mapping__mdt> statusMappings = WorkStepStatusMappingsSelector.newInstance()
            .getAllValues();
        System.assertEquals(
            !statusMappings.isEmpty(),
            true,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
    }
}