sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <description>LEM-6471 This field is used to track rate change request status.</description>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activation Initiated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Associated_stores_updated__c.field-meta.xml
<CustomField>
    <fullName>Associated_stores_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associated stores updated?</label>
    <description>LEM-6471 This field is used to track if associated stores are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Contract_Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Order_Products_Updated__c.field-meta.xml
<CustomField>
    <fullName>Order_Products_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Products Updated</label>
    <description>LEM-6471 This field is used to track if associated order products are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/S_O_Support_Request_Link__c.field-meta.xml
<CustomField>
    <fullName>S_O_Support_Request_Link__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>S&amp;O Support Request Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SO_Support_Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/triggerHandlers/RateChangeRequestsHandlerTest.cls
/**
 * @description This is test class for Rate Change Requests Trigger handler class
 * @author Deloitte
 * @date 13-09-2023
 */
@isTest(seeAllData=false)
public class RateChangeRequestsHandlerTest {
    private static final String APPROVED = 'Approved';
    private static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER = 'CREATE_ACTIVATION_ORDER_AND_PRODUCTS';
    private static final String METADATA_INSTANCE_NAME = 'Activation_Order_Payload_Chunk_Size';
    private static final String METADATA_VALUE = '3';
    private static final String NEW_RATE_CHANGE = 'New';
    private static final String READY_FOR_ACTIVATION = 'Ready for Activation';
    private static final Date TODAY_DATE = System.today();

    /**
     * @description This method is used to test Rate Change Request TriggerHandler
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheck() {
        List<Rate_Change_Request__c> rateChangeRequestList = new List<Rate_Change_Request__c>();
        RateChangeRequestsHandler rateChangeHandlerObject = new RateChangeRequestsHandler(
            rateChangeRequestList
        );
        RateChangeRequestsHandler.Constructor objConstructor = new RateChangeRequestsHandler.Constructor();
        objConstructor.construct(rateChangeRequestList);
        System.assertNotEquals(
            rateChangeHandlerObject,
            objConstructor.construct(rateChangeRequestList),
            'Unexpected result: both constructs are similar.'
        );
    }

    /**
     * @description To test method call on RateChangeRequest update
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenUpdateRateChangeRequestsThenCallCreateActivationOrders() {
        Id rateChangeReqId = Fake.generateId(Rate_Change_Request__c.class);
        Id contractId2 = Fake.generateId(Contract.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c[] oldRateChanges = new List<Rate_Change_Request__c>{
            new Rate_Change_Request__c(
                Id = rateChangeReqId,
                Contract__c = contractId2,
                Effective_Date__c = TODAY_DATE,
                S_O_Support_Request_Link__c = caseId,
                Activation_Status__c = NEW_RATE_CHANGE,
                Associated_stores_updated__c = true,
                Order_Products_Updated__c = true,
                Status__c = APPROVED
            )
        };

        Rate_Change_Request__c[] newRateChanges = new List<Rate_Change_Request__c>{
            new Rate_Change_Request__c(
                Id = rateChangeReqId,
                Contract__c = contractId2,
                Effective_Date__c = TODAY_DATE,
                S_O_Support_Request_Link__c = caseId,
                Activation_Status__c = READY_FOR_ACTIVATION,
                Associated_stores_updated__c = true,
                Order_Products_Updated__c = true,
                Status__c = APPROVED
            )
        };

        Set<Id> rateChangeRequestIds = new Set<Id>();
        rateChangeRequestIds.add(rateChangeReqId);

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IRateChangeRequestService rateChangeRequestsMock = (IRateChangeRequestService) mocks.mock(
            IRateChangeRequestService.class
        );
        IParentWorkOrdersCreationService parentWorkOrdersCreationServiceMock = (IParentWorkOrdersCreationService) mocks.mock(
            IParentWorkOrdersCreationService.class
        );
        IRateChangeRequestSelector rateChangeSelectorMock = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );
        Application.SERVICE.setMock(IRateChangeRequestService.class, rateChangeRequestsMock);
        Application.SERVICE.setMock(
            IParentWorkOrdersCreationService.class,
            parentWorkOrdersCreationServiceMock
        );
        mocks.startStubbing();
        mocks.when(rateChangeSelectorMock.sObjectType())
            .thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.when(
                rateChangeSelectorMock.selectRateChangeRequestById(new Set<Id>{ rateChangeReqId })
            )
            .thenReturn(newRateChanges);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(rateChangeSelectorMock);
        fflib_SObjectDomain.Test.Database.onUpdate(
            newRateChanges,
            new Map<Id, SObject>(oldRateChanges)
        );
        fflib_SObjectDomain.triggerHandler(RateChangeRequestsHandler.class);

        ((IRateChangeRequestService) mocks.verify(rateChangeRequestsMock, 1))
            .publishCreateActivationOrdersNotifierEvent(rateChangeRequestIds);
        ((IParentWorkOrdersCreationService) mocks.verify(parentWorkOrdersCreationServiceMock, 1))
            .createParentWorkOrdersByRateChangeRequest(newRateChanges);
    }
}