sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <description>LEM-6471 This field is used to track rate change request status.</description>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activation Initiated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Contract_Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/S_O_Support_Request_Link__c.field-meta.xml
<CustomField>
    <fullName>S_O_Support_Request_Link__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>S&amp;O Support Request Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SO_Support_Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/batchables/ActiveRatesProvisioningBatchTest.cls
/**
 * @author Deloitte
 * @date 12/09/2023
 * @description This is the test class for AccountUpdateForActiveRatesBatch class
 */
@isTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
public class ActiveRatesProvisioningBatchTest {
    private static final String APPROVED = 'Approved';
    private static final String BATCH_NOT_TRIGGERED_ASSERT_MESSAGE = 'Unexpected Error: The Batch has not been triggered yet';
    private static final String CRON_EXPRESSION = '0 0 1 * * ?';
    private static final String NEW_RATE_CHANGE = 'New';
    private static final String SCHEDULED_JOB_NAME = ActiveRatesProvisioningBatchTest.class
        .getName();
    private static final Date TODAY_DATE = System.today();
    @IsTest
    static void testWhenEffectiveRateChangesArePassedThenUpdateSubscriptionBatchIsCalled() {
        //ARRANGE
        Id contractId = Fake.generateId(Contract.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequest = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .setFakeId()
            .toSObject();

        List<Rate_Change_Request__c> retrievedRateChanges = new List<Rate_Change_Request__c>{
            rateChangeRequest
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IRateChangeRequestSelector selectorMock = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );

        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.when(selectorMock.selectByEffectiveDateToday()).thenReturn(null);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(selectorMock);
        Application.UNITOFWORK.setMock(mockUnitOfWork);

        //ACT
        ActiveRatesProvisioningBatch batch = new ActiveRatesProvisioningBatch();
        batch.start(null);
        batch.execute(null, retrievedRateChanges);
        batch.finish(null);

        //ASSERT
        ((IRateChangeRequestSelector) mocks.verify(selectorMock, 1)).selectByEffectiveDateToday();
    }

    /**
     * @description To validate that schedulable context execute
     * is scheduling the batch job correctly.
     **/
    @isTest
    private static void testWhenBatchIsScheduledThenBatchIsExecutedOnScheduledTime() {
        Test.startTest();
        String jobId = System.schedule(
            SCHEDULED_JOB_NAME,
            CRON_EXPRESSION,
            new ActiveRatesProvisioningBatch()
        );
        Test.stopTest();
        CronTrigger cronTriggerRecord = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime
            FROM CronTrigger
            WHERE Id = :jobId
        ];
        System.assertEquals(
            Time.newInstance(1, 0, 0, 0),
            cronTriggerRecord.NextFireTime.time(),
            BATCH_NOT_TRIGGERED_ASSERT_MESSAGE
        );
    }
}