sfdx-source/force-app/main/default/objects/Lever__c/Lever__c.object-meta.xml
<CustomObject>
    <description>LEM-15226: The object will represent the Growth and Operational Levers which get created after reps choose and select from the raw recommendations.</description>
    <label>Lever</label>
    <nameField>
        <displayFormat>LVR-{0000}</displayFormat>
        <label>Lever Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Levers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It indicates interest level of Lever.</description>
    <inlineHelpText>Indicates the Mx interest level in implementing this Lever.</inlineHelpText>
    <label>Interest Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Evaluated</fullName>
                <default>true</default>
                <label>To Be Evaluated</label>
            </value>
            <value>
                <fullName>Not Interested At All</fullName>
            </value>
            <value>
                <fullName>Somewhat Disinterested</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Interested</fullName>
            </value>
            <value>
                <fullName>Very Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/Product_Insights__c.object-meta.xml
<CustomObject>
    <description>LEM-623: Product Insights object that helps track insights against Opportunity, Account or Initiative to capture Merchant Insights for an active DoorDash product</description>
    <label>Product Insights</label>
    <nameField>
        <displayFormat>PDI-{0}</displayFormat>
        <label>Product Insight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Insights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <description>LEM-623: Captures the level of Interest for a Merchant with whom Product discussions were initiated.</description>
    <inlineHelpText>Indicates the overall Merchant interest level for the campaign product.</inlineHelpText>
    <label>Interest Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested at All</fullName>
            </value>
            <value>
                <fullName>Somewhat Uninterested</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Interested</fullName>
            </value>
            <value>
                <fullName>Very Interested</fullName>
            </value>
            <value>
                <fullName>To Be Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Lever__c.field-meta.xml
<CustomField>
    <fullName>Lever__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15224: It represents the Lever linked to the Product Insight record.</description>
    <label>Lever</label>
    <referenceTo>Lever__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/LeversServiceImpl.cls
/**
 * @author Deloitte
 * @date 06/12/2024
 * @description Service Implementation class for Levers related logic.
 **/
public inherited sharing class LeversServiceImpl implements ILeversService {
    private static final String LOG_DOMAIN = 'Sales';
    private static final String LOG_UPDATE_INTEREST_LEVEL = 'Unexpected Error in updating the Interest Level,';

    /**
     * @description Update interest level on Levers.
     * @param productInsights
     */
    public void updateInterestLevel(List<Product_Insights__c> productInsights) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        for (
            Product_Insights__c eachProductInsight : ProductInsightsSelector.newInstance()
                .selectProductInsightsAndLeversById(
                    (new Map<Id, Product_Insights__c>(productInsights)).keySet()
                )
        ) {
            if (
                String.isNotBlank(eachProductInsight.Interest_Level__c) &&
                String.isNotBlank(eachProductInsight.Lever__c) &&
                eachProductInsight.Lever__r.Interest_Level__c !=
                eachProductInsight.Interest_Level__c
            ) {
                uow.registerDirty(
                    new Lever__c(
                        Id = eachProductInsight.Lever__c,
                        Interest_Level__c = eachProductInsight.Interest_Level__c
                    )
                );
            }
        }
        try {
            uow.commitWork();
        } catch (Exception ex) {
            Logger.publish(LogEntry.newExceptionLog(ex, LogEntry.SeverityLevel.LOW));
            GenericLoggerService.publish(
                GenericLoggerService.createGenericLog(
                        LOG_UPDATE_INTEREST_LEVEL,
                        LOG_DOMAIN,
                        GenericLogEntry.SeverityLevel.LOW
                    )
                    .logException(ex)
            );
        }
    }
}