sfdx-source/force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <description>LEM-596,LEM-14667: Initiative object to capture the various initiatives taken against a Mx (Business Account).Renamed to Mx Touchpoint.</description>
    <label>Mx Touchpoint</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mx Touchpoints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM 596: Relationship to Account on Initiative record</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account selected is not a Business Account. Please select an associated Business Account to save the Initiative.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Is_Parent_Account_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Parent_Account_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-3644: It is used to identify whether an Initiative is updated from Active Prime account merge process.</description>
    <label>Is Parent Account Merged</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-596: Captures the current status of the Initiative</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/triggerHandlers/InitiativesHandler.cls
/**
 * @description Handler to perform all trigger based actions on Initiatives
 *              and other related records
 * @author Deloitte
 * @date 27/04/2022
 */
public class InitiativesHandler extends ApplicationDomainHandler {
    /**
     * @description Constructor to instantiate a List of Initiatives
     * @param sObjectList
     */
    public InitiativesHandler(List<Initiative__c> sObjectList) {
        super(sObjectList);
        setContextBypass(Initiative__c.SObjectType, InitiativesHandler.class);
    }

    /**
     * @description Constructor Class which implements fflib_SObjectDomain.IConstructable class
     */
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        /**
         * @description This method implements construct method of fflibSObjectDomain.IConstructable
         * @param sObjectList
         * @return InitiativesHandler
         */
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new InitiativesHandler(sObjectList);
        }
    }

    /**
     * @description Overriding method to perform default operations on Insertion
     */
    public override void onApplyDefaults() {
        Initiatives.newInstance(getInitiatives()).populateUltimateParentAccount();
    }

    /**
     * @description It is called for after update trigger processing.
     * @JIRA LEM-14728
     * @param existingRecords
     */
    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        Initiatives.newInstance(getInitiativesWithUpdatedStatus())
            .createTaskOnCompleteMxTouchpoints();
    }

    /**
     * @description It is called for after insert trigger processing.
     */
    public override void onAfterInsert() {
        Initiatives.newInstance(this.records).createTaskOnCompleteMxTouchpoints();
    }

    /**
     * @description Before Update Trigger processing
     * @param existingRecords - The map of old Initiative records
     */
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
        Initiatives.newInstance(getInitiativesWithUpdatedAccountRelationships())
            .populateUltimateParentAccount();
        Initiatives.newInstance(
                new List<Initiative__c>(
                    (List<Initiative__c>) getChangedRecords(
                        new Set<SObjectField>{ Initiative__c.Status__c }
                    )
                )
            )
            .addErrorOnCompleteMxTouchpointsWithoutStakeholders();
    }

    /**
     * @description Fetch All Records present in the Trigger Context
     * @return List<Initiative__c>
     */
    private List<Initiative__c> getInitiatives() {
        return (List<Initiative__c>) getRecords();
    }

    /**
     * @description This method is used to call the domain method for
     *              autopopulating blank Account_Name__c field on
     *              Initiative__c records.
     * @return List<Initiative__c>
     */
    private List<Initiative__c> getInitiativesWithUpdatedAccountRelationships() {
        return new List<Initiative__c>(
            (List<Initiative__c>) getChangedRecords(
                new Set<Schema.SObjectField>{
                    Initiative__c.Account__c,
                    Initiative__c.Is_Parent_Account_Merged__c
                }
            )
        );
    }

    /**
     * @description This method is used to get all the Initiatives with updated Status.
     * @return List<Initiative__c>
     */
    private List<Initiative__c> getInitiativesWithUpdatedStatus() {
        return new List<Initiative__c>(
            (List<Initiative__c>) getChangedRecords(
                new Set<SObjectField>{ Initiative__c.Status__c }
            )
        );
    }
}