sfdx-source/force-app/main/default/objects/Order/recordTypes/Primary_Order.recordType-meta.xml
<RecordType>
    <fullName>Primary_Order</fullName>
    <active>true</active>
    <description>LEM-181 - Initial Setup for Order</description>
    <label>Primary Order</label>
</RecordType>

sfdx-source/force-app/main/default/objects/OrderItem/fields/Active_Fee__c.field-meta.xml
<CustomField>
    <fullName>Active_Fee__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/OrderItem/fields/Subscription_Rate_Change__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Rate_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-13931 Associated Subscription Rate Change</description>
    <label>Subscription Rate Change</label>
    <referenceTo>Subscription_Rate_Change__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Active_Commission__c.field-meta.xml
<CustomField>
    <fullName>Active_Commission__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Commission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Active_Fee__c.field-meta.xml
<CustomField>
    <fullName>Active_Fee__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Subscription_Rate_Change__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Rate_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <referenceTo>Subscription_Rate_Change__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>SRC_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/Subscription_Rate_Change__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <nameField>
        <displayFormat>SubscriptionChange-{0000}</displayFormat>
        <label>Subscription Rate Change  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Rate Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Update_complete__c.field-meta.xml
<CustomField>
    <fullName>Update_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Update complete</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Updated_Active_Commission__c.field-meta.xml
<CustomField>
    <fullName>Updated_Active_Commission__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Updated Active Commission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Updated_Active_Fee__c.field-meta.xml
<CustomField>
    <fullName>Updated_Active_Fee__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Updated Active Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/SubscriptionRateChangeServiceImpl.cls
/**
 * @author Deloitte
 * @date 08/21/2023
 * @description Service implementation class for Active Rate Provisioning update flow.
 */
public inherited sharing class SubscriptionRateChangeServiceImpl implements ISubscriptionRateChangeService {
    private static final String PRIMARY_ORDER_RECORD_TYPE_ID = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName()
        .get('Primary_Order')
        .getRecordTypeId();

    /**
     * @description This method is used to set Subscription Rate change to Complete once associated
     * Subscription and Primary Order Products are updated with correct active rates.
     * @param arpAppliedPrimaryOrderItems
     */
    public void setSubscriptionRateChangeComplete(List<OrderItem> arpAppliedPrimaryOrderItems) {
        Set<Id> orderItemIds = new Set<Id>();
        Map<Id, SBQQ__Subscription__c> srcToSubscriptionMap = new Map<Id, SBQQ__Subscription__c>();
        List<Subscription_Rate_Change__c> subscriptionRateChangesToBeUpdated = new List<Subscription_Rate_Change__c>();
        Subscription_Rate_Change__c srcToBeAdded = new Subscription_Rate_Change__c();

        orderItemIds = collectPrimaryOrderProductIds(arpAppliedPrimaryOrderItems);

        List<SBQQ__Subscription__c> subscriptionsAssociated = SubscriptionSelector.newInstance()
            .selectSubscriptionRecordsByPrimaryOrderProduct(orderItemIds);

        if (subscriptionsAssociated.isEmpty()) {
            return;
        }

        srcToSubscriptionMap = getSrcToSubscriptionMap(subscriptionsAssociated);

        List<Subscription_Rate_Change__c> subscriptionRateChanges = SubscriptionRateChangeSelector.newInstance()
            .selectById(srcToSubscriptionMap.keySet());

        for (Subscription_Rate_Change__c eachRateChange : subscriptionRateChanges) {
            SBQQ__Subscription__c associatedSubscription = srcToSubscriptionMap.get(
                eachRateChange.Id
            );
            if (associatedSubscription == null) {
                continue;
            }
            srcToBeAdded = checkIfActiveRatesAreInSync(eachRateChange, associatedSubscription);
            if (srcToBeAdded != null) {
                subscriptionRateChangesToBeUpdated.add(srcToBeAdded);
            }
        }
        updateSubscriptionRateChanges(subscriptionRateChangesToBeUpdated);
    }

    /**
     * @description Collect all primary order item ids
     * @param arpAppliedPrimaryOrderItems
     * @return orderItemIds
     */
    private Set<Id> collectPrimaryOrderProductIds(List<OrderItem> arpAppliedPrimaryOrderItems) {
        Set<Id> orderItemIds = new Set<Id>();
        if (!arpAppliedPrimaryOrderItems.isEmpty()) {
            for (OrderItem eachOrderItem : arpAppliedPrimaryOrderItems) {
                if (eachOrderItem.Order.RecordTypeId == PRIMARY_ORDER_RECORD_TYPE_ID) {
                    orderItemIds.add(eachOrderItem.Id);
                }
            }
        }
        return orderItemIds;
    }

    /**
     * @description Create srcToSubscriptionMap using subscriptions
     * @param subscriptionsAssociated
     * @return srcToSubscriptionMap
     */
    private Map<Id, SBQQ__Subscription__c> getSrcToSubscriptionMap(
        List<SBQQ__Subscription__c> subscriptionsAssociated
    ) {
        Map<Id, SBQQ__Subscription__c> srcToSubscriptionMap = new Map<Id, SBQQ__Subscription__c>();
        for (SBQQ__Subscription__c sub : subscriptionsAssociated) {
            if (
                sub.Active_Fee__c == sub.SBQQ__OrderProduct__r.Active_Fee__c &&
                sub.Active_Commission__c == sub.SBQQ__OrderProduct__r.Active_Commission__c
            ) {
                srcToSubscriptionMap.put(sub.Subscription_Rate_Change__c, sub);
            }
        }
        return srcToSubscriptionMap;
    }

    /**
     * @description Check if the Active rates are in sync along Primary Order products, Subscription Rate Change and Subscriptions in
     * order to complete the Subscription Rate Change
     * @param eachRateChange
     * @param associatedSubscription
     * @return srcToBeAdded
     */
    private Subscription_Rate_Change__c checkIfActiveRatesAreInSync(
        Subscription_Rate_Change__c eachRateChange,
        SBQQ__Subscription__c associatedSubscription
    ) {
        Subscription_Rate_Change__c srcToBeAdded = new Subscription_Rate_Change__c();
        Boolean activeFeeMatch = false;
        Boolean activeCommissionMatch = false;
        Boolean activeFeeUpdated = true;
        Boolean activeCommissionUpdated = true;
        if (eachRateChange.Updated_Active_fee__c != null) {
            if (isActiveFeeMatch(eachRateChange, associatedSubscription)) {
                activeFeeMatch = true;
            }
        } else {
            activeFeeUpdated = false;
        }
        if (eachRateChange.Updated_Active_Commission__c != null) {
            if (isActiveCommissionMatch(eachRateChange, associatedSubscription)) {
                activeCommissionMatch = true;
            }
        } else {
            activeCommissionUpdated = false;
        }
        if (
            (activeFeeUpdated && activeFeeMatch) ||
            (activeCommissionUpdated && activeCommissionMatch)
        ) {
            srcToBeAdded = new Subscription_Rate_Change__c(
                Id = eachRateChange.Id,
                Update_Complete__c = true
            );
        }
        return srcToBeAdded;
    }

    /**
     * @description Check if the Active Fee rates are in sync along Primary Order products, Subscription Rate Change and Subscriptions in
     * order to complete the Subscription Rate Change
     * @param eachRateChange
     * @param associatedSubscription
     * @return isActiveFeeMatch
     */
    private Boolean isActiveFeeMatch(
        Subscription_Rate_Change__c eachRateChange,
        SBQQ__Subscription__c associatedSubscription
    ) {
        Boolean isActiveFeeMatch =
            eachRateChange.Updated_Active_fee__c == associatedSubscription.Active_fee__c &&
            eachRateChange.Updated_Active_Fee__c ==
            associatedSubscription.SBQQ__OrderProduct__r.Active_Fee__c;
        return isActiveFeeMatch;
    }

    /**
     * @description Check if the Active Commission rates are in sync along Primary Order products, Subscription Rate Change and Subscriptions in
     * order to complete the Subscription Rate Change
     * @param eachRateChange
     * @param associatedSubscription
     * @return isActiveCommissionMatch
     */
    private Boolean isActiveCommissionMatch(
        Subscription_Rate_Change__c eachRateChange,
        SBQQ__Subscription__c associatedSubscription
    ) {
        Boolean isActiveCommissionMatch =
            eachRateChange.Updated_Active_Commission__c ==
            associatedSubscription.Active_Commission__c &&
            eachRateChange.Updated_Active_Commission__c ==
            associatedSubscription.SBQQ__OrderProduct__r.Active_Commission__c;
        return isActiveCommissionMatch;
    }

    /**
     * @description Update Subscription Rate Change
     * @param subscriptionRateChangesToUpdate
     */
    private void updateSubscriptionRateChanges(
        List<Subscription_Rate_Change__c> subscriptionRateChangesToUpdate
    ) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDirty(subscriptionRateChangesToUpdate);
        try {
            uow.commitWork();
        } catch (Exception ex) {
            Logger.publish(LogEntry.newExceptionLog(ex, LogEntry.SeverityLevel.HIGH));
        }
    }
}