sfdx-source/force-app/main/default/objects/Brief_Item__c/Brief_Item__c.object-meta.xml
<CustomObject>
    <description>LEM-2983: Campaign Items specific to certain Quote Line Items are captured in Brief Items information.</description>
    <label>Brief Item</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>Brief Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brief Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Brief_Item__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>LEM-2983: Captures the End Date of the Campaign Item.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brief_Item__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-2983: Captures the Quote Line Item with which the Brief Item is associated to.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Brief Items</relationshipLabel>
    <relationshipName>Brief_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brief_Item__c/fields/Quote_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Id__c</fullName>
    <description>LEM-4549: It is the 18 character Id of the related Quote Line Item.</description>
    <formula>CASESAFEID(Quote_Line__c)</formula>
    <label>Quote Line Id</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brief_Item__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>LEM-2983: Captures the Start Date of the Campaign Item.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/SBQQ__Order__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__ProductOption__c/fields/Active_Rate_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Active_Rate_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Rate Eligible</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Active_Commission__c.field-meta.xml
<CustomField>
    <fullName>Active_Commission__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Commission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brief_Item__c.field-meta.xml
<CustomField>
    <fullName>Brief_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-9452: Sync FROM Quote Line and Opportunity TO Brief Item</description>
    <label>Brief Item</label>
    <referenceTo>Brief_Item__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>LEM-486 – Attributes related to Advertisement products</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Has_Brief_Item__c.field-meta.xml
<CustomField>
    <fullName>Has_Brief_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-3957: It is used to indicate if the Quote Line Item has a Brief Item associated.</description>
    <label>Has Brief Item</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Prior_Approved_Commission_Fee__c.field-meta.xml
<CustomField>
    <fullName>Prior_Approved_Commission_Fee__c</fullName>
    <description>LEM-22670: It is used capture Prior Approved Requested Fee by Deal Desk.</description>
    <label>Prior Approved Commission Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Prior_Approved_Commission_Percent__c.field-meta.xml
<CustomField>
    <fullName>Prior_Approved_Commission_Percent__c</fullName>
    <description>LEM-22670: It is used capture Prior Approved Requested Commission by Deal Desk.</description>
    <label>Prior Approved Commission Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Rate_Change__c.field-meta.xml
<CustomField>
<fullName>Rate_Change__c</fullName>
<description>LEM-14968: Determines if requested fee, requested commission or both are updated on Amendment</description>
<formula>IF(Type__c = &quot;Amended&quot;,
IF(
AND(SBQQ__Source__r.SBQQ__SpecialPrice__c &lt;&gt; SBQQ__SpecialPrice__c,
OR(
SBQQ__Source__r.Requested_Commission__c &lt;&gt; Requested_Commission__c,
AND(ISBLANK(SBQQ__Source__r.Requested_Commission__c), NOT(ISBLANK(Requested_Commission__c))),
AND(ISBLANK(Requested_Commission__c), NOT(ISBLANK(SBQQ__Source__r.Requested_Commission__c)))
)
),
&quot;Commission + Fee&quot;,
IF(SBQQ__Source__r.SBQQ__SpecialPrice__c &lt;&gt; SBQQ__SpecialPrice__c,
&quot;Fee&quot;,
IF(OR(
SBQQ__Source__r.Requested_Commission__c &lt;&gt; Requested_Commission__c,
AND(ISBLANK(SBQQ__Source__r.Requested_Commission__c), NOT(ISBLANK(Requested_Commission__c))),
AND(ISBLANK(Requested_Commission__c), NOT(ISBLANK(SBQQ__Source__r.Requested_Commission__c)))
),
&quot;Commission&quot;,
&quot;No&quot;
)
)
),
&quot;No&quot;
)</formula>
<label>Rate Change?</label>
<type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Requested_Commission__c.field-meta.xml
<CustomField>
    <fullName>Requested_Commission__c</fullName>
    <description>LEM-180 – Initial Setup of Quote Line – Quote Line Pricing</description>
    <label>Requested Commission (%)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SpecialPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SpecialPrice__c</fullName>
    <description>Special (volume-discounted or contracted) unit price for the product being quoted by this line item.</description>
    <inlineHelpText>Special unit price for this line item, such as volume discount or contracted price.</inlineHelpText>
    <label>Special Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-5420: Used in Cong Queries and Template to check Type of Quote line on an Amended Quote i.e  if the quote line is  or Amended or Deleted or Existing or New.
        LEM-12478: Updated Formula.</description>
    <formula>IF( SBQQ__Quote__r.Quote_Type__c = &quot;Amendment&quot;,
IF( AND(SBQQ__Source__c  &lt;&gt; &quot;&quot;, SBQQ__UpgradedSubscription__c = &quot;&quot;, SBQQ__Source__r.SBQQ__UpgradedSubscription__c &lt;&gt; &quot;&quot;), &quot;Amended&quot;,
IF( AND(SBQQ__UpgradedSubscription__c &lt;&gt; &quot;&quot;, SBQQ__Quantity__c =0), &quot;Deleted&quot;,
IF( AND(SBQQ__UpgradedSubscription__c &lt;&gt; &quot;&quot;, SBQQ__Quantity__c &gt;0), &quot;Existing&quot;,
IF( AND(SBQQ__UpgradedSubscription__c =&quot;&quot;, SBQQ__Quantity__c &gt;0 ), &quot;New&quot;, &quot;&quot;
)))),&quot;&quot;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/CCP_Unique_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>CCP_Unique_Group_Id__c</fullName>
    <description>LEM-10489- Refers to the first Quote Line group created.</description>
    <label>CCP Unique Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Original_Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Original_Quote_Line_Group__c</fullName>
    <description>LEM-6466: Refers to the group from which it is cloned.</description>
    <label>Original Quote Line Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Active_Commission__c.field-meta.xml
<CustomField>
    <fullName>Active_Commission__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Commission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Active_Fee__c.field-meta.xml
<CustomField>
    <fullName>Active_Fee__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Active Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Brief_Item__c.field-meta.xml
<CustomField>
    <fullName>Brief_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-9452: Sync FROM Quote Line and Opportunity TO Brief Item</description>
    <label>Brief Item</label>
    <referenceTo>Brief_Item__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>LEM-486 – Attributes related to Advertisement products</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Requested_Commission__c.field-meta.xml
<CustomField>
    <fullName>Requested_Commission__c</fullName>
    <description>LEM-184: Initial Setup of Subscription. LEM-6457: Updated label and help text.</description>
    <inlineHelpText>This field was created to capture the base Commission captured in the contract.</inlineHelpText>
    <label>Contracted Commission</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SpecialPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SpecialPrice__c</fullName>
    <description>Special Price for this Subscription.</description>
    <inlineHelpText>This is the Base Fee captured in the Contract.</inlineHelpText>
    <label>Special Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>LEM-486 – Attributes related to Advertisement products</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/services/QuoteLineItemsServiceImplTest.cls
/**
 * @description This is the test class for QuoteLineItemsServiceImpl
 * @author Deloitte
 * @date 25/04/2022
 */
@isTest(SeeAllData=false)
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
public with sharing class QuoteLineItemsServiceImplTest {
    private static final String QUOTE_STATUS_APPROVED = 'Approved';
    private static final String ACCOUNT_SEGMENT_SMB = 'SMB';
    /**
     *@description updates START DATE and END DATE of Brief Items when QLI dates changed.
     */
    @IsTest
    public static void testWhenUpdateQLIStartDateAndEndDateThenItShouldUpdateBriefItemStartDateAndEndDate() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Start_Date__c, System.today() - 2)
            .setField(SBQQ__QuoteLine__c.End_Date__c, System.today() + 4)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setField(Brief_Item__c.Start_Date__c, System.today() - 3)
                .setField(Brief_Item__c.End_Date__c, System.today() + 5)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);
        QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        Brief_Item__c.Start_Date__c => System.today() - 2,
                        Brief_Item__c.End_Date__c => System.today() + 4
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     *@description updates START DATE and END DATE of Brief Items when QLI dates changed.
     */
    @IsTest
    public static void testWhenUpdateQLIStartDateAndEndDateThenItShouldUpdateBriefItemStartDateAndEndDateFailed() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Start_Date__c, System.today() - 2)
            .setField(SBQQ__QuoteLine__c.End_Date__c, System.today() + 4)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setField(Brief_Item__c.Start_Date__c, System.today() - 3)
                .setField(Brief_Item__c.End_Date__c, System.today() + 5)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.doThrowWhen(
                new TestCommitException('Exception occurred while performing DML operation'),
                mockUOW
            ))
            .commitWork();
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);

        try {
            QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
            ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
                .registerDirty(
                    fflib_Match.sObjectWith(
                        new Map<SObjectField, Object>{
                            Brief_Item__c.Start_Date__c => System.today() - 2,
                            Brief_Item__c.End_Date__c => System.today() + 4
                        }
                    )
                );
            ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
        } catch (Exception mockException) {
            System.assertEquals(
                'Exception occurred while performing DML operation',
                mockException.getMessage(),
                'Unexpected Error: The Exception fired was not a TestCommitException.'
            );
        }
    }

    /**
     *@description updates START DATE and END DATE of Brief Items when QLI dates changed.
     */
    @IsTest
    public static void testWhenNotUpdateQLIStartDateAndEndDateThenItShouldNotUpdateBriefItemStartDateAndEndDate() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);
        QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 0))
            .registerDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        Brief_Item__c.Start_Date__c => System.today() - 2,
                        Brief_Item__c.End_Date__c => System.today() + 4
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }
    /**
     * @description updates Brief Items when QLI dates updated.
     */
    @IsTest
    public static void testWhenUpdateQLIThenItShouldUpdateBriefItem() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Start_Date__c, System.today() - 2)
            .setField(SBQQ__QuoteLine__c.End_Date__c, System.today() + 4)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setField(Brief_Item__c.Start_Date__c, System.today() - 3)
                .setField(Brief_Item__c.End_Date__c, System.today() + 5)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);
        QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        Brief_Item__c.Start_Date__c => System.today() - 2,
                        Brief_Item__c.End_Date__c => System.today() + 4
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();

        //Called below method as part of LEM-13065
	    QuoteLineItemsService.deleteBriefItemBeforeQuoteLineIsDeleted(quoteLineItems);
    }

    /**
     * @description updates Brief Items when QLI dates updated.
     */
    @IsTest
    public static void testWhenUpdateQLIThenItShouldUpdateBriefItemFailed() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Start_Date__c, System.today() - 2)
            .setField(SBQQ__QuoteLine__c.End_Date__c, System.today() + 4)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setField(Brief_Item__c.Start_Date__c, System.today() - 3)
                .setField(Brief_Item__c.End_Date__c, System.today() + 5)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.doThrowWhen(
                new TestCommitException('Exception occurred while performing DML operation'),
                mockUOW
            ))
            .commitWork();
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);

        try {
            QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
            ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
                .registerDirty(
                    fflib_Match.sObjectWith(
                        new Map<SObjectField, Object>{
                            Brief_Item__c.Start_Date__c => System.today() - 2,
                            Brief_Item__c.End_Date__c => System.today() + 4
                        }
                    )
                );
            ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
        } catch (Exception mockException) {
            System.assertEquals(
                'Exception occurred while performing DML operation',
                mockException.getMessage(),
                'Unexpected Error: The Exception fired was not a TestCommitException.'
            );
        }
    }

    /**
     * @description updates Brief Items when QLI dates updated.
     */
    @IsTest
    public static void testWhenNotUpdateQLIThenItShouldNotUpdateBriefItem() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);
        IBriefItemsSelector briefItemSelectorMock = (IBriefItemsSelector) mocks.mock(
            IBriefItemsSelector.class
        );
        IQuoteLineItemsSelector selectorMock = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );
        mocks.startStubbing();
        mocks.when(briefItemSelectorMock.sObjectType()).thenReturn(Brief_Item__c.SObjectType);
        mocks.when(briefItemSelectorMock.selectByIds(new Set<Id>{ briefItemIdOne }))
            .thenReturn(briefItemsList);
        mocks.when(selectorMock.sObjectType()).thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{ quoteLineItemIdOne }))
            .thenReturn(quoteLineItems);
        mocks.stopStubbing();
        Application.Selector.setMock(briefItemSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Application.Selector.setMock(selectorMock);
        QuoteLineItemsService.updateBriefItemsQuoteLineSyncFields(quoteLineItems);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 0))
            .registerDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        Brief_Item__c.Start_Date__c => System.today() - 2,
                        Brief_Item__c.End_Date__c => System.today() + 4
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description test clone group logic on amendment quotes
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenAmendedQuoteLineItemsHavingBlankGroupsThenGroupsPopulatedWithClonedDetails() {
        Id quoteId = fflib_IDGenerator.generate(SBQQ__Quote__c.SObjectType);
        Id amendedQuoteId = fflib_IDGenerator.generate(SBQQ__Quote__c.SObjectType);
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id quoteLineItemIdTwo = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id groupId1 = Fake.generateId(SBQQ__QuoteLineGroup__c.class);
        Id contractId = Fake.generateId(Contract.class);
        Id orderId1 = Fake.generateId(Order.class);
        Id subscriptionId1 = Fake.generateId(SBQQ__Subscription__c.class);

        List<SBQQ__Quote__c> amendedQuoteList = new List<SBQQ__Quote__c>{
            (SBQQ__Quote__c) new Fake(SBQQ__Quote__c.class)
                .setField(SBQQ__Quote__c.id, amendedQuoteId)
                .setField(SBQQ__Quote__c.SBQQ__MasterEvergreenContract__c, contractId)
                .setParent(
                    'SBQQ__MasterEvergreenContract__r',
                    new Fake(Contract.class)
                        .setField(Contract.id, contractId)
                        .setField(Contract.SBQQ__Order__c, orderId1)
                        .setParent(
                            'SBQQ__Order__r',
                            new Fake(Order.class)
                                .setField(Order.id, orderId1)
                                .setField(Order.SBQQ__Quote__c, quoteId)
                                .setParent(
                                    'SBQQ__Quote__r',
                                    new Fake(SBQQ__Quote__c.class)
                                        .setField(SBQQ__Quote__c.id, quoteId)
                                )
                        )
                )
                .toSobject()
        };
        Map<Id, SBQQ__Quote__c> quotesMap = new Map<Id, SBQQ__Quote__c>(amendedQuoteList);

        List<SBQQ__QuoteLine__c> prevQuoteLineList = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
                .setField(SBQQ__QuoteLine__c.SBQQ__Quote__c, quoteId)
                .setField(SBQQ__QuoteLine__c.SBQQ__Group__c, groupId1)
                .toSobject()
        };
        List<SBQQ__QuoteLine__c> newQuoteLineList = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdTwo)
                .setField(SBQQ__QuoteLine__c.SBQQ__Quote__c, amendedQuoteId)
                .setField(SBQQ__QuoteLine__c.SBQQ__Group__c, null)
                .setField(SBQQ__QuoteLine__c.SBQQ__UpgradedSubscription__c, subscriptionId1)
                .setParent(
                    'SBQQ__Quote__r',
                    new Fake(SBQQ__Quote__c.class)
                        .setField(SBQQ__Quote__c.id, amendedQuoteId)
                        .setField(SBQQ__Quote__c.SBQQ__Type__c, 'Amendment')
                )
                .setParent(
                    'SBQQ__UpgradedSubscription__r',
                    new Fake(SBQQ__Subscription__c.class)
                        .setField(SBQQ__Subscription__c.id, subscriptionId1)
                        .setField(SBQQ__Subscription__c.SBQQ__QuoteLine__c, quoteLineItemIdOne)
                        .setParent(
                            'SBQQ__QuoteLine__r',
                            new Fake(SBQQ__QuoteLine__c.class)
                                .setField(SBQQ__QuoteLine__c.id, quoteLineItemIdOne)
                                .setField(SBQQ__QuoteLine__c.SBQQ__Group__c, groupId1)
                        )
                )
                .toSobject()
        };
        List<SBQQ__QuoteLineGroup__c> groupList = new List<SBQQ__QuoteLineGroup__c>{
            (SBQQ__QuoteLineGroup__c) new Fake(SBQQ__QuoteLineGroup__c.class)
                .setField(SBQQ__QuoteLineGroup__c.Id, groupId1)
                .setField(SBQQ__QuoteLineGroup__c.Name, 'Fake 3')
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__Number__c, 1)
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__ListTotal__c, 100)
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__CustomerTotal__c, 12)
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__NetTotal__c, 12)
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__Source__c, null)
                .setField(SBQQ__QuoteLineGroup__c.SBQQ__Quote__c, quoteId)
                .toSobject()
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IQuotesSelector mockQuotesSelector = (IQuotesSelector) mocks.mock(IQuotesSelector.class);
        IQuoteLineItemsSelector mockQuoteLineItemsSelector = (IQuoteLineItemsSelector) mocks.mock(
            IQuoteLineItemsSelector.class
        );

        IQuoteLineGroupSelector mockQuoteGroupsSelector = (IQuoteLineGroupSelector) mocks.mock(
            IQuoteLineGroupSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        mocks.startStubbing();
        mocks.when(mockQuotesSelector.sObjectType()).thenReturn(SBQQ__Quote__c.SObjectType);
        mocks.when(mockQuoteLineItemsSelector.sObjectType())
            .thenReturn(SBQQ__QuoteLine__c.SObjectType);
        mocks.when(mockQuoteGroupsSelector.sObjectType())
            .thenReturn(SBQQ__QuoteLineGroup__c.SObjectType);
        mocks.when(
                mockQuotesSelector.selectQuoteFieldsFromOriginalQuote(new Set<Id>{ amendedQuoteId })
            )
            .thenReturn(amendedQuoteList);
        mocks.when(
                mockQuoteLineItemsSelector.selectQuoteLineswithMissingGroups(
                    new Set<Id>{ amendedQuoteId }
                )
            )
            .thenReturn(newQuoteLineList);
        mocks.when(mockQuoteLineItemsSelector.selectQuoteLinesFromQuoteIds(new Set<Id>{ quoteId }))
            .thenReturn(prevQuoteLineList);
        mocks.when(
                mockQuoteGroupsSelector.selectGroupRecordsFromQuote(new Set<Id>{ amendedQuoteId })
            )
            .thenReturn(new List<SBQQ__QuoteLineGroup__c>{});
        mocks.when(mockQuoteGroupsSelector.selectGroupRecords(new Set<Id>{ groupId1 }))
            .thenReturn(new Map<Id, SBQQ__QuoteLineGroup__c>(groupList));
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockQuotesSelector);
        Application.SELECTOR.setMock(mockQuoteLineItemsSelector);
        Application.SELECTOR.setMock(mockQuoteGroupsSelector);
        Application.SELECTOR.setMock(mockQuoteGroupsSelector);

        QuoteLineItemsService.insertMissingAmendmentLineGroups(quotesMap);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 2)).commitWork();
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerNew((List<SObject>) fflib_Match.anyList());
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty((List<SObject>) fflib_Match.anyList());
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.anySObject(),
                fflib_Match.anySObjectField(),
                fflib_Match.anySObject()
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerNew(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            SBQQ__QuoteLineGroup__c.SBQQ__Number__c => 1.0,
                            SBQQ__QuoteLineGroup__c.SBQQ__Source__c => groupId1,
                            SBQQ__QuoteLineGroup__c.Original_Quote_Line_Group__c => groupId1,
                            SBQQ__QuoteLineGroup__c.CCP_Unique_Group_Id__c => groupId1,
                            SBQQ__QuoteLineGroup__c.Name => 'Fake 3',
                            SBQQ__QuoteLineGroup__c.SBQQ__CustomerTotal__c => 12.0,
                            SBQQ__QuoteLineGroup__c.SBQQ__ListTotal__c => 100.0,
                            SBQQ__QuoteLineGroup__c.SBQQ__NetTotal__c => 12.0
                        }
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            SBQQ__Quote__c.Id => amendedQuoteId,
                            SBQQ__Quote__c.SBQQ__LineItemsGrouped__c => true,
                            SBQQ__Quote__c.Has_Groups__c => true
                        }
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{ SBQQ__QuoteLine__c.Id => quoteLineItemIdTwo }
                ),
                fflib_Match.eqSObjectField(SBQQ__QuoteLine__c.SBQQ__Group__c),
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        SBQQ__QuoteLineGroup__c.SBQQ__Source__c => groupId1
                    }
                )
            );
    }

    /**
     * @description update active price fields when quote is submitted for approval
     */
    @IsTest
    public static void testWhenQuoteIsSubmittedForApprovalThenUpdateActivePriceFields() {
        Id quoteLineId = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id quoteLineId2 = Fake.generateId(SBQQ__QuoteLine__c.class);

        List<SBQQ__QuoteLine__c> quoteLineItemList = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId)
                .setField(SBQQ__QuoteLine__c.Requested_Commission__c, 5)
                .setField(SBQQ__QuoteLine__c.SBQQ__SpecialPrice__c, 2)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 4)
                .setField(SBQQ__QuoteLine__c.Active_Fee__c, 1)
                .setField(SBQQ__QuoteLine__c.Rate_Change__c, 'Commission + Fee')
                .toSobject(),
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId2)
                .setField(SBQQ__QuoteLine__c.Requested_Commission__c, 7)
                .setField(SBQQ__QuoteLine__c.SBQQ__SpecialPrice__c, 0)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 9)
                .setField(SBQQ__QuoteLine__c.Active_Fee__c, 8)
                .setField(SBQQ__QuoteLine__c.Type__c, 'New')
                .setParent(
                    'SBQQ__ProductOption__r',
                    new Fake(SBQQ__ProductOption__c.class)
                        .setField(SBQQ__ProductOption__c.Active_Rate_Eligible__c, true)
                )
                .toSobject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);

        QuoteLineItemsService.updateActiveFeeActiveComissionOnQuotelines(quoteLineItemList);

        System.assertEquals(
            quoteLineItemList[0].Active_Commission__c,
            4,
            'Active Price Not Updated'
        );
        System.assertEquals(quoteLineItemList[1].Active_Fee__c, 0, 'Active Price Not Updated');
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description update active price fields when quote is submitted for approval
     */
    @IsTest
    public static void testWhenApprovalsRecalledThenRevertActivePriceFields() {
        Id quoteLineId = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id quoteLineId2 = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id quoteLineId3 = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id quoteLineId4 = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id sourceQL = Fake.generateId(SBQQ__QuoteLine__c.class);

        List<SBQQ__QuoteLine__c> quoteLineItemList = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 4)
                .setParent(
                    'SBQQ__ProductOption__r',
                    new Fake(SBQQ__ProductOption__c.class)
                        .setField(SBQQ__ProductOption__c.Active_Rate_Eligible__c, true)
                )
                .toSobject(),
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId2)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 9)
                .setField(SBQQ__QuoteLine__c.Active_Fee__c, 8)
                .setField(SBQQ__QuoteLine__c.Type__c, 'New')
                .setParent(
                    'SBQQ__ProductOption__r',
                    new Fake(SBQQ__ProductOption__c.class)
                        .setField(SBQQ__ProductOption__c.Active_Rate_Eligible__c, true)
                )
                .toSobject(),
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId4)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 123)
                .setField(SBQQ__QuoteLine__c.Active_Fee__c, 88)
                .setParent(
                    'SBQQ__ProductOption__r',
                    new Fake(SBQQ__ProductOption__c.class)
                        .setField(SBQQ__ProductOption__c.Active_Rate_Eligible__c, true)
                )
                .setParent(
                    'SBQQ__Quote__r',
                    new Fake(SBQQ__Quote__c.class).setField(SBQQ__Quote__c.SBQQ__Type__c, 'Quote')
                )
                .toSobject(),
            (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
                .setField(SBQQ__QuoteLine__c.id, quoteLineId3)
                .setField(SBQQ__QuoteLine__c.Active_Commission__c, 7)
                .setField(SBQQ__QuoteLine__c.Active_Fee__c, 5)
                .setField(SBQQ__QuoteLine__c.Type__c, 'Amended')
                .setField(SBQQ__QuoteLine__c.SBQQ__Source__c, sourceQL)
                .setParent(
                    'SBQQ__ProductOption__r',
                    new Fake(SBQQ__ProductOption__c.class)
                        .setField(SBQQ__ProductOption__c.Active_Rate_Eligible__c, true)
                )
                .setParent(
                    'SBQQ__Source__r',
                    new Fake(SBQQ__QuoteLine__c.class)
                        .setField(SBQQ__QuoteLine__c.Id, sourceQL)
                        .setField(SBQQ__QuoteLine__c.Active_Commission__c, 6)
                        .setField(SBQQ__QuoteLine__c.Active_Fee__c, 6)
                )
                .toSobject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);

        QuoteLineItemsService.revertActiveFeeActiveComissionOnQuotelines(quoteLineItemList);

        System.assertEquals(
            quoteLineItemList[0].Active_Commission__c,
            4,
            'Active Price reverted incorrectly'
        );
        System.assertEquals(
            quoteLineItemList[1].Active_Fee__c,
            null,
            'Active Price reverted incorrectly'
        );
        System.assertEquals(
            quoteLineItemList[2].Active_Commission__c,
            null,
            'Active Price reverted incorrectly'
        );
        System.assertEquals(
            quoteLineItemList[3].Active_Fee__c,
            6,
            'Active Price reverted incorrectly'
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     *@description LEM-13065 if quote line associated is deleted then Brief item must be deleted before.
    */
    @IsTest
    public static void testWhenQuoteLineDeletesThenAssociatedBriefItemIsDeleted() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Id briefItemIdOne = fflib_IDGenerator.generate(Brief_Item__c.SObjectType);

        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Brief_Item__c, briefItemIdOne)
            .setField(SBQQ__QuoteLine__c.Has_Brief_Item__c, true);

        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
                };

         List<Brief_Item__c> briefItemsList = new List<Brief_Item__c>{
            (Brief_Item__c) new Fake(Brief_Item__c.class)
                .setField(Brief_Item__c.Id, briefItemIdOne)
                .setField(Brief_Item__c.Quote_Line__c, quoteLineItemIdOne)
                .setField(Brief_Item__c.Quote_Line_Id__c, (String) quoteLineItemIdOne)
                .setParent('Quote_Line__r', quoteLineItemInstance)
                .toSObject()
         };

         List<Brief_Item__c> briefItemsListId = new List<Brief_Item__c>{
             new Brief_Item__c(Id = briefItemsList[0].Id)
         };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UNITOFWORK.setMock(mockUOW);

        Test.startTest();
        QuoteLineItemsService.deleteBriefItemBeforeQuoteLineIsDeleted(quoteLineItems);
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW))
            .registerDeleted(
                ((List<Brief_Item__c>)fflib_Match.eqList((List<Object>) briefItemsListId)
         ));

        ((fflib_ISObjectUnitOfWork)mocks.verify(mockUOW, 1)).commitWork();
    }

	/**
     * @description Used to test whether or not the Quote Lines are updated when a Quote is updated.
     * @JIRA# LEM-22670
     */
    @IsTest
    private static void testWhenQuoteLinesRecordsPassedThenUpdateQuoteLines() {
        Id quoteLineItemIdOne = fflib_IDGenerator.generate(SBQQ__QuoteLine__c.SObjectType);
        Fake quoteLineItemInstance = new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineItemIdOne)
            .setField(SBQQ__QuoteLine__c.Start_Date__c, System.today() - 2)
            .setField(SBQQ__QuoteLine__c.End_Date__c, System.today() + 4)
            .setField(SBQQ__QuoteLine__c.Prior_Approved_Commission_Fee__c , 3)
        	.setField(SBQQ__QuoteLine__c.Prior_Approved_Commission_Percent__c  , 4);
        List<SBQQ__QuoteLine__c> quoteLineItems = new List<SBQQ__QuoteLine__c>{
            (SBQQ__QuoteLine__c) quoteLineItemInstance.toSObject()
        };
        List<List<SBQQ__QuoteLine__c>> quoteLineRecords = new List<List<SBQQ__QuoteLine__c>>{quoteLineItems};
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UNITOFWORK.setMock(mockUOW);
        Test.startTest();
        QuoteLineItemsService.updatePriorFieldsOnQuoteLines(quoteLineRecords);
        Test.stopTest();
        ((fflib_ISObjectUnitOfWork)mocks.verify(mockUOW, 1)).commitWork();
    }
}