sfdx-source/force-app/main/default/objects/Business_Reference__c/Business_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-2082 Object used for integration of Business Ids</description>
    <label>Business Reference</label>
    <nameField>
        <label>Business Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Business_Reference__c.field-meta.xml
<CustomField>
    <fullName>Business_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1911 Lookup to the Business Reference record</description>
    <label>Business Reference</label>
    <referenceTo>Business_Reference__c</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/IXrefIntegrationService.cls
/**
 * @author atg
 * @date   06/29/2022
 * @description This is the service interface for Integrating Xref__c objects
 */
public interface IXrefIntegrationService {
    /**
     * @description create platform Events to integrate Xref__c objects
     * @param xrefList
     * @param topic
     */
    void createIntegrationPlatformEvents(List<Xref__c> xrefList, String topic);

    /**
     * @description when Business_Reference__c records are updated to Success, update any xref records that
     * had a status of 'Waiting for Business'
     * @param businessReferenceList
     * @param changeOfOwnership
     */
    void updateStatusToReadyForIntegration(
        List<Business_Reference__c> businessReferenceList,
        Boolean changeOfOwnership
    );

    /**
     * @description when an Xref record has been deactivated, we will receive a COO Success Integration Status.
     * @param xrefList
     */
    void processCOOSuccess(List<Xref__c> xrefList);
    /**
     * @description Update the Existing Xrefs which are already Provisioned.
     * @param accountsIdSet
     */
    void updateExistingXrefsForAmendaments(Set<Id> accountsIdSet);
    /**
     * @description Update the Existing Business Accounts based on the Active MDS/Drive Xrefs
     * @param xrefList
     */
    void updateBusinessAccountsForXrefs(List<Xref__c> xrefList);
}