sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/Inbound_Ingestion_Log__c.object-meta.xml
<CustomObject>
    <description>LEM-14648: Custom Inbound Ingestion Log object for SSMO Integration.</description>
    <label>Inbound Ingestion Log</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inbound Ingestion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Ingestion Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>LEM-14648: It is used to capture the UUID received by Mulesoft in the payload.</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/PostSalesTransaction__e/PostSalesTransaction__e.object-meta.xml
<CustomObject>
    <description>This event is used to orchestrate the process lifecycle of inbound PostSales transactions.  Generally these are a result of a Mx Portal transaction payload from Kafka being inserted into the Inbound Ingestion Log object.  
It has it&apos;s own platform event since it is time sensitive and the Mx experience can be impacted by how quickly this process is executed.
It is important that the PreSalesTransaction, PostSalesTransaction, and Instant_Ingestor event objects all have the same field shape.  
LEM-19812</description>
    <label>PostSalesTransaction</label>
    <pluralLabel>PostSalesTransactions</pluralLabel>
</CustomObject>

sfdx-source/force-app/tests/classes/integration/platformEvents/PostSalesEventsIntegrationTest.cls
/**
 * @author Deloitte
 * @date 05/11/2024
 * @description Test class for PostSalesTransactionEvents Trigger.
 */
@isTest
public class PostSalesEventsIntegrationTest {
    private static final String UNIQUE_IDENTIFIER = '92108a53-e8d9-4a0c-9193-9152aeb86fe4';
    private static final String EVENT_BUS_SUBSCRIBER_NAME = 'PostSalesTransactionEvents';
    private static final String EVENT_BUS_SUBSCRIBER_TYPE = 'ApexTrigger';
    private static final String EVENT_BUS_SUBSCRIBER_NAME_DOES_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: the event bus subscriber Name does not match with PostSalesTransactionEvents';
    private static final String EVENT_BUS_SUBSCRIBER_TYPE_DOES_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: the event bus subscriber Type does not match with ApexTrigger';
    private static final String POST_SALES_EVENT = 'PostSalesTransaction__e';
    private static final string STORE_ACCOUNT_NAME = 'Test Store Account';
    private static final String SSOB_EVENT_SERVICE = 'SSOB_EVENT_SERVICE';

    /**
     * @description To test PostSales events subscription by the trigger handler.
     */
    @isTest
    private static void testWhenPostSalesEventPublishedThenPostSalesEventsTriggerListens() {
        Id mockInboundingestionlogId = Fake.generateId(Inbound_Ingestion_Log__c.class);
        Inbound_Ingestion_Log__c inboundIngestionLog = new Inbound_Ingestion_Log__c(
            Id = mockInboundingestionlogId,
            UUID__c = UNIQUE_IDENTIFIER
        );
        Test.startTest();
        InstantIngestorEventsService.publishEvents(
            new Map<String, String>{
                SSOB_EVENT_SERVICE => JSON.serialize(new Set<Id>{ inboundIngestionLog.Id })
            },
            PostSalesTransaction__e.SObjectType
        );
        Test.stopTest();
        List<EventBusSubscriber> eventBusSubscriberResult = [
            SELECT Name, Type
            FROM EventBusSubscriber
            WHERE Topic = :POST_SALES_EVENT
        ];
        System.assertEquals(
            EVENT_BUS_SUBSCRIBER_NAME,
            eventBusSubscriberResult[0].Name,
            EVENT_BUS_SUBSCRIBER_NAME_DOES_NOT_MATCH_ASSERT_MESSAGE
        );
        System.assertEquals(
            EVENT_BUS_SUBSCRIBER_TYPE,
            eventBusSubscriberResult[0].Type,
            EVENT_BUS_SUBSCRIBER_TYPE_DOES_NOT_MATCH_ASSERT_MESSAGE
        );
    }
}