sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/Inbound_Ingestion_Log__c.object-meta.xml
<CustomObject>
    <description>LEM-14648: Custom Inbound Ingestion Log object for SSMO Integration.</description>
    <label>Inbound Ingestion Log</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inbound Ingestion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Ingestion Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <description>LEM-21439 as part of this story created this field to Hold the Business Reference External Id (businessId) from the inbound payload received for RESSMO.
This field is used for retry mechanism in case if there is a failure of same businessId Payload before the NNS payload.</description>
    <label>Business Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Created_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Created_Date_Time__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15613: It indicates created date time for Inbound Ingestion Log record.</description>
    <label>Created Date Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Failure_Step__c.field-meta.xml
<CustomField>
    <fullName>Failure_Step__c</fullName>
    <description>LEM-14648: It is used to capture the step number where the record creation process got failed.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Failure Step</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <description>LEM-14648: It is used to capture the event type received from Mulesoft.</description>
    <label>Integration Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Internal_Payload_For_Retry__c.field-meta.xml
<CustomField>
    <fullName>Internal_Payload_For_Retry__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-19796: It is used to store the amendment wrapper received from ENT.</description>
    <label>Internal Payload For Retry</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Parent_Log__c.field-meta.xml
<CustomField>
  <description>LEM-16003: It is used to store self lookup and will be populated for every child fallout/onboarding ingestion log.</description>
    <complianceGroup>GDPR</complianceGroup>
    <fullName>Parent_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Inbound Ingestion Logs</relationshipLabel>
    <relationshipName>Inbound_Ingestion_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14648: It is used to capture the JSON payload received by Mulesoft.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <description>LEM-16003: It is used to store retry count to be set during every retry process.</description>
    <complianceGroup>GDPR</complianceGroup>
    <fullName>Retry_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>LEM-14648: It is used to capture the source of the integration whether it is an SSMO or SSOB.</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SSMO</fullName>
            </value>
            <value>
                <fullName>SSOB</fullName>
            </value>
            <value>
                <fullName>Mx Portal</fullName>
            </value>
            <value>
                <fullName>RESSMO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>LEM-14648: It is used to capture whether the record creation process was successful or failure for the current record.</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>LEM-17453: It is used to capture the unique Id received by Mulesoft in each payload.</description>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>LEM-14648: It is used to capture the UUID received by Mulesoft in the payload.</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/InboundIngestionLogsSelector.cls
/**
 * @author Deloitte
 * @date 05/15/2024
 * @description Selector class for Inbound_Ingestion_Log__c object.
 */
public inherited sharing class InboundIngestionLogsSelector extends fflib_SObjectSelector implements IInboundIngestionLogsSelector {
    private static final String FAILED_STATUS = 'Failed';
    private static final String FALLOUT_INTEGRATION_TYPE = 'Fallout event';
    private static final String ONBOARDING_INTEGRATION_TYPE = 'Onboarding Event';
    private static final String MX_NSE_INTEGRATION_TYPE = 'Mx Portal New Store Expansion';
    private static final String SUCCESS_STATUS = 'Success';
    private static final String SOURCE_SSMO = 'SSMO';

    /**
     * @description Default constructor for the class.
     * @return IInboundIngestionLogsSelector
     */
    public static IInboundIngestionLogsSelector newInstance() {
        return (IInboundIngestionLogsSelector) Application.Selector.newInstance(
            Inbound_Ingestion_Log__c.SObjectType
        );
    }

    /**
     * @description Overriding default getSObjectType method.
     * @return SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Inbound_Ingestion_Log__c.SObjectType;
    }

    /**
     * @description It is used to get the SObjectFields.
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Inbound_Ingestion_Log__c.Id,
            Inbound_Ingestion_Log__c.Failure_Step__c,
            Inbound_Ingestion_Log__c.Parent_Log__c,
            Inbound_Ingestion_Log__c.Payload__c,
            Inbound_Ingestion_Log__c.Status__c,
            Inbound_Ingestion_Log__c.UUID__c,
            Inbound_Ingestion_Log__c.Source__c,
            Inbound_Ingestion_Log__c.Integration_Type__c,
            Inbound_Ingestion_Log__c.Unique_Id__c,
            Inbound_Ingestion_Log__c.Internal_Payload_For_Retry__c
        };
    }

    /**
     * @description It is used to get the Inbound Ingestion Logs by passed recordIds.
     * @param recordIds
     * @return List<Inbound_Ingestion_Log__c>
     */
    public List<Inbound_Ingestion_Log__c> selectById(Set<Id> recordIds) {
        return (List<Inbound_Ingestion_Log__c>) selectSObjectsById(recordIds);
    }

    /**
     * @description  It is used to query parent Inbound Ingestion Log by passed UUIDs.
     * @param uuids
     * @return List<Inbound_Ingestion_Log__c>
     */
    public List<Inbound_Ingestion_Log__c> selectParentInboundIngestionLogsByUUIDs(
        Set<String> uuids
    ) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('UUID__c IN :uuids AND Parent_Log__c = null')
            .setOrdering('Createddate', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }

    /**
     * @description It is used to get the Inbound Ingestion Logs by passed unique identifiers and integration type.
     * @param integrationTypes
     * @param uniqueIdentifiers
     * @return List<Inbound_Ingestion_Log__c>
     */
    public List<Inbound_Ingestion_Log__c> selectInboundIngestionLogsByUniqueIdentifiers(
        Set<String> integrationTypes,
        Set<String> uniqueIdentifiers
    ) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'UUID__c IN :uniqueIdentifiers AND Parent_Log__c = null AND Integration_Type__c IN :integrationTypes'
            );
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }
    /**
     * @description  It is used to query non fallout Inbound Ingestion Log by passed UUIDs .
     * @param uuids
     * @return List<Inbound_Ingestion_Log__c>
     */
    public List<Inbound_Ingestion_Log__c> selectInboundIngestionLogsByUUIDs(Set<String> uuids) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('UUID__c IN :uuids AND Integration_Type__c !=: FALLOUT_INTEGRATION_TYPE');
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }
    /**
     * @description It is used to query the Inbound Ingestion Logs by passed unique identifiers
     * and integration types.
     * @JIRA# LEM-15616
     * @param integrationTypes
     * @param uniqueIdentifiers
     * @return List<Inbound_Ingestion_Log__c>
     */
    public List<Inbound_Ingestion_Log__c> selectInboundIngestionLogsByUUIDsAndIntegrationTypes(
        Set<String> integrationTypes,
        Set<String> uniqueIdentifiers
    ) {
        fflib_QueryFactory query = newQueryFactory()
            .selectField('Integration_Type__c')
            .selectField('Created_Date_Time__c')
            .setCondition(
                'UUID__c IN :uniqueIdentifiers AND Integration_Type__c IN :integrationTypes'
            );
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }

    /**
     * @description Used to return failed ingestion parent logs
     * @param
     * @return Database.QueryLocator
     */
    @SuppressWarnings('PMD.UnusedLocalVariable') //local variabled used but pmd cannot see it
    public Database.QueryLocator selectFailedIngestionLogs() {
        String failedLogStatus = 'Failed';
        fflib_QueryFactory query = newQueryFactory()
            .selectField('Id')
            .selectField('Parent_Log__c')
            .setCondition(
                'Parent_Log__c = null AND Status__c=:failedLogStatus AND Retry_Count__c<3'
            );
        return Database.getQueryLocator(query.toSOQL());
    }

    /**
     * @description Query based on BizIds to return failed inbound ingestion logs
     * @author VenkateshDD | 10-03-2024
     * @param bizIds
     * @return List<Inbound_Ingestion_Log__c>
     **/
    public List<Inbound_Ingestion_Log__c> selectFailedIngestionLogsByBizIds(Set<String> bizIds) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Id')
            .setCondition('Business_Id__c IN : bizIds AND Status__c = :FAILED_STATUS');
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }

    /**
     * @description selects based on the uuid with the given statuses
     * @author VenkateshDD | 10-09-2024
     * @param uuids
     * @param statuses
     * @param source
     * @return List<Inbound_Ingestion_Log__c>
     **/
    public List<Inbound_Ingestion_Log__c> selectByUUIDStatusSource(
        Set<String> uuids,
        Set<String> statuses,
        String source
    ) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Id')
            .selectField('UUID__c')
            .setCondition('UUID__c IN :uuids AND Status__c IN :statuses AND Source__c = :source');
        return (List<Inbound_Ingestion_Log__c>) Database.query(query.toSOQL());
    }
    /**
     * @description It is used to fetch ingestion log based on the integration type and source.
     * @return List<Inbound_Ingestion_Log__c>
     **/
    public Database.QueryLocator selectSuccessIngestionLogsWithSSMOSourceORMxPortalNSEIntegrationType() {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Id')
            .selectField('UUID__c')
            .selectField('Payload__c')
            .setCondition(
                'UUID__c != null AND ((Integration_Type__c = : ONBOARDING_INTEGRATION_TYPE ' +
                'AND Source__c =: SOURCE_SSMO) OR Integration_Type__c =:MX_NSE_INTEGRATION_TYPE) AND Status__c =:SUCCESS_STATUS'
            )
            .setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING);

        return Database.getQueryLocator(query.toSOQL());
    }
}