sfdx-source/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>LEM -186</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/Agreement_Activation_Event__e.object-meta.xml
<CustomObject>
    <description>LEM-2718: performance optimizations</description>
    <label>Agreement Activation Event</label>
    <pluralLabel>Agreement Activation Events</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Agreement_Ids__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Ids__c</fullName>
    <label>Agreement Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-11329: To store the  Specific Topic Name for the Agreement Activation Event.</description>
    <label>Topic</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/triggerHandlers/AgreementActivationEventsHandlerTest.cls
/**
 * @description This is test class for AgreementActivationEvents
 */
@isTest(seeAllData=false)
public class AgreementActivationEventsHandlerTest {
    static final String UPDATE_ACTIVATION_ORDERS_AND_PRODUCTS_FOR_EXISTING_STORES = 'Update Activation Order And Products For Existing Process';
    static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER = 'Create_Activation_Order_Products';
    private static final String EVENT_TOPIC_UPDATE_MERCHANT_SERVICES = 'Update_Merchant_Services';
    private static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP = 'Create_Activation_Order_Products_ARP';
    /**
     * @description Testing the call to the agreement service to activate
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsertEventThenActivateAgreement() {
        Id agreementId = fflib_IDGenerator.generate(Agreement__c.SObjectType);

        Agreement_Activation_Event__e activationEvent = new Agreement_Activation_Event__e(
            Agreement_Ids__c = JSON.serialize(new List<Id>{ agreementId }),
            Topic__c = EVENT_TOPIC_CREATE_ACTIVATION_ORDER
        );

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IActivationOrdersService serviceMock = (IActivationOrdersService) mocks.mock(
            IActivationOrdersService.class
        );

        Application.SERVICE.setMock(IAgreementsService.class, serviceMock);

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(activationEvent);

        Test.stopTest();

        System.assertEquals(
            true,
            sr.isSuccess(),
            'Unexpected Result: agreement activation event publish failed'
        );
    }

    /**
     * @description Testing the call to the agreement service to activate
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsertEventWithTopicThenUpdateServices() {
        Id agreementId = fflib_IDGenerator.generate(Agreement__c.SObjectType);

        Agreement_Activation_Event__e activationEvent = new Agreement_Activation_Event__e(
            Agreement_Ids__c = JSON.serialize(new List<Id>{ agreementId }),
            Topic__c = UPDATE_ACTIVATION_ORDERS_AND_PRODUCTS_FOR_EXISTING_STORES
        );

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IActivationOrdersService serviceMock = (IActivationOrdersService) mocks.mock(
            IActivationOrdersService.class
        );

        Application.SERVICE.setMock(IAgreementsService.class, serviceMock);

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(activationEvent);

        Test.stopTest();

        System.assertEquals(
            true,
            sr.isSuccess(),
            'Unexpected Result: agreement activation event publish failed'
        );
    }

        /**
     * @description Testing the call to the activate order ARP
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsertEventCreationActivationOrderArpThenCreateActivationOrder() {
        Id agreementId = fflib_IDGenerator.generate(Agreement__c.SObjectType);

        Agreement_Activation_Event__e activationEvent = new Agreement_Activation_Event__e(
            Agreement_Ids__c = JSON.serialize(new List<Id>{ agreementId }),
            Topic__c = EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP
        );

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IActivationOrdersService serviceMock = (IActivationOrdersService) mocks.mock(
            IActivationOrdersService.class
        );

        Application.SERVICE.setMock(IAgreementsService.class, serviceMock);

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(activationEvent);

        Test.stopTest();

        System.assertEquals(
            true,
            sr.isSuccess(),
            'Unexpected Result: agreement activation event publish failed'
        );
    }

    /**
     * @description Testing the call to the Update_Merchant_Services
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsertEventWithTopicUpdateMerchantServicesThenUpdateServices() {
        Id agreementId = fflib_IDGenerator.generate(Agreement__c.SObjectType);

        Agreement_Activation_Event__e activationEvent = new Agreement_Activation_Event__e(
            Agreement_Ids__c = JSON.serialize(new List<Id>{ agreementId }),
            Topic__c = EVENT_TOPIC_UPDATE_MERCHANT_SERVICES
        );

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IActivationOrdersService serviceMock = (IActivationOrdersService) mocks.mock(
            IActivationOrdersService.class
        );

        Application.SERVICE.setMock(IAgreementsService.class, serviceMock);

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(activationEvent);

        Test.stopTest();

        System.assertEquals(
            true,
            sr.isSuccess(),
            'Unexpected Result: agreement activation event publish failed'
        );
    }
}