sfdx-source/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>LEM -186</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/Agreement_Activation_Event__e.object-meta.xml
<CustomObject>
    <description>LEM-2718: performance optimizations</description>
    <label>Agreement Activation Event</label>
    <pluralLabel>Agreement Activation Events</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Agreement_Ids__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Ids__c</fullName>
    <label>Agreement Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-11329: To store the  Specific Topic Name for the Agreement Activation Event.</description>
    <label>Topic</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Notifier__e/Notifier__e.object-meta.xml
<CustomObject>
    <description>LEM-955: It allows generic Platform Event schema and the trigger listener to act as dispatcher of the events. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further processing.</description>
    <label>Notifier</label>
    <pluralLabel>Notifiers</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Notifier__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>LEM-955: It stores the data required for processing by the service layer corresponding to the topic. The format may vary by use-case; it may store set of record ids or JSON string. The service layer will process the payload as needed.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Notifier__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-955: It stores use-case for which event is fired. It is used for identifying service layer for further payload processing.</description>
    <label>Topic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Initiated_Time__c.field-meta.xml
<CustomField>
    <fullName>Activation_Initiated_Time__c</fullName>
    <description>LEM-15034 This field holds time when Rate change request is activation initiated</description>
    <label>Activation Initiated Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <description>LEM-6471 This field is used to track rate change request status.</description>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activation Initiated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Associated_stores_updated__c.field-meta.xml
<CustomField>
    <fullName>Associated_stores_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associated stores updated?</label>
    <description>LEM-6471 This field is used to track if associated stores are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Order_Products_Updated__c.field-meta.xml
<CustomField>
    <fullName>Order_Products_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Products Updated</label>
    <description>LEM-6471 This field is used to track if associated order products are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Ready_For_Activation_Time__c.field-meta.xml
<CustomField>
    <fullName>Ready_For_Activation_Time__c</fullName>
    <description>LEM-15034 This field holds start date/time value when Rate Change Request started processing</description>
    <label>Ready For Activation Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/Subscription_Rate_Change__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <nameField>
        <displayFormat>SubscriptionChange-{0000}</displayFormat>
        <label>Subscription Rate Change  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Rate Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Subscription Rate Changes</relationshipLabel>
    <relationshipName>Subscription_Rate_Changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Update_complete__c.field-meta.xml
<CustomField>
    <fullName>Update_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Update complete</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <description>LEM-186: Initial Setup of Agreement</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/services/RateChangeRequestServiceImpl.cls
/**
 * @author Deloitte
 * @date 09/4/2023
 * @description Implementation class for  Rate_Change_Request__c object.
 */
public class RateChangeRequestServiceImpl implements IRateChangeRequestService {
    private static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP = 'Create_Activation_Order_Products_ARP';
    private static final String EVENT_TOPIC_UPDATE_RATE_CHANGE_REQUEST = 'UPDATE_RATE_CHANGE_REQUEST';
    private static final String READY_FOR_ACTIVATION = 'Ready for Activation';
    private static final String ACTIVATION_INITIATED = 'Activation Initiated';
    private static final String STATUS_CANCELED = 'Canceled';
    private static final String AGREEMENT_EVENTS_CHUNK_SIZE = 'Agreement_Events_Chunk_Size';

    /**
     * @description This method is used to complete the Rate Change Request based on Subscription Rate change.
     * @param completedSRCs
     */
    public void setRateChangeRequestComplete(List<Subscription_Rate_Change__c> completedSRCs) {
        Set<Id> rcrIds = new Set<Id>();
        List<Rate_Change_Request__c> rateChangesList = new List<Rate_Change_Request__c>();
        Map<Id, List<Subscription_Rate_Change__c>> rateChangeToAllSubscriptionRateChanges = new Map<Id, List<Subscription_Rate_Change__c>>();
        Map<Id, List<Subscription_Rate_Change__c>> rateChangeToCompletedSubscriptionRateChanges = new Map<Id, List<Subscription_Rate_Change__c>>();
        List<Rate_Change_Request__c> rateChangesToUpdate = new List<Rate_Change_Request__c>();
        List<Rate_Change_Request__c> rateChangesToComplete = new List<Rate_Change_Request__c>();

        rcrIds = getRCRIds(completedSRCs);
        rateChangesList = RateChangeRequestSelector.newInstance()
            .selectRateChangeRequestById(rcrIds);

        for (Rate_Change_Request__c eachRateChange : rateChangesList) {
            List<Subscription_Rate_Change__c> relatedSubscriptionRateChanges = new List<Subscription_Rate_Change__c>();
            relatedSubscriptionRateChanges.addAll(eachRateChange.Subscription_Rate_Changes__r);
            rateChangeToAllSubscriptionRateChanges.put(
                eachRateChange.Id,
                relatedSubscriptionRateChanges
            );
            for (Subscription_Rate_Change__c eachSRC : relatedSubscriptionRateChanges) {
                if (eachSRC.Update_Complete__c) {
                    if (
                        rateChangeToCompletedSubscriptionRateChanges.containsKey(eachRateChange.Id)
                    ) {
                        rateChangeToCompletedSubscriptionRateChanges.get(eachRateChange.Id)
                            .add(eachSRC);
                    } else {
                        rateChangeToCompletedSubscriptionRateChanges.put(
                            eachRateChange.Id,
                            new List<Subscription_Rate_Change__c>{ eachSRC }
                        );
                    }
                }
            }

            if (
                rateChangeToAllSubscriptionRateChanges.get(eachRateChange.Id).size() ==
                rateChangeToCompletedSubscriptionRateChanges.get(eachRateChange.Id).size()
            ) {
                rateChangesToUpdate.add(eachRateChange);
            }
        }

        if (rateChangesToUpdate.isEmpty()) {
            return;
        }

        for (Rate_Change_Request__c eachRcr : rateChangesToUpdate) {
            Rate_Change_Request__c newRcr = new Rate_Change_Request__c(
                Id = eachRcr.Id,
                Order_Products_Updated__c = true
            );
            if (eachRcr.Associated_stores_updated__c) {
                newRcr.Activation_Status__c = READY_FOR_ACTIVATION;
                newRcr.Ready_For_Activation_Time__c = System.Now();
            }
            rateChangesToComplete.add(newRcr);
        }
        updateRateChangeRequests(rateChangesToComplete);
    }

    private Set<Id> getRCRIds(List<Subscription_Rate_Change__c> completedSRCs) {
        Set<Id> rcrIds = new Set<Id>();
        for (Subscription_Rate_Change__c eachItem : completedSRCs) {
            rcrIds.add(eachItem.Rate_Change_Request__c);
        }
        return rcrIds;
    }

    /**
     * @description This method is used to update the Rate Change Request Store Update Flag to true
     * once all the store Accounts are updated in AccountUpdateForActiveRatesBatch.
     * @param rateChangeRequestId
     */
    public void setRateChangeRequestStoreUpdatedFlagTrue(Id rateChangeRequestId) {
        List<Rate_Change_Request__c> rateChangeRequestsToUpdate = new List<Rate_Change_Request__c>();
        List<Rate_Change_Request__c> retrievedRateChanges = RateChangeRequestSelector.newInstance()
            .selectRateChangeRequestById(new Set<Id>{ rateChangeRequestId });
        if (retrievedRateChanges.isEmpty()) {
            return;
        }
        Rate_Change_Request__c newRateChange = new Rate_Change_Request__c(
            Id = retrievedRateChanges[0].Id,
            Associated_stores_updated__c = true
        );
        if (retrievedRateChanges[0].Order_Products_Updated__c) {
            newRateChange.Activation_Status__c = READY_FOR_ACTIVATION;
            newRateChange.Ready_For_Activation_Time__c = System.Now();
        }
        rateChangeRequestsToUpdate.add(newRateChange);
        updateRateChangeRequests(rateChangeRequestsToUpdate);
    }

    /**
     * @description Update Rate Change Requests
     * @param rateChangesToUpdate
     */
    private void updateRateChangeRequests(List<Rate_Change_Request__c> rateChangesToUpdate) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        uow.registerDirty(rateChangesToUpdate);
        commitWork(uow);
    }

    /**
     * @description Generates Activation Order Creation Event once Rate Change Request Activation Status is set to Ready For Activation.
     * @param rcrIds
     */
    public void publishCreateActivationOrdersNotifierEvent(Set<Id> rcrIds) {
        Set<Id> agreementIds = new Set<Id>();
        Map<Id, Agreement__c> agreementsToActivateMap = new Map<Id, Agreement__c>();
        agreementsToActivateMap = getAgreementsToActivateRates(rcrIds);
        agreementIds = agreementsToActivateMap.keySet();

        if (agreementIds.isEmpty()) {
            return;
        }
        Integer createActivationOrderPayloadChunkSize = Integer.valueOf(
            StaticConfigurationsSelector.newInstance()
                .getInstanceValue(AGREEMENT_EVENTS_CHUNK_SIZE)
                .Configuration_Value__c
        );

        publishBulkAgreementEvents(
            NotifierEventsPayloadGenerationService.generateChunkedPayloadsBySobjectIds(
                agreementIds, //changed paylod Ids to agreementIds
                createActivationOrderPayloadChunkSize
            )
        );
    }

    /**
     * @description It creates Agreement ACtivation Event with passed payloads
     * @JIRA# LEM-5588
     * @param payloads
     */
    private void publishBulkAgreementEvents(List<String> payloads) {
        if (payloads == null) {
            return;
        }
        fflib_ISObjectUnitOfWork uow = Application.UNITOFWORK.newInstance();
        for (String eachPayload : payloads) {
            uow.registerPublishAfterSuccessTransaction(
                new Agreement_Activation_Event__e(
                    Agreement_Ids__c = eachPayload,
                    Topic__c = EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP
                )
            );
        }
        commitWork(uow);
    }

    /**
     * @description It is used to get Rate Change Requests
     * which has all the store accounts updated with its Id.
     * @param rcrIds
     * @return agreementsToActivateMap
     */
    private Map<Id, Agreement__c> getAgreementsToActivateRates(Set<Id> rcrIds) {
        Map<Id, Agreement__c> agreementsToActivateMap = new Map<Id, Agreement__c>(
            AgreementsSelector.newInstance().selectStoreAgreementsByRcrIds(rcrIds)
        );
        return agreementsToActivateMap;
    }

    /**
     * @description This method is used to handle the published Notifier events.
     * @param notifierEvents list of platform events with payload
     */
    public void handleNotifierEvents(List<Notifier__e> notifierEvents) {
        Set<Id> recordIdsByPayload;

        for (Notifier__e eachEvent : notifierEvents) {
            if (eachEvent.Topic__c == EVENT_TOPIC_UPDATE_RATE_CHANGE_REQUEST) {
                recordIdsByPayload = (Set<Id>) JSON.deserialize(
                    eachEvent.Payload__c,
                    Set<Id>.class
                );
            }
            if (recordIdsByPayload == null) {
                continue;
            }
            updateRateChangeRequestAsActivationInitiated(recordIdsByPayload);
        }
    }

    private void updateRateChangeRequestAsActivationInitiated(Set<Id> recordIdsByPayload) {
        List<Rate_Change_Request__c> rateChangeRequests = new List<Rate_Change_Request__c>();
        List<Rate_Change_Request__c> rateChangeRequestsToUpdate = new List<Rate_Change_Request__c>();

        rateChangeRequests = RateChangeRequestSelector.newInstance()
            .selectRateChangeRequestById(recordIdsByPayload);

        if (rateChangeRequests.isEmpty()) {
            return;
        }

        for (Rate_Change_Request__c eachRCR : rateChangeRequests) {
            if (eachRCR.Activation_Status__c == READY_FOR_ACTIVATION) {
                Rate_Change_Request__c newRCR = new Rate_Change_Request__c(
                    Id = eachRCR.Id,
                    Activation_Status__c = ACTIVATION_INITIATED,
                    Activation_Initiated_Time__c = System.Now()
                );
                rateChangeRequestsToUpdate.add(newRCR);
            }
        }

        if (!rateChangeRequestsToUpdate.isEmpty()) {
            updateRateChangeRequests(rateChangeRequestsToUpdate);
        }
    }
    /**
     * @description It is used to update all Rate Change Requests to cancelled.
     * @param rateChangeRequests
     */
    public void updateRateChangeRequestToCancelled(
        List<Rate_Change_Request__c> rateChangeRequests
    ) {
        List<Rate_Change_Request__c> cancelledRCRList = new List<Rate_Change_Request__c>();
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        if (!rateChangeRequests.isEmpty()) {
            for (Rate_Change_Request__c eachRCR : rateChangeRequests) {
                Rate_Change_Request__c rateChange = new Rate_Change_Request__c(
                    Id = eachRCR.Id,
                    Status__c = STATUS_CANCELED
                );
                cancelledRCRList.add(rateChange);
            }
        } else {
            return;
        }
        if (!cancelledRCRList.isEmpty()) {
            uow.registerDirty(cancelledRCRList);
        }
        commitWork(uow);
    }

    private void commitWork(fflib_ISObjectUnitOfWork uow) {
        try {
            uow.commitWork();
        } catch (Exception ex) {
            Logger.publish(LogEntry.newExceptionLog(ex, LogEntry.SeverityLevel.HIGH));
            throw ex;
        }
    }
}