sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/Legal_Entity_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>LEM-578: To store mapping of legal entity name with account fields.</description>
    <label>Legal Entity Mapping</label>
    <pluralLabel>Legal Entity Mapping</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/fields/Billing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Code__c</fullName>
    <description>LEM-578: To store the billing state code.</description>
    <label>Billing State Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/fields/Currency_ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_ISO_Code__c</fullName>
    <description>LEM-4692: It stores currency corresponding to DoorDash Legal Entity.</description>
    <label>Currency ISO Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
                <default>true</default>
                <label>AUD</label>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CZK</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GEL</fullName>
            </value>
            <value>
                <fullName>HRK</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>ILS</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KZT</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>RSD</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <description>LEM-578: To store the legal entity name.</description>
    <label>Legal Entity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <description>LEM-578: To store the primary vertical values.</description>
    <label>Primary Vertical</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Legal_Entity_Mapping__mdt/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <description>LEM-2031: To store the Record Type Name of the Account.</description>
    <label>Record Type Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/LegalEntityMappingSelector.cls
/**
 * @author Deloitte
 * @date 05/24/2022
 * @description Selector class for legal entity mapping metadata
 */
public inherited sharing class LegalEntityMappingSelector extends fflib_SObjectSelector implements ILegalEntityMappingSelector {
    /**
     * @description default constructor for the class
     * @return ILegalEntityMappingSelector - interface of LegalEntityMappingSelector
     */
    public static ILegalEntityMappingSelector newInstance() {
        return (ILegalEntityMappingSelector) Application.Selector.newInstance(
            Legal_Entity_Mapping__mdt.SObjectType
        );
    }

    /**
     * @description override default getSObjectType method
     * @return SObjectType - object type of metadata
     */
    public Schema.SObjectType getSObjectType() {
        return Legal_Entity_Mapping__mdt.SObjectType;
    }

    /**
     * @description Method fetches all metadata records
     * @return List<Legal_Entity_Mapping__mdt> - returns list of metadata records
     */
    public List<Legal_Entity_Mapping__mdt> getAllValues() {
        fflib_QueryFactory query = newQueryFactory();
        query.addOrdering('DeveloperName', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Legal_Entity_Mapping__mdt>) Database.query(query.toSOQL());
    }

    /**
     * @description This method is for getting the fields on Legal_Entity_Mapping__mdt
     * @return List<Schema.SObjectField>- Legal_Entity_Mapping__mdt fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Legal_Entity_Mapping__mdt.Label,
            Legal_Entity_Mapping__mdt.DeveloperName,
            Legal_Entity_Mapping__mdt.Legal_Entity_Name__c,
            Legal_Entity_Mapping__mdt.Billing_State_Code__c,
            Legal_Entity_Mapping__mdt.Primary_Vertical__c,
            Legal_Entity_Mapping__mdt.Record_Type_Name__c,
            Legal_Entity_Mapping__mdt.Currency_ISO_Code__c
        };
    }
}