sfdx-source/force-app/main/default/objects/Account/fields/Account_ID18__c.field-meta.xml
<CustomField>
    <fullName>Account_ID18__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-96: This Field is used to store the 18 digit SFDC Id for the account.</description>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID18</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Integration_Request__c.field-meta.xml
<CustomField>
    <fullName>Integration_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-8993: COO Same Store
On create event stamp the parent Integration request on the Store Account</description>
    <label>Integration Request</label>
    <referenceTo>Integration_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Xref__c.field-meta.xml
<CustomField>
    <fullName>Xref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xref</label>
    <referenceTo>Xref__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <description>Holds the integration requests from BAT and sync the data to the heroku and Figment. 
BZAP-18797</description>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>This field holds COO payload. instead of creating multiple fields we are using this field to hold the payload</description>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/Onboarding_Activation__e.object-meta.xml
<CustomObject>
    <description>LEM-13303: It allows generic Platform Event schema and the trigger listener to act as dispatcher of the events for Merchant Services related functionality. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further processing.</description>
    <label>Onboarding &amp; Activation</label>
    <pluralLabel>Onboarding &amp; Activations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>LEM-13303: t stores the data required for processing by the service layer corresponding to the topic. The format may vary by use-case; it may store set of record ids or JSON string. The service layer will process the payload as needed.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Onboarding_Activation__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-13303: It stores use-case for which event is fired. It is used for identifying service layer for further payload processing.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the ID of the associated backend record.</description>
    <externalId>true</externalId>
    <inlineHelpText>Represents the ID of the associated backend record</inlineHelpText>
    <label>Store ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Salesforce_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Account_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-800: Represents the name of the business or store account in SFDC.</description>
    <inlineHelpText>Represents the name of the business or store account in SFDC</inlineHelpText>
    <label>Salesforce Account Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/FraudEventsServiceImpl.cls
/**
 * @author Deloitte
 * @date 07/01/2024
 * @description Service Implementation for processing Fraud Events.
 */
public inherited sharing class FraudEventsServiceImpl implements IFraudEventsService {
    private static final String BUSINESS_VERIFICATION = 'BusinessVerification';
    private static final String EVENT_TOPIC_FRAUD_EVENT_CHECK = 'EVENT_TOPIC_FRAUD_EVENT_CHECK';
    private static final String PRIMARY_VERTICAL_RX = 'Rx';
    private static final String STORE_ID = 'StoreId';
    private enum EventTopics {
        EVENT_TOPIC_FRAUD_EVENT_CHECK
    }
    private static final Map<String, EventTopics> EVENT_TOPIC_MAPPINGS = new Map<String, EventTopics>{
        EVENT_TOPIC_FRAUD_EVENT_CHECK => EventTopics.EVENT_TOPIC_FRAUD_EVENT_CHECK
    };

    /**
     * @description It is used to handle the published onboardingActivationsEvents.
     * @param onboardingActivationsEvents List of platform events with payload.
     */
    public void handleOnboardingActivationsEvents(
        List<Onboarding_Activation__e> onboardingActivationsEvents
    ) {
        Set<Id> recordIdsByPayload;
        Set<Id> fraudEventIntegrationRequestIds = new Set<Id>();
        for (Onboarding_Activation__e eachEvent : onboardingActivationsEvents) {
            switch on EVENT_TOPIC_MAPPINGS.get(eachEvent.Topic__c) {
                when EVENT_TOPIC_FRAUD_EVENT_CHECK {
                    recordIdsByPayload = (Set<Id>) JSON.deserialize(
                        eachEvent.Payload__c,
                        Set<Id>.class
                    );
                    if (recordIdsByPayload == null) {
                        continue;
                    }
                    fraudEventIntegrationRequestIds.addAll(recordIdsByPayload);
                }
            }
        }
        if (!fraudEventIntegrationRequestIds.isEmpty()) {
            parseFraudEventPayloads(fraudEventIntegrationRequestIds);
        }
    }

    /**
     * @description It is used to parse Business Verification Details for all stores.
     * @param fraudEventIntegrationRequestIds
     */
    private void parseFraudEventPayloads(Set<Id> fraudEventIntegrationRequestIds) {
        List<String> storeIds = new List<String>();
        Set<Id> accountIds = new Set<Id>();
        Map<String, BusinessVerficationDetails> storeIdsToBusinessVertificationDetails = new Map<String, BusinessVerficationDetails>();
        Map<Id, String> salesforceAccountIdToStoreId = new Map<Id, String>();
        if (fraudEventIntegrationRequestIds.isEmpty()) {
            return;
        }
        BusinessVerficationDetails storeData;
        Map<String, Object> dataString;
        for (
            Integration_Request__c eachIntegrationRequest : IntegrationRequestsSelector.newInstance()
                .selectById(fraudEventIntegrationRequestIds)
        ) {
            dataString = (Map<String, Object>) JSON.deserializeUntyped(
                eachIntegrationRequest.Payload__c
            );
            storeData = new BusinessVerficationDetails((String) dataString.get(STORE_ID));
            storeData.businessVerificationDetails = parseBusinessVerificationDetails(
                dataString.get(BUSINESS_VERIFICATION)
            );
            storeIds.add((String) dataString.get(STORE_ID));
            storeIdsToBusinessVertificationDetails.put(
                (String) dataString.get(STORE_ID),
                storeData
            );
        }
        for (
            Xref__c eachXref : XrefsSelector.newInstance()
                .selectXrefsByExternalIdsAndPrimaryVertical(storeIds, PRIMARY_VERTICAL_RX)
        ) {
            accountIds.add(eachXref.Salesforce_Account_Name__r.Account_ID18__c);
            salesforceAccountIdToStoreId.put(
                eachXref.Salesforce_Account_Name__r.Account_ID18__c,
                eachXref.External_Id__c
            );
        }
        //LEM-15834: This updates the Work Steps Status based on Business Verification details.
        WorkStepsService.updateWorkStepsStatusDetailsByBusinessVerificationStatusDetails(
            accountIds,
            salesforceAccountIdToStoreId,
            storeIdsToBusinessVertificationDetails
        );
    }

    /**
     * @description It parses Business Verification Details for all stores.
     * @param businessVerificationDetails
     * @return BusinessVerficationDetails.BusinessVerificationStatusDetails
     */
    private BusinessVerficationDetails.BusinessVerificationStatusDetails parseBusinessVerificationDetails(
        Object businessVerificationDetails
    ) {
        return (BusinessVerficationDetails.BusinessVerificationStatusDetails) JSON.deserialize(
            JSON.serialize(businessVerificationDetails),
            BusinessVerficationDetails.BusinessVerificationStatusDetails.class
        );
    }
}