sfdx-source/force-app/main/default/objects/Account/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-566: The activation status of the store.</description>
    <inlineHelpText>Represents the activation status of the store</inlineHelpText>
    <label>Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Order protocol defined for the Mxs being onboarded</description>
    <inlineHelpText>Signifies the type of order protocol requested for the Mx store</inlineHelpText>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
            </value>
            <value>
                <fullName>Android Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>POS (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet Return Label</fullName>
            </value>
            <value>
                <fullName>Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet and Printer (DoorDash Owns)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Indicates the type of request
BZAP-19603</description>
    <inlineHelpText>Select &apos;POS Integration Request&apos; if the Mx is an existing activated Partner and would like to transition to POS Order Protocol</inlineHelpText>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS Integration Request</fullName>
            </value>
            <value>
                <fullName>POS Test Store for New Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the Business Id that was provisioned during the SSMO process.</description>
    <label>Business Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It stores the Order Protocol value from SSMO on Contact.</description>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Protocol</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Segment on the Account associated with the Contact LEM-15209</description>
    <formula>TEXT(Account.Segment__c)</formula>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13790: It indicates active or inactive status of the SMB contact.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>Indicates whether the status of the SMB contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <description>LEM-14822: It represents the Store Id that was provisioned during the SSMO process.</description>
    <label>Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/Staging_Bulk_Upload_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-15978: Stores Bulk Equipment/Photoshoot references and their status.</description>
    <label>Staging Bulk Upload Reference</label>
    <nameField>
        <displayFormat>BL-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Bulk Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Bulk Upload References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>LEM-15978: Stores dependent picklist values based on the type.</description>
    <inlineHelpText>Picklist values populate based on the type.</inlineHelpText>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Net-New</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-15978: Stores file upload status - Success, In Progress Or Failed.</description>
    <inlineHelpText>It stores file upload status - Success, In Progress Or Failed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-15978: Stores the controlling picklist value for request type field.</description>
    <inlineHelpText>Controlling picklist for request type field.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/Staging_Bulk_Upload_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-15978: Stores CSV file records. System doesn&apos;t allow partial load in case of any error.</description>
    <label>Staging Bulk Upload Request</label>
    <nameField>
        <displayFormat>SBR-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Staging Bulk Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Bulk Upload Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-15978: Stores Business Account Id (18 digits).</description>
    <label>Business ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staging Bulk Upload Requests</relationshipLabel>
    <relationshipName>Staging_Bulk_Upload_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-15978: Stores Contact Id (18 digits).</description>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staging Bulk Upload Requests</relationshipLabel>
    <relationshipName>Staging_Bulk_Upload_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <description>LEM-15978: Stores Order Protocol for Tablet &amp; Marketing-Kit Types.</description>
    <label>Order Protocol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>LEM-15978: Formula for Request Type From The Related Reference (Parent) Record.</description>
    <formula>TEXT( Staging_Upload_Ref__r.Request_Type__c )</formula>
    <label>Request Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Staging_Upload_Ref__c.field-meta.xml
<CustomField>
    <fullName>Staging_Upload_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15978: Stores Staging Bulk Reference (Parent) Record Id.</description>
    <label>Staging Upload Ref</label>
    <referenceTo>Staging_Bulk_Upload_Reference__c</referenceTo>
    <relationshipLabel>Staging Bulk Upload Requests</relationshipLabel>
    <relationshipName>Staging_Bulk_Upload_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-15978: Stores Status Of the Request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Store_ID__c.field-meta.xml
<CustomField>
    <fullName>Store_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-15978: Stores Store Account Id (18 digits).</description>
    <label>Store ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staging Bulk Upload Requests (Store ID)</relationshipLabel>
    <relationshipName>Staging_Bulk_Upload_Requests1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-15978: Formula for Type From The Related Reference (Parent) Record.</description>
    <formula>TEXT(Staging_Upload_Ref__r.Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Order_Protocol.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Android Tablet (Merchant Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet and Printer (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (Merchant Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet Return Label</fullName>
    </customValue>
    <customValue>
        <fullName>POS (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
    </customValue>
    <customValue>
        <fullName>One Time Tablet and Printer Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Indicator Unspecified</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <description>LEM-179 – Initial Setup of Quote object</description>
    <masterLabel>Order Protocol</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/selectors/StagingBulkUploadRequestSelectorTest.cls
/**
 * @author Deloitte
 * @date 08/08/2024
 * @description Test class for StagingBulkUploadRequestSelector class.
 */
@isTest
private class StagingBulkUploadRequestSelectorTest {
    private static final String FIELDS_DO_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: Mismatch in field list';
    private static final String OBJECT_DO_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: The object type must be Staging_Bulk_Upload_Request__c';
    private static final String EMPTY_LIST_ASSERT_MESSAGE = 'Unexpected Result: number of records returned does not match the expected outcome';
    private static final String ASSERT_MESSAGE_STAGING_REQUEST_ORDER_PROTOCOL = 'Unexpected result: Order Protocl is not matching';
    private static final String ACCOUNT_NAME = 'Test McDonald Account';
    private static final String ACCOUNT_NAME_STORE = 'Store Account';
    private static final String ACCOUNT_SEGMENT_SMB = 'SMB';
    private static final String ACCOUNT_BILLING_CITY = 'Missoula';
    private static final String ACCOUNT_BILLING_COUNTRY = 'United States';
    private static final String ACCOUNT_BILLING_POSTAL_CODE = '1234';
    private static final string ACCOUNT_BILLING_STATE = 'California';
    private static final String ACCOUNT_BILLING_COUNTRY_CODE = 'US';
    private static final string ACCOUNT_BILLING_STATE_CODE = 'CA';
    private static final String ACCOUNT_BILLING_STREET = '221B Baker Street';
    private static final String ACCOUNT_ACTIVATION_STATUS_DEACTIVATED = 'Deactivated';
    private static final String ACCOUNT_RECORD_TYPE_NAME_BUSINESS = 'Business';
    private static final String ACCOUNT_BUSINESS_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get(ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
        .getRecordTypeId();
    private static final String ACCOUNT_RECORD_TYPE_NAME_STORE = 'Store';
    private static final String ACCOUNT_STORE_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get(ACCOUNT_RECORD_TYPE_NAME_STORE)
        .getRecordTypeId();
    private static final String CONTACT_EMAIL = 'test@ContactsSelectorTest.com';
    private static final String CONTACT_FIRST_NAME = 'FirstName';
    private static final String CONTACT_LAST_NAME = 'LastName';
    private static final String TYPE_TABLET = 'Tablet';
    private static final String TYPE_MARKETING_KIT = 'Marketing Kit';
    private static final String SUB_TYPE_PHOTOSHOOT = 'Photoshoot';
    private static final String STATUS_SUCCESS = 'Success';

    /**
     * @description To test constructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheckSObjectTypeAndFieldList() {
        StagingBulkUploadRequestSelector stagingRequestInstance = new StagingBulkUploadRequestSelector();
        Schema.SObjectType typeOfObject = stagingRequestInstance.getSObjectType();
        StagingBulkUploadRequestSelector.newInstance();
        System.assertEquals(
            Schema.Staging_Bulk_Upload_Request__c.SObjectType,
            typeOfObject,
            OBJECT_DO_NOT_MATCH_ASSERT_MESSAGE
        );
    }

    /**
     * @description To validate the Staging Request Records selection when Reference Id is passed.
     */
    @isTest
    private static void testWhenReferenceIdsPassedThenReturnReferenceRequestRecords() {
        Account businessAccount = new Account(
            Name = ACCOUNT_NAME,
            RecordTypeId = ACCOUNT_BUSINESS_RECORD_TYPE_ID,
            Segment__c = ACCOUNT_SEGMENT_SMB
        );
        insert businessAccount;

        Account storeAccount = new Account(
            Name = ACCOUNT_NAME_STORE,
            Activation_Status__c = ACCOUNT_ACTIVATION_STATUS_DEACTIVATED,
            BillingStreet = ACCOUNT_BILLING_STREET,
            ParentId = businessAccount.Id,
            RecordTypeId = ACCOUNT_STORE_RECORD_TYPE_ID,
            BillingCity = ACCOUNT_BILLING_CITY,
            BillingPostalCode = ACCOUNT_BILLING_POSTAL_CODE,
            BillingCountry = ACCOUNT_BILLING_COUNTRY,
            BillingState = ACCOUNT_BILLING_STATE,
            Segment__c = ACCOUNT_SEGMENT_SMB
        );
        insert storeAccount;

        Contact newContact = new Contact(
            Email = CONTACT_EMAIL,
            Firstname = CONTACT_FIRST_NAME,
            LastName = CONTACT_LAST_NAME
        );
        insert newContact;

        Staging_Bulk_Upload_Reference__c stagingReferenceRec = new Staging_Bulk_Upload_Reference__c();
        stagingReferenceRec.Type__c = TYPE_MARKETING_KIT;
        stagingReferenceRec.Request_Type__c = TYPE_MARKETING_KIT;
        stagingReferenceRec.Status__c = STATUS_SUCCESS;
        insert stagingReferenceRec;

        Staging_Bulk_Upload_Request__c stagingRequestRec = new Staging_Bulk_Upload_Request__c();
        stagingRequestRec.Staging_Upload_Ref__c = stagingReferenceRec.Id;
        stagingRequestRec.Order_Protocol__c = TYPE_TABLET;
        stagingRequestRec.Address__CountryCode__s = ACCOUNT_BILLING_COUNTRY_CODE;
        stagingRequestRec.Address__Street__s = ACCOUNT_BILLING_STREET;
        stagingRequestRec.Address__City__s = ACCOUNT_BILLING_CITY;
        stagingRequestRec.Address__StateCode__s = ACCOUNT_BILLING_STATE_CODE;
        stagingRequestRec.Address__PostalCode__s = ACCOUNT_BILLING_POSTAL_CODE;
        stagingRequestRec.Business_ID__c = businessAccount.Id;
        stagingRequestRec.Contact_Id__c = newContact.Id;
        stagingRequestRec.Store_ID__c = storeAccount.Id;
        insert stagingRequestRec;

        Test.startTest();
        Database.QueryLocator bulkUploadRequestRecords = StagingBulkUploadRequestSelector.newInstance().selectStagingRequestsByReferenceIds(new Set<String>{ stagingReferenceRec.id });
        Test.stopTest();

        Database.QueryLocatorIterator iteratorOnBulkUploadRequestRecords = bulkUploadRequestRecords.iterator();
        List<Staging_Bulk_Upload_Request__c> fetchedBulkUploadRequestRecords = new List<Staging_Bulk_Upload_Request__c>();

        while (iteratorOnBulkUploadRequestRecords.hasNext()) {
            fetchedBulkUploadRequestRecords.add((Staging_Bulk_Upload_Request__c) iteratorOnBulkUploadRequestRecords.next());
        }
        System.assertEquals(
            1,
            fetchedBulkUploadRequestRecords.size(),
            EMPTY_LIST_ASSERT_MESSAGE
        );
        System.assertEquals(
            TYPE_TABLET,
            fetchedBulkUploadRequestRecords[0].Order_Protocol__c,
            ASSERT_MESSAGE_STAGING_REQUEST_ORDER_PROTOCOL
        );
    }
}