sfdx-source/force-app/main/default/objects/Account/fields/Activated_Centrally_AC__c.field-meta.xml
<CustomField>
    <fullName>Activated_Centrally_AC__c</fullName>
    <description>LEM-658: Indicates if the stores are activated by the activation team.</description>
    <inlineHelpText>Indicates if the stores are activated by the activation team</inlineHelpText>
    <label>Activated Centrally (AC)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Menu_to_be_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Menu_to_be_Completed_By__c</fullName>
    <description>LEM-658: Indicates who will complete Work Order menu.</description>
    <inlineHelpText>Signifies the team that will complete menu setup</inlineHelpText>
    <label>Menu to be Completed By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>DoorDash Onboarding Team</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>None - Menu Setup Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Menu_UI_Type__c.field-meta.xml
<CustomField>
    <fullName>Menu_UI_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1241: Indicates whether Mx will be on restaurant or retail UI.</description>
    <label>Menu UI Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Minimum_Prep_Time__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Prep_Time__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Indicates minimum prep time for order e.g., for new vertical flower shops.</description>
    <inlineHelpText>Signifies minimum prep time in minutes for order e.g., for new vertical flower shops</inlineHelpText>
    <label>Minimum Prep Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Order protocol defined for the Mxs being onboarded</description>
    <inlineHelpText>Signifies the type of order protocol requested for the Mx store</inlineHelpText>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
            </value>
            <value>
                <fullName>Android Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>POS (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet Return Label</fullName>
            </value>
            <value>
                <fullName>Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet and Printer (DoorDash Owns)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/POS_Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>POS_Integration_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Indicates the ID of the associated Mx Store POS. Needed to complete POS integration process.</description>
    <inlineHelpText>Signifies the ID of the associated Mx Store POS. Needed to complete POS integration process</inlineHelpText>
    <label>POS Integration ID</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-280 This picklist defines the primary vertical of the Mx.</description>
    <inlineHelpText>Primary vertical of the Mx</inlineHelpText>
    <label>Primary Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Shopping_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: By default the Shopping Protocol is Mx Pick.</description>
    <inlineHelpText>Shopping protocol signifies retail pick type. By default the Shopping Protocol is Mx Pick</inlineHelpText>
    <label>Shopping Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mx Pick</fullName>
            </value>
            <value>
                <fullName>Dasher Pick</fullName>
            </value>
            <value>
                <fullName>Shopper Pick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/Store_Readiness_Validation_Rule__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores the details of validation rules that needs to be evaluated for store readiness check.</description>
    <label>Readiness Validation Rule</label>
    <pluralLabel>Readiness Validation Rules</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed when the validation rule criteria fails.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates object name on which the validation needs to be performed.</description>
    <label>Object Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Service_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Method_Name__c</fullName>
    <description>LEM-1684: It indicates the service method name where automation is written for the validation rule.</description>
    <label>Service Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <description>LEM-280: This picklist value set is created to define the verticals and sub-verticals associated with store and business accounts.</description>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/services/BulkOnboardingReadinessCheckServiceTest.cls
/**
 * @author BizApps
 * @date 9-June-2024
 * @description Test class for the BulkOnboardingReadinessCheckService class
**/
@IsTest
private class BulkOnboardingReadinessCheckServiceTest {
    private static final String ACCOUNT_OBJECT = 'Account';
    private static final String ACTIVATE_CENTRALLY_YES = 'Yes';
    private static final String MENU_TO_BE_COMPLETED_BY_ACCOUNT_OWNER = 'Account Owner';
    private static final String MENU_UI_TYPE_RETAIL = 'Retail';
    private static final String MENU_UI_TYPE_RESTAURANT = 'Restaurant';
    private static final String ORDER_PROTOCOL_POS = 'POS';
    private static final String PRIMARY_VERTICAL_FLORAL = 'Floral';
    private static final String READINESS_VALIDATION_MISSING_ERROR = 'Readiness Check validation message is not in the list of error messages.';
    private static final String SHOPPER_PICK_SHOPPING_PROTOCOL = 'Shopper Pick';
    private static final String SHOPPING_PROTOCOL_DASHER_PICK = 'Dasher Pick';

    private static final String METHOD_ACTIVATE_CENTRALLY = 'validateActivateCentrally';
    private static final String METHOD_MIN_PREP_TIME = 'validateMinimumPrepTime';
    private static final String METHOD_NULL_FIELDS = 'validateNullFieldValuesOnStore';
    private static final String METHOD_POS_INTEGRATION = 'validatePOSIntegrationFields';
    private static final String METHOD_SHOPPING_PROTOCOL_REQUIRED_MENU_UI = 'validateShoppingProtocolMandatoryOnRetailMenuUIType';
    private static final String METHOD_SHOPPING_PROTOCOL_BLANK_MENU_UI = 'validateShoppingProtocolBlankOnRxMenuUIType';

    /**
     * @description Lists the Store Readiness Metadata Rule records by their Service Method Names
     * @return Map<String, Store_Readiness_Validation_Rule__mdt>
    **/
    public static Map<String, Store_Readiness_Validation_Rule__mdt> metadataRecordsByMethodNames { get {
        if(metadataRecordsByMethodNames == null) {
            metadataRecordsByMethodNames = new Map<String, Store_Readiness_Validation_Rule__mdt>{

            };
        }
        return metadataRecordsByMethodNames;
    } set;}

    private static Map<String, Store_Readiness_Validation_Rule__mdt> readinessChecksByNames { get {
        if(readinessChecksByNames == null) {
            readinessChecksByNames = new Map<String, Store_Readiness_Validation_Rule__mdt>();

            for(Store_Readiness_Validation_Rule__mdt thisReadinessCheck : StoreReadinessValidationRulesSelector.newInstance().selectAllValidReadinessValidationRules()) {
                if(thisReadinessCheck.Object_Name__c != ACCOUNT_OBJECT) {
                    continue;
                }

                readinessChecksByNames.put(thisReadinessCheck.Service_Method_Name__c, thisReadinessCheck);
            }
        }

        return readinessChecksByNames;
    } set;}

    private static BulkCorporateOnboardingWrappers.StoreInfo mockWrapper {get {
        if(mockWrapper == null) {
            mockWrapper = new BulkCorporateOnboardingWrappers.StoreInfo(null, null, null);
            mockWrapper.rowNumber = 1;
        }
        return mockWrapper;
    } set;}


    @IsTest
    static void testWhenRunningReadinessChecksThenReturnCorrectErrors() {
        Account storeWithActivateCentrallyErrors = new Account(Menu_to_be_Completed_By__c = MENU_TO_BE_COMPLETED_BY_ACCOUNT_OWNER, Activated_Centrally_AC__c = ACTIVATE_CENTRALLY_YES);
        Account storeWithMinPrepTimeErrors = new Account(Primary_Vertical__c = PRIMARY_VERTICAL_FLORAL, Minimum_Prep_Time__c = null);
        Account storeWithPosErrors = new Account(Order_Protocol__c = ORDER_PROTOCOL_POS, POS_Integration_ID__c = null);
        Account storeWithMenuUiTypeRequiredErrors = new Account(Menu_UI_Type__c = MENU_UI_TYPE_RETAIL);
        Account storeWithMenuUiTypeBlankErrors = new Account(Menu_UI_Type__c = MENU_UI_TYPE_RESTAURANT, Shopping_Protocol__c = SHOPPING_PROTOCOL_DASHER_PICK);

        Account storeWithMultipleErrors = new Account();
        storeWithMultipleErrors.Menu_to_be_Completed_By__c = MENU_TO_BE_COMPLETED_BY_ACCOUNT_OWNER;
        storeWithMultipleErrors.Activated_Centrally_AC__c = ACTIVATE_CENTRALLY_YES;
        storeWithMultipleErrors.Menu_UI_Type__c = MENU_UI_TYPE_RESTAURANT;
        storeWithMultipleErrors.Shopping_Protocol__c = SHOPPING_PROTOCOL_DASHER_PICK;

        assertReadinessErrorForRecord(storeWithActivateCentrallyErrors, METHOD_ACTIVATE_CENTRALLY);
        assertReadinessErrorForRecord(storeWithMinPrepTimeErrors, METHOD_MIN_PREP_TIME);
        assertReadinessErrorForRecord(storeWithPosErrors, METHOD_POS_INTEGRATION);
        assertReadinessErrorForRecord(storeWithMenuUiTypeRequiredErrors, METHOD_SHOPPING_PROTOCOL_REQUIRED_MENU_UI);
        assertReadinessErrorForRecord(storeWithMenuUiTypeBlankErrors, METHOD_SHOPPING_PROTOCOL_BLANK_MENU_UI);

        // Assert the multi error scenario
        List<BulkCorporateOnboardingWrappers.ErrorMessage> multipleMessages = BulkOnboardingReadinessCheckService.runReadinessChecksAndGetErrors(storeWithMultipleErrors, mockWrapper);
        System.assert(multipleMessages.size() > 1, 'There should be several Readiness Check validations for this Store.');
    }

    @IsTest
    static void testWhenRunningPhoneValidationsThenReturnErrorsIfNeeded() {
        Account testPhoneRecordNoError = new Account(Phone = '15553334444');
        String shouldBeNull = BulkOnboardingReadinessCheckService.runPhoneValidation(
            testPhoneRecordNoError,
            'Phone'
        );
        System.assertEquals(
            null,
            shouldBeNull,
            'The Phone should not throw an error when it is valid'
        );
    }

    private static void assertReadinessErrorForRecord(SObject recordToCheck, String validationMethod) {
        List<BulkCorporateOnboardingWrappers.ErrorMessage> errorMessagesReceived = BulkOnboardingReadinessCheckService.runReadinessChecksAndGetErrors(recordToCheck, mockWrapper);

        String errorMessageToCheck = getErrorMessageFromRuleMethod(validationMethod);
        System.assert(verifyValidation(errorMessagesReceived, errorMessageToCheck), READINESS_VALIDATION_MISSING_ERROR);
    }

    /**
     * @description Returns `true` if an error message array contains a specific error message
     * @param errorMessages
     * @param errorToCheck
     * @return Boolean
    **/
    private static Boolean verifyValidation(List<BulkCorporateOnboardingWrappers.ErrorMessage> errorMessages, String errorToCheck) {
        if(errorMessages == null || errorMessages.isEmpty()) {
            return String.isBlank(errorToCheck); // If there are no errors AND no message, then return true
        }

        for(BulkCorporateOnboardingWrappers.ErrorMessage thisMsgObj : errorMessages) {
            if(thisMsgObj.fullMessage.containsIgnoreCase(errorToCheck)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @description Takes a method name and returns the Error Message from its Readiness Check record
     * @param methodName
     * @return String
    **/
    private static String getErrorMessageFromRuleMethod(String methodName) {
        return readinessChecksByNames.get(methodName).Error_Message__c;
    }
}