sfdx-source/force-app/main/default/objects/Account/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-566: The activation status of the store.</description>
    <inlineHelpText>Represents the activation status of the store</inlineHelpText>
    <label>Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-280 This picklist defines the primary vertical of the Mx.</description>
    <inlineHelpText>Primary vertical of the Mx</inlineHelpText>
    <label>Primary Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Bundled_with_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Bundled_with_Marketplace__c</fullName>
    <description>LEM-1874: It indicates whether Storefront product was sold with Marketplace product in the associated Contract. It also drives the logic for creating Storefront Bundled Work Plan.</description>
    <label>Bundled with Marketplace</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Store_Account_Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Store_Account_Activation_Status__c</fullName>
    <description>LEM-1161: Indicates Store Account&apos;s Activation Status.</description>
    <formula>TEXT(Account.Activation_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
    <label>Store Account Activation Status</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>LEM-813: Account primary vertical.</description>
    <formula>Text(Account.Primary_Vertical__c)</formula>
    <inlineHelpText>Account primary vertical</inlineHelpText>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Parent_Work_Plan__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-527: It is used to maintain relationship with WorkPlan of Parent Work Order.</description>
    <label>Parent Work Plan</label>
    <referenceTo>WorkPlan</referenceTo>
    <relationshipLabel>Child Work Plans</relationshipLabel>
    <relationshipName>Child_Work_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-527: Indicates the overall status of the workplan based on status of the worksteps.</description>
    <inlineHelpText>Indicates the overall status of the workplan based on status of the worksteps</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Workable</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Gone Dark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-1874: It indicates type of Work Plan. It is used to identify the existing Work Plans on Work Order.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Plan_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>LEM-4773: It indicates the Business Vertical value to be used on Work Plan list views.</description>
    <formula>WorkOrder.Vertical__c</formula>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Work_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Work_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Plan Template</label>
    <referenceTo>WorkPlanTemplate</referenceTo>
    <relationshipLabel>Work Plans</relationshipLabel>
    <relationshipName>Work_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlanTemplate/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-1874: It is used for creating the Work Plans on Work Order.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Plan_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlanTemplate/fields/Work_Plan_Default_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Plan_Default_Status__c</fullName>
    <description>LEM-1142: It indicates default Status assigned to WorkPlan on creation.</description>
    <label>Work Plan Default Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <description>LEM-280: This picklist value set is created to define the verticals and sub-verticals associated with store and business accounts.</description>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Work_Plan_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Activations</fullName>
    </customValue>
    <customValue>
        <fullName>Ads and Promo - Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Ads and Promo - Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog</fullName>
    </customValue>
    <customValue>
        <fullName>Caviar - Cross Listing</fullName>
    </customValue>
    <customValue>
        <fullName>Central Activations</fullName>
    </customValue>
    <customValue>
        <fullName>COO Same Store</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Grant Portal Access</fullName>
    </customValue>
    <customValue>
        <fullName>Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Menu Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Rate Change</fullName>
    </customValue>
    <customValue>
        <fullName>Setup Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Listing</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Return</fullName>
    </customValue>
    <customValue>
        <fullName>Central Activations Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Photo Linking</fullName>
    </customValue>
    <customValue>
        <fullName>Photo QA</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <customValue>
        <fullName>Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Promos</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Plan type values.</description>
    <masterLabel>Work Plan Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/services/WorkPlanTemplatesServiceImplTest.cls
/**
 * @author Deloitte
 * @date 05/02/2022
 * @description Test class for WorkPlanTemplatesServiceImpl class.
 * Suppressed Warnings since mock verify method does not require System Assert statements.
 */
@isTest(seeAllData=false)
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
private class WorkPlanTemplatesServiceImplTest {
    private static final String ACCOUNT_ACTIVATION_STATUS_ACTIVE = 'Active';
    private static final String ACCOUNT_BILLING_STREET = '221B Baker Street';
    private static final String ACCOUNT_NAME = 'Test Account';
    private static final String ACCOUNT_STORE_NAME = 'Test Store Account';
    private static final String ACCOUNT_RECORD_TYPE_NAME_STORE = 'Store';
    private static final String ACCOUNT_STORE_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get(ACCOUNT_RECORD_TYPE_NAME_STORE)
        .getRecordTypeId();
    private static final String BUNDLED_WITH_MARKETPLACE_YES = 'Yes';
    private static final String STATUS_CONFIRMED = 'Confirmed';
    private static final String STATUS_NOT_STARTED = 'Not Started';
    private static final String STATUS_NOT_WORKABLE = 'Not Workable';
    private static final String STOREFRONT_BUNDLED = 'Storefront Bundled';
    private static final String TYPE_DRIVE = 'Drive';
    private static final String TYPE_STOREFRONT = 'Storefront';
    private static final String VERTICAL = 'Floral';
    private static final Integer WORK_PLAN_TEMPLATE_RELATIVE_EXECUTION_ORDER = 1;

    /**
     * @description To test creation of Work Plans on insert of Work Orders.
     */
    @isTest
    private static void testWhenWorkOrderIsInsertedThenCreateRelatedWorkPlans() {
        List<WorkPlanTemplate> workPlanTemplateRecords = new List<WorkPlanTemplate>();
        WorkPlanTemplate mockWorkPlanTemplate = new WorkPlanTemplate(
            Id = fflib_IDGenerator.generate(WorkPlanTemplate.SObjectType),
            Name = TYPE_DRIVE,
            Type__c = TYPE_DRIVE,
            IsActive = true,
            Work_Plan_Default_Status__c = STATUS_NOT_STARTED,
            RelativeExecutionOrder = WORK_PLAN_TEMPLATE_RELATIVE_EXECUTION_ORDER
        );
        workPlanTemplateRecords.add(mockWorkPlanTemplate);
        Account parentAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = ACCOUNT_NAME,
            Primary_Vertical__c = VERTICAL
        );
        WorkOrder mockWorkOrder = (WorkOrder) new Fake(WorkOrder.class)
            .setField(WorkOrder.Status, STATUS_CONFIRMED)
            .setField(WorkOrder.Type__c, TYPE_DRIVE)
            .setField(WorkOrder.AccountId, parentAccount.Id)
            .setField(
                WorkOrder.ParentWorkOrderId,
                fflib_IDGenerator.generate(WorkOrder.SObjectType)
            )
            .setFakeId()
            .toSObject();
        WorkPlan newWorkPlan = new WorkPlan(
            Name = mockWorkPlanTemplate.Name,
            Work_Plan_Template__c = mockWorkPlanTemplate.Id,
            Status__c = mockWorkPlanTemplate.Work_Plan_Default_Status__c,
            ParentRecordId = mockWorkOrder.Id,
            Parent_Work_Plan__c = null,
            Type__c = mockWorkPlanTemplate.Type__c,
            WorkOrderId = mockWorkOrder.Id,
            ExecutionOrder = mockWorkPlanTemplate.RelativeExecutionOrder
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        WorkPlanTemplatesSelector mockWorkPlanTemplatesSelector = (WorkPlanTemplatesSelector) mocks.mock(
            WorkPlanTemplatesSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IWorkPlansMapperService mockWorkPlansMapperService = (IWorkPlansMapperService) mocks.mock(
            IWorkPlansMapperService.class
        );
        mocks.startStubbing();
        mocks.when(mockWorkPlanTemplatesSelector.sObjectType())
            .thenReturn(WorkPlanTemplate.SObjectType);
        mocks.when(
                mockWorkPlanTemplatesSelector.selectByType(new Set<String>{ newWorkPlan.Type__c })
            )
            .thenReturn(workPlanTemplateRecords);
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ mockWorkOrder.ParentWorkOrderId }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{ mockWorkOrder.ParentWorkOrderId => new Set<String>{} }
            );
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ mockWorkOrder.Id }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{
                    mockWorkOrder.Id => new Set<String>{ newWorkPlan.Type__c }
                }
            );
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockWorkPlanTemplatesSelector);
        Application.SERVICE.setMock(IWorkPlansMapperService.class, mockWorkPlansMapperService);
        WorkPlanTemplatesService.createWorkPlansOnWorkOrdersByMatchingCriteria(
            new List<WorkOrder>{ mockWorkOrder }
        );

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW))
            .registerNew(new List<WorkPlan>{ newWorkPlan });
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description To test creation of Work Plans on insert of child Work Orders.
     */
    @isTest
    private static void testWhenChildWorkOrderInsertedThenCreateRelatedWorkPlans() {
        List<WorkPlanTemplate> workPlanTemplateRecords = new List<WorkPlanTemplate>();
        WorkPlanTemplate mockWorkPlanTemplate = new WorkPlanTemplate(
            Id = fflib_IDGenerator.generate(WorkPlanTemplate.SObjectType),
            Name = TYPE_DRIVE,
            Type__c = TYPE_DRIVE,
            IsActive = true,
            Work_Plan_Default_Status__c = STATUS_NOT_STARTED,
            RelativeExecutionOrder = WORK_PLAN_TEMPLATE_RELATIVE_EXECUTION_ORDER
        );
        workPlanTemplateRecords.add(mockWorkPlanTemplate);
        Account parentAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = ACCOUNT_NAME,
            Primary_Vertical__c = VERTICAL
        );
        Account storeAccount = (Account) new Fake(Account.class)
            .setField(Account.Name, ACCOUNT_STORE_NAME)
            .setField(Account.Primary_Vertical__c, VERTICAL)
            .setField(Account.RecordTypeId, ACCOUNT_STORE_RECORD_TYPE_ID)
            .setFakeId()
            .toSObject();
        Fake parentWorkOrderFakeInstance = new Fake(WorkOrder.class)
            .setField(WorkOrder.Status, STATUS_CONFIRMED)
            .setField(WorkOrder.Type__c, TYPE_DRIVE)
            .setField(WorkOrder.AccountId, parentAccount.Id)
            .setFakeId();
        WorkOrder parentWorkOrder = (WorkOrder) ServiceMockDataBuilder.convertToSObject(
            parentWorkOrderFakeInstance
        );
        WorkPlan parentWorkPlan = new WorkPlan(
            Name = mockWorkPlanTemplate.Name,
            Work_Plan_Template__c = mockWorkPlanTemplate.Id,
            Status__c = mockWorkPlanTemplate.Work_Plan_Default_Status__c,
            ParentRecordId = parentWorkOrder.Id,
            Parent_Work_Plan__c = null,
            WorkOrderId = parentWorkOrder.Id,
            Type__c = mockWorkPlanTemplate.Type__c,
            ExecutionOrder = mockWorkPlanTemplate.RelativeExecutionOrder
        );
        WorkOrder childWorkOrder = (WorkOrder) new Fake(WorkOrder.class)
            .setField(WorkOrder.Status, STATUS_CONFIRMED)
            .setField(WorkOrder.Type__c, TYPE_DRIVE)
            .setField(WorkOrder.AccountId, storeAccount.Id)
            .setField(WorkOrder.ParentWorkOrderId, parentWorkOrder.Id)
            .setParent('ParentWorkOrder', parentWorkOrderFakeInstance)
            .setFakeId()
            .toSObject();
        WorkPlan childWorkPlan = new WorkPlan(
            Name = mockWorkPlanTemplate.Name,
            Work_Plan_Template__c = mockWorkPlanTemplate.Id,
            Status__c = mockWorkPlanTemplate.Work_Plan_Default_Status__c,
            ParentRecordId = childWorkOrder.Id,
            Parent_Work_Plan__c = parentWorkPlan.Id,
            WorkOrderId = childWorkOrder.Id,
            Type__c = mockWorkPlanTemplate.Type__c,
            ExecutionOrder = mockWorkPlanTemplate.RelativeExecutionOrder
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        WorkPlansSelector mockWorkPlansSelector = (WorkPlansSelector) mocks.mock(
            WorkPlansSelector.class
        );
        WorkPlanTemplatesSelector mockWorkPlanTemplatesSelector = (WorkPlanTemplatesSelector) mocks.mock(
            WorkPlanTemplatesSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IWorkPlansMapperService mockWorkPlansMapperService = (IWorkPlansMapperService) mocks.mock(
            IWorkPlansMapperService.class
        );
        mocks.startStubbing();
        mocks.when(mockWorkPlansSelector.sObjectType()).thenReturn(WorkPlan.SObjectType);
        mocks.when(
                mockWorkPlansSelector.selectWorkPlansByWorkOrderIds(
                    new Set<Id>{ childWorkOrder.ParentWorkOrderId }
                )
            )
            .thenReturn(new List<WorkPlan>{ parentWorkPlan });
        mocks.when(mockWorkPlansSelector.selectWorkPlansByWorkOrderIds(new Set<Id>()))
            .thenReturn(new List<WorkPlan>());
        mocks.when(mockWorkPlanTemplatesSelector.sObjectType())
            .thenReturn(WorkPlanTemplate.SObjectType);
        mocks.when(
                mockWorkPlanTemplatesSelector.selectByType(
                    new Set<String>{ parentWorkPlan.Type__c }
                )
            )
            .thenReturn(workPlanTemplateRecords);
        mocks.when(
                mockWorkPlanTemplatesSelector.selectByType(new Set<String>{ childWorkPlan.Type__c })
            )
            .thenReturn(workPlanTemplateRecords);
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ parentWorkOrder.Id }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{
                    parentWorkOrder.Id => new Set<String>{ parentWorkPlan.Type__c }
                }
            );
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ childWorkOrder.Id }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{
                    childWorkOrder.Id => new Set<String>{ childWorkPlan.Type__c }
                }
            );
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockWorkPlansSelector);
        Application.SELECTOR.setMock(mockWorkPlanTemplatesSelector);
        Application.SERVICE.setMock(IWorkPlansMapperService.class, mockWorkPlansMapperService);
        WorkPlanTemplatesService.createWorkPlansOnWorkOrdersByMatchingCriteria(
            new List<WorkOrder>{ childWorkOrder }
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 2))
            .registerNew(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{ WorkPlan.Name => mockWorkPlanTemplate.Name }
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 2)).commitWork();
    }

    /**
     * @description To test creation of Storefront Bundled Work Plan in Not Started Status if Store Account is Active.
     */
    @isTest
    private static void testWhenWorkOrderIsInsertedForActiveStoreThenCreateStorefrontBundledWorkPlansWithNotStartedStatus() {
        WorkPlanTemplate storefrontBundledWorkPlanTemplate = new WorkPlanTemplate(
            Id = fflib_IDGenerator.generate(WorkPlanTemplate.SObjectType),
            IsActive = true,
            Name = STOREFRONT_BUNDLED,
            RelativeExecutionOrder = WORK_PLAN_TEMPLATE_RELATIVE_EXECUTION_ORDER,
            Type__c = TYPE_STOREFRONT,
            Work_Plan_Default_Status__c = STATUS_NOT_WORKABLE
        );
        Account parentAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Activation_Status__c = ACCOUNT_ACTIVATION_STATUS_ACTIVE,
            BillingStreet = ACCOUNT_BILLING_STREET,
            Name = ACCOUNT_NAME,
            ParentId = fflib_IDGenerator.generate(Account.SObjectType),
            Primary_Vertical__c = VERTICAL,
            RecordTypeID = ACCOUNT_STORE_RECORD_TYPE_ID
        );
        WorkOrder mockWorkOrder = (WorkOrder) new Fake(WorkOrder.class)
            .setField(WorkOrder.AccountId, parentAccount.Id)
            .setField(WorkOrder.Status, STATUS_CONFIRMED)
            .setField(WorkOrder.Bundled_with_Marketplace__c, BUNDLED_WITH_MARKETPLACE_YES)
            .setField(
                WorkOrder.Store_Account_Activation_Status__c,
                ACCOUNT_ACTIVATION_STATUS_ACTIVE
            )
            .setField(WorkOrder.Type__c, TYPE_STOREFRONT)
            .setField(WorkOrder.Vertical__c, VERTICAL)
            .setField(
                WorkOrder.ParentWorkOrderId,
                fflib_IDGenerator.generate(WorkOrder.SObjectType)
            )
            .setFakeId()
            .toSObject();
        WorkPlan newWorkPlan = new WorkPlan(
            ExecutionOrder = storefrontBundledWorkPlanTemplate.RelativeExecutionOrder,
            Name = storefrontBundledWorkPlanTemplate.Name,
            ParentRecordId = mockWorkOrder.Id,
            Parent_Work_Plan__c = null,
            Status__c = STATUS_NOT_STARTED,
            WorkOrderId = mockWorkOrder.Id,
            Type__c = storefrontBundledWorkPlanTemplate.Type__c,
            Work_Plan_Template__c = storefrontBundledWorkPlanTemplate.Id
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        WorkPlanTemplatesSelector mockWorkPlanTemplatesSelector = (WorkPlanTemplatesSelector) mocks.mock(
            WorkPlanTemplatesSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IWorkPlansMapperService mockWorkPlansMapperService = (IWorkPlansMapperService) mocks.mock(
            IWorkPlansMapperService.class
        );
        mocks.startStubbing();
        mocks.when(mockWorkPlanTemplatesSelector.sObjectType())
            .thenReturn(WorkPlanTemplate.SObjectType);
        mocks.when(
                mockWorkPlanTemplatesSelector.selectByType(new Set<String>{ newWorkPlan.Type__c })
            )
            .thenReturn(new List<WorkPlanTemplate>{ storefrontBundledWorkPlanTemplate });
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ mockWorkOrder.ParentWorkOrderId }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{ mockWorkOrder.ParentWorkOrderId => new Set<String>{} }
            );
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ mockWorkOrder.Id }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{
                    mockWorkOrder.Id => new Set<String>{ newWorkPlan.Type__c }
                }
            );
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockWorkPlanTemplatesSelector);
        Application.SERVICE.setMock(IWorkPlansMapperService.class, mockWorkPlansMapperService);
        WorkPlanTemplatesService.createWorkPlansOnWorkOrdersByMatchingCriteria(
            new List<WorkOrder>{ mockWorkOrder }
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW))
            .registerNew(new List<WorkPlan>{ newWorkPlan });
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description To test creation of Work Plans when list of WorkOrders & map of WorkOrder Id
     * to WorkPlan types is passed.
     */
    @isTest
    private static void testWhenWorkOrderIsReevaluatedThenCreateRelatedWorkPlans() {
        List<WorkPlanTemplate> workPlanTemplateRecords = new List<WorkPlanTemplate>();
        WorkPlanTemplate mockWorkPlanTemplate = new WorkPlanTemplate(
            Id = fflib_IDGenerator.generate(WorkPlanTemplate.SObjectType),
            Name = TYPE_DRIVE,
            Type__c = TYPE_DRIVE,
            IsActive = true,
            Work_Plan_Default_Status__c = STATUS_NOT_STARTED,
            RelativeExecutionOrder = WORK_PLAN_TEMPLATE_RELATIVE_EXECUTION_ORDER
        );
        workPlanTemplateRecords.add(mockWorkPlanTemplate);
        Account parentAccount = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = ACCOUNT_NAME,
            Primary_Vertical__c = VERTICAL
        );
        WorkOrder mockWorkOrder = (WorkOrder) new Fake(WorkOrder.class)
            .setField(WorkOrder.Status, STATUS_CONFIRMED)
            .setField(WorkOrder.Type__c, TYPE_DRIVE)
            .setField(WorkOrder.AccountId, parentAccount.Id)
            .setFakeId()
            .toSObject();
        WorkPlan newWorkPlan = new WorkPlan(
            Name = mockWorkPlanTemplate.Name,
            Work_Plan_Template__c = mockWorkPlanTemplate.Id,
            Status__c = mockWorkPlanTemplate.Work_Plan_Default_Status__c,
            ParentRecordId = mockWorkOrder.Id,
            Parent_Work_Plan__c = null,
            Type__c = mockWorkPlanTemplate.Type__c,
            WorkOrderId = mockWorkOrder.Id,
            ExecutionOrder = mockWorkPlanTemplate.RelativeExecutionOrder
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        WorkPlanTemplatesSelector mockWorkPlanTemplatesSelector = (WorkPlanTemplatesSelector) mocks.mock(
            WorkPlanTemplatesSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IWorkPlansMapperService mockWorkPlansMapperService = (IWorkPlansMapperService) mocks.mock(
            IWorkPlansMapperService.class
        );
        mocks.startStubbing();
        mocks.when(mockWorkPlanTemplatesSelector.sObjectType())
            .thenReturn(WorkPlanTemplate.SObjectType);
        mocks.when(
                mockWorkPlanTemplatesSelector.selectByType(new Set<String>{ newWorkPlan.Type__c })
            )
            .thenReturn(workPlanTemplateRecords);
        mocks.when(
                mockWorkPlansMapperService.collectMatchingWorkPlanTypes(
                    new List<String>{ mockWorkOrder.Id }
                )
            )
            .thenReturn(
                new Map<Id, Set<String>>{
                    mockWorkOrder.Id => new Set<String>{ newWorkPlan.Type__c }
                }
            );
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockWorkPlanTemplatesSelector);
        Application.SERVICE.setMock(IWorkPlansMapperService.class, mockWorkPlansMapperService);
        WorkPlanTemplatesService.createWorkPlansOnWorkOrdersByReevaluatingCriteria(
            new List<WorkOrder>{ mockWorkOrder },
            new Map<Id, Set<String>>{
                mockWorkOrder.Id => new Set<String>{ mockWorkPlanTemplate.Name }
            }
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW))
            .registerNew(new List<WorkPlan>{ newWorkPlan });
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }
}