sfdx-source/force-app/main/default/objects/Account/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-566: The activation status of the store.</description>
    <inlineHelpText>Represents the activation status of the store</inlineHelpText>
    <label>Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-6471</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>LEM -186</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/Agreement_Activation_Event__e.object-meta.xml
<CustomObject>
    <description>LEM-2718: performance optimizations</description>
    <label>Agreement Activation Event</label>
    <pluralLabel>Agreement Activation Events</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Agreement_Ids__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Ids__c</fullName>
    <label>Agreement Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement_Activation_Event__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-11329: To store the  Specific Topic Name for the Agreement Activation Event.</description>
    <label>Topic</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Notifier__e/Notifier__e.object-meta.xml
<CustomObject>
    <description>LEM-955: It allows generic Platform Event schema and the trigger listener to act as dispatcher of the events. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further processing.</description>
    <label>Notifier</label>
    <pluralLabel>Notifiers</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Notifier__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>LEM-955: It stores the data required for processing by the service layer corresponding to the topic. The format may vary by use-case; it may store set of record ids or JSON string. The service layer will process the payload as needed.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Notifier__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>LEM-955: It stores use-case for which event is fired. It is used for identifying service layer for further payload processing.</description>
    <label>Topic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <description>LEM-6471 This field is used to track rate change request status.</description>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activation Initiated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Associated_stores_updated__c.field-meta.xml
<CustomField>
    <fullName>Associated_stores_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associated stores updated?</label>
    <description>LEM-6471 This field is used to track if associated stores are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Contract_Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Order_Products_Updated__c.field-meta.xml
<CustomField>
    <fullName>Order_Products_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Products Updated</label>
    <description>LEM-6471 This field is used to track if associated order products are updated.</description>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/S_O_Support_Request_Link__c.field-meta.xml
<CustomField>
    <fullName>S_O_Support_Request_Link__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>S&amp;O Support Request Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SO_Support_Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__Subscription__c/fields/Subscription_Rate_Change__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Rate_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <referenceTo>Subscription_Rate_Change__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>SRC_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Static_Configurations__mdt/Static_Configurations__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1517: This custom metadata stores static configurations. For Example: URLs to MINT or Merchant Portal</description>
    <label>Static Configurations</label>
    <pluralLabel>Static Configurations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Static_Configurations__mdt/fields/Configuration_Value__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Value__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1517: This field holds the static configuration value.</description>
    <inlineHelpText>This field holds the static configuration value</inlineHelpText>
    <label>Configuration Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/Subscription_Rate_Change__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <nameField>
        <displayFormat>SubscriptionChange-{0000}</displayFormat>
        <label>Subscription Rate Change  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Rate Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Subscription Rate Changes</relationshipLabel>
    <relationshipName>Subscription_Rate_Changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscription Rate Changes</relationshipLabel>
    <relationshipName>Subscription_SRC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Update_complete__c.field-meta.xml
<CustomField>
    <fullName>Update_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Update complete</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Updated_Active_Commission__c.field-meta.xml
<CustomField>
    <fullName>Updated_Active_Commission__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Updated Active Commission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Updated_Active_Fee__c.field-meta.xml
<CustomField>
    <fullName>Updated_Active_Fee__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Updated Active Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <description>LEM-186: Initial Setup of Agreement</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/services/RateChangeRequestServiceImplTest.cls
/**
 * @author Deloitte
 * @date 14/09/2023
 * @description Test class for RateChangeRequestServiceImpl class.
 */
@isTest(seeAllData=false)
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
public class RateChangeRequestServiceImplTest {
    private static final String ACTIVATION_INITIATED = 'Activation Initiated';
    private static final String AGREEMENT_EVENTS_CHUNK_SIZE = 'Agreement_Events_Chunk_Size';
    private static final Integer AGREEMENT_EVENTS_CHUNK_SIZE_RECORD = 50;
    private static final String STATUS_CANCELLED = 'Canceled';
    private static final String APPROVED = 'Approved';
    private static final String NEW_RATE_CHANGE = 'New';
    private static final Date TODAY_DATE = System.today();
    private static final String ASSERT_MESSAGE_UPDATED_RATE_CHANGE_COMPLETE = 'Unexpected result: Rate change request is not completed';
    private static final String READY_FOR_ACTIVATION = 'Ready for Activation';
    private static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER = 'CREATE_ACTIVATION_ORDER_AND_PRODUCTS';
    private static final String EVENT_TOPIC_UPDATE_RATE_CHANGE_REQUEST = 'UPDATE_RATE_CHANGE_REQUEST';
    private static final String METADATA_INSTANCE_NAME = 'Activation_Order_Payload_Chunk_Size';
    private static final String METADATA_VALUE = '3';
    private static final String EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP = 'Create_Activation_Order_Products_ARP';

    @isTest
    private static void testWhenAllSubscriptionRateChangesAreCompletedThenRCRisCompleted() {
        //ARRANGE
        Id subscriptionId1 = fflib_IDGenerator.generate(SBQQ__Subscription__c.SObjectType);
        Id rateChangeReqId = Fake.generateId(Rate_Change_Request__c.class);
        Id subRateChangeReqId = Fake.generateId(Subscription_Rate_Change__c.class);
        Id contractId = Fake.generateId(Contract.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequestinstance = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Id, rateChangeReqId)
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .setField(Rate_Change_Request__c.Order_Products_Updated__c, false)
            .setField(Rate_Change_Request__c.Associated_stores_updated__c, true)
            .setChildren(
                'Subscription_Rate_Changes__r',
                new List<Fake>{
                    new Fake(Subscription_Rate_Change__c.class)
                        .setField(Subscription_Rate_Change__c.Id, subRateChangeReqId)
                        .setField(
                            Subscription_Rate_Change__c.Rate_Change_Request__c,
                            rateChangeReqId
                        )
                        .setField(Subscription_Rate_Change__c.Updated_Active_Fee__c, '53')
                        .setField(Subscription_Rate_Change__c.Updated_Active_Commission__c, '43')
                        .setField(Subscription_Rate_Change__c.Subscription__c, subscriptionId1)
                        .setField(Subscription_Rate_Change__c.Update_complete__c, true)
                }
            )
            .toSObject();

        Subscription_Rate_Change__c subscriptionRateChangeRequest = (Subscription_Rate_Change__c) new Fake(
                Subscription_Rate_Change__c.class
            )
            .setField(Subscription_Rate_Change__c.Id, subRateChangeReqId)
            .setField(Subscription_Rate_Change__c.Rate_Change_Request__c, rateChangeReqId)
            .setField(Subscription_Rate_Change__c.Updated_Active_Fee__c, '53')
            .setField(Subscription_Rate_Change__c.Updated_Active_Commission__c, '43')
            .setField(Subscription_Rate_Change__c.Subscription__c, subscriptionId1)
            .setField(Subscription_Rate_Change__c.Update_complete__c, true)
            .setParent(
                'Rate_Change_Request__r',
                new Fake(Rate_Change_Request__c.class)
                    .setField(Rate_Change_Request__c.Id, rateChangeReqId)
                    .setField(Rate_Change_Request__c.Contract__c, contractId)
                    .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
                    .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
                    .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
                    .setField(Rate_Change_Request__c.Status__c, APPROVED)
            )
            .toSObject();

        List<Subscription_Rate_Change__c> subscriptionRateChangeRequests = new List<Subscription_Rate_Change__c>();
        subscriptionRateChangeRequests.add(subscriptionRateChangeRequest);

        List<Rate_Change_Request__c> rateChangeRequestsList = new List<Rate_Change_Request__c>();
        rateChangeRequestsList.add(rateChangeRequestinstance);

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IRateChangeRequestSelector rateChangeSelectorMock = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        mocks.startStubbing();
        mocks.when(rateChangeSelectorMock.sObjectType())
            .thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.when(
                rateChangeSelectorMock.selectRateChangeRequestById(new Set<Id>{ rateChangeReqId })
            )
            .thenReturn(rateChangeRequestsList);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(rateChangeSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Test.startTest();
        RateChangeRequestService.setRateChangeRequestComplete(subscriptionRateChangeRequests);
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            Rate_Change_Request__c.Id => rateChangeRequestsList[0].Id,
                            Rate_Change_Request__c.Order_Products_Updated__c => true,
                            Rate_Change_Request__c.Activation_Status__c => READY_FOR_ACTIVATION
                        }
                    }
                )
            );

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    @isTest
    private static void testWhenAllStoresAreUpdatedThenRCRStoreUpdatedFlagIsTrue() {
        //ARRANGE
        Id subscriptionId1 = fflib_IDGenerator.generate(SBQQ__Subscription__c.SObjectType);
        Id rateChangeReqId = Fake.generateId(Rate_Change_Request__c.class);
        Id subRateChangeReqId = Fake.generateId(Subscription_Rate_Change__c.class);
        Id contractId = Fake.generateId(Contract.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequestinstance = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Id, rateChangeReqId)
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .setField(Rate_Change_Request__c.Order_Products_Updated__c, true)
            .setChildren(
                'Subscription_Rate_Changes__r',
                new List<Fake>{
                    new Fake(Subscription_Rate_Change__c.class)
                        .setField(Subscription_Rate_Change__c.Id, subRateChangeReqId)
                        .setField(
                            Subscription_Rate_Change__c.Rate_Change_Request__c,
                            rateChangeReqId
                        )
                        .setField(Subscription_Rate_Change__c.Updated_Active_Fee__c, '53')
                        .setField(Subscription_Rate_Change__c.Updated_Active_Commission__c, '43')
                        .setField(Subscription_Rate_Change__c.Subscription__c, subscriptionId1)
                        .setField(Subscription_Rate_Change__c.Update_complete__c, true)
                }
            )
            .toSObject();

        List<Rate_Change_Request__c> rateChangeRequestsList = new List<Rate_Change_Request__c>();
        rateChangeRequestsList.add(rateChangeRequestinstance);

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IRateChangeRequestSelector rateChangeSelectorMock = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        mocks.startStubbing();
        mocks.when(rateChangeSelectorMock.sObjectType())
            .thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.when(
                rateChangeSelectorMock.selectRateChangeRequestById(new Set<Id>{ rateChangeReqId })
            )
            .thenReturn(rateChangeRequestsList);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(rateChangeSelectorMock);
        Application.UNITOFWORK.setMock(mockUOW);
        Test.startTest();
        RateChangeRequestService.setRateChangeRequestStoreUpdatedFlagTrue(rateChangeReqId);
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            Rate_Change_Request__c.Id => rateChangeRequestsList[0].Id,
                            Rate_Change_Request__c.Activation_Status__c => READY_FOR_ACTIVATION
                        }
                    }
                )
            );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }
    /**
     * @description To test method call on Order update
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenRateChangeRequestUpdatedThenCallPublishCreateActivationOrders() {
        Id accountId = Fake.generateId(Account.class);
        Id accountId2 = Fake.generateId(Account.class);
        Id agreementId = Fake.generateId(Agreement__c.class);
        Id agreementId2 = Fake.generateId(Agreement__c.class);
        Id contractId = Fake.generateId(Contract.class);
        Id rcrId = Fake.generateId(Rate_Change_Request__c.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequest = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .setFakeId()
            .toSObject();

        List<Agreement__c> agreements = new List<Agreement__c>{
            (Agreement__c) new Fake(Agreement__c.class)
                .setField(Agreement__c.Account__c, accountId)
                .setField(Agreement__c.Id, agreementId)
                .setParent(
                    'Account',
                    new Fake(Account.class)
                        .setField(Account.Id, accountId)
                        .setField(Account.Rate_Change_Request__c, rcrId)
                )
                .toSObject(),
            (Agreement__c) new Fake(Agreement__c.class)
                .setField(Agreement__c.Account__c, accountId2)
                .setField(Agreement__c.Id, agreementId2)
                .setParent(
                    'Account',
                    new Fake(Account.class)
                        .setField(Account.Id, accountId2)
                        .setField(Account.Rate_Change_Request__c, rcrId)
                )
                .toSObject()
        };

        Static_Configurations__mdt agreementMetadta = new Static_Configurations__mdt(
            DeveloperName = AGREEMENT_EVENTS_CHUNK_SIZE,
            MasterLabel = AGREEMENT_EVENTS_CHUNK_SIZE,
            Configuration_Value__c = String.valueOf(AGREEMENT_EVENTS_CHUNK_SIZE_RECORD)
        );

        List<Id> agreementIdsChunk1 = new List<Id>{ agreements[0].Id, agreements[1].Id };

        List<String> payloads = new List<String>{ JSON.serialize(agreementIdsChunk1) };

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        IAgreementsSelector mockAgreementsSelector = (IAgreementsSelector) mocks.mock(
            IAgreementsSelector.class
        );

        IStaticConfigurationsSelector mockStaticConfigurations = (IStaticConfigurationsSelector) mocks.mock(
            IStaticConfigurationsSelector.class
        );

        INotifierEventsPayloadGenerationService notifierEventsPayloadGenerationServiceMock = (INotifierEventsPayloadGenerationService) mocks.mock(
            INotifierEventsPayloadGenerationService.class
        );

        mocks.startStubbing();
        mocks.when(
                notifierEventsPayloadGenerationServiceMock.generateChunkedPayloadsBySobjectIds(
                    new Set<Id>{ agreements[0].Id, agreements[1].Id },
                    AGREEMENT_EVENTS_CHUNK_SIZE_RECORD
                )
            )
            .thenReturn(payloads);
        mocks.when(mockStaticConfigurations.sObjectType())
            .thenReturn(Static_Configurations__mdt.SObjectType);
        mocks.when(mockStaticConfigurations.getInstanceValue(AGREEMENT_EVENTS_CHUNK_SIZE))
            .thenReturn(agreementMetadta);
        mocks.when(mockAgreementsSelector.sObjectType()).thenReturn(Agreement__c.SObjectType);
        mocks.when(
                mockAgreementsSelector.selectStoreAgreementsByRcrIds(
                    new Set<Id>{ rateChangeRequest.Id }
                )
            )
            .thenReturn(agreements);
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockAgreementsSelector);
        Application.SELECTOR.setMock(mockStaticConfigurations);
        Application.SERVICE.setMock(
            INotifierEventsPayloadGenerationService.class,
            notifierEventsPayloadGenerationServiceMock
        );

        Test.startTest();
        RateChangeRequestService.publishCreateActivationOrdersNotifierEvent(
            new Set<Id>{ rateChangeRequest.Id }
        );
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerPublishAfterSuccessTransaction(
                new Agreement_Activation_Event__e(
                    Agreement_Ids__c = JSON.serialize(
                        new List<Id>{ agreements[0].Id, agreements[1].Id }
                    ),
                    Topic__c = EVENT_TOPIC_CREATE_ACTIVATION_ORDER_ARP
                )
            );
    }

    /**
     * @description To test method call on Rate Change Request update
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenXRefIsReadyForIntegrationThenCallUpdateRateChangeRequestAsActivationInitiated() {
        Id contractId = Fake.generateId(Contract.class);
        Id rcrId = Fake.generateId(Rate_Change_Request__c.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequest = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Id, rcrId)
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, READY_FOR_ACTIVATION)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        Application.UNITOFWORK.setMock(mockUOW);

        String eventPayload = JSON.serialize(new Set<Id>{ rateChangeRequest.Id });
        Notifier__e mockNotifierEvent = new Notifier__e(
            Payload__c = eventPayload,
            Topic__c = 'UPDATE_RATE_CHANGE_REQUEST'
        );

        IRateChangeRequestSelector mockRateChangeRequestSelector = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );

        List<Rate_Change_Request__c> rateChangeRequestsList = new List<Rate_Change_Request__c>();
        rateChangeRequestsList.add(rateChangeRequest);

        mocks.startStubbing();
        mocks.when(mockRateChangeRequestSelector.sObjectType())
            .thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.when(
                mockRateChangeRequestSelector.selectRateChangeRequestById(
                    new Set<Id>{ rateChangeRequest.Id }
                )
            )
            .thenReturn(rateChangeRequestsList);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(mockRateChangeRequestSelector);

        Test.startTest();
        RateChangeRequestService.execute(new List<Notifier__e>{ mockNotifierEvent });
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            Rate_Change_Request__c.Id => rateChangeRequestsList[0].Id,
                            Rate_Change_Request__c.Activation_Status__c => ACTIVATION_INITIATED
                        }
                    }
                )
            );

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description To test method call on Rate Change Request update
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenBatchJobExecutedThenCallupdateRateChangeRequestToCancelled() {
        Id contractId = Fake.generateId(Contract.class);
        Id rcrId = Fake.generateId(Rate_Change_Request__c.class);
        Id caseId = Fake.generateId(Case.class);

        Rate_Change_Request__c rateChangeRequest = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Id, rcrId)
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, READY_FOR_ACTIVATION)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        Application.UNITOFWORK.setMock(mockUOW);

        IRateChangeRequestSelector mockRateChangeRequestSelector = (IRateChangeRequestSelector) mocks.mock(
            IRateChangeRequestSelector.class
        );

        List<Rate_Change_Request__c> rateChangeRequestsList = new List<Rate_Change_Request__c>();
        rateChangeRequestsList.add(rateChangeRequest);

        mocks.startStubbing();
        mocks.when(mockRateChangeRequestSelector.sObjectType())
            .thenReturn(Rate_Change_Request__c.SObjectType);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(mockRateChangeRequestSelector);

        Test.startTest();
        RateChangeRequestService.updateRateChangeRequestToCancelled(
            new List<Rate_Change_Request__c>{ rateChangeRequest }
        );
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1))
            .registerDirty(
                fflib_Match.sObjectsWith(
                    new List<Map<SObjectField, Object>>{
                        new Map<SObjectField, Object>{
                            Rate_Change_Request__c.Id => rateChangeRequestsList[0].Id,
                            Rate_Change_Request__c.Status__c => STATUS_CANCELLED
                        }
                    }
                )
            );

        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }
}