sfdx-source/force-app/main/default/objects/Account/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-566: The activation status of the store.</description>
    <inlineHelpText>Represents the activation status of the store</inlineHelpText>
    <label>Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-6471</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Activation_Status__c</fullName>
    <label>Activation Status</label>
    <description>LEM-6471 This field is used to track rate change request status.</description>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activation Initiated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Contract_Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/S_O_Support_Request_Link__c.field-meta.xml
<CustomField>
    <fullName>S_O_Support_Request_Link__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>S&amp;O Support Request Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SO_Support_Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Rate Change Requests</relationshipLabel>
    <relationshipName>Rate_Change_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/batchables/AccountUpdateForActiveRatesBatchTest.cls
/**
 * @author Deloitte
 * @date 12/09/2023
 * @description This is the test class for AccountUpdateForActiveRatesBatch class
 */
@isTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
public class AccountUpdateForActiveRatesBatchTest {
    private static final String NEW_RATE_CHANGE = 'New';
    private static final String APPROVED = 'Approved';
    private static final Date TODAY_DATE = System.today();
    @IsTest
    static void testWhenForPassedListOfAccountsThenRateChangeRequestIdIsStamped() {
        //ARRANGE
        Id accountId = Fake.generateId(Account.class);
        Id accId = Fake.generateId(Account.class);
        Id contractId = Fake.generateId(Contract.class);
        Id caseId = Fake.generateId(Case.class);
        Account account1 = (Account) new Fake(Account.class)
            .setField(Account.Name, 'Test Account 1 - Batch')
            .setField(Account.Id, accountId)
            .toSObject();

        Account account2 = (Account) new Fake(Account.class)
            .setField(Account.Name, 'Test Account 2 - Batch')
            .setField(Account.Id, accId)
            .toSObject();

        Rate_Change_Request__c rateChangeRequest = (Rate_Change_Request__c) new Fake(
                Rate_Change_Request__c.class
            )
            .setField(Rate_Change_Request__c.Contract__c, contractId)
            .setField(Rate_Change_Request__c.Effective_Date__c, TODAY_DATE)
            .setField(Rate_Change_Request__c.S_O_Support_Request_Link__c, caseId)
            .setField(Rate_Change_Request__c.Activation_Status__c, NEW_RATE_CHANGE)
            .setField(Rate_Change_Request__c.Status__c, APPROVED)
            .setFakeId()
            .toSObject();

        List<Account> storeAccountsToUpdate = new List<Account>{ account1, account2 };
        Set<Id> storeAccountIdsToUpdate = new Set<Id>{ account1.Id, account2.Id };

        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IAccountsSelector selectorMock = (IAccountsSelector) mocks.mock(IAccountsSelector.class);

        IAccountsService serviceMock = (IAccountsService) mocks.mock(IAccountsService.class);

        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorMock.getStoreAccountsById(new Set<Id>{ account1.Id, account2.Id }))
            .thenReturn(null);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(selectorMock);
        Application.SERVICE.setMock(IAccountsService.class, serviceMock);
        Application.UNITOFWORK.setMock(mockUnitOfWork);

        //ACT
        AccountUpdateForActiveRatesBatch batch = new AccountUpdateForActiveRatesBatch(
            storeAccountIdsToUpdate,
            rateChangeRequest.Id
        );
        batch.start(null);
        batch.execute(null, storeAccountsToUpdate);
        batch.finish(null);

        //ASSERT
        ((IAccountsService) mocks.verify(serviceMock, 1))
            .updateRateChangeRequestOnAccount(storeAccountsToUpdate, rateChangeRequest.Id);
        ((IAccountsSelector) mocks.verify(selectorMock, 1))
            .getStoreAccountsById(new Set<Id>{ account1.Id, account2.Id });
    }
}