sfdx-source/force-app/main/default/objects/Account/fields/Address_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-95:It stores account status in order to validate entity address.</description>
    <label>Address Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
                <default>true</default>
                <label>Unverified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Time_Zone_Backend__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Backend__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13514: It indicates the time zone value based on address to be populated by Mulesoft.</description>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Address_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It stores Account status in order to validate entity address.</description>
    <label>Address Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Email_Cassie_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_Cassie_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16624: It stores the Email Cassie ID.</description>
    <label>Email Cassie ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Inbound_Ingestion_Log__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Ingestion_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14813: It is used to store the associated inbound ingestion log.</description>
    <label>Inbound Ingestion Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/Inbound_Ingestion_Log__c.object-meta.xml
<CustomObject>
    <description>LEM-14648: Custom Inbound Ingestion Log object for SSMO Integration.</description>
    <label>Inbound Ingestion Log</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inbound Ingestion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Ingestion Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Lead/fields/Address_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13402,LEM-13404: It stores account status in order to validate entity address.</description>
    <label>Address Verification Status</label>
     <inlineHelpText>Displays the status of Lead address verification</inlineHelpText>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified</fullName>
                <default>true</default>
                <label>Unverified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Email_Cassie_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_Cassie_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16624: It stores Email Cassie ID.</description>
    <label>Email Cassie ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Inbound_Ingestion_Log__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Ingestion_Log__c</fullName>
    <description>LEM-16814: It is used to store related Inbound Ingestion log Id.</description>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inbound Ingestion Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Primary_Campaign_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Campaign_Source__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15472: It represents the Primary Campaign Source.</description>
    <inlineHelpText>Campaign that the Lead has been engaged with</inlineHelpText>
    <label>Primary Campaign Source</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/SMS_Opted_Out__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opted_Out__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-17656: It is used to indicate if Mx has opted out of SMS.</description>
    <defaultValue>false</defaultValue>
    <label>SMS Opted Out</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/SSMO_UUID__c.field-meta.xml
<CustomField>
    <fullName>SSMO_UUID__c</fullName>
    <description>LEM-14186: It stores the SSMO UUID a unique identifier assigned to Salesforce records.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>This field stores the SSMO UUID a unique identifier assigned to Salesforce records</inlineHelpText>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Time_Zone_Backend__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Backend__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13514: It indicates the time zone value based on address to be populated by Mulesoft.</description>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/triggerHandlers/LeadsHandler.cls
/**
 * @author Deloitte
 * @date 03/27/2024
 * @description Trigger Handler for Leads.
 */
public class LeadsHandler extends ApplicationDomainHandler {
    /**
     * @description Constructor Method
     * @param sObjectList - Leads Record List
     */
    public LeadsHandler(List<Lead> sObjectList) {
        super(sObjectList);
        setContextBypass(Lead.SObjectType, LeadsHandler.class);
    }
    /**
     * @description Constructor class implements fflib_SObjectDomain class
     */
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        /**
         * @description This method implements construct method of fflib_SObjectDomain.IConstructable
         * @param sObjectList - List of SObjects
         * @return LeadsHandler
         */
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new LeadsHandler(sObjectList);
        }
    }

    /**
     * @description It is used to perform processing after Lead insertion.
     */
    public override void onAfterInsert() {
        AddressVerificationService.publishAddressVerificationEvent(this.records);
        Leads.newInstance(this.records)
            .updateInboundIngestionLogsToCompletedStatusOnSSMOLeadCreation();
    }

    /**
     * @description It is used to perform processing after Leads are updated.
     * @param existing
     */
    public override void onAfterUpdate(Map<Id, SObject> existing) {
        AddressVerificationService.publishAddressVerificationEvent(
            leadsWithUpdatedAddressOrStatus()
        );
        Leads.newInstance(checkForConvertedLeads()).processLeadsOnConversion();
        List<Lead> leadsToBeUpdatedOnFallout = getChangedRecords(
            new Set<SObjectField>{ Lead.Inbound_Ingestion_Log__c, Lead.SSMO_UUID__c }
        );
        SSMOLeadCreationService.createTaskOnLeadAfterFallout(
            leadsToBeUpdatedOnFallout,
            (Map<Id, Lead>) existing
        );
        List<Lead> leadsWithStatusUpdateOnFallout = getChangedRecords(
            new Set<SObjectField>{ Lead.Inbound_Ingestion_Log__c, Lead.Status }
        );
        SSMOLeadCreationService.updateInboundIngestionLogsToCompletedStatusOnSSMOLeadUpdationWhenInClosedStatus(
            leadsWithStatusUpdateOnFallout,
            (Map<Id, Lead>) existing
        );
    }

    /**
     * @description Called to perform after Undelete processing
     */
    public override void onAfterUndelete() {
        AddressVerificationService.publishAddressVerificationEvent(this.records);
    }

    /**
     * @description It is used to perform processing before Leads are inserted.
     */
    public override void onBeforeInsert() {
        TimeZoneCalculationService.calculateTimeZone(this.records);
        Leads.newInstance(this.records).setDefaultValuesBeforeConversion();
        CassieIdEncryptionService.encryptCassieId(this.records, 'Email', 'Email_Cassie_ID__c');
    }

    /**
     * @description It is used to perform processing before Leads are updated.
     * @param existing
     */
    public override void onBeforeUpdate(Map<Id, SObject> existing) {
        Leads.newInstance(leadsWithUpdatedAddresses()).resetAddressAttributes();
        Leads.newInstance(this.records).setDefaultValuesBeforeConversion();
        TimeZoneCalculationService.calculateTimeZone(leadsWithUpdatedTimeZone());
        Leads.newInstance(leadsWithUpdatedPrimaryCampaignSource()).updateLastInboundDateTime();
        List<Lead> leadsToBeUpdatedOnFallout = getChangedRecords(
            new Set<SObjectField>{ Lead.Inbound_Ingestion_Log__c }
        );
        SSMOLeadCreationService.updateFieldsOnLeadAfterFallout(leadsToBeUpdatedOnFallout);
        CassieIdEncryptionService.encryptCassieId(
            leadsWithUpdatedEmail(),
            'Email',
            'Email_Cassie_ID__c'
        );
        OptOutOfCommunicationsService.updateDoNotCallAndSMSOptedOut(leadsWithUpdatedPhone());
        OptOutOfCommunicationsService.updateDateSMSOptedOutOrIn(leadsWithUpdatedSMSOptedOut());
        //@JIRA# LEM-21484
        List<Lead> statusUpdatedLeads = new List<Lead>(
            (List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.Status })
        );
        Leads.newInstance(statusUpdatedLeads).updateLastStatusChangeDate();
    }

    /**
     * @description this method used to get changed records .
     * @return List<Contact>
     */
    private List<Lead> leadsWithUpdatedPhone() {
        return new List<Lead>((List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.Phone }));
    }

    /**
     * @description To update address verification status and date
     * @return List<Lead>
     */
    private List<Lead> leadsWithUpdatedEmail() {
        return new List<Lead>((List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.Email }));
    }

    /**
     * @description this method used to get changed records.
     * @return List<Contact>
     */
    private List<Lead> leadsWithUpdatedSMSOptedOut() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.SMS_Opted_Out__c })
        );
    }
    /**
     * @description Check if Lead has been converted
     * @return List<Lead>
     */
    private list<lead> checkForConvertedLeads() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(new Set<Schema.SObjectField>{ Lead.isConverted })
        );
    }

    /**
     * @description It gets the account ids from the list of converted leads.
     * @param newConvertedLeads
     * @return List<Lead>
     */
    private Set<Id> collectAccountIdsFromConvertedLeads(List<Lead> newConvertedLeads) {
        Set<Id> accountIdsFromConvertedLeads = new Set<Id>();
        for (Lead eachConvertedLead : newConvertedLeads) {
            accountIdsFromConvertedLeads.add(eachConvertedLead.convertedAccountId);
        }
        return accountIdsFromConvertedLeads;
    }

    /**
     * @description It is used to get Leads with updated Address or Status.
     * @return List<Lead>
     */
    private List<Lead> leadsWithUpdatedAddressOrStatus() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(
                new Set<SObjectField>{
                    Lead.Country,
                    Lead.CountryCode,
                    Lead.State,
                    Lead.StateCode,
                    Lead.City,
                    Lead.PostalCode,
                    Lead.Street,
                    Lead.Address_Verification_Status__c
                }
            )
        );
    }

    /**
     * @description To update address verification status and date
     * @return List<Lead>
     */
    private List<Lead> leadsWithUpdatedAddresses() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(
                new Set<SObjectField>{
                    Lead.Country,
                    Lead.CountryCode,
                    Lead.State,
                    Lead.StateCode,
                    Lead.City,
                    Lead.PostalCode,
                    Lead.Street
                }
            )
        );
    }
    /**
     * @description It is used to collect Leads with updated Time Zone backend field
     * @return List<Lead>
     */
    private List<Lead> leadsWithUpdatedTimeZone() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.Time_Zone_Backend__c })
        );
    }

    /**
     * @description It is used to collect Leads with updated Primary Campaign Source field
     * @return List<Lead>
     */
    private List<Lead> leadsWithUpdatedPrimaryCampaignSource() {
        return new List<Lead>(
            (List<Lead>) getChangedRecords(new Set<SObjectField>{ Lead.Primary_Campaign_Source__c })
        );
    }
}