sfdx-source/force-app/main/default/objects/Account/fields/Alcohol_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Alcohol_Eligibility__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-2141: Signifies whether Mx’s location is eligible for alcohol sales and/or deliveries</description>
    <inlineHelpText>Signifies whether Mx’s location is eligible for alcohol sales and/or deliveries</inlineHelpText>
    <label>Alcohol Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wet</fullName>
            </value>
            <value>
                <fullName>Moist</fullName>
            </value>
            <value>
                <fullName>Dry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1157: This field describes whether the store is in coverage or not.</description>
    <inlineHelpText>Indicates whether the store is in coverage or not. Store not in coverage will not be onboarded to DoorDash platform</inlineHelpText>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Coverage</fullName>
            </value>
            <value>
                <fullName>Not in Coverage</fullName>
            </value>
            <value>
                <fullName>Coverage check failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Last_Coverage_Check_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Coverage_Check_Time__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1157: This represents the time when the last coverage check was run.</description>
    <inlineHelpText>Indicates when the store coverage check was last run</inlineHelpText>
    <label>Last Coverage Check Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Order protocol defined for the Mxs being onboarded</description>
    <inlineHelpText>Signifies the type of order protocol requested for the Mx store</inlineHelpText>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
            </value>
            <value>
                <fullName>Android Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>POS (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet Return Label</fullName>
            </value>
            <value>
                <fullName>Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet and Printer (DoorDash Owns)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Order_Protocol_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol_Email__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Signifies the email to which orders will be sent to in case order protocol is email.</description>
    <inlineHelpText>Signifies the email to which orders will be sent to in case order protocol is email</inlineHelpText>
    <label>Order Protocol Email</label>
    <type>Email</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-280 This picklist defines the primary vertical of the Mx.</description>
    <inlineHelpText>Primary vertical of the Mx</inlineHelpText>
    <label>Primary Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Starting_Point__c.field-meta.xml
<CustomField>
    <fullName>Starting_Point__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1157: This field represents the starting point of the store account.</description>
    <inlineHelpText>Indicates the starting point of the store account</inlineHelpText>
    <label>Starting Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Starting_Point_ID__c.field-meta.xml
<CustomField>
    <fullName>Starting_Point_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1514: Represents the Starting Point ID of the store account.</description>
    <inlineHelpText>Indicates the Starting Point ID of the store account</inlineHelpText>
    <label>Starting Point ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648, LEM-14727: It is used to capture the UUID received by Mulesoft in the payload. </description>
    <inlineHelpText>Displays the SSMO UUID of the Mx if one exists.</inlineHelpText>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Address_ID__c.field-meta.xml
<CustomField>
    <fullName>Address_ID__c</fullName>
    <description>LEM-14822: It is used to store address Id recieved from SSMO payload.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Address ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Address_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Address_Rejection_Reason__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the address rejection reasons.</description>
    <label>Address Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bad Address</fullName>
            </value>
            <value>
                <fullName>Incomplete Address</fullName>
            </value>
            <value>
                <fullName>Technical Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Alcohol_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Alcohol_Eligibility__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It signifies whether Mx’s location is eligible for alcohol sales and/or deliveries.</description>
    <label>Alcohol Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wet</fullName>
            </value>
            <value>
                <fullName>Moist</fullName>
            </value>
            <value>
                <fullName>Dry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Came_into_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Came_into_Coverage__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It indicates when the Contact became in coverage.</description>
    <label>Came into Coverage</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14818: It is used to Store the Company Name received in payload on SSMO fallout.</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It indicates whether the Contact is in coverage or not.</description>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Coverage</fullName>
            </value>
            <value>
                <fullName>Not In Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fallout Event</fullName>
            </value>
            <value>
                <fullName>Onboarding Event</fullName>
            </value>
            <value>
                <fullName>SSOB Onboarding Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Last_Coverage_Check_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Coverage_Check_Time__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It indicates the time when the last coverage check was run.</description>
    <label>Last Coverage Check Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It stores the Order Protocol value from SSMO on Contact.</description>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Protocol</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Order_Protocol_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol_Email__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <label>Order Protocol Email</label>
    <type>Email</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Order_Protocol_Phone__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol_Phone__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14590: It stores the Order Protocol Phone value from SSMO on Lead.</description>
    <label>Order Protocol Phone</label>
    <type>Phone</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It defines the primary vertical of the SMB.</description>
    <label>Primary Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Campaign_Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/SSMO_Business_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>SSMO_Business_Account_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16814: It is used to store SSMO business Account Id.</description>
    <label>SSMO Business Account Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/SSMO_Matching_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>SSMO_Matching_Account_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14818: It is used to Store the matching account Id received in payload on SSMO fallout.</description>
    <label>SSMO Matching Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Starting_Point__c.field-meta.xml
<CustomField>
    <fullName>Starting_Point__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the starting point of the Contact.</description>
    <label>Starting Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Starting_Point_ID__c.field-meta.xml
<CustomField>
    <fullName>Starting_Point_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the Starting Point ID of the Contact.</description>
    <label>Starting Point ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>LEM-17453: It is used to store the SSMO unique Id received by Mulesoft in each payload for this Contact.</description>
    <label>SSMO Transactional Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648: It is used to capture the SSMO UUID received by Mulesoft in the payload .</description>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Order/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648: It is used to capture the UUID received by Mulesoft in the payload.</description>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Campaign_Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>CGnA</fullName>
        <isActive>false</isActive>
        <label>CGnA</label>
    </customValue>
    <customValue>
        <fullName>C&amp;G (no DM)</fullName>
        <isActive>false</isActive>
        <label>C&amp;G (no DM)</label>
    </customValue>
    <description>LEM-9256: New field for A&amp;P Pipeline tracking.</description>
    <masterLabel>Campaign Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Order_Protocol.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Android Tablet (Merchant Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet and Printer (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (Merchant Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (DoorDash Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet Return Label</fullName>
    </customValue>
    <customValue>
        <fullName>POS (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and Tablet (Caviar Owns)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
    </customValue>
    <customValue>
        <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
    </customValue>
    <customValue>
        <fullName>One Time Tablet and Printer Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Indicator Unspecified</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <description>LEM-179 – Initial Setup of Quote object</description>
    <masterLabel>Order Protocol</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <description>LEM-280: This picklist value set is created to define the verticals and sub-verticals associated with store and business accounts.</description>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/services/SSMOContactCreationServiceImpl.cls
/**
 * @author Deloitte
 * @date   05/17/2024
 * @description It is the service implementation class for Contact creation on SSMO fallout event.
 */

public inherited sharing class SSMOContactCreationServiceImpl implements ISSMOContactCreationService {
    private static final String CONTACT_STATUS_UNTOUCHED = 'Untouched';
    private static final String CONTACT_SOURCE = 'get.doordash.com';
    private static final Integer CONTACT_NO_OF_LOCATION = 1;
    private static final String CONTACT_EMAIL_VERIFICATION_INVALID = 'Invalid';
    private static final String CONTACT_EMAIL_VERIFICATION_VALID = 'Valid';
    private static final String CONTACT_IN_COVERAGE = 'In Coverage';
    private static final String CONTACT_NOT_IN_COVERAGE = 'Not In Coverage';
    private static final String CONTACT_ADDRESS_VERIFICATION_REJECTED = 'Rejected';
    private static final String CONTACT_NAME_UNKNOWN = 'Unknown';
    private static final String CONTACT_EVENT_TYPE_FALLOUT = 'Fallout Event';
    private static final String LOG_SALES_DOMAIN = 'Sales';
    private static final String LOG_SELF_SERVING_FALLOUT_SERVICE = 'selfserviceFalloutService';
    private static final String PRIMARY_VERTICAL_RX = 'Rx';
    private static final String STATUS_VERIFIED = 'Verified';
    private static final String STATUS_UNVERIFIED = 'Unverified';
    private static final Map<String, String> ORDER_PROTOCOL_MAPPING = SSMOFalloutWrapper.ORDER_PROTOCOL_MAPPING;
    private static final Map<String, String> LOCALE_LANGUAGE_MAPPING = SSMOFalloutWrapper.LOCALE_LANGUAGE_MAPPING;
    private static final Map<String, String> PRIMARY_VERTICAL_MAPPING = SSMOFalloutWrapper.PRIMARY_VERTICAL_MAPPING;
    private static final Map<String, String> SELF_SERVE_STEP_MAPPING = SSMOFalloutWrapper.SELF_SERVE_STEP_MAPPING;
    private static final Integer HOURS_OF_OPERATION_MAX_LENGTH = 255;
    private static final Integer FIRSTNAME_LASTNAME_MAX_LENGTH = 40;

    /**
     * @description It is used to populate contact with Basic fields on basis of payload.
     * @param payLoad
     * @param contactToInsert
     * @return Contact
     */
    public Contact insertContactSSMO(SSMOFalloutWrapper payLoad, Contact contactToInsert) {
        contactToInsert.AccountId = contactToInsert.SSMO_Business_Account_Id__c;
        contactToInsert.Unique_Identifier__c = payload.sourceUniqueId;
        contactToInsert.Company__c = payload.storeName;
        contactToInsert.FirstName = (String.isNotEmpty(payload.ownerFirstName) && (payload.ownerFirstName).length() > FIRSTNAME_LASTNAME_MAX_LENGTH)
                         ? (payload.ownerFirstName).substring(0, FIRSTNAME_LASTNAME_MAX_LENGTH)
                         : payload.ownerFirstName;
        contactToInsert.LastName = (String.isNotEmpty(payload.ownerLastName) && (payload.ownerLastName).length() > FIRSTNAME_LASTNAME_MAX_LENGTH)
                         ? (payload.ownerLastName).substring(0, FIRSTNAME_LASTNAME_MAX_LENGTH)
                         : payload.ownerLastName;
        contactToInsert.MobilePhone = payload.ownerPhone;
        contactToInsert.Email = payload.email;
        contactToInsert.Event_Type__c = CONTACT_EVENT_TYPE_FALLOUT;
        contactToInsert.Primary_Vertical__c = PRIMARY_VERTICAL_RX;
        contactToInsert.Unique_Id__c = payload.id;
        return contactToInsert;
    }

    /**
     * @description It is used to populate Contact with fields on basis of payload.
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    public Contact updateContactSSMO(SSMOFalloutWrapper inputPayload, Contact contactForUpdate) {
        contactForUpdate.SSMO_Matching_Account_Id__c = getMatchingAccountId(inputPayload);
        if (contactForUpdate.Order_Protocol__c == null && inputPayload.orderProtocol != null) {
            String protocolValue = inputPayload.orderProtocol;
            contactForUpdate.Order_Protocol__c = ORDER_PROTOCOL_MAPPING.containsKey(protocolValue)
                ? ORDER_PROTOCOL_MAPPING.get(protocolValue)
                : null;
        }
        contactForUpdate = updateAddressVerification(inputPayload, contactForUpdate);
        contactForUpdate = updatePrimaryFields(inputPayload, contactForUpdate);
        contactForUpdate = updateNameFields(inputPayload, contactForUpdate);
        contactForUpdate = updateOrderProtocolFields(inputPayload, contactForUpdate);
        contactForUpdate = overrideFields(inputPayload, contactForUpdate);
        contactForUpdate = updateEmailVerification(inputPayload, contactForUpdate);
        contactForUpdate = updateStoreInformation(inputPayload, contactForUpdate);
        if (contactForUpdate.MailingAddress == null) {
            contactForUpdate = updateMailingAddress(inputPayload, contactForUpdate);
        }
        contactForUpdate.Unique_Identifier__c = inputPayload.sourceUniqueId;
        return contactForUpdate;
    }

    /**
     * @description It is used to update the mailing address in the contact
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateMailingAddress(
        SSMOFalloutWrapper inputPayload,
        Contact contactForUpdate
    ) {
        if (
            inputPayload.addressVerificationInfo?.addressVerificationStatus == STATUS_VERIFIED &&
            inputPayload.addressVerificationInfo?.validatedAddress != null
        ) {
            contactForUpdate.MailingCity = inputPayload.addressVerificationInfo
                ?.validatedAddress
                ?.city;
            contactForUpdate.MailingPostalCode = inputPayload.addressVerificationInfo
                ?.validatedAddress
                ?.postalCode;
            contactForUpdate.MailingCountry = inputPayload.addressVerificationInfo
                ?.validatedAddress
                ?.country;
            contactForUpdate.MailingCountryCode = inputPayload.addressVerificationInfo
                ?.validatedAddress
                ?.countryShortname;
            contactForUpdate.MailingStateCode = inputPayload.addressVerificationInfo
                ?.validatedAddress
                ?.state;
            if (contactForUpdate.MailingStateCode?.length() > 4) {
                contactForUpdate.MailingStateCode = null;
                contactForUpdate.MailingState = inputPayload.addressVerificationInfo
                    ?.validatedAddress
                    ?.state;
            }
            contactForUpdate = getStreetAddress(inputPayload, contactForUpdate);
        } else if (inputPayload.storeAddress != null) {
            contactForUpdate.MailingCity = inputPayload.storeAddress?.city;
            contactForUpdate.MailingPostalCode = inputPayload.storeAddress?.postalCode;
            contactForUpdate.MailingCountryCode = inputPayload.storeAddress?.country;
            contactForUpdate.MailingStateCode = inputPayload.storeAddress?.state;
            if (contactForUpdate.MailingStateCode?.length() > 4) {
                contactForUpdate.MailingStateCode = null;
                contactForUpdate.MailingState = inputPayload.storeAddress?.state;
            }
            contactForUpdate = getStreetAddress(inputPayload, contactForUpdate);
        }
        return contactForUpdate;
    }

    /**
     * @description It is used to override the contact fields
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact overrideFields(SSMOFalloutWrapper inputPayload, Contact contactForUpdate) {
        contactForUpdate.Unique_Identifier__c = inputPayload.sourceUniqueId;
        contactForUpdate.Coverage__c = (String.isNotEmpty(
                inputPayload.addressVerificationInfo?.submarket?.id
            ))
            ? CONTACT_IN_COVERAGE
            : CONTACT_NOT_IN_COVERAGE;
        if (contactForUpdate.Coverage__c == CONTACT_IN_COVERAGE) {
            contactForUpdate.Came_into_Coverage__c = DateTime.now();
        }
        contactForUpdate.Last_Coverage_Check_Time__c = DateTime.now();
        contactForUpdate.Alcohol_Eligibility__c = inputPayload.addressVerificationInfo
            ?.alcoholRules
            ?.alcoholAllowanceCategory;
        if (String.isNotEmpty(inputPayload.addressVerificationInfo?.startingPoint?.startingPoint)) {
            contactForUpdate.Starting_Point__c = inputPayload.addressVerificationInfo?.startingPoint?.startingPoint;
        }
        if (inputPayload.addressVerificationInfo?.startingPoint?.id != null) {
            contactForUpdate.Starting_Point_ID__c = inputPayload.addressVerificationInfo?.startingPoint?.id;
        }
        if (String.isNotEmpty(inputPayload.addressVerificationInfo?.validatedAddress?.addressId)) {
            contactForUpdate.Address_ID__c = inputPayload.addressVerificationInfo?.validatedAddress?.addressId;
        }
        if (String.isNotEmpty(inputPayload.addressVerificationInfo?.rejectedReason)) {
            contactForUpdate.Address_Rejection_Reason__c = inputPayload.addressVerificationInfo?.rejectedReason;
        }
        return contactForUpdate;
    }

    /**
     * @description This method will update contact order protocol fields
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateOrderProtocolFields(
        SSMOFalloutWrapper inputPayload,
        Contact contactForUpdate
    ) {
        contactForUpdate.Order_Protocol_Phone__c = (inputPayload.orderProtocolPhone != null &&
            !String.isEmpty(inputPayload.orderProtocolPhone))
            ? inputPayload.orderProtocolPhone
            : contactForUpdate.Order_Protocol_Phone__c;
        contactForUpdate.Order_Protocol_Email__c = (inputPayload.orderProtocolEmail != null &&
            !String.isEmpty(inputPayload.orderProtocolEmail))
            ? inputPayload.orderProtocolEmail
            : contactForUpdate.Order_Protocol_Email__c;
        contactForUpdate.POS_System__c = (inputPayload.orderProtocolPosProviderType != null &&
            !String.isEmpty(inputPayload.orderProtocolPosProviderType))
            ? inputPayload.orderProtocolPosProviderType
            : contactForUpdate.POS_System__c;
        contactForUpdate.Menu_URL__c = (contactForUpdate.Menu_URL__c == null &&
            inputPayload.menuLinks != null)
            ? String.join(inputPayload.menuLinks, ',')
            : contactForUpdate.Menu_URL__c;
        return contactForUpdate;
    }

    /**
     * @description It is used to update contact store information
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateStoreInformation(
        SSMOFalloutWrapper inputPayload,
        Contact contactForUpdate
    ) {
        contactForUpdate.Business_Id__c = (contactForUpdate.Business_Id__c == null &&
            inputPayload.businessId != null)
            ? String.valueOf(inputPayload.businessId)
            : contactForUpdate.Business_Id__c;
        contactForUpdate.Store_Id__c = (contactForUpdate.Store_Id__c == null &&
            inputPayload.storeId != null)
            ? String.valueOf(inputPayload.storeId)
            : contactForUpdate.Store_Id__c;
            contactForUpdate.Hours_of_Operation__c = (contactForUpdate.Hours_of_Operation__c == null &&
            inputPayload.storeHours != null)
            ? ((inputPayload.storeHours).length() > HOURS_OF_OPERATION_MAX_LENGTH)
            	? (inputPayload.storeHours).substring(0, HOURS_OF_OPERATION_MAX_LENGTH) : inputPayload.storeHours
            : contactForUpdate.Hours_of_Operation__c;
        return contactForUpdate;

    }

    /**
     * @description It is used to update primary details of the contact
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updatePrimaryFields(SSMOFalloutWrapper inputPayload, Contact contactForUpdate) {
        if (contactForUpdate.Phone == null && inputPayload.businessPhone != null) {
            contactForUpdate.Phone = inputPayload.businessPhone;
        }
        if (contactForUpdate.Email == null && inputPayload.email != null) {
            contactForUpdate.Email = inputPayload.email;
        }
        if (contactForUpdate.Preferred_Language__c == null && inputPayload.locale != null) {
            contactForUpdate.Preferred_Language__c = LOCALE_LANGUAGE_MAPPING.containsKey(
                    inputPayload.locale
                )
                ? LOCALE_LANGUAGE_MAPPING.get(inputPayload.locale)
                : null;
        }
        return contactForUpdate;
    }

    /**
     * @description It is used to update Contact name fields
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateNameFields(SSMOFalloutWrapper inputPayload, Contact contactForUpdate) {
        if (String.isEmpty(contactForUpdate.FirstName)) {
            contactForUpdate.FirstName = (inputPayload.ownerFirstName != null &&
                !String.isEmpty(inputPayload.ownerFirstName))
                ? inputPayload.ownerFirstName
                : CONTACT_NAME_UNKNOWN;
        }
        if (String.isEmpty(contactForUpdate.LastName)) {
            contactForUpdate.LastName = (inputPayload.ownerLastName != null &&
                !String.isEmpty(inputPayload.ownerLastName))
                ? inputPayload.ownerLastName
                : CONTACT_NAME_UNKNOWN;
        }
        return contactForUpdate;
    }

    /**
     * @description It is used to update contact's address verification details
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateAddressVerification(
        SSMOFalloutWrapper inputPayload,
        Contact contactForUpdate
    ) {
        String verificationDate;
        if (inputPayload.addressVerificationInfo != null) {
            contactForUpdate.Address_Verification_Status__c = (String.isNotEmpty(
                    inputPayload.addressVerificationInfo?.rejectedReason
                ))
                ? CONTACT_ADDRESS_VERIFICATION_REJECTED
                : inputPayload.addressVerificationInfo?.addressVerificationStatus;
            verificationDate = inputPayload.addressVerificationInfo?.addressVerificationDate;
            contactForUpdate.Address_Verification_Date__c = (String.isNotEmpty(verificationDate))
                ? ((DateTime) Json.deserialize('"' + verificationDate + '"', DateTime.class))
                : null;
        } else {
            contactForUpdate.Address_Verification_Status__c = STATUS_UNVERIFIED;
        }
        if (inputPayload.selfServeStep != null && !String.isEmpty(inputPayload.selfServeStep)) {
            contactForUpdate.Self_Serve_Step__c = SELF_SERVE_STEP_MAPPING.containsKey(
                    inputPayload.selfServeStep
                )
                ? SELF_SERVE_STEP_MAPPING.get(inputPayload.selfServeStep)
                : '';
        }
        return contactForUpdate;
    }

    /**
     * @description It is used to update contact email vertification status and primary vertical
     * @param inputPayload
     * @param contactForUpdate
     * @return Contact
     */
    private Contact updateEmailVerification(
        SSMOFalloutWrapper inputPayload,
        Contact contactForUpdate
    ) {
        if (inputPayload.hasValidEmail != null) {
            contactForUpdate.Email_Verification_Status__c = inputPayload.hasValidEmail
                ? CONTACT_EMAIL_VERIFICATION_VALID
                : CONTACT_EMAIL_VERIFICATION_INVALID;
        } else {
            contactForUpdate.Email_Verification_Status__c = CONTACT_EMAIL_VERIFICATION_INVALID;
        }
        contactForUpdate.Primary_Vertical__c = PRIMARY_VERTICAL_MAPPING.containsKey(
                inputPayload.verticalType
            )
            ? PRIMARY_VERTICAL_MAPPING.get(inputPayload.verticalType)
            : PRIMARY_VERTICAL_RX;
        return contactForUpdate;
    }

    /**
     * @description It is used get the matching Account Id from Payload.
     * @param falloutWrapper
     * @return String
     */
    private String getMatchingAccountId(SSMOFalloutWrapper falloutWrapper) {
        String matchingAccountId;
        if (
            !falloutWrapper?.matchedRecords?.account.isEmpty() &&
            String.isNotEmpty(falloutWrapper?.matchedRecords?.account[0]?.Id)
        ) {
            matchingAccountId = falloutWrapper.matchedRecords.account[0].Id;
        }
        return String.isNotEmpty(matchingAccountId) ? matchingAccountId : '';
    }
    /**
     * @description It is used to update the street address in the Contact
     * @param inputPayload
     * @param contactForUpdate
     * @return String
     */
    private Contact getStreetAddress(SSMOFalloutWrapper inputPayload, Contact contactForUpdate) {
        if (inputPayload.addressVerificationInfo?.addressVerificationStatus == STATUS_VERIFIED) {
            contactForUpdate.MailingStreet =
                (String.isNotBlank(
                        inputPayload.addressVerificationInfo?.validatedAddress?.addressLine1
                    )
                    ? inputPayload.addressVerificationInfo?.validatedAddress?.addressLine1
                    : '') +
                (String.isNotBlank(
                        inputPayload.addressVerificationInfo?.validatedAddress?.addressLine2
                    )
                    ? inputPayload.addressVerificationInfo?.validatedAddress?.addressLine2
                    : '');
        } else {
            contactForUpdate.MailingStreet =
                (String.isNotBlank(inputPayload.storeAddress?.addressLine1)
                    ? inputPayload.storeAddress?.addressLine1
                    : '') +
                (String.isNotBlank(inputPayload.storeAddress?.addressLine2)
                    ? inputPayload.storeAddress?.addressLine2
                    : '');
            if (
                (String.isBlank(inputPayload.storeAddress?.country)) &&
                (String.isNotBlank(inputPayload.storeAddress?.state))
            ) {
                contactForUpdate.MailingStreet =
                    contactForUpdate.MailingStreet +
                    ' ' +
                    inputPayload.storeAddress?.state;
                contactForUpdate.MailingState = null;
                contactForUpdate.MailingStateCode = null;
            }
        }
        return contactForUpdate;
    }
}