sfdx-source/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1139: This field represents the Brand associated with the store.</description>
    <inlineHelpText>Represents the Brand associated with the store</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Accounts (Stores)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Price_Range__c.field-meta.xml
<CustomField>
    <fullName>Price_Range__c</fullName>
    <description>LEM-3123: Depicts price range that will be used to establish # of dollar signs on DoorDash App.</description>
    <label>Price Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$</fullName>
            </value>
            <value>
                <fullName>$$</fullName>
            </value>
            <value>
                <fullName>$$$</fullName>
            </value>
            <value>
                <fullName>$$$$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648, LEM-14727: It is used to capture the UUID received by Mulesoft in the payload. </description>
    <inlineHelpText>Displays the SSMO UUID of the Mx if one exists.</inlineHelpText>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Brand_Owner__c.field-meta.xml
<CustomField>
    <fullName>Brand_Owner__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-564: Represents the Owner of the Brand.</description>
    <inlineHelpText>Represents the Owner of the Brand</inlineHelpText>
    <label>Brand Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Price_Range__c.field-meta.xml
<CustomField>
    <fullName>Price_Range__c</fullName>
    <defaultValue>&apos;$$&apos;</defaultValue>
    <description>LEM-6195: It indicates the price range that will be used to establish # of dollar signs on DoorDash App.</description>
    <label>Price Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$</fullName>
            </value>
            <value>
                <fullName>$$</fullName>
            </value>
            <value>
                <fullName>$$$</fullName>
            </value>
            <value>
                <fullName>$$$$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648: It is used to capture the SSMO UUID received by Mulesoft in the payload .</description>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/BrandsSelectorTest.cls
/**
 * @author Deloitte
 * @date 10/31/2022
 * @description Test class for BrandsSelector class.
 */
@isTest(SeeAllData=false)
private class BrandsSelectorTest {
    private static final String LICENSOR = 'Licensor';
    private static final string INVALID_ASSERT_MESSAGE = 'Unexpected results';
    private static final Id BUSINESS_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Business')
        .getRecordTypeId();
    private static final String UNIQUE_IDENTIFIER = '92108a53-e8d9-4a0c-9193-9152aeb86fe4';
    /**
     * @description To test Contructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCall() {
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = businessAccountRecordTypeId,
            Type = 'Corporate',
            Segment__c = 'SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandKFC;
        Brand__c brandMcDonalds = new Brand__c(
            Name = 'McDonalds',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandMcDonalds;
        BrandsSelector brandsInstance = new BrandsSelector();
        Schema.SObjectType typeOfObj = brandsInstance.getSObjectType();
        System.assertEquals(
            Schema.Brand__c.SObjectType,
            typeOfObj,
            'The object type must be Brand'
        );
        List<Schema.SObjectField> fieldList = brandsInstance.getSObjectFieldList();
        System.assertEquals(
            new List<Schema.SObjectField>{ Brand__c.Id, Brand__c.Name, Brand__c.Price_Range__c },
            fieldList,
            'Mismatch in field list'
        );
    }

    /**
     * @description To test the selection of Brands by the passed Ids.
     */
    @isTest
    private static void testWhenSelectByIdThenReturnBrands() {
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = businessAccountRecordTypeId,
            Type = 'Corporate',
            Segment__c ='SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandKFC;
        Brand__c brandMcDonalds = new Brand__c(
            Name = 'McDonalds',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandMcDonalds;
        List<Brand__c> queryResult = BrandsSelector.newInstance()
            .selectById(new Set<Id>{ brandKFC.Id, brandMcDonalds.Id });
        System.assertEquals(2, queryResult.size(), 'Failed to query Brands by Id');
    }

    /**
     * @description To test the selection of Brands by the passed Ids.
     * for method selectBrandsByIdWithParentIds
     */
    @isTest
    private static void testWhenSelectBrandsByIdWithParentIdsThenReturnExpectedValues() {
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = businessAccountRecordTypeId,
            Type = 'Corporate',
            Segment__c ='SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandKFC;
        Brand__c brandMcDonalds = new Brand__c(
            Name = 'McDonalds',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandMcDonalds;
        List<Brand__c> queryResult01 = BrandsSelector.newInstance()
            .selectBrandsByIdWithParentIds(new Set<Id>{ brandKFC.Id, brandMcDonalds.Id });
        List<Brand__c> queryResult02 = BrandsSelector.newInstance()
            .selectBrandsByIdWithParentIds(new Set<Id>{ brandKFC.Id });
        List<Brand__c> queryResult03 = BrandsSelector.newInstance()
            .selectBrandsByIdWithParentIds(new Set<Id>{ brandMcDonalds.Id });
        System.assertEquals(2, queryResult01.size(), 'Failed to query Brands by Id');
        System.assertEquals(1, queryResult02.size(), 'Failed to query Brands by Id');
        System.assertEquals(1, queryResult03.size(), 'Failed to query Brands by Id');
        System.assertEquals(brandKFC.Id, queryResult02[0].Id, 'Failed to query Brands by Id');
        System.assertEquals(brandMcDonalds.Id, queryResult03[0].Id, 'Failed to query Brands by Id');
    }

    /**
     * @description To test the selection of Brands by names passed
     * for method getBrandsByBrandName
     */
    @isTest
    private static void testWhenValidateBrandNameThenReturnExpectedValues() {
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = businessAccountRecordTypeId,
            Type = 'Corporate',
            Segment__c ='SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandKFC;
        Brand__c brandMcDonalds = new Brand__c(
            Name = 'McDonalds',
            Brand_Owner__c = corporateAccountWithBrand.Id
        );
        insert brandMcDonalds;
        List<Brand__c> queryResult01 = BrandsSelector.newInstance()
            .getBrandsByBrandName(new List<String>{ 'KFC', 'McDonalds' });
        List<Brand__c> queryResult02 = BrandsSelector.newInstance()
            .getBrandsByBrandName(new List<String>{ 'KFC' });
        List<Brand__c> queryResult03 = BrandsSelector.newInstance()
            .getBrandsByBrandName(new List<String>{ 'McDonalds' });
        System.assertEquals(2, queryResult01.size(), 'Failed to query Brands by Id');
        System.assertEquals(1, queryResult02.size(), 'Failed to query Brands by Id');
        System.assertEquals(1, queryResult03.size(), 'Failed to query Brands by Id');
        System.assertEquals(brandKFC.Id, queryResult02[0].Id, 'Failed to query Brands by Id');
        System.assertEquals(brandMcDonalds.Id, queryResult03[0].Id, 'Failed to query Brands by Id');
    }

    /**
     * @description To test the selection of Brands by the passed uuids.
     */
    @isTest
    private static void testWhenUniqueIdentifiersPassedThenReturnBrands() {
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = BUSINESS_RECORD_TYPE_ID,
            Type = 'Corporate',
            Segment__c ='SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id,
            Unique_Identifier__c = UNIQUE_IDENTIFIER
        );
        insert brandKFC;

        Test.startTest();
        List<Brand__c> queryResult = BrandsSelector.newInstance()
            .selectBrandsByUniqueIdentifiers(new Set<String>{ UNIQUE_IDENTIFIER });
        Test.stopTest();
        System.assertEquals(1, queryResult.size(), INVALID_ASSERT_MESSAGE);
    }
    /**
     * @description To test the selection of Brands by the passed AccountIds.
     */
    @isTest
    private static void testWhenAccountIdsPassedThenReturnBrands() {
        Account corporateAccountWithBrand = new Account(
            Name = 'McDonalds Canada',
            RecordTypeId = BUSINESS_RECORD_TYPE_ID,
            Type = 'Corporate',
            Segment__c ='SMB'
        );
        insert corporateAccountWithBrand;
        Brand__c brandKFC = new Brand__c(
            Name = 'KFC',
            Brand_Owner__c = corporateAccountWithBrand.Id,
            Unique_Identifier__c = UNIQUE_IDENTIFIER
        );
        insert brandKFC;

        Test.startTest();
        List<Brand__c> queryResult = BrandsSelector.newInstance()
            .selectBrandsByAccountIds(new Set<Id>{ corporateAccountWithBrand.Id });
        Test.stopTest();
        System.assertEquals(1, queryResult.size(), INVALID_ASSERT_MESSAGE);
    }
}