sfdx-source/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1139: This field represents the Brand associated with the store.</description>
    <inlineHelpText>Represents the Brand associated with the store</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Accounts (Stores)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Business_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Business_Vertical__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-11073: It is used to associate the Business Vertical to a Store Account.</description>
    <label>Business Vertical</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Vertical__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Vertical__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/Business_Vertical__c.object-meta.xml
<CustomObject>
    <description>LEM-11076: It is used to capture the Vertical, UI Type and Product as a singular Business Vertical Id.</description>
    <label>Business Vertical</label>
    <nameField>
        <label>Business Vertical</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/classes/services/IInstantIngestionAccountService.cls
/**
 * @author Deloitte
 * @date 05/15/2024
 * @description Interface class for InstantIngestionAccountService.
 */

public interface IInstantIngestionAccountService {
    /**
     * @description It is used to create the Business Account from the Payload.
     * @param payload
     * @param submarketId
     * @param integrationTypeByUUID
     * @return Account
     */
    Account createBusinessAccount(
        InstantIngestionPayloadParser payload,
        String submarketId,
        String integrationTypeByUUID
    );

    /**
     * @description It is used to create the Business Account from the SSOB Payload.
     * @param payload
     * @param parsedpayload
     * @return Account
     */
    Account createBusinessAccountSSOB(String payload, SSOBOnboardingPayloadParser parsedpayload);

    /**
     * @description It is used to create the Brand using the Payload and Account.
     * @param account
     * @return Brand__c
     */
    Brand__c createBrand(Account account);

    /**
     * @description It is used to create Store Account using the Payload, BrandId,
     * Business Vertical and SubmarketId.
     * @param payload
     * @param brandId
     * @param businessAccount
     * @param businessVertical
     * @param submarketId
     * @return Account
     */
    Account createStoreAccount(
        InstantIngestionPayloadParser payload,
        Id brandId,
        Account businessAccount,
        Business_Vertical__c businessVertical,
        String submarketId
    );
}