sfdx-source/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1139: This field represents the Brand associated with the store.</description>
    <inlineHelpText>Represents the Brand associated with the store</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Accounts (Stores)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Business_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Business_Vertical__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-11073: It is used to associate the Business Vertical to a Store Account.</description>
    <label>Business Vertical</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Vertical__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Vertical__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <description>LEM-6187</description>
    <label>Experience</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DoorDash</fullName>
            </value>
            <value>
                <fullName>Caviar</fullName>
            </value>
            <value>
                <fullName>Storefront</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Franchise_Parent__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Parent__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-99: Describes the parent of a franchisee.</description>
    <label>Franchise Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Franchise Parents</relationshipLabel>
    <relationshipName>FranchiseParents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Reference__c/Business_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-2082 Object used for integration of Business Ids</description>
    <label>Business Reference</label>
    <nameField>
        <label>Business Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-12683</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Business References</relationshipLabel>
    <relationshipName>Business_References</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Business_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Business_Vertical__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-11072: It is used to associate a Business Vertical to the Business Reference.</description>
    <label>Business Vertical</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Vertical__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Vertical__c</referenceTo>
    <relationshipLabel>Business References</relationshipLabel>
    <relationshipName>Business_References</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Default_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Type__c</fullName>
    <description>LEM-2306</description>
    <label>Default Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>COO Graveyard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>LEM-2082 Represents the corresponding record ID in the external source. For example, the Business ID of a record in MDS.</description>
    <label>Business ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Source__c</fullName>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <label>External Id Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Id_Source</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/Business_Vertical__c.object-meta.xml
<CustomObject>
    <description>LEM-11076: It is used to capture the Vertical, UI Type and Product as a singular Business Vertical Id.</description>
    <label>Business Vertical</label>
    <nameField>
        <label>Business Vertical</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/globalValueSets/External_Id_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MDS</fullName>
    </customValue>
    <customValue>
        <fullName>DriveDb</fullName>
    </customValue>
    <customValue>
        <fullName>Figment</fullName>
    </customValue>
    <customValue>
        <fullName>MDS - Catering</fullName>
    </customValue>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <masterLabel>External Id Source</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/services/XrefAndBizRefMatchingServiceImpl.cls
/**
 * @author DoorDash
 * @date   02/06/2024
 * @description This is the service impl class for matching bizref and xref
 */
public inherited sharing class XrefAndBizRefMatchingServiceImpl implements IXrefAndBizRefMatchingService {
    private static final String BUSINESS_REFERENCE_CORPORATE = 'Corporate';
    private static final String BUSINESS_REFERENCE_FRANCHISE = 'Franchise';
    private static final String CANNOT_FIND_BUS_REF_ERROR_MESSAGE = 'A Business Reference with the following criteria could not be found: ';
    private static final String DASH_STRING = '-'; //Make the matching criteria easier to read for the error message.
    private static final Map<String, String> EXPERIANCE_TO_EXTERNALSOURCE_MAP = new Map<String, String>{
        'DoorDash' => 'MDS',
        'Caviar' => 'MDS',
        'Storefront' => 'MDS'
        //'Drive' => 'DriveDB',
        //'Voice' => 'DriveDB'
    };
    private Set<String> storeCurrencyIsoCodes;
    private Set<String> brandNames;

    /**
     * @description Default Constructor to initialize class variables.
     */
    public XrefAndBizRefMatchingServiceImpl() {
        storeCurrencyIsoCodes = new Set<String>();
        brandNames = new Set<String>();
    }

    /**
     * @description LEM-12595 validate matching business ref exists for readiness check
     * @param accounts
     * @return businessRefMap
     */
    public Map<Id, String> findMatchingBizRefForReadinesCheck(List<Account> accounts) {
        Map<Id, String> accountIdToErrorMessage = new Map<Id, String>();
        Set<String> businessVerticalIds = getBusinessVerticals(accounts);
        Map<String, Business_Reference__c> businessRefMap = getBusinessReferencesByMatchingKey(
            businessVerticalIds
        );
        for (Account storeAccount : accounts) {
            Set<String> externalSources = getExternalSourceFromAccount(storeAccount);
            for (String externalSource : externalSources) {
                if (String.isBlank(externalSource)) {
                    continue;
                }
                Business_Reference__c bizref = matchTheBizRefWithAccountByExternalSource(
                    storeAccount,
                    businessRefMap,
                    externalSource
                );
                if (bizref == null) {
                    accountIdToErrorMessage.put(
                        storeAccount.Id,
                        getBizRefMatchingErrorDisplayMessage(storeAccount, externalSource)
                    );
                }
            }
        }
        return accountIdToErrorMessage;
    }
    /**
     * @description LEM-12595 Get Business References by Matching Business Vertical
     * @param accountBusinessVerticals
     * @return businessRefMap
     */
    @testvisible
    public Map<String, Business_Reference__c> getBusinessReferencesByMatchingKey(
        Set<String> accountBusinessVerticals
    ) {
        Map<String, Business_Reference__c> businessRefMap = new Map<String, Business_Reference__c>();
        for (
            Business_Reference__c businessRefObj : collectBusinessReferencesByStoreDetails(
                accountBusinessVerticals
            )
        ) {
            String matchingKey =
                businessRefObj.CurrencyIsoCode +
                businessRefObj.Business_Vertical__c +
                businessRefObj.External_Id_Source__c +
                businessRefObj.Default_Type__c;
            matchingKey += businessRefObj.Brand__c != null
                ? businessRefObj.Brand__r?.Name?.toUppercase()
                : '';
            businessRefMap.put(matchingKey, businessRefObj);
        }
        return businessRefMap;
    }

    /**
     * @description LEM-17673 Get Business References by Matching External Id.
     * @param businessIds
     * @return businessRefMap
     */
    @testvisible
    public Map<String, Business_Reference__c> getBusinessReferencesByMatchingBusinessId(
        Set<String> businessIds
    ) {
        Map<String, Business_Reference__c> businessRefMap = new Map<String, Business_Reference__c>();
        for (
            Business_Reference__c businessRefObj : BusinessReferencesSelector.newInstance()
                .selectMDSBusinessReferencesWithSuccessIntegrationStatusByBusinessIds(businessIds)
        ) {
            businessRefMap.put(businessRefObj.External_Id__c, businessRefObj);
        }
        return businessRefMap;
    }

    /**
     * @description It gets Business References by matching Business Vertical Ids, Brand Names
     * and Currency ISO Codes from passed Store accounts.
     * @JIRA# LEM-15747
     * @param storeAccounts
     * @return businessRefMap
     */
    public Map<String, Business_Reference__c> getBusinessReferencesByMatchingKey(
        List<Account> storeAccounts
    ) {
        Map<String, Business_Reference__c> businessRefMap = new Map<String, Business_Reference__c>();
        Set<String> accountBusinessVerticals = getBusinessVerticals(storeAccounts);
        for (
            Business_Reference__c businessRefObj : collectBusinessReferencesByStoreDetails(
                accountBusinessVerticals
            )
        ) {
            String matchingKey =
                businessRefObj.CurrencyIsoCode +
                businessRefObj.Business_Vertical__c +
                businessRefObj.External_Id_Source__c +
                businessRefObj.Default_Type__c;
            matchingKey += businessRefObj.Brand__c != null
                ? businessRefObj.Brand__r?.Name?.toUppercase()
                : '';
            businessRefMap.put(matchingKey, businessRefObj);
        }
        return businessRefMap;
    }

    /**
     * @description LEM-12595 get external source mapping from experiance field use mapping to derive.
     * @param storeAccount
     * @return externalSources
     */
    public Set<String> getExternalSourceFromAccount(Account storeAccount) {
        Set<String> externalSources = new Set<String>();

        if (String.isBlank(storeAccount.Experience__c)) {
            return externalSources;
        }
        for (String experiance : storeAccount.Experience__c.split(';')) {
            if (EXPERIANCE_TO_EXTERNALSOURCE_MAP.containsKey(experiance)) {
                externalSources.add(EXPERIANCE_TO_EXTERNALSOURCE_MAP.get(experiance));
            }
        }
        return externalSources;
    }
    /**
     * @description LEM-12595 Get Business verticals from store account
     * @param storeAccounts
     * @return businessVerticalIds
     */
    public Set<String> getBusinessVerticals(List<Account> storeAccounts) {
        Set<String> businessVerticalIds = new Set<String>();
        for (Account storeAccount : storeAccounts) {
            if (storeAccount.Business_Vertical__c != null) {
                businessVerticalIds.add(storeAccount.Business_Vertical__c);
                storeCurrencyIsoCodes.add(storeAccount.CurrencyISOCode);
                brandNames.add(storeAccount.Brand__r.Name);
            }
        }
        return businessVerticalIds;
    }
    /**
     * @description LEM-12595 run the mathcing logic to find the mathcing ref by key from account and external source
     * @param accObj
     * @param businessRefMap
     * @param eachExternSource
     * @return businessRefMap
     */
    public Business_Reference__c matchTheBizRefWithAccountByExternalSource(
        Account accObj,
        Map<String, Business_Reference__c> businessRefMap,
        String eachExternSource
    ) {
        if (businessRefMap.isEmpty()) {
            return null;
        }
        string defaultType = '';
        if (accObj.Franchise_Parent__c != null) {
            defaultType = BUSINESS_REFERENCE_FRANCHISE;
        } else {
            defaultType = BUSINESS_REFERENCE_CORPORATE;
        }
        String brandName = accObj.Brand__r.Name;
        brandName = brandName == null ? brandName : brandName.toUppercase();
        string matchingKey =
            accObj.CurrencyIsoCode +
            accObj.Business_Vertical__c +
            eachExternSource +
            defaultType +
            brandName;
        Business_Reference__c businessObj = businessRefMap.containsKey(matchingKey)
            ? businessRefMap.get(matchingKey)
            : null;
        return businessObj;
    }
    /**
     * @description LEM-4208, LEM-12595 Display error message when Business Reference not found
     * @param accObj
     * @param eachExternSource
     * @return String
     */
    public String getBizRefMatchingErrorDisplayMessage(Account accObj, String eachExternSource) {
        string defaultType = '';
        if (accObj.Franchise_Parent__c != null) {
            defaultType = BUSINESS_REFERENCE_FRANCHISE;
        } else {
            defaultType = BUSINESS_REFERENCE_CORPORATE;
        }
        String brandName = accObj.Brand__r.Name;
        string errorMessage =
            CANNOT_FIND_BUS_REF_ERROR_MESSAGE +
            accObj.CurrencyIsoCode +
            DASH_STRING +
            accObj.Business_Vertical__r.Name +
            DASH_STRING +
            eachExternSource +
            DASH_STRING +
            defaultType +
            DASH_STRING +
            brandName;

        return errorMessage;
    }

    /**
     * @description It collects Business References by matching Business Vertical Ids, Brand Names
     * and Currency ISO Codes.
     * Added additional filter criteria to reduce retrieved rows maintaining governer limits.
     * @JIRA# LEM-15747
     * @param accountBusinessVerticals
     * @return businessRefMap
     */
    private List<Business_Reference__c> collectBusinessReferencesByStoreDetails(
        Set<String> accountBusinessVerticals
    ) {
        if (!brandNames.isEmpty() && !storeCurrencyIsoCodes.isEmpty()) {
            return BusinessReferencesSelector.newInstance()
                .selectByBusinessVerticalsBrandNamesAndCurrencyISOCodes(
                    accountBusinessVerticals,
                    brandNames,
                    storeCurrencyIsoCodes
                );
        }
        return BusinessReferencesSelector.newInstance()
            .selectByBusinessVerticals(accountBusinessVerticals);
    }
}