sfdx-source/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1139: This field represents the Brand associated with the store.</description>
    <inlineHelpText>Represents the Brand associated with the store</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Accounts (Stores)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Franchise_Parent__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Parent__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-99: Describes the parent of a franchisee.</description>
    <label>Franchise Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Franchise Parents</relationshipLabel>
    <relationshipName>FranchiseParents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Brand_Owner__c.field-meta.xml
<CustomField>
    <fullName>Brand_Owner__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-564: Represents the Owner of the Brand.</description>
    <inlineHelpText>Represents the Owner of the Brand</inlineHelpText>
    <label>Brand Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/Business_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-2082 Object used for integration of Business Ids</description>
    <label>Business Reference</label>
    <nameField>
        <label>Business Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-12683</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Business References</relationshipLabel>
    <relationshipName>Business_References</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Name__c</fullName>
    <description>LEM-2082 Name of the Business as provisioned in its external source.</description>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Default_Type__c.field-meta.xml
<CustomField>
    <fullName>Default_Type__c</fullName>
    <description>LEM-2306</description>
    <label>Default Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>COO Graveyard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>LEM-2082 Represents the corresponding record ID in the external source. For example, the Business ID of a record in MDS.</description>
    <label>Business ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Source__c</fullName>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <label>External Id Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Id_Source</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/Process_Flow_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-8466 - Tracks a request for onboarding a number of Store Accounts, so request information can be referenced in a front-end process flow. Contains lookups to relevant records -- such as Contract, WorkOrder, etc. -- as well as information on the request&apos;s Status and other important parameters.</description>
    <label>Process Flow Request</label>
    <nameField>
        <displayFormat>PFR-{00000000}</displayFormat>
        <label>Process Flow Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Flow Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-8466 - Relationship to the relevant Contract from which the Bulk Corporate Onboarding Request originated.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Process Flow Requests</relationshipLabel>
    <relationshipName>Process_Flow_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Serialized_Object_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Object_Data__c</fullName>
    <description>LEM-8466 - Contains a JSON string of serialized data used in the request.</description>
    <label>Serialized Object Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>LEM-8466 - Picklist with values representing the specific stage at which the Flow is on.</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Order Type Selection</fullName>
            </value>
            <value>
                <fullName>Work Order Creation</fullName>
            </value>
            <value>
                <fullName>Work Order Association</fullName>
            </value>
            <value>
                <fullName>Account File Upload</fullName>
            </value>
            <value>
                <fullName>Business Vertical</fullName>
            </value>
            <value>
                <fullName>Payment Account</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Final Error Check</fullName>
            </value>
            <value>
                <fullName>Processing Stores</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
            <value>
                <fullName>Flow Initiated</fullName>
            </value>
            <value>
                <fullName>Flow Completed</fullName>
            </value>
            <value>
                <fullName>External Ids Created</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
            </value>
            <value>
                <fullName>Select Entitlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-8466 - Picklist with values representing the status of the flow request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/External_Id_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MDS</fullName>
    </customValue>
    <customValue>
        <fullName>DriveDb</fullName>
    </customValue>
    <customValue>
        <fullName>Figment</fullName>
    </customValue>
    <customValue>
        <fullName>MDS - Catering</fullName>
    </customValue>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <masterLabel>External Id Source</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/domains/ProcessFlowRequestsTest.cls
/**
* @author Aethereus
* @description Test class for the ProcessFlowRequests class
**/
@IsTest
private class ProcessFlowRequestsTest {
    private static final String REQUEST_STATUS_IN_PROGRESS = 'In Progress';
	public static final String STATUS_SUCCESS = 'Success';
    public static final String STATUS_FAILURE = 'Failure';
    public static final String STATUS_READY_FOR_INTEGRATION = 'Ready for Integration';
    public static final String STATUS_COO_SUCCESS = 'COO Success';
    public static final String STATUS_READY_FOR_COO_INTEGRATION = 'Ready for COO Integration';
    private static final String EXTERNAL_ID_SOURCE_DRIVE = 'DriveDb';
    private static final String BUSINESS_VERTICAL_NAME = 'Business Vertical 1';
  	private static final String PRIMARY_VERTICAL_ALCOHOL = 'Alcohol';
    private static final String PRODUCT_MARKETPLACE = 'Marketplace';
    private static final String VERTICAL_NAME = 'misc_retail_ui';
    private static final String MENU_UI_TYPE_RETAIL = 'Retail';
    private static final String LICENSOR = 'Licensor';
    private static final Id STORE_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Store')
        .getRecordTypeId();
    private static final String BRANDANDBUSINESSFLOW_RECORDTYPE = System.Label.Brand_and_Business_Reference_Flow_Record_Type_Name;
    private static final Id BUSINESS_REFERENCE_ID = Fake.generateId(Business_Reference__c.class);


   /**
	* @description Creates a JSON string For caseWithListOfBrandAndBizRefs
	* @param businessReferenceList List of Business_Reference__c
    * @return JSON string
	**/
    private static String serializeBrandandBizRefFullData(List<Business_Reference__c> businessReferenceList) {
       	Id storeAccountId = Fake.generateId(Account.class);
        Id franchiseAccountId = Fake.generateId(Account.class);
        Id parentAccountId = Fake.generateId(Account.class);

        Account newAccount = (Account) new Fake(Account.class)
            .setField(Account.Id, storeAccountId)
            .setField(Account.Name, 'Mc Donald')
            .setField(Account.RecordTypeId, STORE_RECORD_TYPE_ID)
            .setField(Account.Franchise_Parent__c, franchiseAccountId)
            .setField(Account.ParentId, parentAccountId)
            .toSObject();

        Brand__c brand = (Brand__c) new Fake(Brand__c.class)
            .setField(Brand__c.Name, 'Pop tates')
            .setField(Brand__c.Brand_Owner__c, newAccount.Id)
            .setFakeId()
            .toSObject();

        List<BrandWrapper.BrandAndBizRefs> brandAndBusinessRefs = new List<BrandWrapper.BrandAndBizRefs>{new BrandWrapper.BrandAndBizRefs(brand,businessReferenceList)};

            Case fakeCase = (Case) new Fake(
                Case.class
            )
            .setFakeId()
            .toSObject();

        BrandWrapper.CaseWithListOfBrandAndBizRefs caseWithListOfBrandAndBizRefs = new BrandWrapper.CaseWithListOfBrandAndBizRefs();
        caseWithListOfBrandAndBizRefs.brandAndBizRefsList = brandAndBusinessRefs;
        caseWithListOfBrandAndBizRefs.caseRecord = fakeCase;

        return JSON.serialize(CaseWithListOfBrandAndBizRefs);
    }

    /**
     * @description Test when sendNotificationForProcessFlowRequestWithExternalIdsCreated when full data then send email
     */

    @isTest
    static void testWhenSendNotificationForProcessFlowRequestWithExternalIdsCreatedWhenFullDataThenSendEmail(){
        Id brefId = Fake.generateId(Business_Reference__c.class);
        List<Business_Reference__c> businessReferenceList = new List<Business_Reference__c>{
            new Business_Reference__c(
                Id = brefId,
                CurrencyIsoCode = 'USD',
                External_Id_Source__c = EXTERNAL_ID_SOURCE_DRIVE,
                External_Id__c = '12345',
                Business_Name__c = 'Test',
                Default_Type__c = 'Corporate'
            )
                };

                    Id flowRequestId = Fake.generateId(Process_Flow_Request__c.class);
        Id brandAndBusinessFlowRecordTypeId = Schema.SObjectType.Process_Flow_Request__c.getRecordTypeInfosByDeveloperName()
            .get(BRANDANDBUSINESSFLOW_RECORDTYPE)
            .getRecordTypeId();
        List<Process_Flow_Request__c> requests = new List<Process_Flow_Request__c>();
        Process_Flow_Request__c request = new Process_Flow_Request__c(
            Id = flowRequestId,
            Contract__c = Fake.generateId(Contract.class),
            Status__c = REQUEST_STATUS_IN_PROGRESS,
            Serialized_Object_Data__c = serializeBrandandBizRefFullData(businessReferenceList),
            OwnerId = UserInfo.getUserId(),
            RecordTypeId = brandAndBusinessFlowRecordTypeId

        );
        requests.add(request);


        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IProcessFlowRequestsSelector mockProcessFlowRequestSelector = (IProcessFlowRequestsSelector) mocks.mock(
            IProcessFlowRequestsSelector.class
        );
        IBusinessReferencesSelector mockBusinessReferencesSelector = (IBusinessReferencesSelector) mocks.mock(
            BusinessReferencesSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockProcessFlowRequestSelector.sObjectType()).thenReturn(Process_Flow_Request__c.SObjectType);
        mocks.when(mockBusinessReferencesSelector.sObjectType()).thenReturn(Business_Reference__c.SObjectType);

        mocks.when(mockBusinessReferencesSelector.selectByIds( new Set<Id>{brefId}))
            .thenReturn(businessReferenceList);

        mocks.when(mockProcessFlowRequestSelector.selectBrandAndBusinessFlowByIds(new Set<Id>{flowRequestId}))
            .thenReturn(requests);

        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockProcessFlowRequestSelector);
        Application.SELECTOR.setMock(mockBusinessReferencesSelector);

        ProcessFlowRequests.newInstance(requests)
            .sendNotifcationsForProcessFlowRequestWithExternalIdsCreated();
            System.assertEquals(REQUEST_STATUS_IN_PROGRESS, requests[0].Status__c, 'The Status__c field should be updated');
    }

    /**
     * @description Test when sendNotificationForProcessFlowRequestWithExternalIdsCreated when full data then Throw error
     */
    @isTest
    static void testWhenSendEmailNotificationWhenNotificationNotProperlyConstructedThenThrowError(){
        Test.startTest();
        Exception actualException;
        try {
            ProcessFlowRequests.sendEmailNotifications(null);
        } catch (Exception e) {
            actualException = e;
        }
        Test.stopTest();
        System.assertEquals(null, actualException, 'An exception should be thrown when sendEmailNotifications is called with null');
    }

    /**
     * @description Test when SendNotificationWhenNotificationNotProperlyConstructed Then Throw Error
     */
     @isTest
    static void testWhenSendNotificationWhenNotificationNotProperlyConstructedThenThrowError(){
        Test.startTest();
        Exception actualException;
        try {
            ProcessFlowRequests.sendNotification(null, new Set<String>());
        } catch (Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assertEquals(null, actualException, 'An exception should be thrown when sendNotification is called with null and an empty set');

    }

    @isTest
    static void testWhenGetOrgWideEmailAdressWhenInCorrectAddressThenSendNull(){
        Id brandAndBusinessFlowRecordTypeId = Schema.SObjectType.Process_Flow_Request__c.getRecordTypeInfosByDeveloperName()
            .get(BRANDANDBUSINESSFLOW_RECORDTYPE)
            .getRecordTypeId();

        List<Process_Flow_Request__c> processFlowRequestsList = new List<Process_Flow_Request__c>{
            new Process_Flow_Request__c(
                Stage__c = 'Flow Initiated',
                Status__c = REQUEST_STATUS_IN_PROGRESS,
                RecordTypeId = brandAndBusinessFlowRecordTypeId
            )
        };
        insert processFlowRequestsList;
        update processFlowRequestsList;
        Test.startTest();
	    OrgWideEmailAddress owea =  ProcessFlowRequests.getOrgWideEmailAddressforEmailNotification('SomeRandom@address.com');
        System.assertEquals(
            owea,
            null,
            'No Org Wide Email Address Should be returned'
        );
        Test.stopTest();
    }

    @isTest
    static void testWhenGetCreateBrandNotificationWhenInCorrectNameThenSendNull(){
        Test.startTest();
	    CustomNotificationType notificationType =  ProcessFlowRequests.getCreateBrandNotification('SomeRandomName');
        System.assertEquals(
            notificationType,
            null,
            'No Notification Type Should be returned'
        );
        Test.stopTest();
    }


}