sfdx-source/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1139: This field represents the Brand associated with the store.</description>
    <inlineHelpText>Represents the Brand associated with the store</inlineHelpText>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Accounts (Stores)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Price_Range__c.field-meta.xml
<CustomField>
    <fullName>Price_Range__c</fullName>
    <description>LEM-3123: Depicts price range that will be used to establish # of dollar signs on DoorDash App.</description>
    <label>Price Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$</fullName>
            </value>
            <value>
                <fullName>$$</fullName>
            </value>
            <value>
                <fullName>$$$</fullName>
            </value>
            <value>
                <fullName>$$$$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1206: It indicates record type name of the Account record.</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Brand_Owner__c.field-meta.xml
<CustomField>
    <fullName>Brand_Owner__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-564: Represents the Owner of the Brand.</description>
    <inlineHelpText>Represents the Owner of the Brand</inlineHelpText>
    <label>Brand Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brands</relationshipLabel>
    <relationshipName>Brands</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Brand__c/fields/Price_Range__c.field-meta.xml
<CustomField>
    <fullName>Price_Range__c</fullName>
    <defaultValue>&apos;$$&apos;</defaultValue>
    <description>LEM-6195: It indicates the price range that will be used to establish # of dollar signs on DoorDash App.</description>
    <label>Price Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$</fullName>
            </value>
            <value>
                <fullName>$$</fullName>
            </value>
            <value>
                <fullName>$$$</fullName>
            </value>
            <value>
                <fullName>$$$$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/Readiness_Check_Failure__c.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores validation rules evaluated successfully for a store Account related to a Work Order during readiness check. Onboarding and activations persona&apos;s user will take corrective actions to resolve the failures captured in this object in order to make a store ready for provisioning.</description>
    <label>Readiness Check Failure</label>
    <nameField>
        <displayFormat>RCF-{0}</displayFormat>
        <label>Readiness Check Failure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readiness Check Failures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the store Account that needs correction to resolve the failure.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Readiness Check Failures</relationshipLabel>
    <relationshipName>Readiness_Check_Failures</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Child_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Child_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the Work Order related to store associated to this failure record.</description>
    <label>Child Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Store Level Readiness Check Corrections</relationshipLabel>
    <relationshipName>Store_Level_Readiness_Check_Corrections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed to onboarding and activations persona&apos;s user for corrections on the store related to the failure record.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>LEM-1684: It indicates the field name where the failure occurred.</description>
    <label>Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates the object name where the failure occurred.</description>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the parent of work order related to the readiness check failure record.</description>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Readiness Check Corrections</relationshipLabel>
    <relationshipName>Readiness_Check_Corrections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/Store_Readiness_Validation_Rule__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores the details of validation rules that needs to be evaluated for store readiness check.</description>
    <label>Readiness Validation Rule</label>
    <pluralLabel>Readiness Validation Rules</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed when the validation rule criteria fails.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>LEM-1684: It indicates label of the field on which the validation needs to be performed.</description>
    <label>Field Label</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>LEM-1684: It indicates the field name on which the validation needs to be performed.</description>
    <label>Field Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Object_Label__c.field-meta.xml
<CustomField>
    <fullName>Object_Label__c</fullName>
    <description>LEM-1684: It indicates the label of object on which the validation needs to be performed.</description>
    <label>Object Label</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates object name on which the validation needs to be performed.</description>
    <label>Object Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + AccountId , Account.Name , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Account_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Type_Name__c</fullName>
    <formula>Account.RecordType.DeveloperName</formula>
    <inlineHelpText>LEM-658: It indicates name of Account record type.</inlineHelpText>
    <label>Account Record Type Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <description>LEM-16014: It indicates Id of Parent Work Order.</description>
    <formula>CASESAFEID(ParentWorkOrderId)</formula>
    <label>Parent Work Order</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/services/BrandValidationsServiceImplTest.cls
/**
 * @author Deloitte
 * @date 04/28/2023
 * @description Test class for BrandValidationsServiceImpl class.
 * Suppressed Warnings since mock verify method does not require system assert statements.
 */
@isTest(SeeAllData=false)
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
private class BrandValidationsServiceImplTest {
    private static final String ACCOUNT_PARENT_RELATIONSHIP_NAME = 'Parent';
    private static final String ACCOUNT_RECORD_TYPE_NAME_BUSINESS = 'Business';
    private static final String ACCOUNT_RECORD_TYPE_NAME_STORE = 'Store';
    private static final String BRAND_OBJECT_NAME = 'Brand';
    private static final String BRAND_OBJECT_API_NAME = 'Brand__c';
    private static final String BRAND_NAME = 'Kfc Brand';
    private static final String ERROR_MESSAGE_PRICE_RANGE = 'Please ensure Price Range is populated on the Brand.';
    private static final String FIELD_API_NAME_PRICE_RANGE = 'Price_Range__c';
    private static final String FIELD_LABEL_PRICE_RANGE = 'Price Range';
    private static final String PRICE_RANGE_FIELD_VALUE = '$';
    private static final String SERVICE_CLASS_NAME = 'IBrandValidationsService';
    private static final String SERVICE_METHOD_VALIDATE_PRICERANGE = 'validateNullFieldValuesByWorkOrderType';
    private static final String TYPE_MARKETPLACE = 'Marketplace';
    private static final String VERTICAL = 'Rx';
    private static final String WORK_ORDER_ACCOUNT_RELATIONSHIP_NAME = 'Account';

    /**
     * @description To test Readiness Check Failures creation
     * when 'Price Range' field value is not populated on Brand associated to store.
     */
    @isTest
    private static void testWhenPriceRangeNullOnBrandThenReadinessCheckFailuresCreated() {
        List<Store_Readiness_Validation_Rule__mdt> storeReadinessValidationRules = new List<Store_Readiness_Validation_Rule__mdt>{
            (Store_Readiness_Validation_Rule__mdt) ServiceMockDataBuilder.convertToSObject(
                ServiceMockDataBuilder.createStoreReadinessValidationRuleFakeInstance(
                        ERROR_MESSAGE_PRICE_RANGE,
                        FIELD_LABEL_PRICE_RANGE,
                        SERVICE_METHOD_VALIDATE_PRICERANGE,
                        BRAND_OBJECT_NAME,
                        SERVICE_CLASS_NAME
                    )
                    .setField(
                        Store_Readiness_Validation_Rule__mdt.Field_Name__c,
                        FIELD_API_NAME_PRICE_RANGE
                    )
            )
        };
        Fake parentAccountFakeInstance = ServiceMockDataBuilder.createAccountFakeInstance(
            VERTICAL,
            ACCOUNT_RECORD_TYPE_NAME_BUSINESS
        );
        Account parentAccount = (Account) ServiceMockDataBuilder.convertToSObject(
            parentAccountFakeInstance
        );
        Fake brandFakeInstance = new Fake(Brand__c.class)
            .setField(Brand__c.Brand_Owner__c, parentAccount.Id)
            .setField(Brand__c.Price_Range__c, null)
            .setField(Brand__c.Name, BRAND_NAME)
            .setFakeId();
        Brand__c brandInstance = (Brand__c) ServiceMockDataBuilder.convertToSObject(
            brandFakeInstance
        );
        Fake childAccountFakeInstance = ServiceMockDataBuilder.createStoreAccountRecordWithProvidedPrimaryVerticalValue(
                parentAccount.Id,
                VERTICAL
            )
            .setField(Account.Brand__c, brandInstance.Id)
            .setField(Account.Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_STORE)
            .setParent(ACCOUNT_PARENT_RELATIONSHIP_NAME, parentAccountFakeInstance);
        Account storeAccount = (Account) ServiceMockDataBuilder.convertToSObject(
            childAccountFakeInstance
        );
        Fake parentWorkOrderFakeInstance = ServiceMockDataBuilder.createWorkOrderFakeInstance(
                parentAccount.Id,
                TYPE_MARKETPLACE
            )
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
            .setParent(WORK_ORDER_ACCOUNT_RELATIONSHIP_NAME, parentAccountFakeInstance);
        WorkOrder parentWorkOrder = (WorkOrder) ServiceMockDataBuilder.convertToSObject(
            parentWorkOrderFakeInstance
        );
        Fake workOrderFakeInstance = ServiceMockDataBuilder.createWorkOrderFakeInstance(
                storeAccount.Id,
                TYPE_MARKETPLACE
            )
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_STORE)
            .setField(WorkOrder.ParentWorkOrderId, parentWorkOrder.Id)
            .setParent(WORK_ORDER_ACCOUNT_RELATIONSHIP_NAME, childAccountFakeInstance)
            .setParent('ParentWorkOrder', parentWorkOrderFakeInstance)
            .setParent('Account', childAccountFakeInstance);
        WorkOrder workOrder = (WorkOrder) ServiceMockDataBuilder.convertToSObject(
            workOrderFakeInstance
        );
        List<Readiness_Check_Failure__c> mockReadinessCheckFailures = new List<Readiness_Check_Failure__c>{
            new Readiness_Check_Failure__c(
                Object_Name__c = storeReadinessValidationRules[0].Object_Label__c,
                Field_Name__c = storeReadinessValidationRules[0].Field_Label__c,
                Error_Message__c = storeReadinessValidationRules[0].Error_Message__c,
                Parent_Work_Order__c = workOrder.ParentWorkOrderId,
                Child_Work_Order__c = workOrder.Id,
                Account_Name__c = workOrder.AccountId
            )
        };

        List<Readiness_Check_Failure__c> mockExistingReadinessCheckFailures = new List<Readiness_Check_Failure__c>();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IBrandsSelector mockBrandSelector = (IBrandsSelector) mocks.mock(IBrandsSelector.class);
        mocks.startStubbing();
        mocks.when(mockBrandSelector.sObjectType()).thenReturn(Brand__c.SObjectType);
        mocks.when(mockBrandSelector.selectById(new Set<Id>{ brandInstance.Id }))
            .thenReturn(new List<Brand__c>{ brandInstance });
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockBrandSelector);
        BrandValidationsServiceImpl brandValidationsSrvcImplInstance = new BrandValidationsServiceImpl();
        brandValidationsSrvcImplInstance.validate(
            new List<WorkOrder>{ workOrder },
            new List<WorkOrder>{ parentWorkOrder },
            storeReadinessValidationRules,
            mockExistingReadinessCheckFailures,
            BRAND_OBJECT_API_NAME
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, mocks.times(1)))
            .registerNew(mockReadinessCheckFailures);
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 1)).commitWork();
    }

    /**
     * @description To test Readiness Check Failures not created
     * when 'Price Range' field value is populated on Brand associated to store.
     */
    @isTest
    private static void testWhenPriceRangePopulatedOnBrandThenReadinessCheckFailuresNotCreated() {
        List<Store_Readiness_Validation_Rule__mdt> storeReadinessValidationRules = new List<Store_Readiness_Validation_Rule__mdt>{
            (Store_Readiness_Validation_Rule__mdt) ServiceMockDataBuilder.convertToSObject(
                ServiceMockDataBuilder.createStoreReadinessValidationRuleFakeInstance(
                        ERROR_MESSAGE_PRICE_RANGE,
                        FIELD_LABEL_PRICE_RANGE,
                        SERVICE_METHOD_VALIDATE_PRICERANGE,
                        BRAND_OBJECT_NAME,
                        SERVICE_CLASS_NAME
                    )
                    .setField(
                        Store_Readiness_Validation_Rule__mdt.Field_Name__c,
                        FIELD_API_NAME_PRICE_RANGE
                    )
            )
        };
        Fake parentAccountFakeInstance = ServiceMockDataBuilder.createAccountFakeInstance(
            VERTICAL,
            ACCOUNT_RECORD_TYPE_NAME_BUSINESS
        );
        Account parentAccount = (Account) ServiceMockDataBuilder.convertToSObject(
            parentAccountFakeInstance
        );
        Fake brandFakeInstance = new Fake(Brand__c.class)
            .setField(Brand__c.Brand_Owner__c, parentAccount.Id)
            .setField(Brand__c.Price_Range__c, PRICE_RANGE_FIELD_VALUE)
            .setField(Brand__c.Name, BRAND_NAME)
            .setFakeId();
        Brand__c brandInstance = (Brand__c) ServiceMockDataBuilder.convertToSObject(
            brandFakeInstance
        );
        Fake childAccountFakeInstance = ServiceMockDataBuilder.createStoreAccountRecordWithProvidedPrimaryVerticalValue(
                parentAccount.Id,
                VERTICAL
            )
            .setField(Account.Brand__c, brandInstance.Id)
            .setField(Account.Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_STORE)
            .setParent(ACCOUNT_PARENT_RELATIONSHIP_NAME, parentAccountFakeInstance);
        Account storeAccount = (Account) ServiceMockDataBuilder.convertToSObject(
            childAccountFakeInstance
        );
        Fake parentWorkOrderFakeInstance = ServiceMockDataBuilder.createWorkOrderFakeInstance(
                parentAccount.Id,
                TYPE_MARKETPLACE
            )
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
            .setParent(WORK_ORDER_ACCOUNT_RELATIONSHIP_NAME, parentAccountFakeInstance);
        WorkOrder parentWorkOrder = (WorkOrder) ServiceMockDataBuilder.convertToSObject(
            parentWorkOrderFakeInstance
        );
        Fake workOrderFakeInstance = ServiceMockDataBuilder.createWorkOrderFakeInstance(
                storeAccount.Id,
                TYPE_MARKETPLACE
            )
            .setField(WorkOrder.Account_Record_Type_Name__c, ACCOUNT_RECORD_TYPE_NAME_STORE)
            .setField(WorkOrder.ParentWorkOrderId, parentWorkOrder.Id)
            .setParent(WORK_ORDER_ACCOUNT_RELATIONSHIP_NAME, childAccountFakeInstance)
            .setParent('ParentWorkOrder', parentWorkOrderFakeInstance)
            .setParent('Account', childAccountFakeInstance);
        WorkOrder workOrder = (WorkOrder) ServiceMockDataBuilder.convertToSObject(
            workOrderFakeInstance
        );

        List<Readiness_Check_Failure__c> mockExistingReadinessCheckFailures = new List<Readiness_Check_Failure__c>();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        IBrandsSelector mockBrandSelector = (IBrandsSelector) mocks.mock(IBrandsSelector.class);
        mocks.startStubbing();
        mocks.when(mockBrandSelector.sObjectType()).thenReturn(Brand__c.SObjectType);
        mocks.when(mockBrandSelector.selectById(new Set<Id>{ brandInstance.Id }))
            .thenReturn(new List<Brand__c>{ brandInstance });
        mocks.stopStubbing();
        Application.UNITOFWORK.setMock(mockUOW);
        Application.SELECTOR.setMock(mockBrandSelector);
        BrandValidationsServiceImpl brandValidationsSrvcImplInstance = new BrandValidationsServiceImpl();
        brandValidationsSrvcImplInstance.validate(
            new List<WorkOrder>{ workOrder },
            new List<WorkOrder>{ parentWorkOrder },
            storeReadinessValidationRules,
            mockExistingReadinessCheckFailures,
            BRAND_OBJECT_API_NAME
        );
        // Readiness Check Failures not created as the Price Range is populated in Brand.
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 0)).commitWork();
    }
}