sfdx-source/force-app/main/default/objects/Account/fields/Bulk_Corporate_Onboarding_Request__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Corporate_Onboarding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-8466 - Connects Store Accounts to the Bulk Corporate Onboarding Request (Process_Flow_Request__c) from which they originated</description>
    <label>Bulk Corporate Onboarding Request</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Store Accounts can be affiliated to Bulk Corporate Onboarding Requests.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Process_Flow_Request__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/Account_Payment_Account_Relation__c.object-meta.xml
<CustomObject>
    <label>Account To Payment Account Relation</label>
    <nameField>
        <displayFormat>APA-{0000}</displayFormat>
        <label>Account Payment Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account To Payment Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1150: This field represents the associated Account</description>
    <inlineHelpText>This field represents the associated Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Account_Payment_Account_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1150: This field represents the associated payment account.</description>
    <inlineHelpText>This field represents the associated payment account.</inlineHelpText>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Payment_Account_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1212: Indicates link to contract that case is related to.</description>
    <inlineHelpText>Link to contract that case is related to</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Bulk Upload Request Cases</relationshipLabel>
    <relationshipName>Bulk_Upload_Request_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13790: It indicates active or inactive status of the SMB contact.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>Indicates whether the status of the SMB contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/Process_Flow_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-8466 - Tracks a request for onboarding a number of Store Accounts, so request information can be referenced in a front-end process flow. Contains lookups to relevant records -- such as Contract, WorkOrder, etc. -- as well as information on the request&apos;s Status and other important parameters.</description>
    <label>Process Flow Request</label>
    <nameField>
        <displayFormat>PFR-{00000000}</displayFormat>
        <label>Process Flow Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Flow Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Async_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Async_Job_ID__c</fullName>
    <description>Stores the unique identifier for the associated Salesforce Batch Apex job. Useful for monitoring job status, troubleshooting, and auditing.</description>
    <inlineHelpText>Stores the unique identifier for the associated Salesforce Batch Apex job. Useful for monitoring job status, troubleshooting, and auditing.</inlineHelpText>
    <label>Async Job ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/CCP_Applied__c.field-meta.xml
<CustomField>
    <fullName>CCP_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-16093 It indicates whether user has modified Package/Product Selection/Deselection on Entitlement Selection in ANSO</description>
    <label>CCP Applied</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-8466 - Relationship to the relevant Contract from which the Bulk Corporate Onboarding Request originated.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Process Flow Requests</relationshipLabel>
    <relationshipName>Process_Flow_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>LEM-12362 Contains Id of the contract associated Quote Line Group</description>
    <label>Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Serialized_Entitlements_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Entitlements_Data__c</fullName>
    <description>LEM-12362 Contains a JSON string of entitlement selection/deselection</description>
    <label>Serialized Entitlements Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Serialized_Object_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Object_Data__c</fullName>
    <description>LEM-8466 - Contains a JSON string of serialized data used in the request.</description>
    <label>Serialized Object Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>LEM-8466 - Picklist with values representing the specific stage at which the Flow is on.</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Order Type Selection</fullName>
            </value>
            <value>
                <fullName>Work Order Creation</fullName>
            </value>
            <value>
                <fullName>Work Order Association</fullName>
            </value>
            <value>
                <fullName>Account File Upload</fullName>
            </value>
            <value>
                <fullName>Business Vertical</fullName>
            </value>
            <value>
                <fullName>Payment Account</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Final Error Check</fullName>
            </value>
            <value>
                <fullName>Processing Stores</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
            <value>
                <fullName>Flow Initiated</fullName>
            </value>
            <value>
                <fullName>Flow Completed</fullName>
            </value>
            <value>
                <fullName>External Ids Created</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
            </value>
            <value>
                <fullName>Select Entitlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-8466 - Picklist with values representing the status of the flow request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Process_Flow_Request__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-8466 - Association of a Bulk Corporate Onboarding Request to a specific Work Order.</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Process Flow Requests</relationshipLabel>
    <relationshipName>Process_Flow_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Contract linked to the onboarding event.</description>
    <inlineHelpText>Contract linked to the onboarding event</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/batchables/BulkStoreOnboardingBatch.cls
/**
 * @description Handles Bulk Store uploads initiated by the Bulk Store Onboarding Flow.
 * @author BizApps
 * @date 31-August-2023
 **/
@SuppressWarnings('PMD.StdCyclomaticComplexity, PMD.CyclomaticComplexity')
public with sharing class BulkStoreOnboardingBatch implements Database.Batchable<sObject>, Database.Stateful, Database.RaisesPlatformEvents {
    private Map<Id, List<LogMessageEntry>> accountIdToLogMessageEntries;
    private Id flowRequestId;
    private Process_Flow_Request__c pfr;
    private Integer storeCount = 0;
    private Integer maxCpuTime = 0;
    private Integer maxHeapSize = 0;
    private Integer maxDmlStatements = 0;
    private Integer maxSoqlQueries = 0;
    private Boolean containsFailures = false;
    private String contractName;
    private Map<Id, BulkCorporateOnboardingWrappers.StoreInfo> storeInfoMap;
    private BulkCorporateOnboardingWrappers.StoreProcessingMetrics storeProcessMetrics;
    private Set<Id> skippedStores;
    private Set<Id> unprocessedStores;
    private Set<Id> finishedStores;
    private List<AccountContactRelation> newDecisionMakers;
    private List<Account_Payment_Account_Relation__c> newPaymentAccountRelations;
    private Map<Id, Contact> decisionMakersMap;
    private static final String COMMA_SEPARATOR = ',';
    private static final String DECISION_MAKER_CONTACT_ROLE = 'Decision Maker';
    private static final String EVENT_TOPIC_BUSINESS_ERROR_LOGS_CREATION = 'BUSINESS_ERROR_LOGS_CREATION';
    private static final String LOG_SERVICE_NAME = 'ANSO';
    private static final String LOG_DOMAIN_NAME = 'Onboarding';
    private static final String LOG_RECORD_METHOD_NAME = 'BulkStoreOnboardingBatch.finish';
    private static final String LOG_ERROR_MESSAGE_FOR_FAILED_STORES = 'This store could not be added to the Work Order due to address verification issues. Please review and update the address on it. Once this is completed, click the "Retry" button to proceed with onboarding these stores.';
    private static final String LOGS_PAYLOAD_CHUNK_SIZE_STATIC_CONFIG = 'Logs_Payload_Chunk_Size';
    private static final String OBJECT_INSTANCE_MAP_EMPTY = '{}';
    private static final String OBJECT_INSTANCE_NULL = 'null';
    private static final String OBJECT_INSTANCE_LIST_OR_SET_EMTPY = '[]';
    private static final String REQUEST_STATUS_COMPLETED = 'Completed';
    private static final String REQUEST_STATUS_FAILED = 'Failed';
    private static final String UPLOAD_COMPLETE = 'Upload Complete';
    private static final String RESULT_SUCCESS = 'Success';
    private static final String RESULT_PARTIAL_SUCCESS = 'Partial Success';
    private static final String RESULT_FAILURE = 'Failure';
    private static final String ANNSO_BUTTON_NAME = 'Onboard Corporate Stores';
    private static final String ANSO_BUTTON_NAME = 'Onboard Corporate Stores';
    private static final String GENERIC_LOG_SERVICE_ANSO = 'ANSO';
    private static Integer logsPayloadChunkSize = Integer.valueOf(
        StaticConfigurationsSelector.newInstance()
            .getInstanceValue(LOGS_PAYLOAD_CHUNK_SIZE_STATIC_CONFIG)
            .Configuration_Value__c
    );

    /**
     * @description Constructor to initialize and query the PFR record
     * @param flowRequestId
     **/
    public BulkStoreOnboardingBatch(Id flowRequestId) {
        this.accountIdToLogMessageEntries = new Map<Id, List<LogMessageEntry>>();
        this.skippedStores = new Set<Id>();
        this.unprocessedStores = new Set<Id>();
        this.finishedStores = new Set<Id>();
        this.flowRequestId = flowRequestId;
        this.storeProcessMetrics = new BulkCorporateOnboardingWrappers.StoreProcessingMetrics();
        this.pfr = BulkCorporateOnboardingRequestService.getBulkOnboardingRequestOrAbort(
            flowRequestId
        );
        this.contractName = (String.isNotBlank(this.pfr.Contract__r?.ContractNumber))
            ? this.pfr.Contract__r.ContractNumber
            : '';
        setStoreInfoMap();
    }

    /**
     * @description Start method to query all Stores that relate to the PFR passed to the controller
     * @param bc - Database.BatchableContext
     * @return Database.QueryLocator
     **/
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [SELECT Id FROM Account WHERE Bulk_Corporate_Onboarding_Request__c = :pfr.Id]
        );
    }

    /**
     * @description Performs the following operations on each Store:
     *                  1. Create Payment Account Relationship(s)
     *                  2. Create Account Contact Relationship(s)
     *                  3. Manage Stores
     *                  4. Add Stores on the Work Order
     * @param bc - Database.BatchableContext
     * @param records - List<Account>
     **/
    public void execute(Database.BatchableContext bc, List<sObject> records) {
        List<Account> stores = (List<Account>) records;
        Set<Id> validStoreIds = new Set<Id>();
        this.decisionMakersMap = new Map<Id, Contact>();
        this.newDecisionMakers = new List<AccountContactRelation>();
        this.newPaymentAccountRelations = new List<Account_Payment_Account_Relation__c>();

        for (BulkCorporateOnboardingWrappers.StoreInfo thisStoreInfo : storeInfoMap.values()) {
            if (thisStoreInfo.decisionMakerId != null) {
                decisionMakersMap.put(thisStoreInfo.decisionMakerId, new Contact());
            }
        }

        decisionMakersMap = new Map<Id, Contact>(
            ContactsSelector.newInstance().selectById(decisionMakersMap.keySet())
        );

        for (Account store : stores) {
            BulkCorporateOnboardingWrappers.StoreInfo storeWrapperObj = storeInfoMap.get(store.Id);
            // Skip if we have already run the job on this Store
            if (storeWrapperObj?.isJobComplete == true) {
                if (storeWrapperObj != null) {
                    skippedStores.add(storeWrapperObj.storeId);
                }

                continue;
            }

            initStoreJunctionRecords(storeWrapperObj);

            if (storeWrapperObj.isVerified && !storeWrapperObj.skipBatch) {
                validStoreIds.add(store.Id);
            } else {
                this.unprocessedStores.add(store.Id);
            }
        }

        if (!validStoreIds.isEmpty()) {
            runManageStoresAndAddStores(validStoreIds);
        }

        // Increment the store count
        this.storeCount += stores.size();

        fflib_ISObjectUnitOfWork uow = Application.UNITOFWORK.newInstance();
        uow.registerNew(newDecisionMakers);
        uow.registerNew(newPaymentAccountRelations);

        try {
            uow.commitWork();
        } catch (Exception ex) {
            Logger.publish(ex, LogEntry.SeverityLevel.HIGH);

            GenericLoggerService.publish(
                GenericLoggerService.createGenericLog(
                        LOG_SERVICE_NAME,
                        LOG_DOMAIN_NAME,
                        GenericLogEntry.SeverityLevel.MEDIUM
                    )
                    .logException(ex)
            );
        }
        updateMetrics();
    }

    /**
     * @description It is used to update processing metrics for batch
     */
    @TestVisible
    private void updateMetrics() {
        maxCpuTime = Limits.getCpuTime() >= maxCpuTime ? Limits.getCpuTime() : maxCpuTime;
        maxHeapSize = Limits.getHeapSize() >= maxHeapSize ? Limits.getHeapSize() : maxHeapSize;
        maxDmlStatements = Limits.getDMLStatements() >= maxDmlStatements
            ? Limits.getDMLStatements()
            : maxDmlStatements;
        maxSoqlQueries = Limits.getQueries() >= maxSoqlQueries
            ? Limits.getQueries()
            : maxSoqlQueries;
    }

    /**
     * @description Standard Batch finish() method. We will, at a minimum, need to update the PFR record's Status
     * @param bc - Database.BatchableContext
     **/
    public void finish(Database.BatchableContext bc) {
        containsFailures = !this.unprocessedStores.isEmpty();

        pfr = getFlowRequest(); // Get updated PFR
        pfr.Async_Job_Id__c = bc.getJobId();
        pfr.Stage__c = UPLOAD_COMPLETE;
        pfr.Status__c = getStatusValue();
        pfr.Result__c = getResultValue();
        pfr.Serialized_Object_Data__c = getSerializedStores();

        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType>{ Process_Flow_Request__c.sObjectType }
        );
        uow.registerDirty(pfr);

        try {
            uow.commitWork();
        } catch (Exception ex) {
            logErrors(
                ex.getMessage(),
                new Contract(Id = pfr.Contract__c),
                LogEntry.LogCategory.BUSINESS_ERROR.name(),
                true,
                pfr.Contract__c,
                LogEntry.SeverityLevel.HIGH.name()
            );
        } finally {
            for (
                Account eachFailedStore : BulkCorporateOnboardingRequestService.getFailedStores(
                    pfr.Id
                )
            ) {
                logErrors(
                    LOG_ERROR_MESSAGE_FOR_FAILED_STORES,
                    eachFailedStore,
                    LogEntry.LogCategory.BUSINESS_ERROR.name(),
                    true,
                    pfr.Contract__c,
                    LogEntry.SeverityLevel.HIGH.name()
                );
            }
            createLogEntries();
        }

        // Email the Owner - Should we have the user opt-in to this?
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject(getEmailSubject());
        mail.setTargetObjectId(pfr.OwnerId);
        mail.setSaveAsActivity(false);
        mail.setPlainTextBody(getEmailBody());
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
        sendNotification();
        logStoreBatchMetrics();
    }

    /**
     * @description It is used to update processing metrics for batch
     */
    @TestVisible
    private void logStoreBatchMetrics() {
        this.storeProcessMetrics.maxCpuTime = maxCpuTime;
        this.storeProcessMetrics.maxHeapSize = maxHeapSize;
        this.storeProcessMetrics.maxDmlStatements = maxDmlStatements;
        this.storeProcessMetrics.maxSoqlQueries = maxSoqlQueries;
        this.storeProcessMetrics.storesProcessed = this.finishedStores.size();
        this.storeProcessMetrics.storesFailed = this.unprocessedStores.size();

        String limitsJson = JSON.serialize(this.storeProcessMetrics);
        GenericLoggerService.publish(
            GenericLoggerService.createGenericLog(
                    GENERIC_LOG_SERVICE_ANSO,
                    GenericLogEntry.GENERIC_LOG_DOMAIN_ONBOARDING,
                    GenericLogEntry.SeverityLevel.LOW
                )
                .logException(new DmlException('ANSO Batch execution details: ' + limitsJson))
                .setCategory(GenericLogEntry.GENERIC_LOG_INFORMATION)
                .setLogLevel(GenericLogEntry.GENERIC_LOG_INFORMATION)
        );
    }

    /**
     * @description Invoked from the `execute()` method, this creates records related to Store Accounts
     *              to link Payment Accounts and Decision Makers.
     * @param storeWrapperObj - BulkCorporateOnboardingWrappers.StoreInfo
     **/
    private void initStoreJunctionRecords(
        BulkCorporateOnboardingWrappers.StoreInfo storeWrapperObj
    ) {
        Id decisionMakerId = storeWrapperObj.decisionMakerId;

        // Add Store Decision Maker
        // Note: There is an edge case where, if the Contact does not have an `AccountId`, it is considered
        // to be a "private" Contact and then you cannot make an AccountContactRelation for it without first
        // setting its `AccountId`. There are not really any Contacts in the system that this applies to,
        // as they all have related Accounts, but possibly consider this as a future fix.
        if (decisionMakerId != null && decisionMakersMap.get(decisionMakerId).AccountId != null) {
            AccountContactRelation acr = new AccountContactRelation();
            acr.AccountId = storeWrapperObj.storeId;
            acr.ContactId = decisionMakerId;
            acr.IsActive = true;
            acr.Roles = DECISION_MAKER_CONTACT_ROLE;
            acr.StartDate = System.today();
            this.newDecisionMakers.add(acr);
        }

        // Check if the store has no payment account on it (for DSD stores) then don't create an Account-Payment Account Relation
        if (storeWrapperObj.paymentAccountId != null) {
            // Add link to Payment Account
            Account_Payment_Account_Relation__c par = new Account_Payment_Account_Relation__c();
            par.Account__c = storeWrapperObj.storeId;
            par.Payment_Account__c = storeWrapperObj.paymentAccountId;
            this.newPaymentAccountRelations.add(par);
        }
    }

    /**
     * @description Invoked from the `execute()` method, this invokes the "Manage Stores" and "Add Stores"
     *              logic in order to associate Stores to the Work Order and create Agreements.
     * @param validStoreIds - Set<Id>
     **/
    private void runManageStoresAndAddStores(Set<Id> validStoreIds) {
        // "Add Stores" logic
        String storeIdString = String.join(new List<Id>(validStoreIds), ',');
        AddStoresOnWorkOrderController.validateStores(pfr.Work_Order__c, storeIdString);
        AddStoresOnWorkOrderController.createChildWorkOrders(pfr.Work_Order__c, storeIdString);
        // Maybe implement some logic for it we get these validation errors

        AssociatedAccountsWrapper.SelectedAndDeselectedEntitlements sade;

        // "Manage Stores" logic
        List<Contract> contractsList = new List<Contract>{ new Contract(Id = pfr.Contract__c) };
        try {
            sade = (AssociatedAccountsWrapper.SelectedAndDeselectedEntitlements) JSON.deserialize(
                pfr.Serialized_Entitlements_Data__c,
                AssociatedAccountsWrapper.SelectedAndDeselectedEntitlements.class
            );
        } catch (Exception ex) {
            Logger.publish(ex, LogEntry.SeverityLevel.HIGH);
        }

        Contracts.newInstance(contractsList)
            .setAssociatedAccountsWithGroups(
                new List<AssociatedAccountsWrapper>{
                    new AssociatedAccountsWrapper(
                        pfr.Group__c,
                        storeIdString,
                        pfr.Contract__c,
                        false,
                        sade
                    )
                },
                pfr.CCP_Applied__c,
                'Yes'
            );

        this.finishedStores.addAll(validStoreIds);
    }

    /**
     * @description It is used to create log records for the issues recorded
     * while bulk onboarding stores.
     */
    @TestVisible
    private void createLogEntries() {
        Set<Object> logCreationEntries = new Set<Object>();
        if (isEmptyOrNull(accountIdToLogMessageEntries.values())) {
            return;
        }
        // Create payload for asynchronous creation of business error logs.
        for (List<LogMessageEntry> eachLogMessageEntries : accountIdToLogMessageEntries.values()) {
            logCreationEntries.add(
                new LogCreationEntry(
                    BulkStoreOnboardingBatch.class.getName(),
                    LOG_RECORD_METHOD_NAME,
                    eachLogMessageEntries
                )
            );
        }
        NotifierEventsService.publishBulkEvents(
            new Map<String, List<String>>{
                EVENT_TOPIC_BUSINESS_ERROR_LOGS_CREATION => NotifierEventsPayloadGenerationService.generateChunkedPayloadsByObjects(
                    logCreationEntries,
                    logsPayloadChunkSize
                )
            }
        );
    }

    /**
     * @description To check whether the passed list or set or map is null or empty.
     * @param objectInstance - List/Set/Map
     * @return Boolean
     */
    private Boolean isEmptyOrNull(Object objectInstance) {
        return (JSON.serialize(objectInstance) == OBJECT_INSTANCE_NULL) ||
            JSON.serialize(objectInstance).equals(OBJECT_INSTANCE_LIST_OR_SET_EMTPY) ||
            JSON.serialize(objectInstance).equals(OBJECT_INSTANCE_MAP_EMPTY);
    }

    /**
     * @description It is used to capture the log details for initializing
     * creation of Logs.
     * @param detailedMessage
     * @param sObjectInstance
     * @param logErrorType
     * @param notifyAccountOwner
     * @param sourceRecordId
     * @param severityLevel
     */
    @TestVisible
    @SuppressWarnings('PMD.ExcessiveParameterList')
    private void logErrors(
        String detailedMessage,
        SObject sObjectInstance,
        String logErrorType,
        Boolean notifyAccountOwner,
        Id sourceRecordId,
        String severityLevel
    ) {
        Id parentId;
        String accountName;
        Account accountInstance;
        Set<String> recipientIdsToNotify = new Set<String>();
        if (sObjectInstance.Id.getSObjectType() == Schema.Account.SObjectType) {
            parentId = (Id) sObjectInstance.get('ParentId');
            accountName = (String) sObjectInstance.get('Name');
            accountInstance = (Account) sObjectInstance;
        }
        if (!accountIdToLogMessageEntries.containsKey(sObjectInstance.Id)) {
            accountIdToLogMessageEntries.put(sObjectInstance.Id, new List<LogMessageEntry>());
        }
        for (
            LogMessageEntry eachLogMessageEntry : accountIdToLogMessageEntries.get(
                sObjectInstance.Id
            )
        ) {
            if (eachLogMessageEntry.detailedMessage == detailedMessage) {
                return;
            }
        }
        LogMessageEntry logMessageEntry = new LogMessageEntry(
            parentId,
            detailedMessage,
            userInfo.getUserId(),
            sourceRecordId,
            sObjectInstance.Id
        );
        if (accountInstance != null) {
            recipientIdsToNotify.add(accountInstance.Parent.OwnerId);
            recipientIdsToNotify.add(pfr.Work_Order__r.OwnerId);
        }
        logMessageEntry.logType = logErrorType;
        logMessageEntry.recipientIdsToNotify = String.join(
            new List<String>(recipientIdsToNotify),
            COMMA_SEPARATOR
        );
        logMessageEntry.sendNotification = notifyAccountOwner;
        logMessageEntry.severityLevel = severityLevel;
        logMessageEntry.storeAccountName = accountName;
        accountIdToLogMessageEntries.get(sObjectInstance.Id).add(logMessageEntry);
    }

    /**
     * @description Puts the `StoreInfo` wrapper objects into a Map data structure and uses the Store ID (`Account.Id` of the Stores) as the key
     **/
    private void setStoreInfoMap() {
        List<BulkCorporateOnboardingWrappers.StoreInfo> storeInfos = BulkCorporateOnboardingRequestService.unpackStoreInfos(
            pfr.Id,
            pfr.Serialized_Object_Data__c
        );

        storeInfoMap = new Map<Id, BulkCorporateOnboardingWrappers.StoreInfo>();
        for (BulkCorporateOnboardingWrappers.StoreInfo storeInfo : storeInfos) {
            storeInfoMap.put(storeInfo.storeId, storeInfo);
        }
    }

    /**
     * @description Returns the Process Flow Request for this Batch run
     * @return Process_Flow_Request__c
     **/
    private Process_Flow_Request__c getFlowRequest() {
        List<Process_Flow_Request__c> requests = ProcessFlowRequestsSelector.newInstance()
            .selectById(new Set<Id>{ flowRequestId });
        return (requests != null && !requests.isEmpty()) ? requests[0] : null;
    }

    /**
     * @description Returns a String indicating the result of the batch operation
     * @return String
     **/
    private String getResultValue() {
        String result;
        Integer completedStores = this.finishedStores.size() + this.skippedStores.size();

        if (completedStores == this.storeInfoMap.keySet().size()) {
            result = RESULT_SUCCESS;
        } else if (completedStores == 0) {
            result = RESULT_FAILURE;
        } else {
            result = RESULT_PARTIAL_SUCCESS;
        }

        return result;
    }

    /**
     * @description Returns a String indicating the Status of the request
     * @return String
     **/
    private String getStatusValue() {
        String status;

        if (!containsFailures) {
            status = REQUEST_STATUS_COMPLETED;
        } else {
            status = REQUEST_STATUS_FAILED;
        }

        return status;
    }

    /**
     * @description Returns a String email subject
     * @return String
     **/
    private String getEmailSubject() {
        return (!containsFailures)
            ? 'Store Onboarding Completed'
            : 'ACTION REQUIRED: Store Onboarding Results';
    }

    /**
     * @description Returns a String email body
     * @return String
     **/
    private String getEmailBody() {
        String plainTextBody = '';

        if (!containsFailures) {
            plainTextBody +=
                'Your Store Onboarding Request is now completed. ' +
                this.storeCount +
                ' stores were processed successfully.';
        } else {
            plainTextBody +=
                'Your Store Onboarding Request has been processed. ' +
                this.storeCount +
                ' stores were processed successfully. ';
            plainTextBody += getFailureNotificationBody(); // Add details on the failures
        }

        return plainTextBody;
    }

    /**
     * @description Triggers a "Bell Notification" for the incomplete Stores.
     **/
    private void sendNotification() {
        if (containsFailures) {
            CustomNotificationType notificationType = BulkCorporateOnboardingRequestService.getNewStoreOnboardingCustomNotificationType();

            if (notificationType != null) {
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                notification.setNotificationTypeId(notificationType.Id);
                notification.setTargetId(pfr.OwnerId);
                notification.setTitle('Incomplete Store Onboarding Alert');
                notification.setBody(getFailureNotificationBody());
                notification.send(new Set<String>{ pfr.OwnerId });
            }
        }
    }

    /**
     * @description Returns the ContractNumber formatted for a notification
     * @return String
     **/
    private String getContractDisplayName() {
        String displayString = '';

        if (String.isNotBlank(this.contractName)) {
            displayString = '(' + this.contractName + ')';
        }

        return displayString;
    }

    /**
     * @description Returns the String for failure notifications
     * @return String
     **/
    private String getFailureNotificationBody() {
        String textBody = 'Some stores were not completed and added to the Work Order due to unverified or out of coverage addresses. ';
        textBody +=
            'Please navigate to the Contract ' +
            getContractDisplayName() +
            ' and click on "' +
            ANSO_BUTTON_NAME +
            '" for more details. ';
        textBody += 'From there, you can retry processing these stores once the addresses are verified.';
        return textBody;
    }

    /**
     * @description Updates the Serialized_Object_Data__c with the results of the job
     * @return String
     **/
    private String getSerializedStores() {
        List<BulkCorporateOnboardingWrappers.StoreInfo> storeInfos = BulkCorporateOnboardingRequestService.unpackStoreInfos(
            pfr.Id,
            pfr.Serialized_Object_Data__c
        );
        for (BulkCorporateOnboardingWrappers.StoreInfo storeInfo : storeInfos) {
            // If the batch was already completed, OR if it was completed in this run
            storeInfo.isJobComplete =
                storeInfo.isJobComplete || this.finishedStores.contains(storeInfo.storeId);
        }

        return BulkCorporateOnboardingRequestService.packStoreInfos(storeInfos);
    }
}