sfdx-source/force-app/main/default/objects/Account/fields/DoorDash_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>DoorDash_Legal_Entity__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-578 : To store DoorDash legal entity for contract template generation.</description>
    <label>DoorDash Legal Entity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/OAuth_Config__c/OAuth_Config__c.object-meta.xml
<CustomObject>
    <description>LEM-1285: Configure Netsuite OAuth-1 protocol setting configuration.</description>
    <label>OAuth Config</label>
    <nameField>
        <label>OAuth Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth Configs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/OAuth_Config__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>LEM-1285: It contains Authentication keys.</description>
    <label>Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing street</inlineHelpText>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>LEM-1150: This field used to store Bank account number.</description>
    <inlineHelpText>Please enter the correct Bank Account Number length (AUS = 6-10 digits, US = 6-17 digits, NZ = 13-16 digits, CAN = 7-12 digits)</inlineHelpText>
    <label>Bank Account Number</label>
    <length>50</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Bill_To_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Company_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-2029: Refers to the billing entity of the MX</description>
    <inlineHelpText>Refers to the billing entity of the MX</inlineHelpText>
    <label>Bill To Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Billing_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Email__c</fullName>
    <description>LEM-1285: Formula field to get the Email from Contact lookup field</description>
    <formula>Billing_Contact_Name__r.Email</formula>
    <label>Billing Contact Email</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1371: Field to be only used when Record Type is Invoice. Payment Account record type uses the Contact related list for Billing Contact Name (is n:n relationship).</description>
    <inlineHelpText>Captures the first name, last name, and email address to be setup in NetSuite</inlineHelpText>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-2506: Signifies the business account this payment account is related to.</description>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Channel Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>LEM-4702: It represents business unit of payment account.</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing city</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing country</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Country_Code_Alpha_2__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_Alpha_2__c</fullName>
    <description>LEM-1285: Given a country, calculates the Alpha-2 ISO Code. Currently used for Netsuite integration.</description>
    <formula>Case( Country__c ,
&apos;United States&apos;, &apos;US&apos;,
&apos;Canada&apos;, &apos;CA&apos;,
&apos;Australia&apos;, &apos;AU&apos;,
&apos;New Zealand&apos;, &apos;NZ&apos;,
&apos;Japan&apos;, &apos;JP&apos;,
&apos;Germany&apos;, &apos;DE&apos;,
NULL)</formula>
    <label>Country Code (Alpha-2)</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing currency</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/DoorDash_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>DoorDash_Legal_Entity__c</fullName>
    <description>LEM-3150: DoorDash Legal Entity</description>
    <label>DoorDash Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DoorDash_Legal_Entity</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Institution_Number__c.field-meta.xml
<CustomField>
    <fullName>Institution_Number__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>LEM-1150: To store Institution number.
LEM-3993: Converted to text field to allow storing leading zeros.</description>
    <inlineHelpText>For Canadian merchants, please enter the merchant bank&apos;s institution number.</inlineHelpText>
    <label>Institution Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures the NetSuite record ID of the related Customer account in NetSuite.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Netsuite_Sync_Initiator__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Sync_Initiator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-3150: Capture user details on Sync With Netsuite Action</description>
    <label>NetSuite Sync Initiator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sync_With_Netsuite_User</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/NetSuite_Sync_Response__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync_Response__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures the response code from NetSuite for the latest sync</inlineHelpText>
    <label>NetSuite Sync Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/NetSuite_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync_Status__c</fullName>
    <label>NetSuite Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures payment terms</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/RoutingNumber__c.field-meta.xml
<CustomField>
    <fullName>RoutingNumber__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>LEM-2387 : Routing Number of the Mx.</description>
    <inlineHelpText>Routing Number of the Mx.</inlineHelpText>
    <label>Routing Number</label>
    <length>18</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing state</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

sfdx-source/force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <description>LEM-1371: Payment Account Object setup</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <description>LEM-1371: Payment Account Object setup</description>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/DoorDash_Legal_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DoorDash, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Essentials LLC, Australia</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash G&amp;C, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Pharmacy Services, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Technologies Australia Pty Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Technologies Canada, Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Technologies New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>DoorDash Technologies Puerto Rico, LLC</fullName>
    </customValue>
    <customValue>
        <fullName>Rapid Retail Canada Inc.</fullName>
    </customValue>
    <description>LEM-3150 : DoorDash Legal Entity Global Picklist</description>
    <masterLabel>DoorDash Legal Entity</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Payment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Due on receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Net 7</fullName>
    </customValue>
    <customValue>
        <fullName>Net 15</fullName>
    </customValue>
    <customValue>
        <fullName>Net 20</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
        <default>true</default>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>Net 45</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 70</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Net 120</fullName>
    </customValue>
    <description>LEM-1371: Payment Account Object setup</description>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/selectors/PaymentAccountsSelector.cls
/**
 * @author Deloitte
 * @date 15/07/2022
 * @description Selector class for Payment Account object.
 */
public inherited sharing class PaymentAccountsSelector extends fflib_SObjectSelector implements IPaymentAccountsSelector, IEncryptedDataSelector {
    private static final Id INVOICE_RECORD_TYPE_ID = Schema.SObjectType.Payment_Account__c.getRecordTypeInfosByDeveloperName()
        .get('Invoice')
        .getRecordTypeId();
    /**
     * @description Default constructor for the PaymentAccountsSelector selector class.
     * @return IPaymentAccountsSelector - instance of IPaymentAccountsSelector
     */
    public static IPaymentAccountsSelector newInstance() {
        return (IPaymentAccountsSelector) Application.Selector.newInstance(
            Payment_Account__c.SObjectType
        );
    }

    /**
     * @description It is used for getting the fields of Payment_Account__c object.
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Payment_Account__c.Id,
            Payment_Account__c.Billing_Contact_Name__c,
            Payment_Account__c.Payment_Terms__c,
            Payment_Account__c.NetSuite_ID__c,
            Payment_Account__c.recordTypeId,
            Payment_Account__c.Bank_Account_Number__c,
            Payment_Account__c.Billing_Contact_Email__c,
            Payment_Account__c.Bill_To_Company_Name__c,
            Payment_Account__c.Country_Code_Alpha_2__c,
            Payment_Account__c.Address_Line_1__c,
            Payment_Account__c.State__c,
            Payment_Account__c.Country__c,
            Payment_Account__c.City__c,
            Payment_Account__c.Postal_Code__c,
            Payment_Account__c.Currency__c,
            Payment_Account__c.CurrencyIsoCode,
            Payment_Account__c.DoorDash_Legal_Entity__c,
            Payment_Account__c.Institution_Number__c,
            Payment_Account__c.NetSuite_Sync_Status__c,
            Payment_Account__c.Netsuite_Sync_Initiator__c,
            Payment_Account__c.NetSuite_Sync_Response__c,
            Payment_Account__c.Business_Unit__c,
            Payment_Account__c.RoutingNumber__c,
            Payment_Account__c.Name
        };
    }

    /**
     * @description It is used for getting object type.
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Payment_Account__c.SObjectType;
    }

    /**
     * @description It is used for getting Payment Accounts by the passed Ids.
     * @param paymentAccountIds
     * @return List<Payment_Account__c>
     */
    public List<Payment_Account__c> selectById(Set<Id> paymentAccountIds) {
        return (List<Payment_Account__c>) selectSObjectsById(paymentAccountIds);
    }

    /**
     * @description It is used to get the encrypted data stored in the passed fields
     * by the passed sObjectIds.
     * @JIRA# LEM-2255
     * @param fieldSet
     * @param sobjectIds
     * @return List<SObject>
     */
    public List<SObject> selectEncryptedData(Schema.FieldSet fieldSet, Set<Id> sobjectIds) {
        fflib_QueryFactory paymentAccountQuery = newQueryFactory()
            .selectFieldSet(fieldSet)
            .setCondition('Id IN :sobjectIds');
        return (List<Payment_Account__c>) Database.query(paymentAccountQuery.toSOQL());
    }
    /**
     * @description Return Payment Account record by Id for Netsuite integration
     * @param paymentAccountId
     * @return List<Payment_Account__c>
     */
    public Payment_Account__c selectPaymentAccountByIdForNetsuiteIntegration(Id paymentAccountId) {
        fflib_QueryFactory paymentAccountQuery = newQueryFactory(false);
        for (
            OAuth_Config__c config : OAuth1ConfigsSelector.newInstance()
                .getNetsuiteIntegrationDatamap()
        ) {
            paymentAccountQuery.selectField(config.Key__c);
        }
        paymentAccountQuery.setCondition('Id = :paymentAccountId');
        paymentAccountQuery.setLimit(1);
        return (Payment_Account__c) Database.query(paymentAccountQuery.toSOQL());
    }

    /**
     * @description It is used to get the related business accounts of the payment accounts
     * @JIRA# LEM-3121
     * @param accountIds
     * @return List<Payment_Account__c>
     */
    public List<Payment_Account__c> selectRelatedBusinessAccounts(Set<Id> accountIds) {
        fflib_QueryFactory query = newQueryFactory()
            .selectField('Business_Account__c')
            .selectField('Business_Account__r.CurrencyIsoCode')
            .setCondition(
                'Business_Account__r.Id IN : accountIds AND RecordtypeId = :INVOICE_RECORD_TYPE_ID'
            );
        return (List<Payment_Account__c>) Database.query(query.toSOQL());
    }

    /**
     * @description  It queries Payment Accounts with 'Invoice' record type by passed list of Payment Account Ids
     * @JIRA# LEM-10203
     * @param paymentAccountIds
     * @return List<Payment_Account__c>
     */
    public List<Payment_Account__c> selectInvoicePaymentAccountsByIds(Set<Id> paymentAccountIds) {
        fflib_QueryFactory query = newQueryFactory(false)
            .setCondition('RecordtypeId = :INVOICE_RECORD_TYPE_ID AND Id IN :paymentAccountIds');

        return (List<Payment_Account__c>) Database.query(query.toSOQL());
    }
}