sfdx-source/force-app/main/default/objects/Account/fields/Franchise_Parent__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Parent__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-99: Describes the parent of a franchisee.</description>
    <label>Franchise Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Franchise Parents</relationshipLabel>
    <relationshipName>FranchiseParents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Bundled_with_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Bundled_with_Marketplace__c</fullName>
    <description>LEM-1874: It indicates whether Storefront product was sold with Marketplace product in the associated Contract. It also drives the logic for creating Storefront Bundled Work Plan.</description>
    <label>Bundled with Marketplace</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/IsStoresAssociationInProgress__c.field-meta.xml
<CustomField>
    <fullName>IsStoresAssociationInProgress__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-3711: It is used to check whether the stores association is in progress for parent Work Order in order to display the banner message.</description>
    <label>IsStoreAssociationInProgress</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Opportunity linked to the onboarding event.</description>
    <inlineHelpText>Opportunity linked to the onboarding event</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/tests/classes/integration/batchables/NintexWorkOrdersProcessorIntegrationTest.cls
/**
 * @author Deloitte
 * @date 11/29/2022
 * @description Integration test class for NintexWorkOrdersProcessorBatch class.
 */
@isTest(SeeAllData=false)
private class NintexWorkOrdersProcessorIntegrationTest {
    private static final String ACCOUNT_PRIMARY_VERTICAL_GIFTS = 'Gifts';
    private static final String ACCOUNT_RECORD_TYPE_NAME_BUSINESS = 'Business';
    private static final String ACCOUNT_RECORD_TYPE_ID_BUSINESS = Schema.SObjectType.Account.getRecordTypeInfosByName()
        .get(ACCOUNT_RECORD_TYPE_NAME_BUSINESS)
        .getRecordTypeId();
    private static final String BUNDLED_WITH_MARKETPLACE_NO = 'No';
    private static final String CHILD_WORK_ORDERS_SIZE_NOT_MATCHED_ASSERT_MESSAGE = 'Unexpected result: Child Work Orders size is not matching on parent Work Order';
    private static final String OPPORTUNITY_NAME = 'McDonald Test';
    private static final String OPPORTUNITY_STAGE = 'Prospecting';
    private static final Integer STORE_ACCOUNTS_COUNT = 150;
    private static final String WORK_ORDER_TYPE_MARKETPLACE = 'Marketplace';

    /**
     * @description To setup relevant test data.
     */
    @testSetup
    private static void setupData() {
        Account businessAccount = ServiceIntegrationDataBuilder.createBusinessAccountInstance(
            ACCOUNT_PRIMARY_VERTICAL_GIFTS
        );
        insert businessAccount;
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook;
        Opportunity parentOpportunity = new Opportunity(
            AccountId = businessAccount.Id,
            Name = OPPORTUNITY_NAME,
            CloseDate = System.today().addMonths(2),
            Pricebook2Id = Test.getStandardPricebookId(),
            StageName = OPPORTUNITY_STAGE
        );
        insert parentOpportunity;
        List<Account> storeAccounts = new List<Account>();
        for (Integer iterator = 0; iterator < STORE_ACCOUNTS_COUNT; ++iterator) {
            Account storeAccount = ServiceIntegrationDataBuilder.createStoreAccountInstance(
                businessAccount.Id,
                ACCOUNT_PRIMARY_VERTICAL_GIFTS
            );
            storeAccount.Franchise_Parent__c = businessAccount.Id;
            storeAccounts.add(storeAccount);
        }
        insert storeAccounts;
        WorkOrder parentWorkOrder = ServiceIntegrationDataBuilder.createWorkOrderInstance(
            businessAccount.Id,
            WORK_ORDER_TYPE_MARKETPLACE
        );
        parentWorkOrder.Bundled_with_Marketplace__c = BUNDLED_WITH_MARKETPLACE_NO;
        parentWorkOrder.IsStoresAssociationInProgress__c = false;
        parentWorkOrder.Opportunity__c = parentOpportunity.Id;
        insert parentWorkOrder;
    }

    /**
     * @description To test creation of child Work Orders on parent Work Orders related to
     * franchise Accounts of the passed store Accounts through batch execution.
     */
    @isTest
    private static void testWhenStoreAccountsAssociatedWithFranchiseAccountsExecutedInBatchThenCorrespondingChildWorkOrdersCreated() {
        Account businessAccount = [
            SELECT Id
            FROM Account
            WHERE RecordTypeId = :ACCOUNT_RECORD_TYPE_ID_BUSINESS
        ];
        Opportunity parentOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE AccountId = :businessAccount.Id
        ];
        WorkOrder parentWorkOrder = [
            SELECT Id
            FROM WorkOrder
            WHERE AccountId = :businessAccount.Id
        ];
        NintexWorkOrdersProcessorBatch batchInstance = new NintexWorkOrdersProcessorBatch(
            new Map<Id, Id>{ businessAccount.Id => parentOpportunity.Id }
        );
        Test.startTest();
        Database.executeBatch(batchInstance);
        Test.stopTest();
        List<WorkOrder> childWorkOrdersResult = [
            SELECT Id
            FROM WorkOrder
            WHERE ParentWorkOrderId = :parentWorkOrder.Id
        ];
        System.assertEquals(
            STORE_ACCOUNTS_COUNT,
            childWorkOrdersResult.size(),
            CHILD_WORK_ORDERS_SIZE_NOT_MATCHED_ASSERT_MESSAGE
        );
    }
}