sfdx-source/force-app/main/default/objects/Account/fields/Legal_Business_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Business_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-274: This field specifies the legal business name.</description>
    <inlineHelpText>Represents the legal business name</inlineHelpText>
    <label>Legal Business Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-280 This picklist defines the primary vertical of the Mx.</description>
    <inlineHelpText>Primary vertical of the Mx</inlineHelpText>
    <label>Primary Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>LEM -186</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/Is_Churned_Mx_Contract_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Churned_Mx_Contract_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-23780: It indicates that the batch has successfully processed the Churned Mx cleanup.</description>
    <label>Is Churned Mx Contract Processed?</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/SBQQ__Order__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Service__c/Merchant_Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Merchant_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>LEM-187: Initial Setup of Merchant Service</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Service__c/fields/Mx_Agreed_to_Product__c.field-meta.xml
<CustomField>
    <fullName>Mx_Agreed_to_Product__c</fullName>
    <description>LEM-2589 Used to indicate whether the product must be provisioned for the Mx. A value of Yes indicates a Mx is entitled to a product and signed a contract agreeing to its terms and conditions. A value of No indicates a Mx is entitled to a service but has not chosen to take advantage of this product.</description>
    <label>Mx Agreed to Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-187: Initial Setup of Merchant Service</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Merchant Services</relationshipLabel>
    <relationshipName>Merchant_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Merchant_Service__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>LEM-187: Initial Setup of Merchant Service</description>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Merchant Services</relationshipLabel>
    <relationshipName>Merchant_Services</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <description>LEM-1145: Opportunity Lite</description>
    <inlineHelpText>Indicates whether this deal will follow the standard opportunity workflow or the lite process.</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Lite</fullName>
            </value>
            <value>
                <fullName>Self-Serve</fullName>
            </value>
            <value>
                <fullName>Full-Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Estimated_Number_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Number_of_Stores__c</fullName>
    <description>LEM-74: Estimated number of stores to which this deal will apply.</description>
    <inlineHelpText>Estimated number of stores to which this deal will apply</inlineHelpText>
    <label>Estimated # of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Opportunity_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Sub_Type__c</fullName>
    <description>LEM-78: This field indicates the sub-type based on the selected Opportunity Type.</description>
    <inlineHelpText>Indicates sub-type based on selected Opportunity type</inlineHelpText>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Former Partner</fullName>
            </value>
            <value>
                <fullName>Net New Partner</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Ads &amp; Promos</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Rescue</fullName>
            </value>
            <value>
                <fullName>Contract Correction</fullName>
                <label>Contract Correction - New</label>
            </value>
            <value>
                <fullName>Contract Correction - Amendment</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>New Store Expansion</fullName>
            </value>
            <value>
                <fullName>Contract Consolidation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/fields/Opportunity_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Sub_Type__c</fullName>
    <description>LEM-9256</description>
    <formula>TEXT( SBQQ__Opportunity2__r.Opportunity_Sub_Type__c )</formula>
    <label>Opportunity Sub Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>LEM-1980 Segment field from Account</description>
    <formula>TEXT(SBQQ__Account__r.Segment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Contract linked to the onboarding event.</description>
    <inlineHelpText>Contract linked to the onboarding event</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Estimated_Number_Of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Number_Of_Stores__c</fullName>
    <description>LEM-813: Estimated number of stores to be onboarded as part of the work order.</description>
    <inlineHelpText>Estimated number of stores to be onboarded as part of the work order</inlineHelpText>
    <label>Estimated Number Of Stores</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>LEM-813: Account segment linked to the onboarding event.</description>
    <formula>Text(Account.Segment__c)</formula>
    <inlineHelpText>Account segment linked to the onboarding event</inlineHelpText>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Agreement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Franchise Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Store Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agreement</fullName>
    </customValue>
    <description>LEM-186, LEM-3818: Initial Setup of Agreement</description>
    <masterLabel>Agreement Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <description>LEM-280: This picklist value set is created to define the verticals and sub-verticals associated with store and business accounts.</description>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/integration/batchables/ProcessChurnedMerchantRecordsBatchTest.cls
/**
 * @author Deloitte
 * @date 07/11/2024
 * @description This is the test class for ProcessChurnedMerchantRecordsBatch class
 */
@isTest(SeeAllData=false)
private class ProcessChurnedMerchantRecordsBatchTest {
    private static final String ASSERTION_FAILED = 'Unexpected Result: Batch did not execute successfully';
    private static final String BUSINESS_ACCOUNT = 'Business';
    private static final String BATCH_NAME = 'ProcessChurnedMerchantRecordsScheduledBatch';
    private static final String CRON_EXPRESSION = '0 0 1 * * ?';
    private static final String STORE_ACCOUNT = 'Store';
    private static final String EXTERNAL_ID_SOURCE_MDS = 'MDS';
    private static final String XREF_STATUS_ACTIVE = 'Active';
    private static final String XREF_STATUS_INACTIVE = 'Inactive';
    private static final String AGREEMENT_NAME = 'Test Agreement';
    private static final String AGREEMENT_STATUS_PENDING = 'Pending';
    private static final String AGREEMENT_TYPE_FRANCHISE_AGREEMENT = 'Franchise Agreement';
    private static final String NAME_ACCOUNT = 'Test Acc';
    private static final String NAME_OPPORTUNITY = 'Test Opportunity';
    private static final String NAME_ACCOUNT_CHILD = 'Test Acc Child';
    private static final String UNITED_STATES = 'United States';
    private static final String BILLING_STREET = '123 Test Street';
    private static final String BILLING_CITY = 'Missoula';
    private static final String BILLING_CITY2 = 'New York';
    private static final String BILLING_STATE = 'Montana';
    private static final String BILLING_CODE = '59801';
    private static final String BILLING_CODE2 = '59802';
    private static final String ACCOUNT_SEGMENT = 'SMB';
    private static final String PRODUCT_NAME_MARKETPLACE = 'Marketplace';
    private static final String PRODUCT_CODE_10017 = '10017';
    private static final String PRIMARY_VERTICAL = 'Hot & Prepared';
    private static final String CONTRACTTYPE_CHURNEDMERCHANT = 'Churned Merchant';
    private static final String CONTRACTTYPE_CORE = 'Core';
    private static final String MX_AGREED_TO_PRODUCT_YES = 'Yes';
    private static final String PROVISIONING_STATUS_READY_FOR_PROVISIONING = 'Ready for Provisioning';
    private static final String WORKORDER_TYPE_STOREFRONT = 'Storefront';
    private static final String PROCESS_CHURNED_MX_CONTRACTS_RECORDS_SCOPE_METADATA = 'ProcessChurnedMxContractRecordsScope';
    private static final String STAGENAME = 'Prospecting';
    private static final String DEAL_TYPE = 'Standard';
    private static final String OPPORTUNITY_SUB_TYPE = 'Former Partner';
    private static final String XREF_EXTERNAL_ID = '12345';

    /**
     * @description It is used to test whether the batch is invoked for the Contract with type as
     * "Churned Merchant". It also checks whether the associated child records are deleted or updated.
     */
    @isTest
    private static void testWhenChurnedMxContractsExecutedByBatchThenChildRecordsDeletedOrUpdated() {
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(BUSINESS_ACCOUNT)
            .getRecordTypeId();
        Id storeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(STORE_ACCOUNT)
            .getRecordTypeId();
        SBQQ.TriggerControl.disable();
        Account businessAccount = new Account(
            Name = NAME_ACCOUNT,
            RecordTypeId = businessRecordTypeId,
            BillingCountry = UNITED_STATES,
            Segment__c = ACCOUNT_SEGMENT,
            Legal_Business_Name__c = BUSINESS_ACCOUNT,
            Primary_Vertical__c = PRIMARY_VERTICAL
        );

        Account childAccount = new Account(
            Name = NAME_ACCOUNT_CHILD,
            RecordTypeId = storeRecordTypeId,
            ParentId = businessAccount.Id,
            BillingCountry = UNITED_STATES,
            BillingStreet = BILLING_STREET,
            BillingCity = BILLING_CITY2,
            BillingState = BILLING_STATE,
            BillingPostalCode = BILLING_CODE2,
            Segment__c = ACCOUNT_SEGMENT,
            Primary_Vertical__c = PRIMARY_VERTICAL
        );
        insert businessAccount;
        insert childAccount;
        Opportunity testOpp = new Opportunity(
            AccountId = businessAccount.Id,
            Name = NAME_OPPORTUNITY,
            CloseDate = System.today() + 30,
            StageName = STAGENAME,
            Deal_Type__c = DEAL_TYPE,
            Opportunity_Sub_Type__c = OPPORTUNITY_SUB_TYPE,
            Estimated_Number_of_Stores__c = 1
        );
        insert testOpp;
        SBQQ__Quote__c quote = CPQTestDataFactory.createQuote(testOpp, businessAccount, null, true);
        Order order = CPQTestDataFactory.createOrder(businessAccount, testOpp, quote, false);
        order.SBQQ__Quote__c = null; //null out quote so order is not activated.
        insert order;

        Order churnedMxOrder = [SELECT Id, SBQQ__Quote__c, AccountId FROM Order];
        churnedMxOrder.Type = CONTRACTTYPE_CHURNEDMERCHANT;
        update churnedMxOrder;

        Contract contractInstance = new Contract(
            AccountId = businessAccount.Id,
            SBQQ__Order__c = churnedMxOrder.Id,
            Is_Churned_Mx_Contract_Processed__c = false
        );
        insert contractInstance;
        Product2 marketplaceProduct = new Product2(
            Name = PRODUCT_NAME_MARKETPLACE,
            ProductCode = PRODUCT_CODE_10017
        );
        insert marketplaceProduct;
        SBQQ__Subscription__c subscription = new SBQQ__Subscription__c(
            SBQQ__Product__c = marketplaceProduct.Id,
            SBQQ__Contract__c = contractInstance.Id,
            SBQQ__Account__c = businessAccount.Id,
            SBQQ__Quantity__c = 200
        );
        insert subscription;
        Merchant_Service__c marketplaceMerchantService = new Merchant_Service__c(
            Account__c = childAccount.Id,
            Mx_Agreed_to_Product__c = MX_AGREED_TO_PRODUCT_YES,
            Product__c = marketplaceProduct.Id,
            Subscription__c = subscription.Id
        );
        insert marketplaceMerchantService;
        Agreement__c mockFranchiseAgreement = new Agreement__c(
            Name = AGREEMENT_NAME,
            Account__c = childAccount.Id,
            Contract__c = contractInstance.Id,
            Type__c = AGREEMENT_TYPE_FRANCHISE_AGREEMENT,
            Status__c = AGREEMENT_STATUS_PENDING
        );
        insert mockFranchiseAgreement;
        Xref__c[] xrefs = new List<Xref__c>{
            new Xref__c(
                Salesforce_Account_Name__c = childAccount.Id,
                External_ID_Source__c = EXTERNAL_ID_SOURCE_MDS,
                Xref_Status__c = XREF_STATUS_ACTIVE,
                External_ID__c = XREF_EXTERNAL_ID
            )
        };
        insert xrefs;
        WorkOrder parentStorefrontWorkOrderInstance = new WorkOrder(
            AccountId = businessAccount.Id,
            Provisioning_Status__c = PROVISIONING_STATUS_READY_FOR_PROVISIONING,
            Type__c = WORKORDER_TYPE_STOREFRONT,
            Contract__c = contractInstance.Id,
            Opportunity__c = testOpp.Id
        );
        insert parentStorefrontWorkOrderInstance;
        SBQQ.TriggerControl.enable();
        Test.startTest();
        Database.executeBatch(new ProcessChurnedMerchantRecordsBatch());
        Test.stopTest();
        List<Xref__c> inactiveXrefs = [
            SELECT Id, Salesforce_Account_Name__c, Xref_Status__c
            FROM Xref__c
            WHERE Salesforce_Account_Name__c = :childAccount.Id
        ];
        List<Agreement__c> agreements = [
            SELECT Id
            FROM Agreement__c
            WHERE Contract__c = :contractInstance.Id
        ];
        List<Contract> updatedContracts = [
            SELECT Id, Is_Churned_Mx_Contract_Processed__c
            FROM Contract
            WHERE Id = :contractInstance.Id
        ];
        System.assertEquals(
            inactiveXrefs[0].Xref_Status__c,
            XREF_STATUS_INACTIVE,
            ASSERTION_FAILED
        );
        System.assertEquals(agreements.size(), 0, ASSERTION_FAILED);
        System.assertEquals(
            updatedContracts[0].Is_Churned_Mx_Contract_Processed__c,
            true,
            ASSERTION_FAILED
        );
    }

    /**
     * @description It is used to test the batch is not invoked or executed for the Contract with type as
     * "Core". It also ensures associated child records are not deleted or updated.
     */
    @isTest
    private static void testWhenNonChurnedMxContractsExecutedByBatchThenChildRecordsAreNotDeletedOrUpdated() {
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(BUSINESS_ACCOUNT)
            .getRecordTypeId();
        Id storeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(STORE_ACCOUNT)
            .getRecordTypeId();
        SBQQ.TriggerControl.disable();
        Account businessAccount = new Account(
            Name = NAME_ACCOUNT,
            RecordTypeId = businessRecordTypeId,
            BillingCountry = UNITED_STATES,
            Segment__c = ACCOUNT_SEGMENT,
            Legal_Business_Name__c = BUSINESS_ACCOUNT,
            Primary_Vertical__c = PRIMARY_VERTICAL
        );

        Account childAccount = new Account(
            Name = NAME_ACCOUNT_CHILD,
            RecordTypeId = storeRecordTypeId,
            ParentId = businessAccount.Id,
            BillingCountry = UNITED_STATES,
            BillingStreet = BILLING_STREET,
            BillingCity = BILLING_CITY2,
            BillingState = BILLING_STATE,
            BillingPostalCode = BILLING_CODE2,
            Segment__c = ACCOUNT_SEGMENT,
            Primary_Vertical__c = PRIMARY_VERTICAL
        );
        insert businessAccount;
        insert childAccount;
        Opportunity testOpp = new Opportunity(
            AccountId = businessAccount.Id,
            Name = NAME_OPPORTUNITY,
            CloseDate = System.today() + 30,
            StageName = STAGENAME,
            Deal_Type__c = DEAL_TYPE,
            Opportunity_Sub_Type__c = OPPORTUNITY_SUB_TYPE,
            Estimated_Number_of_Stores__c = 1
        );
        insert testOpp;
        SBQQ__Quote__c quote = CPQTestDataFactory.createQuote(testOpp, businessAccount, null, true);
        Order order = CPQTestDataFactory.createOrder(businessAccount, testOpp, quote, false);
        order.SBQQ__Quote__c = null; //null out quote so order is not activated.
        insert order;
        Order churnedMxOrder = [SELECT Id, SBQQ__Quote__c, AccountId FROM Order];
        churnedMxOrder.Type = CONTRACTTYPE_CORE;
        update churnedMxOrder;
        Contract contractInstance = new Contract(
            AccountId = businessAccount.Id,
            SBQQ__Order__c = churnedMxOrder.Id,
            Is_Churned_Mx_Contract_Processed__c = false
        );
        insert contractInstance;
        Product2 marketplaceProduct = new Product2(
            Name = PRODUCT_NAME_MARKETPLACE,
            ProductCode = PRODUCT_CODE_10017
        );
        insert marketplaceProduct;
        SBQQ__Subscription__c subscription = new SBQQ__Subscription__c(
            SBQQ__Product__c = marketplaceProduct.Id,
            SBQQ__Contract__c = contractInstance.Id,
            SBQQ__Account__c = businessAccount.Id,
            SBQQ__Quantity__c = 200
        );
        insert subscription;
        Merchant_Service__c marketplaceMerchantService = new Merchant_Service__c(
            Account__c = childAccount.Id,
            Mx_Agreed_to_Product__c = MX_AGREED_TO_PRODUCT_YES,
            Product__c = marketplaceProduct.Id,
            Subscription__c = subscription.Id
        );
        insert marketplaceMerchantService;
        Agreement__c mockFranchiseAgreement = new Agreement__c(
            Name = AGREEMENT_NAME,
            Account__c = childAccount.Id,
            Contract__c = contractInstance.Id,
            Type__c = AGREEMENT_TYPE_FRANCHISE_AGREEMENT,
            Status__c = AGREEMENT_STATUS_PENDING
        );
        insert mockFranchiseAgreement;
        Xref__c[] xrefs = new List<Xref__c>{
            new Xref__c(
                Salesforce_Account_Name__c = childAccount.Id,
                External_ID_Source__c = EXTERNAL_ID_SOURCE_MDS,
                Xref_Status__c = XREF_STATUS_ACTIVE,
                External_ID__c = XREF_EXTERNAL_ID
            )
        };
        insert xrefs;
        WorkOrder parentStorefrontWorkOrderInstance = new WorkOrder(
            AccountId = businessAccount.Id,
            Provisioning_Status__c = PROVISIONING_STATUS_READY_FOR_PROVISIONING,
            Type__c = WORKORDER_TYPE_STOREFRONT,
            Contract__c = contractInstance.Id,
            Opportunity__c = testOpp.Id
        );
        insert parentStorefrontWorkOrderInstance;
        SBQQ.TriggerControl.enable();
        Test.startTest();
        Database.executeBatch(new ProcessChurnedMerchantRecordsBatch());
        Test.stopTest();
        List<Xref__c> associatedXrefs = [
            SELECT Id, Salesforce_Account_Name__c, Xref_Status__c
            FROM Xref__c
            WHERE Salesforce_Account_Name__c = :childAccount.Id
        ];
        List<Agreement__c> agreements = [
            SELECT Id
            FROM Agreement__c
            WHERE Contract__c = :contractInstance.Id
        ];
        System.assertEquals(
            associatedXrefs[0].Xref_Status__c,
            XREF_STATUS_ACTIVE,
            ASSERTION_FAILED
        );
        System.assertEquals(agreements.size(), 1, ASSERTION_FAILED);
        System.assertEquals(
            contractInstance.Is_Churned_Mx_Contract_Processed__c,
            false,
            ASSERTION_FAILED
        );
    }

    /**
     * @description It is used to test whether the batch is scheduled or not for the given cron
     * expression.
     */
    @isTest
    private static void testWhenBatchIsScheduledThenAsyncJobCreated() {
        Test.startTest();
        String jobId = System.schedule(
            BATCH_NAME,
            CRON_EXPRESSION,
            new ProcessChurnedMerchantRecordsBatch()
        );
        Test.stopTest();
        CronTrigger cronTriggerRecord = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime
            FROM CronTrigger
            WHERE Id = :jobId
        ];
        System.assertEquals(
            Time.newInstance(1, 0, 0, 0),
            cronTriggerRecord.NextFireTime.time(),
            ASSERTION_FAILED
        );
    }
}