sfdx-source/force-app/main/default/objects/Account/fields/Menu_to_be_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Menu_to_be_Completed_By__c</fullName>
    <description>LEM-658: Indicates who will complete Work Order menu.</description>
    <inlineHelpText>Signifies the team that will complete menu setup</inlineHelpText>
    <label>Menu to be Completed By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>DoorDash Onboarding Team</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>None - Menu Setup Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1046: This field is used to represent the type of agency.</description>
    <inlineHelpText>Represents the type of agency</inlineHelpText>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Full Service</fullName>
            </value>
            <value>
                <fullName>Creative</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/Readiness_Check_Failure__c.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores validation rules evaluated successfully for a store Account related to a Work Order during readiness check. Onboarding and activations persona&apos;s user will take corrective actions to resolve the failures captured in this object in order to make a store ready for provisioning.</description>
    <label>Readiness Check Failure</label>
    <nameField>
        <displayFormat>RCF-{0}</displayFormat>
        <label>Readiness Check Failure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readiness Check Failures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the store Account that needs correction to resolve the failure.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Readiness Check Failures</relationshipLabel>
    <relationshipName>Readiness_Check_Failures</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Child_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Child_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the Work Order related to store associated to this failure record.</description>
    <label>Child Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Store Level Readiness Check Corrections</relationshipLabel>
    <relationshipName>Store_Level_Readiness_Check_Corrections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed to onboarding and activations persona&apos;s user for corrections on the store related to the failure record.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>LEM-1684: It indicates the field name where the failure occurred.</description>
    <label>Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates the object name where the failure occurred.</description>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the parent of work order related to the readiness check failure record.</description>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Readiness Check Corrections</relationshipLabel>
    <relationshipName>Readiness_Check_Corrections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/Store_Readiness_Validation_Rule__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores the details of validation rules that needs to be evaluated for store readiness check.</description>
    <label>Readiness Validation Rule</label>
    <pluralLabel>Readiness Validation Rules</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed when the validation rule criteria fails.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>LEM-1684: It indicates label of the field on which the validation needs to be performed.</description>
    <label>Field Label</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>LEM-1684: It indicates the field name on which the validation needs to be performed.</description>
    <label>Field Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Object_Label__c.field-meta.xml
<CustomField>
    <fullName>Object_Label__c</fullName>
    <description>LEM-1684: It indicates the label of object on which the validation needs to be performed.</description>
    <label>Object Label</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates object name on which the validation needs to be performed.</description>
    <label>Object Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Store_Readiness_Validation_Rule__mdt/fields/Service_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Method_Name__c</fullName>
    <description>LEM-1684: It indicates the service method name where automation is written for the validation rule.</description>
    <label>Service Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + AccountId , Account.Name , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Menu_to_be_Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Menu_to_be_Completed_By__c</fullName>
    <description>LEM-793: Indicates who will complete Work Order menu.</description>
    <inlineHelpText>Signifies the team that will complete menu setup</inlineHelpText>
    <label>Menu to be Completed By</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>DoorDash Onboarding Team</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>None - Menu Setup Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <description>LEM-16014: It indicates Id of Parent Work Order.</description>
    <formula>CASESAFEID(ParentWorkOrderId)</formula>
    <label>Parent Work Order</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>LEM-1271: Type of request.</description>
    <inlineHelpText>Type of request</inlineHelpText>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ads and Promo - Activate</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Deactivate</fullName>
            </value>
            <value>
                <fullName>Auto-Activations</fullName>
            </value>
            <value>
                <fullName>Business/store mapping update</fullName>
            </value>
            <value>
                <fullName>Caviar - Cross Listing</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Invoicing group/NetSuite setup/update</fullName>
            </value>
            <value>
                <fullName>Menu Updates</fullName>
            </value>
            <value>
                <fullName>Metro Based Promo</fullName>
            </value>
            <value>
                <fullName>Net-new business</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partnership creation/update</fullName>
            </value>
            <value>
                <fullName>Portal access</fullName>
            </value>
            <value>
                <fullName>Rate Change</fullName>
            </value>
            <value>
                <fullName>SaaS Fee Setup</fullName>
            </value>
            <value>
                <fullName>Self Delivery</fullName>
            </value>
            <value>
                <fullName>Sponsored Listing</fullName>
            </value>
            <value>
                <fullName>COO Same Store</fullName>
            </value>
            <value>
                <fullName>Withholding</fullName>
            </value>
            <value>
                <fullName>Net-New</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Additional store creation</fullName>
                <isActive>false</isActive>
                <label>Additional store creation</label>
            </value>
            <value>
                <fullName>Marketing Free Credit</fullName>
                <isActive>false</isActive>
                <label>Marketing Free Credit</label>
            </value>
            <value>
                <fullName>Partnership update</fullName>
                <isActive>false</isActive>
                <label>Partnership update</label>
            </value>
            <value>
                <fullName>Return and Replacement</fullName>
                <isActive>false</isActive>
                <label>Return and Replacement</label>
            </value>
            <value>
                <fullName>Store Expansion</fullName>
                <isActive>false</isActive>
                <label>Store Expansion</label>
            </value>
            <value>
                <fullName>Virtual Kitchen</fullName>
                <isActive>false</isActive>
                <label>Virtual Kitchen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Withholding_with_Auto_Activations__c.field-meta.xml
<CustomField>
    <fullName>Withholding_with_Auto_Activations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-10519: It indicates whether Work Order is a withholding with auto-activations i.e. the associated Contract has &quot;Payment Method&quot; as &apos;Withholding&apos; and &quot;Drive Auto-Activation Supported&quot; as &apos;Yes&apos;.</description>
    <inlineHelpText>True when the contract is set to Drive Auto-Activation Supported and Payment Method is &quot;Withholding&quot;</inlineHelpText>
    <label>Withholding with Auto-Activations?</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/services/WorkOrderValidationsServiceImpl.cls
/**
 * @author Deloitte
 * @date 07/12/2022
 * @description Service implementation class for WorkOrder's
 * store readiness validations related logic.
 */
@SuppressWarnings('PMD.CyclomaticComplexity')
public inherited sharing class WorkOrderValidationsServiceImpl implements IWorkOrderValidationsService, IHandleStoreReadinessValidations {
    private enum MethodTypes {
        ACTIVATECENTRALLY,
        ACTIVATECENTRALLYFORMARKETPLACEANDCOO,
        BUSINESSID,
        CONTRACTFORMARKETPLACE,
        GOOGLESHEETURL,
        MENUTOBECOMPLETEDBY,
        NULLVALUES,
        NUMBEROFSTORES,
        OPPORTUNITYSTAGE,
        ORDERPROTOCOL,
        PDOAONMARKETPLACEANDCOO,
        PROPOSEDDATEOFACTIVATION,
        PROPOSEDDATEOFMENU,
        PROPOSEDDATEOFTABLET,
        PROPOSEDDATEOFTABLETINPAST,
        MPBZIDFORDRIVEWITHHOLDING
    }
    private static final Map<String, MethodTypes> METHODNAMETOMETHODTYPES = new Map<String, MethodTypes>{
        'validateActivateCentrally' => MethodTypes.ACTIVATECENTRALLY,
        'validateActivateCentrallyOnMarketplaceAndCOO' => MethodTypes.ACTIVATECENTRALLYFORMARKETPLACEANDCOO,
        'validateContractOnMarketplace' => MethodTypes.CONTRACTFORMARKETPLACE,
        'validateGoogleSheetURL' => MethodTypes.GOOGLESHEETURL,
        'validateMenuToBeCompletedBy' => MethodTypes.MENUTOBECOMPLETEDBY,
        'validateNullFieldValues' => MethodTypes.NULLVALUES,
        'validateNumberOfStores' => MethodTypes.NUMBEROFSTORES,
        'validateOpportunityStage' => MethodTypes.OPPORTUNITYSTAGE,
        'validateOrderProtocol' => MethodTypes.ORDERPROTOCOL,
        'validatePDOA' => MethodTypes.PROPOSEDDATEOFACTIVATION,
        'validatePDOAOnWeekend' => MethodTypes.PROPOSEDDATEOFACTIVATION,
        'validateProposedDateOfMenu' => MethodTypes.PROPOSEDDATEOFMENU,
        'validateProposedDateOfTablet' => MethodTypes.PROPOSEDDATEOFTABLET,
        'validateProposedDateOfTabletInPast' => MethodTypes.PROPOSEDDATEOFTABLETINPAST,
        'validatePDOAOnMarketplaceAndCOO' => MethodTypes.PDOAONMARKETPLACEANDCOO,
        'validateMPBZIdOnDriveWithholding' => MethodTypes.MPBZIDFORDRIVEWITHHOLDING,
        'validateBusinessId' => MethodTypes.BUSINESSID
    };
    private static final String ACTIVATE_CENTRALLY_NO = 'No';
    private static final String AUTO_ACTIVATIONS_SUB_TYPE = 'Auto-Activations';
    private static final String OPPORTUNITY_STAGE_CLOSED_WON = 'Closed Won';
    private static final String PDOA_DAYS_IN_FUTURE_LIMIT_STATIC_CONFIG = 'PDOA_DAYS_IN_FUTURE_LIMIT';
    private static final String WORKORDER_ACTIVATED_CENTRALLY_NO = 'No';
    private static final String WORKORDER_DELAY_TABLET_SHIPMENT_YES = 'Yes';
    private static final String WORKORDER_MENU_TO_BE_COMPLETED_BY_ACCOUNT_OWNER = 'Account Owner';
    private static final String WORKORDER_SUB_TYPE_WITHHOLDING = 'Withholding';
    private static final String WORKORDER_TYPE_COO = 'COO';
    private static final String WORKORDER_TYPE_MARKETPLACE = 'Marketplace';
    private static final String LOG_SERVICE_WORK_ORDER = 'Work Order Service';
    private static final String LOG_DOMAIN_PROVISIONING = 'Provisioning';
    private static final String SEPARATOR = System.Label.Separator;
    private static final String PROVISIONING_PROCESS_AUTOMATIC = 'Automatic';
    private static final String SEGMENT_SMB = 'SMB';
    private List<WorkOrder> childWorkOrders;
    private Map<Id, WorkOrder> parentWorkOrders;
    private List<Readiness_Check_Failure__c> readinessValidationFailures;
    private Map<String, Map<String, Set<String>>> readinessValidationToTypeToSubTypes;
    private List<Readiness_Check_Failure__c> existingReadinessValidationFailuresRecords; //* @jira LEM-13963
    private String readinessObjectName; //* @jira LEM-13963
    private static final String CLASS_NAME = 'WorkOrderValidationsServiceImpl'; //* @jira LEM-13963

    /**
     * @description Default Constructor to initialize class variables
     */
    public WorkOrderValidationsServiceImpl() {
        this.childWorkOrders = new List<WorkOrder>();
        this.parentWorkOrders = new Map<Id, WorkOrder>();
        this.readinessValidationFailures = new List<Readiness_Check_Failure__c>();
        this.readinessValidationToTypeToSubTypes = new Map<String, Map<String, Set<String>>>();
        this.existingReadinessValidationFailuresRecords = new List<Readiness_Check_Failure__c>(); //* @jira LEM-13963
    }

    /**
     * @description It performs readiness validations on the passed WorkOrders
     * according to the rules configured in the custom metadata.
     * @JIRA# LEM-1684 @jira LEM-13963
     * @param childWorkOrders
     * @param parentWorkOrders
     * @param storeReadinessValidations - custom metadata records
     * @param existingReadinessCheckFailures
     * @param objectName
     */
    public void validate(
        List<WorkOrder> childWorkOrders,
        List<WorkOrder> parentWorkOrders,
        List<Store_Readiness_Validation_Rule__mdt> storeReadinessValidations,
        List<Readiness_Check_Failure__c> existingReadinessCheckFailures,
        String objectName
    ) {
        this.childWorkOrders.addAll(childWorkOrders);
        this.parentWorkOrders = new Map<Id, WorkOrder>(parentWorkOrders);
        this.readinessValidationToTypeToSubTypes = ReadinessValidationRulesService.collectReadinessValidationRuleMappings(
            storeReadinessValidations
        );
        this.existingReadinessValidationFailuresRecords.addAll(existingReadinessCheckFailures); //* @jira LEM-13963
        this.readinessObjectName = objectName; //* @jira LEM-13963
        runValidations(storeReadinessValidations);
        publishReadinessCheckFailures();
    }

    /**
     * @description It checks whether the passed field value is null on the passed sObjectInstance.
     * @JIRA# LEM-2644
     * @param sObjectInstance
     * @param fieldName
     * @return Boolean
     */
    private Boolean isFieldValueNull(SObject sObjectInstance, String fieldName) {
        return sObjectInstance.get(fieldName) == null;
    }

    /**
     * @description It validates that a valid Google Sheet URL is populated by checking
     * if the URL contains 'https://docs.google.com/spreadsheets/'.
     * @JIRA# LEM-11502
     * @param googleSheetURL
     * @return Boolean
     */
    private Boolean isGoogleSheetURLInvalid(String googleSheetURL) {
        return !googleSheetURL.contains(System.Label.Google_Sheet_URL);
    }

    /**
     * @description It validates that the passed Work Order ineligible to validate Google Sheet URL
     * by checking the following conditions:
     * 1. Work Order Sub-Type is Auto-Activations OR
     * 2. Work Order is Withholding with Auto-Activations OR
     * 3. Work Order is created by Process Automation User
     * @JIRA# LEM-11502
     * @param workOrder
     * @return Boolean
     */
    private Boolean isWorkOrderIneligibleToValidateGoogleSheetURL(WorkOrder workOrder) {
        return ((workOrder.Sub_Type__c == AUTO_ACTIVATIONS_SUB_TYPE ||
        (workOrder.Sub_Type__c == WORKORDER_SUB_TYPE_WITHHOLDING &&
        workOrder.Withholding_with_Auto_Activations__c)) ||
        workOrder.CreatedBy.Name.startsWithIgnoreCase(
            System.Label.Automated_Process_User_Full_Name
        ));
    }

    /**
     * @description It run store readiness validations on parent Work Orders.
     * @JIRA# LEM-1684
     * @param storeReadinessValidations - custom metadata records
     */
    private void runValidations(
        List<Store_Readiness_Validation_Rule__mdt> storeReadinessValidations
    ) {
        for (
            Store_Readiness_Validation_Rule__mdt eachStoreReadinessValidationRule : storeReadinessValidations
        ) {
            switch on
                METHODNAMETOMETHODTYPES.get(
                    eachStoreReadinessValidationRule.Service_Method_Name__c
                ) {
                when ACTIVATECENTRALLYFORMARKETPLACEANDCOO {
                    validateActivateCentrallyOnMarketplaceAndCOO(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when ACTIVATECENTRALLY {
                    validateActivateCentrally(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when CONTRACTFORMARKETPLACE {
                    validateContractOnMarketplace(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values(),
                        childWorkOrders
                    );
                }
                when GOOGLESHEETURL {
                    validateGoogleSheetURL(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when MENUTOBECOMPLETEDBY {
                    validateMenuToBeCompletedBy(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when NULLVALUES {
                    validateNullFieldValues(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when OPPORTUNITYSTAGE {
                    validateOpportunityStage(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when ORDERPROTOCOL {
                    validateOrderProtocol(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when PDOAONMARKETPLACEANDCOO {
                    validatePDOAOnMarketplaceAndCOO(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when PROPOSEDDATEOFACTIVATION {
                    validateProposedDateOfActivation(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when PROPOSEDDATEOFMENU {
                    validateProposedDateOfMenu(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when PROPOSEDDATEOFTABLET {
                    validateProposedDateOfTablet(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when PROPOSEDDATEOFTABLETINPAST {
                    validateProposedDateOfTabletInPast(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when MPBZIDFORDRIVEWITHHOLDING {
                    validateMPBZIdOnDriveWithholding(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values()
                    );
                }
                when BUSINESSID {
                    validateBusinessId(eachStoreReadinessValidationRule, parentWorkOrders.values());
                }
                when NUMBEROFSTORES {
                    validateNumberOfStores(
                        eachStoreReadinessValidationRule,
                        parentWorkOrders.values(),
                        childWorkOrders
                    );
                }
            }
        }
    }

    /**
     * @description It creates 'Readiness Check Failures' records based on the passed Work Order
     * and Store Readiness Validation Rule.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrder
     */
    private void logReadinessCheckFailure(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        WorkOrder workOrder
    ) {
        readinessValidationFailures.add(
            new Readiness_Check_Failure__c(
                Account_Name__c = workOrder.AccountId,
                Child_Work_Order__c = workOrder.Id,
                Error_Message__c = storeReadinessValidationRule.Error_Message__c,
                Field_Name__c = storeReadinessValidationRule.Field_Label__c,
                Object_Name__c = storeReadinessValidationRule.Object_Label__c,
                Parent_Work_Order__c = workOrder.ParentWorkOrderId == null
                    ? workOrder.Id
                    : workOrder.ParentWorkOrderId
            )
        );
    }

    /**
     * @description It commits 'Readiness Check Failures' records in the database.
     * @JIRA# LEM-1684 // @jira LEM-13963
     */
    private void publishReadinessCheckFailures() {
        StoreReadinessModificationService.processReadinessCheckFailures(
            existingReadinessValidationFailuresRecords,
            readinessValidationFailures,
            readinessObjectName,
            CLASS_NAME
        );
    }

    /**
     * @description It validates that 'Activate Centrally' should be 'No'
     * when 'Menu to be completed by' is 'Account Owner'.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateActivateCentrally(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                eachWorkOrder.Menu_to_be_Completed_By__c ==
                WORKORDER_MENU_TO_BE_COMPLETED_BY_ACCOUNT_OWNER &&
                eachWorkOrder.Activated_Centrally_AC__c != WORKORDER_ACTIVATED_CENTRALLY_NO
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Actual Number Of Stores' should not be
     * greater than 'Number of Stores on Quote'.
     * @JIRA# LEM-18591
     * @param storeReadinessValidationRule
     * @param parentWorkOrders
     * @param childWorkOrders
     */
    private void validateNumberOfStores(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> parentWorkOrders,
        List<WorkOrder> childWorkOrders
    ) {
        Set<Id> storeAccountIds = new Set<Id>();
        for (WorkOrder eachWorkOrder : childWorkOrders) {
            if (eachWorkOrder.AccountId != null) {
                storeAccountIds.add(eachWorkOrder.AccountId);
            }
        }
        for (WorkOrder eachWorkOrder : parentWorkOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                !storeAccountIds.isEmpty() &&
                (storeAccountIds.size() > eachWorkOrder.Number_of_Stores_on_Quote__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Activate Centrally' is required
     * when WorkOrder Type is 'Marketplace' or 'COO'.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateActivateCentrallyOnMarketplaceAndCOO(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) && isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that Contract is populated
     * when Workorder type is 'Marketplace'.
     * @JIRA# LEM-7999
     * @param storeReadinessValidationRule
     * @param workOrders
     * @param childWorkOrders
     */
    private void validateContractOnMarketplace(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders,
        List<WorkOrder> childWorkOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                eachWorkOrder.Type__c == WORKORDER_TYPE_MARKETPLACE &&
                isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
        for (WorkOrder eachWorkOrder : childWorkOrders) {
            if (ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                eachWorkOrder.Type__c == WORKORDER_TYPE_MARKETPLACE &&
                isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that a valid Google Sheet URL is populated
     * on the passed Work Orders.
     * @JIRA# LEM-11502
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateGoogleSheetURL(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                !isWorkOrderIneligibleToValidateGoogleSheetURL(eachWorkOrder) &&
                (isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c) ||
                isGoogleSheetURLInvalid(
                    eachWorkOrder.get(storeReadinessValidationRule.Field_Name__c).toString()
                ))
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Menu to be completed by' is required
     * when WorkOrder Type is 'Marketplace'.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateMenuToBeCompletedBy(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) && isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It is used to perform validation to check whether the field configured
     * in the passed custom metadata is null on the passed Work Orders.
     * @JIRA# LEM-2858
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateNullFieldValues(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) && isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that Opportunity Stage is 'Closed/Won'
     * when Work Order type is 'Marketplace'/'Storefront'/'Drive'/'COO' or
     * 'Post-Sales' with sub-type as 'Rate Change'.
     * @JIRA# LEM-10031
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateOpportunityStage(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                String.isNotBlank(eachWorkOrder.Opportunity__c) &&
                eachWorkOrder.Opportunity__r.StageName != OPPORTUNITY_STAGE_CLOSED_WON
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that Order protocol is populated
     * when Work Order type is 'Marketplace' or 'COO'.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateOrderProtocol(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) && isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Proposed Date of Activation' is required
     * when WorkOrder Type is 'Marketplace' or 'COO'.
     * @JIRA# LEM-2644
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validatePDOAOnMarketplaceAndCOO(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) && isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Proposed Date of Activation' does not occur in the past and
     * not less than configured days in the future.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateProposedDateOfActivation(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRuleToValidate;
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                !ReadinessValidationRulesService.isBypassedBySegmentType(
                    storeReadinessValidationRule.DeveloperName,
                    eachWorkOrder
                )
            ){
            storeReadinessValidationRuleToValidate = ReadinessValidationRulesService.getProposedDateOfActivationFailedReadinessCheck(
                readinessValidationToTypeToSubTypes,
                storeReadinessValidationRule,
                eachWorkOrder
            );
            if (storeReadinessValidationRuleToValidate != null) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }
    }

    /**
     * @description It validates that 'Proposed Date of Menu' does not occur in the past.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateProposedDateOfMenu(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (eachWorkOrder.Proposed_Date_of_Menu__c < System.today()) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Proposed Date of Tablet' is populated
     * when HasTabletWorkPlan__c is enabled.
     * @JIRA# LEM-1684
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateProposedDateOfTablet(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                eachWorkOrder.Has_Any_Store_Tablet_Shipment_Delayed__c &&
                isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It validates that 'Proposed Date of Tablet' does not occur in the past.
     * @JIRA# LEM-2625
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateProposedDateOfTabletInPast(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                eachWorkOrder.Proposed_Date_of_Tablet__c != null &&
                eachWorkOrder.Proposed_Date_of_Tablet__c < System.today()
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It is used to perform validation on MP_Bz_Id__c check whether the field configured
     * in the passed custom metadata is null on Contract or Opportunity associated to the passed Work Orders.
     * @JIRA# LEM-16290
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateMPBZIdOnDriveWithholding(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRuleToValidate;
        for (WorkOrder eachWorkOrder : workOrders) {
            storeReadinessValidationRuleToValidate = ReadinessValidationRulesService.getMpBzIdNullReadinessCheck(
                readinessValidationToTypeToSubTypes,
                storeReadinessValidationRule,
                eachWorkOrder
            );

            if (storeReadinessValidationRuleToValidate != null) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }
    /**
     * @description It validates that 'Business Id' must match with External Id populated
     * on business reference when WorkOrder Type is 'Marketplace' or 'COO'.
     * @JIRA# LEM-15213
     * @param storeReadinessValidationRule
     * @param workOrders
     */
    private void validateBusinessId(
        Store_Readiness_Validation_Rule__mdt storeReadinessValidationRule,
        List<WorkOrder> workOrders
    ) {
        Set<String> businessIdsToQuery = new Set<String>();
        List<WorkOrder> workOrdersToValidate = new List<WorkOrder>();
        Set<String> businessReferenceExternalIdsToValidate = new Set<String>();
        for (WorkOrder eachWorkOrder : workOrders) {
            if (
                ReadinessValidationRulesService.hasTypeSubTypeMatchingWithWorkOrder(
                    readinessValidationToTypeToSubTypes,
                    storeReadinessValidationRule,
                    eachWorkOrder
                ) &&
                !isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c) &&
                isWorkOrderSegmentSMB(eachWorkOrder.Segment__c) &&
                eachWorkOrder.Business_to_Store_Assignment__c == PROVISIONING_PROCESS_AUTOMATIC
            ) {
                businessIdsToQuery.add(eachWorkOrder.Business_Id__c);
                workOrdersToValidate.add(eachWorkOrder);
            }
        }
        for (
            Business_Reference__c eachBusinessReference : BusinessReferencesSelector.newInstance()
                .selectMDSBusinessReferencesWithSuccessIntegrationStatusByBusinessIds(
                    businessIdsToQuery
                )
        ) {
            businessReferenceExternalIdsToValidate.add(eachBusinessReference.External_Id__c);
        }

        for (WorkOrder eachWorkOrder : workOrdersToValidate) {
            if (
                !isFieldValueNull(eachWorkOrder, storeReadinessValidationRule.Field_Name__c) &&
                !businessReferenceExternalIdsToValidate.contains(eachWorkOrder.Business_Id__c)
            ) {
                logReadinessCheckFailure(storeReadinessValidationRule, eachWorkOrder);
            }
        }
    }

    /**
     * @description It is used to validate whether the passed Segment value is 'SMB'.
     * @JIRA# LEM-15213
     * @param segmentValue
     * @return Boolean
     */
    private Boolean isWorkOrderSegmentSMB(String segmentValue) {
        return segmentValue == SEGMENT_SMB;
    }
}