sfdx-source/force-app/main/default/objects/Account/fields/Mx_Tag_Associations_Concatenated__c.field-meta.xml
<CustomField>
    <fullName>Mx_Tag_Associations_Concatenated__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-25211: It stores the concatenated Mx Tag Names related to this Account.</description>
    <inlineHelpText>Includes all active Mx Tag Associations against this particular account.</inlineHelpText>
    <label>Mx Tag Associations - Concatenated</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/Mx_Tag_Association__c.object-meta.xml
<CustomObject>
    <description>LEM-14102: It is a junction object between Mx Tag and other objects.</description>
    <label>Mx Tag Association</label>
    <nameField>
        <displayFormat>[TAG-{0000}]</displayFormat>
        <label>Mx Tag Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Tags Association</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14102: It associates Mx Tag Association records with Account.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mx Tags Association</relationshipLabel>
    <relationshipName>Mx_Tags_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>LEM-14103: It stores description of the Mx Tag.</description>
    <formula>MxTag__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14102: It associates Mx Tag Association records with Lead.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Mx Tags Association</relationshipLabel>
    <relationshipName>Mx_Tags_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/MxTag__c.field-meta.xml
<CustomField>
    <fullName>MxTag__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14102, LEM-16913: It associates Mx Tag Association records with Mx Tag.</description>
    <label>Mx Tag</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MxTag__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MxTag__c</referenceTo>
    <relationshipLabel>Mx Tags Association</relationshipLabel>
    <relationshipName>Mx_Tags_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/MxTagAssociation_Status__c.field-meta.xml
<CustomField>
    <fullName>MxTagAssociation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14987: It is used to represent the status of the the Mx Tag Association.</description>
    <inlineHelpText>Indicates the status of the the Mx Tag Association.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/MxTagName__c.field-meta.xml
<CustomField>
    <fullName>MxTagName__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14105: It stores the name of the associated Mx Tag.</description>
    <formula>MxTag__r.Name</formula>
    <label>Mx Tag Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14102: It displays the Name of the Mx Tag as a hyperlink.</description>
    <formula>HYPERLINK(LEFT($Api.Enterprise_Server_URL_540, FIND($CustomMetadata.Static_Configurations__mdt.Enterprise_Server_URL_Search_Key.Configuration_Value__c, $Api.Enterprise_Server_URL_540, 0) - 1) + MxTag__c, MxTag__r.Name)</formula>
    <label>Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>LEM-14102: It associates Mx Tag Association records with Opportunity.</description>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Mx Tags Association</relationshipLabel>
    <relationshipName>Mx_Tags_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/Opportunity_Account__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-25211: It stores AccountId associated to the Opportunity.</description>
    <formula>Opportunity__r.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
    <label>Opportuinty Account</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MxTag__c/MxTag__c.object-meta.xml
<CustomObject>
    <description>LEM-14102,14103: It store unique data specific to Mx.</description>
    <label>Mx Tag</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mx Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/MxTag__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>LEM-14103: It stores description of the Mx Tag.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>Description of the Mx Tag</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MxTag__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14103: It stores name of the Mx Tag.</description>
    <inlineHelpText>Name of the Mx Tag</inlineHelpText>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>LEM-4987: It is used to maintain information regarding the Opportunity and its current status.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Mx_Tag_Associations_Concatenated__c.field-meta.xml
<CustomField>
    <fullName>Mx_Tag_Associations_Concatenated__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-18923: It stores the concatenated Mx Tag Names.</description>
    <label>Mx Tag Associations - Concatenated</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/MxTagAssociationsSelector.cls
/**
 * @author Deloitte
 * @date 22/02/2022
 * @description Selector Class for Mx_Tag Association Object
 * Suppressed warnings since selector class contains multiple public methods.
 */
@SuppressWarnings('PMD.ExcessivePublicCount')
public inherited sharing class MxTagAssociationsSelector extends fflib_SObjectSelector implements IMxTagAssociationsSelector {
    private static final String ACTIVE = 'Active';
    private static final String BUSINESS = System.Label.BusinessAccountRecordTypeName;
    private static final String MX_TAG_BATCH_UPDATE_CRITERIA = System.Label.MxTagAssociationQueryConditionForBatch;
    private static final String STORE = System.Label.StoreAccountRecordTypeName;
    private static final String TOP_MX_TAG = 'Top MX';
    /**
     * @description Default constructor for the class
     * @return IMxTagAssociationsSelector - interface of IMxTagAssociationsSelector.
     */
    public static IMxTagAssociationsSelector newInstance() {
        return (IMxTagAssociationsSelector) Application.Selector.newInstance(
            Mx_Tag_Association__c.SObjectType
        );
    }

    /**
     * @description override default getSObjectType method.
     * @return SObjectType - object type
     */
    public Schema.SObjectType getSObjectType() {
        return Mx_Tag_Association__c.SObjectType;
    }

    /**
     * @description This method is for getting the fields on Mx_Tag_Association__c.
     * @return List<Schema.SObjectField>- Mx_Tag_Association__c fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Mx_Tag_Association__c.Description__c,
            Mx_Tag_Association__c.Account__c,
            Mx_Tag_Association__c.Id,
            Mx_Tag_Association__c.Opportunity__c,
            Mx_Tag_Association__c.MxTag__c,
            Mx_Tag_Association__c.Lead__c,
            Mx_Tag_Association__c.Name,
            Mx_Tag_Association__c.MxTagAssociation_Status__c,
            Mx_Tag_Association__c.MxTagName__c
        };
    }

    /**
     * @description  It is used to get Mx_Tag Associations by Business Account Ids.
     * @param businessAccountIds
     * @return List<Mx_Tag_Association__c>
     */
    public List<Mx_Tag_Association__c> selectByBusinessAccountIds(Set<Id> businessAccountIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'Account__c IN :businessAccountIds AND MxTagAssociation_Status__c =: ACTIVE'
            );
        return (List<Mx_Tag_Association__c>) Database.query(query.toSOQL());
    }

    /**
     * @description  It is used to get Mx_Tag Associations by Opportunity Ids.
     * @param opportunityIds
     * @return List<Mx_Tag_Association__c>
     */
    public List<Mx_Tag_Association__c> selectByOpportunityIds(Set<Id> opportunityIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Opportunity__c IN :opportunityIds');
        return (List<Mx_Tag_Association__c>) Database.query(query.toSOQL());
    }

    /**
     * @description It is used to get Mx Tag Associations by business Account Ids where Top Mx tag is present.
     * @param businessAccountIds
     * @return List<Mx_Tag_Association__c>
     */
    public List<Mx_Tag_Association__c> selectTopMXTagByBusinessAccountIds(
        Set<Id> businessAccountIds
    ) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Account__c IN :businessAccountIds AND MxTag__r.name__c = :TOP_MX_TAG');
        return (List<Mx_Tag_Association__c>) Database.query(query.toSOQL());
    }

    /**
     * @description It is used to get active Mx Tag Associations associated with Business Account
     * which are created/updated within last 24 hours.
     * @return List<Mx_Tag_Association__c >
     */
    public Database.QueryLocator selectActiveMxTagAssociationsCreatedUpdatedInLast24Hours() {
        fflib_QueryFactory query = newQueryFactory(false);
        query.selectField('Account__c');
        query.selectField('Account__r.Mx_Tag_Associations_Concatenated__c');
        query.selectField('Account__r.RecordType.Name');
        query.selectField('CreatedDate');
        query.selectField('LastModifiedDate');
        query.selectField('MxTagName__c');
        query.selectField('Opportunity_Account__c');
        query.setCondition(MX_TAG_BATCH_UPDATE_CRITERIA);
        return Database.getQueryLocator(query.toSOQL());
    }
}