sfdx-source/force-app/main/default/objects/Account/fields/NDA_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>NDA_Expiration_Date__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM:1039: Captures the expiry date of the Agreement with the Merchant</description>
    <inlineHelpText>Indicates the date the NDA expires.</inlineHelpText>
    <label>NDA Expiration Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/NDA_Status__c.field-meta.xml
<CustomField>
    <fullName>NDA_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1039: NDA Status to track the current status of the Merchant Agreement</description>
    <inlineHelpText>Indicates the current status of NDA.</inlineHelpText>
    <label>NDA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/batchables/NdaExpirationBatchTest.cls
/**
 * @author Deloitte
 * @description This is the test class for NdaExpirationBatch class
 * @date 27/04/2022
 */
@isTest
private class NdaExpirationBatchTest {
    @IsTest
    static void testWhenNDAExpiredAccountsExistThenUpdateNDAStatus() {
        //ARRANGE
        Account account1 = (Account) new Fake(Account.class)
            .setField(Account.Name, 'Test Account 1 - Batch')
            .setField(Account.NDA_Expiration_Date__c, Date.today() - 3)
            .setField(Account.NDA_Status__c, 'Active')
            .setFakeId()
            .toSObject();

        List<Account> accountRecords = new List<Account>{ account1 };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IAccountsSelector accountsSelectorMock = (IAccountsSelector) mocks.mock(
            IAccountsSelector.class
        );
        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        mocks.startStubbing();
        mocks.when(accountsSelectorMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(accountsSelectorMock.selectAccountsWithExpiredNda()).thenReturn(null);
        mocks.stopStubbing();

        Application.Selector.setMock(accountsSelectorMock);
        Application.UNITOFWORK.setMock(mockUnitOfWork);

        //ACT
        NdaExpirationBatch batch = new NdaExpirationBatch();
        batch.start(null);
        batch.execute(null, accountRecords);
        batch.finish(null);

        //ASSERT
        ((IAccountsSelector) mocks.verify(accountsSelectorMock, 1)).selectAccountsWithExpiredNda();
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUnitOfWork, 1)).commitWork();
        System.assertEquals(
            'Expired',
            accountRecords[0].NDA_Status__c,
            'NDA Status is not updated as expected'
        );
    }
}