sfdx-source/force-app/main/default/objects/Account/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1048: Order protocol defined for the Mxs being onboarded</description>
    <inlineHelpText>Signifies the type of order protocol requested for the Mx store</inlineHelpText>
    <label>Order Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 Tablets (Caviar and DoorDash Own)</fullName>
            </value>
            <value>
                <fullName>Android Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>POS (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (Caviar POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and 2 Tablets (DoorDash POS, DoorDash and Caviar Tablets)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet (Merchant Owns)</fullName>
            </value>
            <value>
                <fullName>POS and Tablet Return Label</fullName>
            </value>
            <value>
                <fullName>Tablet (Caviar Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet (DoorDash Owns)</fullName>
            </value>
            <value>
                <fullName>Tablet and Printer (DoorDash Owns)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Indicates the type of request
BZAP-19603</description>
    <inlineHelpText>Select &apos;POS Integration Request&apos; if the Mx is an existing activated Partner and would like to transition to POS Order Protocol</inlineHelpText>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS Integration Request</fullName>
            </value>
            <value>
                <fullName>POS Test Store for New Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/Staging_Bulk_Upload_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-15978: Stores Bulk Equipment/Photoshoot references and their status.</description>
    <label>Staging Bulk Upload Reference</label>
    <nameField>
        <displayFormat>BL-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Bulk Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Bulk Upload References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>LEM-15978: Stores dependent picklist values based on the type.</description>
    <inlineHelpText>Picklist values populate based on the type.</inlineHelpText>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Net-New</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-15978: Stores file upload status - Success, In Progress Or Failed.</description>
    <inlineHelpText>It stores file upload status - Success, In Progress Or Failed.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Reference__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-15978: Stores the controlling picklist value for request type field.</description>
    <inlineHelpText>Controlling picklist for request type field.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Marketing Kit</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/Staging_Bulk_Upload_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-15978: Stores CSV file records. System doesn&apos;t allow partial load in case of any error.</description>
    <label>Staging Bulk Upload Request</label>
    <nameField>
        <displayFormat>SBR-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Staging Bulk Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Bulk Upload Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Defective_Printer_IMEI__c.field-meta.xml
<CustomField>
    <fullName>Defective_Printer_IMEI__c</fullName>
    <description>LEM-15978: Stores Defective Printer IMEI Number For Return/Replacement Request Types.</description>
    <label>Defective Printer IMEI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Order_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Order_Protocol__c</fullName>
    <description>LEM-15978: Stores Order Protocol for Tablet &amp; Marketing-Kit Types.</description>
    <label>Order Protocol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Product_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Product_Bundle__c</fullName>
    <description>LEM-15978: Stores Product Bundle For Net-New/Replacement/Marketing-Kit Request Types.</description>
    <label>Product Bundle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>LEM-15978: Formula for Request Type From The Related Reference (Parent) Record.</description>
    <formula>TEXT( Staging_Upload_Ref__r.Request_Type__c )</formula>
    <label>Request Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Staging_Upload_Ref__c.field-meta.xml
<CustomField>
    <fullName>Staging_Upload_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15978: Stores Staging Bulk Reference (Parent) Record Id.</description>
    <label>Staging Upload Ref</label>
    <referenceTo>Staging_Bulk_Upload_Reference__c</referenceTo>
    <relationshipLabel>Staging Bulk Upload Requests</relationshipLabel>
    <relationshipName>Staging_Bulk_Upload_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-15978: Stores Status Of the Request.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Staging_Bulk_Upload_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-15978: Formula for Type From The Related Reference (Parent) Record.</description>
    <formula>TEXT(Staging_Upload_Ref__r.Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/batchables/BulkOrderCreationBatchTest.cls
/**
 * @author Deloitte
 * @date 08/08/2024
 * @description Test class for BulkOrderCreationBatch
 */
@isTest
private class BulkOrderCreationBatchTest {
    private static final String TYPE_TABLET = 'Tablet';
    private static final String SUB_TYPE_NET_NEW = 'Net-New';
    private static final String STATUS_SUCCESS = 'Success';
    private static final String WORK_ORDER_PRODUCT_BUNDLE = 'US Tablet';
    private static final String DEFECTIVE_PRINTER_IMEI = 'ABC00000';
    /**
     * @description It is to test that parent and child work orders are not created when
     * the batch is executed from Trigger handler
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenPlatformEventReceivedThenDoNotCreateBulkParentAndChilOrders() {
        Id stagingBulkReferenceId = Fake.generateId(Staging_Bulk_Upload_Reference__c.class);
        Staging_Bulk_Upload_Reference__c stagingReferenceRec = (Staging_Bulk_Upload_Reference__c) new Fake(Staging_Bulk_Upload_Reference__c.class)
            .setField(Staging_Bulk_Upload_Reference__c.Id, stagingBulkReferenceId)
            .setField(Staging_Bulk_Upload_Reference__c.Type__c, TYPE_TABLET)
            .setField(Staging_Bulk_Upload_Reference__c.Request_Type__c, SUB_TYPE_NET_NEW)
            .setField(Staging_Bulk_Upload_Reference__c.Status__c, STATUS_SUCCESS)
            .toSObject();

        Id stagingBulkRequestId = Fake.generateId(Staging_Bulk_Upload_Request__c.class);
        Staging_Bulk_Upload_Request__c stagingRequestRec = (Staging_Bulk_Upload_Request__c) new Fake(Staging_Bulk_Upload_Request__c.class)
            .setField(Staging_Bulk_Upload_Request__c.Staging_Upload_Ref__c, stagingReferenceRec.Id)
            .setField(Staging_Bulk_Upload_Request__c.Product_Bundle__c, WORK_ORDER_PRODUCT_BUNDLE)
            .setField(Staging_Bulk_Upload_Request__c.Defective_Printer_IMEI__c, DEFECTIVE_PRINTER_IMEI)
            .setField(Staging_Bulk_Upload_Request__c.Order_Protocol__c, TYPE_TABLET)
            .setField(Staging_Bulk_Upload_Request__c.Id, stagingBulkRequestId)
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IStagingBulkUploadRequestSelector bulkRequestSelectorMock = (IStagingBulkUploadRequestSelector) mocks.mock(IStagingBulkUploadRequestSelector.class);
        IBulkOrdersCreationService serviceMock = (IBulkOrdersCreationService) mocks.mock(
            IBulkOrdersCreationService.class
        );
        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        mocks.startStubbing();
        mocks.when(bulkRequestSelectorMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(bulkRequestSelectorMock.selectStagingRequestsByReferenceIds(new Set<String>{stagingBulkReferenceId})).thenReturn(stagingRequestRec);
        mocks.stopStubbing();

        Application.SERVICE.setMock(IBulkOrdersCreationService.class, serviceMock);
        Application.UNITOFWORK.setMock(mockUnitOfWork);

        BulkOrderCreationBatch batch = new BulkOrderCreationBatch(new Set<String>{stagingBulkReferenceId});
        batch.start(null);
        batch.execute(null, null);
        batch.finish(null);

        ((IBulkOrdersCreationService) mocks.verify(serviceMock, 0))
            .createBulkParentAndChilOrders(new List<Staging_Bulk_Upload_Request__c>{ stagingRequestRec });
    }

    /**
     * @description It is to test the creation of parent and child work orders when
     * the batch is executed from Trigger handler
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenPlatformEventReceivedThenCreateBulkParentAndChilOrders() {
        Id stagingBulkReferenceId = Fake.generateId(Staging_Bulk_Upload_Reference__c.class);
        Staging_Bulk_Upload_Reference__c stagingReferenceRec = (Staging_Bulk_Upload_Reference__c) new Fake(Staging_Bulk_Upload_Reference__c.class)
            .setField(Staging_Bulk_Upload_Reference__c.Id, stagingBulkReferenceId)
            .setField(Staging_Bulk_Upload_Reference__c.Type__c, TYPE_TABLET)
            .setField(Staging_Bulk_Upload_Reference__c.Request_Type__c, SUB_TYPE_NET_NEW)
            .setField(Staging_Bulk_Upload_Reference__c.Status__c, STATUS_SUCCESS)
            .toSObject();

        Id stagingBulkRequestId = Fake.generateId(Staging_Bulk_Upload_Request__c.class);
        Staging_Bulk_Upload_Request__c stagingRequestRec = (Staging_Bulk_Upload_Request__c) new Fake(Staging_Bulk_Upload_Request__c.class)
            .setField(Staging_Bulk_Upload_Request__c.Staging_Upload_Ref__c, stagingReferenceRec.Id)
            .setField(Staging_Bulk_Upload_Request__c.Product_Bundle__c, WORK_ORDER_PRODUCT_BUNDLE)
            .setField(Staging_Bulk_Upload_Request__c.Defective_Printer_IMEI__c, DEFECTIVE_PRINTER_IMEI)
            .setField(Staging_Bulk_Upload_Request__c.Order_Protocol__c, TYPE_TABLET)
            .setField(Staging_Bulk_Upload_Request__c.Id, stagingBulkRequestId)
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IStagingBulkUploadRequestSelector bulkRequestSelectorMock = (IStagingBulkUploadRequestSelector) mocks.mock(IStagingBulkUploadRequestSelector.class);
        IBulkOrdersCreationService serviceMock = (IBulkOrdersCreationService) mocks.mock(
            IBulkOrdersCreationService.class
        );
        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        mocks.startStubbing();
        mocks.when(bulkRequestSelectorMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(bulkRequestSelectorMock.selectStagingRequestsByReferenceIds(new Set<String>{stagingBulkReferenceId})).thenReturn(stagingRequestRec);
        mocks.stopStubbing();

        Application.SERVICE.setMock(IBulkOrdersCreationService.class, serviceMock);
        Application.UNITOFWORK.setMock(mockUnitOfWork);

        BulkOrderCreationBatch batch = new BulkOrderCreationBatch(new Set<String>{stagingBulkReferenceId});
        batch.start(null);
        batch.execute(null, new List<Staging_Bulk_Upload_Request__c>{ stagingRequestRec });
        batch.finish(null);

        ((IBulkOrdersCreationService) mocks.verify(serviceMock, 1))
            .createBulkParentAndChilOrders(new List<Staging_Bulk_Upload_Request__c>{ stagingRequestRec });
    }
}