sfdx-source/force-app/main/default/objects/Account/fields/Proposed_Date_of_Activation__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Date_of_Activation__c</fullName>
    <description>LEM-658: Onboarding event proposed date of activation.</description>
    <inlineHelpText>Onboarding event proposed date of activation</inlineHelpText>
    <label>Proposed Date of Activation</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1046: This field is used to represent the type of agency.</description>
    <inlineHelpText>Represents the type of agency</inlineHelpText>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Full Service</fullName>
            </value>
            <value>
                <fullName>Creative</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <description>LEM -186</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Agreement</label>
    <referenceTo>Agreement__c</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Deactivation_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Date__c</fullName>
    <description>LEM-1014 - Set the Deactivation Date for the Agreement</description>
    <label>Deactivation Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-2353 Populate the Opportunity while creating the Franchise Agreements</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>LEM-1014 - Stamp the Start date of the Agreement</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Agreement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-186: Initial Setup of Agreement</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Agreement_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Static_Configurations__mdt/Static_Configurations__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1517: This custom metadata stores static configurations. For Example: URLs to MINT or Merchant Portal</description>
    <label>Static Configurations</label>
    <pluralLabel>Static Configurations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Static_Configurations__mdt/fields/Configuration_Value__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Value__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1517: This field holds the static configuration value.</description>
    <inlineHelpText>This field holds the static configuration value</inlineHelpText>
    <label>Configuration Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Contract linked to the onboarding event.</description>
    <inlineHelpText>Contract linked to the onboarding event</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Opportunity linked to the onboarding event.</description>
    <inlineHelpText>Opportunity linked to the onboarding event</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Proposed_Date_of_Activation__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Date_of_Activation__c</fullName>
    <description>LEM-813: Onboarding event proposed date of activation.</description>
    <inlineHelpText>Onboarding event proposed date of activation</inlineHelpText>
    <label>Proposed Date of Activation</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>LEM-1271: Type of request.</description>
    <inlineHelpText>Type of request</inlineHelpText>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ads and Promo - Activate</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Deactivate</fullName>
            </value>
            <value>
                <fullName>Auto-Activations</fullName>
            </value>
            <value>
                <fullName>Business/store mapping update</fullName>
            </value>
            <value>
                <fullName>Caviar - Cross Listing</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Invoicing group/NetSuite setup/update</fullName>
            </value>
            <value>
                <fullName>Menu Updates</fullName>
            </value>
            <value>
                <fullName>Metro Based Promo</fullName>
            </value>
            <value>
                <fullName>Net-new business</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partnership creation/update</fullName>
            </value>
            <value>
                <fullName>Portal access</fullName>
            </value>
            <value>
                <fullName>Rate Change</fullName>
            </value>
            <value>
                <fullName>SaaS Fee Setup</fullName>
            </value>
            <value>
                <fullName>Self Delivery</fullName>
            </value>
            <value>
                <fullName>Sponsored Listing</fullName>
            </value>
            <value>
                <fullName>COO Same Store</fullName>
            </value>
            <value>
                <fullName>Withholding</fullName>
            </value>
            <value>
                <fullName>Net-New</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Additional store creation</fullName>
                <isActive>false</isActive>
                <label>Additional store creation</label>
            </value>
            <value>
                <fullName>Marketing Free Credit</fullName>
                <isActive>false</isActive>
                <label>Marketing Free Credit</label>
            </value>
            <value>
                <fullName>Partnership update</fullName>
                <isActive>false</isActive>
                <label>Partnership update</label>
            </value>
            <value>
                <fullName>Return and Replacement</fullName>
                <isActive>false</isActive>
                <label>Return and Replacement</label>
            </value>
            <value>
                <fullName>Store Expansion</fullName>
                <isActive>false</isActive>
                <label>Store Expansion</label>
            </value>
            <value>
                <fullName>Virtual Kitchen</fullName>
                <isActive>false</isActive>
                <label>Virtual Kitchen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Agreement_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Franchise Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Store Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Business Agreement</fullName>
    </customValue>
    <description>LEM-186, LEM-3818: Initial Setup of Agreement</description>
    <masterLabel>Agreement Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <description>LEM-186: Initial Setup of Agreement</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/domains/AgreementsTest.cls
/**
 * @description Test Class for Agreements Domain class
 * @author DoorDash
 * @date 06/02/2022
 */
@isTest(seeAllData=false)
public class AgreementsTest {
    private static final String AGREEMENT_NAME = 'Test business agreement';
    private static final String AGREEMENT_STATUS_ACTIVE = 'Active';
    private static final String AGREEMENT_TYPE_BUSINESS_AGREEMENT = 'Business Agreement';
    private static final String EVENT_TOPIC_READINESS_CHECK_ON_PARENT_WORK_ORDERS = 'READINESS_CHECK_ON_PARENT_WORK_ORDERS';
    private static final String PARENT_WORKORDER_IDS_CHUNK_SIZE_STATIC_CONFIG = 'Parent_WorkOrders_Payload_Chunk_Size';
    private static final String WORK_ORDER_STATUS_PLANNING = 'Planning';
    private static final String WORK_ORDER_TYPE_DRIVE = 'Drive';
    private static final String WORK_ORDER_SUB_TYPE_WITHHOLDING = 'Withholding';
    private static final String STATUS_CANCELLED = 'Cancelled'; //@JIRA #LEM-15980
    /**
     * @description this method is to test Nintex selectors.
     */
    @isTest
    private static void testWhenAgreementsCallsThenReturnRecords() {
        List<Agreement__c> agreementRecords = new List<Agreement__c>{
            new Agreement__c(
                Id = fflib_IDGenerator.generate(Agreement__c.SObjectType),
                Name = 'Test 1 Store Agreement',
                Account__c = fflib_IDGenerator.generate(Account.SObjectType),
                Start_Date__c = System.today(),
                Deactivation_Date__c = System.today() + 10
            ),
            new Agreement__c(
                Id = fflib_IDGenerator.generate(Agreement__c.SObjectType),
                Name = 'Test 1 Store Agreement',
                Account__c = fflib_IDGenerator.generate(Account.SObjectType),
                Start_Date__c = System.today() + 5,
                Deactivation_Date__c = System.today() + 20
            )
        };
        Set<Id> accountSet = Agreements.newInstance(agreementRecords).getAccountIds();
        System.assertEquals(2, accountSet.size(), 'Call returned the incorrect number of rows');
    }

    /**
     * @description To test Notifier event published when onAfterInsertHandleRelatedRecords called
     * on creation of Business Agreements.
     * Suppressing Warning as mock.verify method is equivalent of System.assert statement.
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenOnAfterInsertHandleRelatedRecordsCalledThenNotifierEventPublished() {
        Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
        Id contractId = fflib_IDGenerator.generate(Contract.SObjectType);
        Id parentOpportunityId = fflib_IDGenerator.generate(Opportunity.SObjectType);
        Id parentWorkOrderId = fflib_IDGenerator.generate(WorkOrder.SObjectType);
        Agreement__c businessAgreement = new Agreement__c(
            Id = fflib_IDGenerator.generate(Agreement__c.SObjectType),
            Name = AGREEMENT_NAME,
            Account__c = fflib_IDGenerator.generate(Account.SObjectType),
            Contract__c = contractId,
            Start_Date__c = System.today(),
            Deactivation_Date__c = System.today() + 10,
            Status__c = AGREEMENT_STATUS_ACTIVE,
            Type__c = AGREEMENT_TYPE_BUSINESS_AGREEMENT
        );
        WorkOrder parentWorkOrder = (WorkOrder) new Fake(WorkOrder.class)
            .setField(WorkOrder.Id, parentWorkOrderId)
            .setField(WorkOrder.Type__c, WORK_ORDER_TYPE_DRIVE)
            .setField(WorkOrder.Sub_Type__c, WORK_ORDER_SUB_TYPE_WITHHOLDING)
            .setField(WorkOrder.AccountId, accountId)
            .setField(WorkOrder.Opportunity__c, parentOpportunityId)
            .setField(WorkOrder.Status, WORK_ORDER_STATUS_PLANNING)
            .setField(WorkOrder.Proposed_Date_of_Activation__c, System.today())
            .toSObject();
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IStaticConfigurationsSelector mockStaticConfigurations = (IStaticConfigurationsSelector) mocks.mock(
            IStaticConfigurationsSelector.class
        );
        INotifierEventsService notifierEventService = (INotifierEventsService) mocks.mock(
            INotifierEventsService.class
        );
        IWorkOrdersSelector mockWorkOrdersSelector = (IWorkOrdersSelector) mocks.mock(
            IWorkOrdersSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockStaticConfigurations.sObjectType())
            .thenReturn(Static_Configurations__mdt.SObjectType);
        mocks.when(
                mockStaticConfigurations.getInstanceValue(
                    PARENT_WORKORDER_IDS_CHUNK_SIZE_STATIC_CONFIG
                )
            )
            .thenReturn(
                new Static_Configurations__mdt(
                    Label = PARENT_WORKORDER_IDS_CHUNK_SIZE_STATIC_CONFIG,
                    Configuration_Value__c = '1'
                )
            );
        mocks.when(mockWorkOrdersSelector.sObjectType()).thenReturn(WorkOrder.SObjectType);
        mocks.when(
                mockWorkOrdersSelector.selectParentWorkOrdersByContractIds(
                    new Set<Id>{ contractId }
                )
            )
            .thenReturn(new List<WorkOrder>{ parentWorkOrder });
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockStaticConfigurations);
        Application.SELECTOR.setMock(mockWorkOrdersSelector);
        Application.SERVICE.setMock(INotifierEventsService.class, notifierEventService);
        Test.startTest();
        Agreements.newInstance(new List<Agreement__c>{ businessAgreement })
            .onAfterInsertHandleRelatedRecords(new List<Agreement__c>{ businessAgreement });
        Test.stopTest();
        List<Id> parentWorkOrderIds = new List<Id>{ parentWorkOrder.Id };
        ((INotifierEventsService) mocks.verify(notifierEventService, 1))
            .publishBulkEvents(
                new Map<String, List<String>>{
                    EVENT_TOPIC_READINESS_CHECK_ON_PARENT_WORK_ORDERS => new List<String>{
                        JSON.serialize(parentWorkOrderIds)
                    }
                }
            );
    }

       /**
     * @description To test updated agreements
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenAgreementUpdatedThenUpdateStatus() {
        Id agreementId1 = fflib_IDGenerator.generate(Agreement__c.SObjectType);
        Id agreementId2 = fflib_IDGenerator.generate(Agreement__c.SObjectType);

        List<Agreement__c> agreementsList = new List<Agreement__c>{
            new Agreement__c(
                Id = agreementId1,
                Status__c = AGREEMENT_STATUS_ACTIVE,
                Deactivation_Date__c = System.today()
            ),
            new Agreement__c(Id = agreementId2, Status__c = STATUS_CANCELLED)
        };
        // Call the method
        Agreements.newInstance(agreementsList).updateDeactivationDateOrStatus(agreementsList);
        // Assert the results
        System.assertEquals(
            System.today(),
            agreementsList[0].Deactivation_Date__c,
            'Deactivation should be todays date'
        );
        System.assertEquals(
            STATUS_CANCELLED,
            agreementsList[1].Status__c,
            'Status Should be cancelled'
        );
    }
}