sfdx-source/force-app/main/default/objects/Account/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-6471</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Xref__c.field-meta.xml
<CustomField>
    <fullName>Xref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xref</label>
    <referenceTo>Xref__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Business_GroupID__c.field-meta.xml
<CustomField>
    <fullName>Business_GroupID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-2197: Signifies the corresponding backend store ID for the business.</description>
    <formula>Business_Reference__r.Business_Group_Id__c</formula>
    <inlineHelpText>Signifies the corresponding backend store ID for the business</inlineHelpText>
    <label>Business Group ID</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/BusinessID__c.field-meta.xml
<CustomField>
    <fullName>BusinessID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-2197: Signifies the corresponding backend business ID for the business.</description>
    <formula>Business_Reference__r.External_Id__c</formula>
    <inlineHelpText>Signifies the corresponding backend business ID for the business</inlineHelpText>
    <label>Business ID</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the ID of the associated backend record.</description>
    <externalId>true</externalId>
    <inlineHelpText>Represents the ID of the associated backend record</inlineHelpText>
    <label>Store ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID_Source__c.field-meta.xml
<CustomField>
    <fullName>External_ID_Source__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the Business ID for the Mx in product.</description>
    <inlineHelpText>Represents product backend source of the Store ID for the Mx</inlineHelpText>
    <label>External ID Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Figment</fullName>
            </value>
            <value>
                <fullName>MDS - Catering</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>DriveDb</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
                <isActive>false</isActive>
                <label>Drive</label>
            </value>
            <value>
                <fullName>Marketplace</fullName>
                <isActive>false</isActive>
                <label>Marketplace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>LEM-1911</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Waiting for Business</fullName>
            </value>
            <value>
                <fullName>Ready for Integration</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Ready for COO Integration</fullName>
            </value>
            <value>
                <fullName>COO Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Salesforce_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Account_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-800: Represents the name of the business or store account in SFDC.</description>
    <inlineHelpText>Represents the name of the business or store account in SFDC</inlineHelpText>
    <label>Salesforce Account Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Xref_Status__c.field-meta.xml
<CustomField>
    <fullName>Xref_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <description>LEM-1631: This field is used to represent the status of the store account</description>
    <inlineHelpText>This field represents the status of the store account</inlineHelpText>
    <label>Xref Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/controllers/DisplayActiveXrefForRCRControllerTest.cls
/**
 * @description This is a test class created for DisplayActiveXrefForRateChangeRequest.
 * @author Deloitte
 * @date 27/09/2023
 */
@isTest(SeeAllData=false)
private class DisplayActiveXrefForRCRControllerTest {
    /**
     * @description To test the retrieved fields when get fields method is called.
     */
    @isTest
    private static void testWhenRetriveFieldsFromFieldSetThenReturnDefaultFieldsAndTheirAttributesInJsonFormat() {
        String jsonData = DisplayActiveXrefForRCRController.getFields();
        List<DynamicColumn> dynamicColumn = (List<DynamicColumn>) JSON.deserialize(
            jsonData,
            List<DynamicColumn>.class
        );
        System.assertEquals(
            'xrefHyperLink',
            dynamicColumn[0].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'url',
            dynamicColumn[0].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Xref Name',
            dynamicColumn[0].label,
            'Unexpected Error: Field Name is not matching'
        );
        System.assertEquals(
            'accountNameHyperLink',
            dynamicColumn[1].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'url',
            dynamicColumn[1].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Salesforce Account Name',
            dynamicColumn[1].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'Integration_Status__c',
            dynamicColumn[2].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[2].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Integration Status',
            dynamicColumn[2].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'External_ID__c',
            dynamicColumn[3].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[3].type,
            'Unexpected Error: Field Type is not matching'
        );
        System.assertEquals(
            'External ID',
            dynamicColumn[3].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'External_ID_Source__c',
            dynamicColumn[4].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[4].type,
            'Unexpected Error: Field Type is not matching'
        );
        System.assertEquals(
            'External Source',
            dynamicColumn[4].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'BusinessID__c',
            dynamicColumn[5].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[5].type,
            'Unexpected Error: Field Type is not matching'
        );
        System.assertEquals(
            'Business ID',
            dynamicColumn[5].label,
            'Unexpected Error: Field Label is not matching'
        );
    }

    /**
     * @description To test if active records are retrieved when get get xrefs details method is
     * called from Parent WorkOrder For MarketPlace
     */
    @IsTest
    private static void testWhenGetXrefsRecordsByStoreAccountThenReturnActiveXrefsRecords() {
        Id storeId1 = Fake.generateId(Account.class);
        Id rcrId = Fake.generateId(Rate_Change_Request__c.class);
        Id xrefId = Fake.generateId(Xref__c.class);

        Xref__c[] xrefs = new List<Xref__c>{
            (Xref__c) new Fake(Xref__c.class)
                .setField(Xref__c.ID, xrefId)
                .setField(Xref__c.BusinessID__c, '1234')
                .setField(Xref__c.Business_GroupID__c, '981234')
                .setField(Xref__c.Xref_Status__c, 'Active')
                .setField(Xref__c.Salesforce_Account_Name__c, storeId1)
                .setParent(
                    'Account',
                    new Fake(Account.class)
                        .setField(Account.Id, storeId1)
                        .setField(Account.Rate_Change_Request__c, rcrId)
                )
                .toSObject()
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        IXrefsSelector selectorXrefMock = (IXrefsSelector) mocks.mock(IXrefsSelector.class);
        mocks.startStubbing();

        mocks.when(selectorXrefMock.sObjectType()).thenReturn(Xref__c.SObjectType);
        mocks.when(selectorXrefMock.selectRelatedRateChangeIds(new Set<Id>{ rcrId }))
            .thenReturn(new List<Xref__c>{ xrefs[0] });
        mocks.stopStubbing();

        Application.SELECTOR.setMock(selectorXrefMock);
        List<Xref__c> activeXrefs = DisplayActiveXrefForRCRController.getXrefDetails(rcrId);
        System.assertEquals(1, activeXrefs.size(), 'The list size does not match');
    }
}