sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Xref__c.field-meta.xml
<CustomField>
    <fullName>Xref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xref</label>
    <referenceTo>Xref__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/Business_Reference__c.object-meta.xml
<CustomObject>
    <description>LEM-2082 Object used for integration of Business Ids</description>
    <label>Business Reference</label>
    <nameField>
        <label>Business Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>LEM-2082 Represents the corresponding record ID in the external source. For example, the Business ID of a record in MDS.</description>
    <label>Business ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/External_Id_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Source__c</fullName>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <label>External Id Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Id_Source</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>LEM-2082 The integration status of the record. When set to “Ready for Integration”, the record is automatically pushed to its external source to be created/updated.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Status</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Reference__c/fields/System_Created__c.field-meta.xml
<CustomField>
    <fullName>System_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-2082 If the record was created automatically during the onboarding of one or more stores, this field is true. If the record was created manually by a user or data load, this field is false.

Duplication rules and logic are only applied to records that were system created.</description>
    <label>System Created</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Business_Reference__c.field-meta.xml
<CustomField>
    <fullName>Business_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1911 Lookup to the Business Reference record</description>
    <label>Business Reference</label>
    <referenceTo>Business_Reference__c</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the ID of the associated backend record.</description>
    <externalId>true</externalId>
    <inlineHelpText>Represents the ID of the associated backend record</inlineHelpText>
    <label>Store ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID_Source__c.field-meta.xml
<CustomField>
    <fullName>External_ID_Source__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the Business ID for the Mx in product.</description>
    <inlineHelpText>Represents product backend source of the Store ID for the Mx</inlineHelpText>
    <label>External ID Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Figment</fullName>
            </value>
            <value>
                <fullName>MDS - Catering</fullName>
            </value>
            <value>
                <fullName>MDS</fullName>
            </value>
            <value>
                <fullName>DriveDb</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
                <isActive>false</isActive>
                <label>Drive</label>
            </value>
            <value>
                <fullName>Marketplace</fullName>
                <isActive>false</isActive>
                <label>Marketplace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <description>LEM-1911</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Waiting for Business</fullName>
            </value>
            <value>
                <fullName>Ready for Integration</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Ready for COO Integration</fullName>
            </value>
            <value>
                <fullName>COO Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Salesforce_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Account_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-800: Represents the name of the business or store account in SFDC.</description>
    <inlineHelpText>Represents the name of the business or store account in SFDC</inlineHelpText>
    <label>Salesforce Account Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Xref_Status__c.field-meta.xml
<CustomField>
    <fullName>Xref_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <description>LEM-1631: This field is used to represent the status of the store account</description>
    <inlineHelpText>This field represents the status of the store account</inlineHelpText>
    <label>Xref Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/External_Id_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MDS</fullName>
    </customValue>
    <customValue>
        <fullName>DriveDb</fullName>
    </customValue>
    <customValue>
        <fullName>Figment</fullName>
    </customValue>
    <customValue>
        <fullName>MDS - Catering</fullName>
    </customValue>
    <description>LEM-2082 Identifies the external system or database where the External Id resides.</description>
    <masterLabel>External Id Source</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Ready for Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Ready for COO Integration</fullName>
    </customValue>
    <customValue>
        <fullName>COO Success</fullName>
    </customValue>
    <description>LEM-2082 The integration status of the record. When set to “Ready for Integration”, the record is automatically pushed to its external source to be created/updated.</description>
    <masterLabel>Integration Status</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/selectors/XrefsHistorySelectorTest.cls
/**
 * @author Aethereus
 * @date 03/07/2024
 * @description Test class for XrefsHistorySelector class.
 */
@isTest(seeAllData=false)
private class XrefsHistorySelectorTest {
    private static final String ACCOUNT_BILLING_CITY = 'Missoula';
    private static final String ACCOUNT_BILLING_COUNTRY = 'United States';
    private static final String ACCOUNT_BILLING_POSTAL_CODE = '1234';
    private static final String ACCOUNT_BILLING_STATE = 'California';
    private static final String ACCOUNT_BILLING_STREET = '221B Baker Street';
    private static final String AGGREGATE_XREFSCOUNT_FIELD_ALIAS = 'xrefsCount';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_EXTERNAL_ID = 'Unexpected result: External Id does not match';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: There is a mismatch in fields list';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: The object type must be Xref__c';
    private static final String BUSINESS_ACCOUNT_NAME = 'Test Business Account';
    private static final String EMPTY_LIST_ASSERT_MESSAGE = 'Unexpected Result: number of records returned does not match the expected outcome';
    private static final String EXTERNAL_ID = '12345';
    private static final String EXTERNAL_ID_SOURCE_MDS = 'MDS';
    private static final String EXTERNAL_ID_SOURCE_DRIVE = 'DriveDb';
    private static final String XREF_STATUS_ACTIVE = 'Active';
    private static final String STORE_ID = '2480';
    private static final String POS_INTEGRATION_ID = '1122334455';
    private static final String SUCCESS = 'Success';
    private static final String WAITING_FOR_BUSINESS = 'Waiting for Business';
    static final String MDS = 'MDS';
    static final String FAILURE = 'Failure';
    static final String INTEGRATION_SUCCESS = 'Success';
    private static final String ACCOUNT_SEGMENT_SMB = 'SMB';

    /**
     * @description Test method for selectXrefsHistory method.
     * This method tests the behavior when the method is called with valid parameters.
     */
    @isTest
    Private static void testWhenSelectXrefHistoryThenReturnHistories() {

        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        List<String> userIds = System.Label.MINT_Upate_Users .split(';');
        List<User> users = [SELECT ID FROM USER WHERE ID IN : userIds];
        Account businessAccount = new Account(
            Name = BUSINESS_ACCOUNT_NAME,
            RecordtypeId = businessRecordTypeId,
            BillingStreet = ACCOUNT_BILLING_STREET,
            BillingCity = ACCOUNT_BILLING_CITY,
            BillingState = ACCOUNT_BILLING_STATE,
            BillingPostalCode = ACCOUNT_BILLING_POSTAL_CODE,
            BillingCountry = ACCOUNT_BILLING_COUNTRY,
            Segment__c = ACCOUNT_SEGMENT_SMB
        );
        insert businessAccount;
        Business_Reference__c businessReference = new Business_Reference__c(
            External_ID__c = EXTERNAL_ID,
            System_Created__c = true,
            External_ID_Source__c = EXTERNAL_ID_SOURCE_MDS,
            Integration_Status__c = FAILURE
        );
        insert businessReference;
        Business_Reference__c businessReference2 = new Business_Reference__c(
            External_ID__c = EXTERNAL_ID,
            System_Created__c = true,
            External_ID_Source__c = EXTERNAL_ID_SOURCE_MDS,
            Integration_Status__c = SUCCESS
        );
        insert businessReference2;
        Xref__c xref = new Xref__c(
            Business_Reference__c = businessReference.Id,
            Salesforce_Account_Name__c = businessAccount.Id,
            External_ID_Source__c = EXTERNAL_ID_SOURCE_MDS,
            Xref_Status__c = XREF_STATUS_ACTIVE,
            Integration_Status__c = INTEGRATION_SUCCESS,
            External_ID__c = EXTERNAL_ID
        );
        insert xref;

        Test.startTest();
        xref.Business_Reference__c = businessReference2.Id;
    	update xref;

        List<Xref__History> xrefHistories = XrefsHistorySelector.newInstance().selectXrefHistory(
            new Set<String>{'Field'},
            new Set<String>{'Field'},
            new List<String>{users[0].Id},
            DateTime.now().addDays(-1)
        );
        Test.stopTest();

        System.assertNotEquals(1, xrefHistories.size(), 'No xref history should be returned');

    }


}