sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>LEM-1337: This object is used to define the relationship Cross Accounts</description>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR - {0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1337: The Account that lookups to one side of the Account Relationship.</description>
    <inlineHelpText>The account from which the relationship is originating.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Relationships cannot be created involving store accounts. Please update the Account and Related Account accordingly.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Related_Accounts_Originating_Relation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>LEM-1337: External Id field that holds the combination of the Accounts being related in the relationship and their respective Types</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Inverse_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Relationship_Type__c</fullName>
    <description>LEM-1337: Captures the type of Account from which the Relationship has been created.</description>
    <inlineHelpText>The type of account from which the relationship is originating.</inlineHelpText>
    <label>Inverse Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1337: This looks-up to the Account residing on the other side of the Account Relationship</description>
    <inlineHelpText>The account with which the user is creating a relationship to.</inlineHelpText>
    <label>Related Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Relationships cannot be created involving store accounts. Please update the Account and Related Account accordingly.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receiving Related Accounts</relationshipLabel>
    <relationshipName>Related_Accounts_Receiving_Relation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the current status of the relationship between the Accounts involved</description>
    <label>Relationship Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the type of Account to which the Relationship is being created.</description>
    <inlineHelpText>The type of account with which the user is creating a relationship to.</inlineHelpText>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Account_Relationships_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Measurement Partner</fullName>
    </customValue>
    <customValue>
        <fullName>AdTech</fullName>
    </customValue>
    <customValue>
        <fullName>POS/MWP Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusive Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Franchise</fullName>
    </customValue>
    <description>LEM-1337: Captures the possible types of Accounts between which relationships can be created</description>
    <masterLabel>Account Relationships Types</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/integration/domains/AccountRelationshipsIntegrationTest.cls
/**
 * @author Deloitte
 * @date 25/05/2022
 * @description Integration Test class for AccountRelationships
 */
@isTest
public class AccountRelationshipsIntegrationTest {
    @testSetup
    static void setupRelationshipData() {
        List<Account> accountList = new List<Account>{
            new Account(Name = 'Parent 1', Segment__c = 'Enterprise'),
            new Account(Name = 'Parent 2', Segment__c = 'Enterprise')
        };
        insert accountList;

        Account_Relationship__c accountRelationship = new Account_Relationship__c(
            Relationship_Type__c = 'Agency',
            Inverse_Relationship_Type__c = 'Measurement Partner',
            Account__c = accountList[0].Id,
            Relationship_Status__c = 'Active',
            Related_Account__c = accountList[1].Id
        );
        insert accountRelationship;
    }

    @isTest
    private static void testWhenRelationshipsAreInsertedThenReciprocalRelationshipsAreCreated() {
        List<Account_Relationship__c> insertedRelationship = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c,
                External_Id__c
            FROM Account_Relationship__c
            WHERE Relationship_Type__c = 'Agency'
        ];
        List<Account_Relationship__c> allRelationships = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c,
                External_Id__c
            FROM Account_Relationship__c
            ORDER BY Name
        ];
        System.assertEquals(
            insertedRelationship[0].Account__c +
            insertedRelationship[0].Inverse_Relationship_Type__c +
            insertedRelationship[0].Related_Account__c +
            insertedRelationship[0].Relationship_Type__c,
            allRelationships[0].External_Id__c,
            'The External Id was not autopopulated as expected'
        );
        System.assertEquals(2, allRelationships.size(), 'The reciprocal record was not generated.');
        System.assertEquals(
            insertedRelationship[0].Related_Account__c +
            insertedRelationship[0].Relationship_Type__c +
            insertedRelationship[0].Account__c +
            insertedRelationship[0].Inverse_Relationship_Type__c,
            allRelationships[1].External_Id__c,
            'The External Id of the reciprocal relationship was not autopopulated appropriately.'
        );
    }

    @isTest
    private static void testWhenRelationshipsAreUpdatedThenReciprocalRelationshipsAreUpdated() {
        List<Account_Relationship__c> insertedRelationship = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c
            FROM Account_Relationship__c
            WHERE Relationship_Type__c = 'Agency'
        ];
        List<Account_Relationship__c> reciprocalRelationship = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c
            FROM Account_Relationship__c
            WHERE Inverse_Relationship_Type__c = 'Agency'
        ];
        //Before Update Assertions
        System.assertNotEquals(
            null,
            reciprocalRelationship[0],
            'Unexpected Error: The expected reciprocal Account Relationship record was not created/fetched correctly.'
        );
        System.assertEquals(
            'Agency',
            reciprocalRelationship[0].Inverse_Relationship_Type__c,
            'Unexpected Error: The reciprocal Relationship was not created appropriately'
        );

        insertedRelationship[0].Relationship_Type__c = 'AdTech';

        Test.startTest();
        update insertedRelationship;
        Test.stopTest();

        //Fetch New Records
        Map<Id, Account_Relationship__c> afterUpdateStateOfRelationships = new Map<Id, Account_Relationship__c>(
            [
                SELECT
                    Id,
                    Name,
                    External_Id__c,
                    Relationship_Type__c,
                    Relationship_Status__c,
                    Inverse_Relationship_Type__c,
                    Account__c,
                    Related_Account__c
                FROM Account_Relationship__c
            ]
        );

        System.assertEquals(
            'AdTech',
            afterUpdateStateOfRelationships.get(insertedRelationship[0].Id).Relationship_Type__c,
            'Unexpected Error: The updates were not appropriately performed.'
        );
        System.assertEquals(
            'AdTech',
            afterUpdateStateOfRelationships.get(reciprocalRelationship[0].Id)
                .Inverse_Relationship_Type__c,
            'Unexpected Error: The updates were not properly mapped to the Reciprocal Relationship.'
        );
        System.assertEquals(
            reciprocalRelationship[0].Account__c +
            'AdTech' +
            reciprocalRelationship[0].Related_Account__c +
            'Measurement Partner',
            afterUpdateStateOfRelationships.get(reciprocalRelationship[0].Id).External_Id__c,
            'Unexpected Error: The External unique Id was not populated appropriately.'
        );
    }

    @isTest
    private static void testWhenRelationshipIsDeletedThenReciprocalIsDeleted() {
        List<Account_Relationship__c> allRelationships = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c,
                External_Id__c
            FROM Account_Relationship__c
            ORDER BY Name
        ];
        //Before Delete check
        System.assertEquals(
            2,
            allRelationships.size(),
            'The system must contain an account Relationship along with its Reciprocal. The records are not available as expected.'
        );

        Test.startTest();
        //Delete only inserted record
        delete allRelationships[0];
        Test.stopTest();

        List<Account_Relationship__c> allRelationshipsAfterDelete = [
            SELECT
                Id,
                Name,
                Relationship_Type__c,
                Relationship_Status__c,
                Inverse_Relationship_Type__c,
                Account__c,
                Related_Account__c,
                External_Id__c
            FROM Account_Relationship__c
            ORDER BY Name
        ];
        System.assertEquals(
            0,
            allRelationshipsAfterDelete.size(),
            'The reciprocal record was not deleted on deletion of the account relationship.'
        );
    }
}