sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract/fields/Associated_Account_Ids__c.field-meta.xml
<CustomField>
    <fullName>Associated_Account_Ids__c</fullName>
    <description>LEM-779 Accounts Associated to this Contract</description>
    <label>Associated Account Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/Contract_Associated_Accounts__c.object-meta.xml
<CustomObject>
    <label>Contract Associated Accounts</label>
    <nameField>
        <displayFormat>CAA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Associated_Account_Ids__c.field-meta.xml
<CustomField>
    <fullName>Associated_Account_Ids__c</fullName>
    <description>LEM-6144 This holds a collection of Account IDs, up to its limit of ~7000.</description>
    <label>Associated Account Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Batch_Process_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It determines whether the requests should be processed via Batch?</description>
    <inlineHelpText>Whether the requests should be processed via Batch?</inlineHelpText>
    <label>Batch Process Enabled?</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Batch_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process_Status__c</fullName>
    <label>Batch Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-6144: This represents the main Contract record on which the Associated Account Ids are currently stored.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associated Accounts</relationshipLabel>
    <relationshipName>Contract_Associated_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-11329 Corporate cherry picking</description>
    <label>Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>QLG Contract Associated Accounts</relationshipLabel>
    <relationshipName>QLG_Contract_Associated_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/IsProcessingExistingStores__c.field-meta.xml
<CustomField>
    <fullName>IsProcessingExistingStores__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-11329 To store whether CAA record was created in the scenario of new stores or existing stores.</description>
    <inlineHelpText>Whether the requests should be processed via Batch?</inlineHelpText>
    <label>Is Processing Existing Stores?</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Indicates ordering/number of Contract Associated Accounts -- i.e., the first record will have 1 in this field, the second record (if needed) will have 2, etc.</description>
    <inlineHelpText>Indicates ordering/number of Contract Associated Accounts -- i.e., the first record will have 1 in this field, the second record (if needed) will have 2, etc.</inlineHelpText>
    <label>Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Serialized_Entitlements_Data__c.field-meta.xml
<CustomField>
    <fullName>Serialized_Entitlements_Data__c</fullName>
    <description>LEM-11329 To store the manage stores entitlement details in JSON format.Selected: Contains ‘Selected packages and selected entitlement’Deselected: Contains ‘Selected packages and deselected entitlements'</description>
    <label>Serialized Entitlements Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/ContractAssociatedAccountsSelectorTest.cls
/**
 * @author BizApps
 * @date 5/23
 * @description This is test class for ContractAssociatedAccountsSelector class
 */
@isTest
public class ContractAssociatedAccountsSelectorTest {
    @testSetup
    static void setupData() {
        Account parentAccount = new Account(Name = 'Test Parent Account', Segment__c = 'Enterprise');
        insert parentAccount;
        List<Contract> childContracts = new List<Contract>{
            new Contract(
                StartDate = Date.today() + 1,
                Status = 'Draft',
                AccountId = parentAccount.Id
            ),
            new Contract(
                StartDate = Date.today() + 1,
                Status = 'Draft',
                AccountId = parentAccount.Id
            )
        };
        insert childContracts;
    }

    @isTest
    private static void testWhenClassInstantiatesThenCall() {
        Account acc = new Account(Name = 'Test 1', Segment__c = 'Enterprise');
        insert acc;
        Contract testContract1 = new Contract(Name = 'Test Contract1', AccountId = acc.Id);
        insert testContract1;
        Contract_Associated_Accounts__c conAssociatedAccount = new Contract_Associated_Accounts__c(
            Contract__c = testContract1.Id,
            Order__c = 1
        );
        insert ConAssociatedAccount;
        List<Contract_Associated_Accounts__c> contractsAssociatedAccounts = ContractAssociatedAccountsSelector.newInstance()
            .selectById(new Set<Id>{ conAssociatedAccount.Id });
        System.assertEquals(
            contractsAssociatedAccounts.size(),
            1,
            'The list should Contain 1 Contract Associated Account'
        );

        ContractAssociatedAccountsSelector contractAssoAccountInstance = new ContractAssociatedAccountsSelector();
        Schema.SObjectType typeOfObj = contractAssoAccountInstance.getSObjectType();
        System.assertEquals(
            Schema.Contract_Associated_Accounts__c.SObjectType,
            typeOfObj,
            'The object type must be Contract Associated Account'
        );
        List<Schema.SObjectField> fieldList = contractAssoAccountInstance.getSObjectFieldList();
        System.assertEquals(
            new List<Schema.SObjectField>{
                Contract_Associated_Accounts__c.Id,
                Contract_Associated_Accounts__c.Associated_Account_Ids__c,
                Contract_Associated_Accounts__c.Contract__c,
                Contract_Associated_Accounts__c.Batch_Process_Enabled__c,
                Contract_Associated_Accounts__c.Batch_Process_Status__c,
                Contract_Associated_Accounts__c.Order__c,
                Contract_Associated_Accounts__c.Group__c,
                Contract_Associated_Accounts__c.IsProcessingExistingStores__c,
                Contract_Associated_Accounts__c.Serialized_Entitlements_Data__c
            },
            fieldList,
            ' Mismatch in field list'
        );
    }

    /**
     * @description To test When ContractId Is Passed Then ContractAssociatedAccounts Are Returned
     */
    @isTest
    private static void testWhenContractIdIsPassedThenContractAssociatedAccountsAreReturned() {
        Contract testContract1 = [SELECT id FROM Contract LIMIT 1][0];
        List<Contract_Associated_Accounts__c> conAssociatedAccounts = new List<Contract_Associated_Accounts__c>{
            new Contract_Associated_Accounts__c(Contract__c = testContract1.Id, Order__c = 1),
            new Contract_Associated_Accounts__c(Contract__c = testContract1.Id, Order__c = 2)
        };
        insert conAssociatedAccounts;
        ContractAssociatedAccountsSelector contractAssoAccountInstance = new ContractAssociatedAccountsSelector();
        List<Contract_Associated_Accounts__c> conAssoAccounts = contractAssoAccountInstance.selectByContractId(
            testContract1.Id
        );
        System.assertEquals(
            2,
            conAssoAccounts.size(),
            'Should return 2 ContractAssociatedAccounts'
        );
    }

    /**
     * @description To test When ContractId Is Passed Then ContractAssociatedAccounts Are Returned
     */
    @isTest
    private static void testWhenContractIdsArePassedThenContractAssociatedAccountsAreReturned() {
        List<Contract> testContractList = [SELECT Id FROM Contract LIMIT 2];
        List<Contract_Associated_Accounts__c> conAssociatedAccounts = new List<Contract_Associated_Accounts__c>{
            new Contract_Associated_Accounts__c(Contract__c = testContractList[0].Id, Order__c = 1),
            new Contract_Associated_Accounts__c(Contract__c = testContractList[1].Id, Order__c = 2)
        };
        insert conAssociatedAccounts;
        ContractAssociatedAccountsSelector contractAssoAccountInstance = new ContractAssociatedAccountsSelector();
        List<Contract_Associated_Accounts__c> conAssoAccounts = contractAssoAccountInstance.selectByContractIds(
            new Set<Id>{ testContractList[0].Id, testContractList[1].Id }
        );
        System.assertEquals(
            2,
            conAssoAccounts.size(),
            'Should return 2 ContractAssociatedAccounts'
        );
    }

    @isTest
    private static void testWhenSearchingByBatchProcessEnabledThenReturnRecords() {
        Account acc1 = new Account(Name = 'Test 1', Segment__c = 'Enterprise');
        Account acc2 = new Account(Name = 'Test 2', Segment__c = 'Enterprise');
        insert new List<Account>{ acc1, acc2 };
        Contract testContract = [SELECT id FROM Contract][0];
        Contract_Associated_Accounts__c contractAssociatedAccount = new Contract_Associated_Accounts__c(
            Contract__c = testContract.Id,
            Order__c = 1,
            Batch_Process_Status__c = 'Not Started',
            Batch_Process_Enabled__c = true,
            Associated_Account_Ids__c = acc1.Id + ',' + acc2.Id
        );
        insert contractAssociatedAccount;
        Test.startTest();
        ContractAssociatedAccountsSelector contractAssoAccountInstance = new ContractAssociatedAccountsSelector();
        Database.QueryLocator queryLocator = contractAssoAccountInstance.selectByBatchProcessEnabledAndStatus();
        List<Contract_Associated_Accounts__c> conAssociatedAccounts = Database.query(
            queryLocator.getQuery()
        );
        Test.stopTest();
        System.assertEquals(
            1,
            conAssociatedAccounts.size(),
            '1 record is expected for this criteria'
        );
    }

    @isTest
    private static void testWhenSearchingByBatchProcessEnabledIdsThenReturnRecords() {
        Account acc1 = new Account(Name = 'Test 1', Segment__c = 'Enterprise');
        Account acc2 = new Account(Name = 'Test 2', Segment__c = 'Enterprise');
        insert new List<Account>{ acc1, acc2 };
        Contract testContract = [SELECT id FROM Contract][0];
        Contract_Associated_Accounts__c contractAssociatedAccount = new Contract_Associated_Accounts__c(
            Contract__c = testContract.Id,
            Order__c = 1,
            Batch_Process_Status__c = 'Not Started',
            Batch_Process_Enabled__c = true,
            Associated_Account_Ids__c = acc1.Id + ',' + acc2.Id
        );
        insert contractAssociatedAccount;
        Test.startTest();
        ContractAssociatedAccountsSelector contractAssoAccountInstance = new ContractAssociatedAccountsSelector();
        Set<Id> conAssociatedAccountIds = new Set<Id>{ contractAssociatedAccount.Id };
        Database.QueryLocator queryLocator = contractAssoAccountInstance.selectByBatchProcessEnabledAndStatusIds(
            conAssociatedAccountIds
        );
        List<Contract_Associated_Accounts__c> conAssociatedAccounts = Database.query(
            queryLocator.getQuery()
        );
        Test.stopTest();
        System.assertEquals(
            1,
            conAssociatedAccounts.size(),
            '1 record is expected for this criteria'
        );
    }
}