sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/Account_Payment_Account_Relation__c.object-meta.xml
<CustomObject>
    <label>Account To Payment Account Relation</label>
    <nameField>
        <displayFormat>APA-{0000}</displayFormat>
        <label>Account Payment Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account To Payment Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1150: This field represents the associated Account</description>
    <inlineHelpText>This field represents the associated Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Account_Payment_Account_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1150: This field represents the associated payment account.</description>
    <inlineHelpText>This field represents the associated payment account.</inlineHelpText>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Payment_Account_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Payment_Account_Relation__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <description>LEM-2826: Defaulting Payment Terms based on the Payment Account.</description>
    <formula>TEXT(Payment_Account__r.Payment_Terms__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures payment terms</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

sfdx-source/force-app/main/default/objects/Payment_Account__c/recordTypes/Payments.recordType-meta.xml
<RecordType>
    <fullName>Payments</fullName>
    <active>true</active>
    <label>Payments</label>
</RecordType>

sfdx-source/force-app/main/default/globalValueSets/Payment_Terms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Due on receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Net 7</fullName>
    </customValue>
    <customValue>
        <fullName>Net 15</fullName>
    </customValue>
    <customValue>
        <fullName>Net 20</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
        <default>true</default>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>Net 45</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 70</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Net 120</fullName>
    </customValue>
    <description>LEM-1371: Payment Account Object setup</description>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/selectors/AccountPaymentAccountRelationsSelectTest.cls
/**
 * @author Deloitte
 * @date 10/0y/2022
 * @description Test class for AccountPaymentAccountRelationsSelector class.
 */
@isTest(seeAllData=false)
private class AccountPaymentAccountRelationsSelectTest {
    private static final String ACCOUNT_NAME = AccountPaymentAccountRelationsSelectTest.class
        .getName();
    private static final String FIELDS_DO_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: mismatch in field list';
    private static final String OBJECT_DO_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: the object type must be Account_Payment_Account_Relation__c';
    private static final Id PAYMENT_ACCOUNT_INVOICE_RECORD_TYPE_ID = Schema.SObjectType.Payment_Account__c.getRecordTypeInfosByDeveloperName()
        .get('Invoice')
        .getRecordTypeId();
    private static final Id PAYMENT_ACCOUNT_PAYMENTS_RECORD_TYPE_ID = Schema.SObjectType.Payment_Account__c.getRecordTypeInfosByDeveloperName()
        .get('Payments')
        .getRecordTypeId();
    private static final String PAYMENT_ACCOUNT_RECORD_TYPE_INVOICE = 'Invoice';
    private static final String PAYMENT_ACCOUNT_RECORD_TYPE_PAYMENTS = 'Payments';
    private static final String PAYMENT_TERMS_NET_15 = 'Net 15';
    private static final String ERROR_LIST_SIZE_DOES_NOT_MATCH = 'Unexpected result: mismatch in field list size';
    private static final String ERROR_PAYMENT_TERMS_DOES_NOT_MATCH = 'Unexpected result: mismatch in field payment terms';

    /**
     * @description To test Contructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheckSObjectTypeAndFieldList() {
        AccountPaymentAccountRelationsSelector accountPaymentAccountRelationsSelectorInstance = (AccountPaymentAccountRelationsSelector) AccountPaymentAccountRelationsSelector.newInstance();
        Schema.SObjectType typeOfObject = accountPaymentAccountRelationsSelectorInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = accountPaymentAccountRelationsSelectorInstance.getSObjectFieldList();
        System.assertEquals(
            Schema.Account_Payment_Account_Relation__c.SObjectType,
            typeOfObject,
            OBJECT_DO_NOT_MATCH_ASSERT_MESSAGE
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Account_Payment_Account_Relation__c.Id,
                Account_Payment_Account_Relation__c.Account__c,
                Account_Payment_Account_Relation__c.Payment_Account__c,
                Account_Payment_Account_Relation__c.Payment_Terms__c
            },
            sObjectFields,
            FIELDS_DO_NOT_MATCH_ASSERT_MESSAGE
        );
    }

    /**
     * @description Tests select by id with payment account payment terms
     */
    @isTest
    private static void testWhenSelectByIdCalledThenReturn() {
        Payment_Account__c paymentAccount = new Payment_Account__c(
            Payment_Terms__c = PAYMENT_TERMS_NET_15
        );

        insert paymentAccount;

        Account_Payment_Account_Relation__c accountToPaymentAccountRelation = new Account_Payment_Account_Relation__c(
            Payment_Account__c = paymentAccount.Id
        );

        insert accountToPaymentAccountRelation;

        List<Account_Payment_Account_Relation__c> accountToPaymentAccountRelations = AccountPaymentAccountRelationsSelector.newInstance()
            .selectById(new Set<Id>{ accountToPaymentAccountRelation.Id });

        System.assert(accountToPaymentAccountRelations.size() == 1, ERROR_LIST_SIZE_DOES_NOT_MATCH);
        System.assert(
            accountToPaymentAccountRelations[0].Payment_Terms__c == PAYMENT_TERMS_NET_15,
            ERROR_PAYMENT_TERMS_DOES_NOT_MATCH
        );
    }

    /**
     * @description To test query on Account To Payment Account relations
     * associated with the passed Account Ids having Payment Accounts with Invoice record type.
     */
    @isTest
    private static void testWhenSelectByAccountIdsCalledThenAccountPaymentAccountRelationsWithInvoicePaymentAccountsReturned() {
        Payment_Account__c paymentAccount = new Payment_Account__c(
            Payment_Terms__c = PAYMENT_TERMS_NET_15,
            RecordTypeId = PAYMENT_ACCOUNT_INVOICE_RECORD_TYPE_ID
        );
        insert paymentAccount;
        Account account = new Account(Name = ACCOUNT_NAME, Segment__c = 'Enterprise');
        insert account;
        Account_Payment_Account_Relation__c accountToPaymentAccountRelation = new Account_Payment_Account_Relation__c(
            Payment_Account__c = paymentAccount.Id,
            Account__c = account.Id
        );
        insert accountToPaymentAccountRelation;
        List<Account_Payment_Account_Relation__c> accountToPaymentAccountRelations = AccountPaymentAccountRelationsSelector.newInstance()
            .selectByAccountIdsAndPaymentAccountRecordTypes(
                new Set<Id>{ account.Id },
                new Set<String>{ PAYMENT_ACCOUNT_RECORD_TYPE_INVOICE }
            );
        System.assertEquals(
            1,
            accountToPaymentAccountRelations.size(),
            ERROR_LIST_SIZE_DOES_NOT_MATCH
        );
    }

    /**
     * @description To test query on Account To Payment Account relations
     * associated with the passed Account Ids having Payment Accounts with Payments record type.
     */
    @isTest
    private static void testWhenAccountIdsAndPaymentsRecordTypePassedThenAccountPaymentAccountRelationsWithPaymentAccountsOfPaymentsRecordTypeReturned() {
        Payment_Account__c paymentAccount = new Payment_Account__c(
            Payment_Terms__c = PAYMENT_TERMS_NET_15,
            RecordTypeId = PAYMENT_ACCOUNT_PAYMENTS_RECORD_TYPE_ID
        );
        insert paymentAccount;
        Account account = new Account(Name = ACCOUNT_NAME, Segment__c = 'Enterprise');
        insert account;
        Account_Payment_Account_Relation__c accountToPaymentAccountRelation = new Account_Payment_Account_Relation__c(
            Payment_Account__c = paymentAccount.Id,
            Account__c = account.Id
        );
        insert accountToPaymentAccountRelation;
        List<Account_Payment_Account_Relation__c> accountToPaymentAccountRelations = AccountPaymentAccountRelationsSelector.newInstance()
            .selectByAccountIdsAndPaymentAccountRecordTypes(
                new Set<Id>{ account.Id },
                new Set<String>{ PAYMENT_ACCOUNT_RECORD_TYPE_PAYMENTS }
            );
        System.assertEquals(
            1,
            accountToPaymentAccountRelations.size(),
            ERROR_LIST_SIZE_DOES_NOT_MATCH
        );
    }
}