sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity_Account_Relationship__c/Opportunity_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Opportunity Account Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000}</displayFormat>
        <label>Opportunity Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Opportunity_Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-341: This field will contains the Account from which the Account relationship is originating.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Account Relationships</relationshipLabel>
    <relationshipName>Opportunity_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity_Account_Relationship__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>LEM-341: This field is used to track that the Product Insights are related to the Opportunity through Account relationship record.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Account Relationships</relationshipLabel>
    <relationshipName>Opportunity_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity_Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-341: This field is used to track the Account with which the user is originating the relationship with.</description>
    <label>Related Account</label>
    <referenceTo>Account_Relationship__c</referenceTo>
    <relationshipLabel>Opportunity Account Relationships</relationshipLabel>
    <relationshipName>Opportunity_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/OpportunityAccountRelationsSelectTest.cls
/**
 * @author Deloitte
 * @date 19/06/2022
 * @description Test Class for OpportunityAccountRelationshipsSelector
 */
@isTest
private class OpportunityAccountRelationsSelectTest {
    @isTest
    private static void testWhenParentOpportunitiesAreProvidedThenReturnChildRelationships() {
        Account parentAccount = new Account(Name = 'Parent Account', Segment__c = 'Enterprise');
        insert parentAccount;

        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(Id = pricebookId, IsActive = true);
        update standardPricebook;

        Opportunity testEnterpriseOpportunity = new Opportunity(
            Name = 'Test Enterprise Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today() + 1,
            AccountId = parentAccount.Id,
            Pricebook2Id = pricebookId
        );
        insert testEnterpriseOpportunity;

        Opportunity testSmbOpportunity = new Opportunity(
            Name = 'Test SMB Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today() + 1,
            AccountId = parentAccount.Id,
            Pricebook2Id = pricebookId
        );
        insert testSmbOpportunity;

        Set<String> opportunityIds = new Set<String>(
            new List<String>{ testEnterpriseOpportunity.Id, testSmbOpportunity.Id }
        );

        Opportunity_Account_Relationship__c testEntepriseOpportunityAccountRelationship = new Opportunity_Account_Relationship__c(
            Opportunity__c = testEnterpriseOpportunity.Id
        );
        insert testEntepriseOpportunityAccountRelationship;

        Opportunity_Account_Relationship__c testSmbOpportunityAccountRelationship = new Opportunity_Account_Relationship__c(
            Opportunity__c = testSmbOpportunity.Id
        );
        insert testSmbOpportunityAccountRelationship;

        OpportunityAccountRelationshipsSelector relationshipSelectorInstance = new OpportunityAccountRelationshipsSelector();

        List<Opportunity_Account_Relationship__c> opportunityAccountRelationships = relationshipSelectorInstance.fetchRelationshipsByParentOpportunities(
            opportunityIds
        );
        System.assertEquals(
            2,
            opportunityAccountRelationships.size(),
            'Unexpected Error: Relationships were not fetched correctly.'
        );
    }

    @isTest
    private static void testWhenClassInstantiatesThenCall() {
        Opportunity_Account_Relationship__c testEntepriseOpportunityAccountRelationship = new Opportunity_Account_Relationship__c();

        OpportunityAccountRelationshipsSelector relationshipSelectorInstance = new OpportunityAccountRelationshipsSelector();

        List<Opportunity_Account_Relationship__c> relationships = relationshipSelectorInstance.selectById(
            new Set<Id>{ testEntepriseOpportunityAccountRelationship.Id }
        );
        Schema.SObjectType typeOfObj = relationshipSelectorInstance.getSObjectType();
        List<Schema.SObjectField> fieldList = relationshipSelectorInstance.getSObjectFieldList();

        OpportunityAccountRelationshipsSelector.newInstance();

        System.assertEquals(
            Schema.Opportunity_Account_Relationship__c.SObjectType,
            typeOfObj,
            'The object type must be Opportunity Account Relationship'
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Opportunity_Account_Relationship__c.Id,
                Opportunity_Account_Relationship__c.Name,
                Opportunity_Account_Relationship__c.Account__c,
                Opportunity_Account_Relationship__c.Opportunity__c,
                Opportunity_Account_Relationship__c.Related_Account__c
            },
            fieldList,
            'Mismatch in field list'
        );
        System.assert(
            relationships != null,
            'The list does not contain any Opportunity Account Relationships'
        );
    }
}