sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1595: Lookup to the Account to maintain Brand Level Campaign for a given overall Initiative.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <description>LEM-596,LEM-14667: Initiative object to capture the various initiatives taken against a Mx (Business Account).Renamed to Mx Touchpoint.</description>
    <label>Mx Touchpoint</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mx Touchpoints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM 596: Relationship to Account on Initiative record</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account selected is not a Business Account. Please select an associated Business Account to save the Initiative.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1595: Lookup to Campaign on Initiative.</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Campaign_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Id__c</fullName>
    <description>LEM-1595: Captures the Id of the Campaign Member to link the Account for which the Initiative has been created.</description>
    <label>Campaign Member Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>LEM-596: Captures the start date of the Initiative</description>
    <inlineHelpText>The date the touchpoint was held or that the touchpoint was kicked off.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-596: Captures the current status of the Initiative</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-596: This field indicates the Initiative picklist Type</description>
    <inlineHelpText>Indicates the type of touchpoint being held.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Review</fullName>
            </value>
            <value>
                <fullName>Strategic Effort</fullName>
            </value>
            <value>
                <fullName>Churn / Retention</fullName>
            </value>
            <value>
                <fullName>Pilot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/integration/services/CampaignMembersServiceImplIntTest.cls
/**
 * @author Deloitte
 * @date 14/06/2022
 * @description Integration Test class for CampaignMembersServiceImpl
 */
@isTest
private class CampaignMembersServiceImplIntTest {
    private static final String ASSERT_ERROR_FOR_NO_FILTERED_CAMPAIGNS = 'Campaign Members with Initiatives have also been improperly fetched';
    private static final String ASSERT_ERROR_FOR_FILTERED_CAMPAIGNS = 'The Campaign members were not filtered correctly';

    @testSetup
    static void setupCampaignData() {
        List<Account> accountList = new List<Account>{ new Account(Name = 'Parent 1', Segment__c = 'Enterprise') };
        insert accountList;

        List<Campaign> campaigns = new List<Campaign>{
            new Campaign(Name = 'Test Campaign 1'),
            new Campaign(Name = 'Test Campaign 2')
        };
        insert campaigns;

        List<CampaignMember> campaignMembers = new List<CampaignMember>{
            new CampaignMember(AccountId = accountList[0].Id, CampaignId = campaigns[0].Id),
            new CampaignMember(AccountId = accountList[0].Id, CampaignId = campaigns[1].Id)
        };
        insert campaignMembers;

        List<Initiative__c> initativeRec = new List<Initiative__c>{
            new Initiative__c(
                Type__c = 'Business Review',
                Name = 'Initiative 1',
                Start_Date__c = System.today().addDays(3),
                Account__c = accountList[0].Id,
                Status__c = 'Not Started',
                Campaign__c = campaigns[0].Id,
                Campaign_Member_Id__c = campaignMembers[0].Id
            ),
            new Initiative__c(
                Type__c = 'Business Review',
                Name = 'Initiative 2',
                Start_Date__c = System.today().addDays(3),
                Account__c = accountList[0].Id,
                Status__c = 'Not Started'
            )
        };
        insert initativeRec;
    }

    @isTest
    private static void testWhenCampaignMembersWithInitiativesAreProvidedThenReturnNoCampaignMembers() {
        List<Campaign> campaigns = [SELECT Id, Name FROM Campaign WHERE Name = 'Test Campaign 1'];
        List<CampaignMember> campaignMembersWithInitiative = [
            SELECT Id, Name
            FROM CampaignMember
            WHERE CampaignId = :campaigns[0].Id
        ];

        List<List<CampaignMember>> campaignMembersFromFlow = new List<List<CampaignMember>>();
        List<List<CampaignMember>> filteredCampaignMembers = new List<List<CampaignMember>>();
        campaignMembersFromFlow.add(campaignMembersWithInitiative);
        filteredCampaignMembers = CampaignMembersService.filterOutCampaignMembersWithInitiatives(
            campaignMembersFromFlow
        );
        System.assertEquals(
            0,
            filteredCampaignMembers[0].size(),
            ASSERT_ERROR_FOR_NO_FILTERED_CAMPAIGNS
        );
    }

    @isTest
    private static void testWhenCampaignMembersWithoutInitiativesAreProvidedThenReturnAllMembers() {
        List<Campaign> campaigns = [SELECT Id, Name FROM Campaign WHERE Name = 'Test Campaign 2'];
        List<CampaignMember> campaignMembersWithInitiative = [
            SELECT Id, Name
            FROM CampaignMember
            WHERE CampaignId = :campaigns[0].Id
        ];

        List<List<CampaignMember>> campaignMembersFromFlow = new List<List<CampaignMember>>();
        List<List<CampaignMember>> filteredCampaignMembers = new List<List<CampaignMember>>();
        campaignMembersFromFlow.add(campaignMembersWithInitiative);
        filteredCampaignMembers = CampaignMembersService.filterOutCampaignMembersWithInitiatives(
            campaignMembersFromFlow
        );
        System.assertEquals(
            1,
            filteredCampaignMembers[0].size(),
            ASSERT_ERROR_FOR_FILTERED_CAMPAIGNS
        );
    }
}