sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Mx_Country__c.field-meta.xml
<CustomField>
    <fullName>Mx_Country__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15838: It stores the Merchant&apos;s Country code.</description>
    <label>Mx Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Mx_Document_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15838: It indicates the document verification status. The default value is &quot;Pending Review&quot;.</description>
    <label>Mx Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Mx_Fraud_Document__c.field-meta.xml
<CustomField>
    <fullName>Mx_Fraud_Document__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15836 : It associates the content version to Merchant Fraud Document record.</description>
    <label>Mx Fraud Document</label>
    <referenceTo>Mx_Fraud_Document__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores Store Id of the document.</description>
    <label>Related To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/Mx_Fraud_Document__c.object-meta.xml
<CustomObject>
    <description>LEM-15836: It is used to store all required documents and validation details for fraud verification purposes.</description>
    <label>Mx Fraud Document</label>
    <nameField>
        <displayFormat>MX-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Fraud Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Country__c.field-meta.xml
<CustomField>
    <fullName>Mx_Country__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It indicates the Store&apos;s Country code Information to store the document. This is controlling field for document type.</description>
    <label>Mx Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores all document type and dependent on country code. This is not a restricted picklist so it allows user to insert new value.</description>
    <label>Mx Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mx_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ABN Document</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>DBA (Doing Business As)</fullName>
            </value>
            <value>
                <fullName>EIN Verification Letter (147C)</fullName>
            </value>
            <value>
                <fullName>Food License</fullName>
            </value>
            <value>
                <fullName>Form SS-4</fullName>
            </value>
            <value>
                <fullName>HST/GST Document</fullName>
            </value>
            <value>
                <fullName>NZBN Document</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Photo Identification Back</fullName>
            </value>
            <value>
                <fullName>Photo Identification Front</fullName>
            </value>
            <value>
                <fullName>W9 with Schedule C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Notes__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Notes__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the Document Verification Notes or Comments.</description>
    <label>Mx Document Verification Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the document verification status. The default value is &quot;Pending Review&quot;.</description>
    <label>Mx Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Mx_Store_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>LEM-15836: It associates the Mx Fraud Document to the Store Account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mx Fraud Documents</relationshipLabel>
    <relationshipName>Mx_Fraud_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/ContentVersionsSelectorTest.cls
/**
 * @author DoorDash
 * @description Test class for ContentVersion Selector class.
 **/
@IsTest
private class ContentVersionsSelectorTest {
    private static final String ACCOUNT_BILLING_CITY = 'Missoula';
    private static final String ACCOUNT_BILLING_COUNTRY = 'United States';
    private static final String ACCOUNT_BILLING_POSTAL_CODE = '1234';
    private static final String ACCOUNT_BILLING_STATE = 'California';
    private static final String ACCOUNT_BILLING_STREET = '221B Baker Street';
    private static final String ACCOUNT_SEGMENT_SMB = 'SMB';
    private static final String ASSERT_MESSAGE_CONTENT_VERSION_NOT_RETURNED = 'Unexpected Result: Content Versions not retrieved.';
    private static final String BUSINESS_ACCOUNT_NAME = 'Test Business Account';
    private static final String DOCUMENT_STATUS = 'Approved';
    private static final String DOCUMENT_TYPE_PASSPORT = 'Passport';
    private static final String MX_COUNTRY_US = 'US';
    private static final String STORE_ACCOUNT_NAME = 'Test Store Account';
    private static final String RECORD_TYPE_BUSINESS = 'Business';
    private static final String RECORD_TYPE_STORE = 'Store';
    private static final String CONTENT_VERSION_TITLE = 'Test McDonald Document';
    private static final String CONTENT_VERSION_PATH_ON_CLIENT = 'TestDocument1.txt';
    @TestSetup
    static void setupTestData() {
        ContentVersion contentVersion1 = new ContentVersion(
            Title = 'Test Document 1',
            PathOnClient = 'TestDocument1.txt',
            VersionData = Blob.valueOf('Test content 1'),
            IsMajorVersion = true
        );
        insert contentVersion1;

        ContentVersion contentVersion2 = new ContentVersion(
            Title = 'Test Document 2',
            PathOnClient = 'TestDocument2.txt',
            VersionData = Blob.valueOf('Test content 2'),
            IsMajorVersion = true
        );
        insert contentVersion2;
    }

    @isTest
    private static void testWhenClassInstantiatesThenCall() {
        ContentVersionsSelector selectorInstance = new ContentVersionsSelector();
        Schema.SObjectType typeOfObj = selectorInstance.getSObjectType();

        System.assertEquals(
            ContentVersion.SObjectType,
            typeOfObj,
            'The object type must match ContentVersion'
        );

        List<Schema.SObjectField> fieldList = selectorInstance.getSObjectFieldList();

        System.assertEquals(
            new List<Schema.SObjectField>{
                ContentVersion.Id,
                ContentVersion.CreatedById,
                ContentVersion.CreatedDate,
                ContentVersion.FileType,
                ContentVersion.LastModifiedDate,
                ContentVersion.LastModifiedById,
                ContentVersion.ContentDocumentId,
                ContentVersion.Description,
                ContentVersion.IsLatest,
                ContentVersion.Title,
                ContentVersion.VersionNumber,
                ContentVersion.VersionData
            },
            fieldList,
            'Mismatch in field list'
        );
    }

    @isTest
    private static void testWhenVersionIdsAreProvidedThenVersionsAreReceived() {
        List<ContentVersion> contentVersions = [SELECT Id FROM ContentVersion];
        Set<Id> idSet = new Set<Id>();
        for (ContentVersion cv : contentVersions) {
            idSet.add(cv.Id);
        }

        List<ContentVersion> results = ContentVersionsSelector.newInstance().selectById(idSet);

        System.assertNotEquals(null, results, 'Should not return null');
        System.assertEquals(
            idSet.size(),
            results.size(),
            'Should return the same number of records'
        );
    }

    @isTest
    private static void testWhenDocumentIdsAreProvidedThenRetrieveVersions() {
        List<ContentVersion> contentVersions = [SELECT ContentDocumentId FROM ContentVersion];
        Set<Id> documentIds = new Set<Id>();
        for (ContentVersion cv : contentVersions) {
            documentIds.add(cv.ContentDocumentId);
        }

        List<ContentVersion> results = ContentVersionsSelector.newInstance()
            .selectByContentDocumentIds(documentIds);

        System.assertNotEquals(null, results, 'Should not return null');
        System.assertEquals(
            documentIds.size(),
            results.size(),
            'Should return the same number of records'
        );
    }

    @isTest
    private static void testWhenDocumentIdsAreProvidedThenRetrieveLatestVersions() {
        List<ContentVersion> contentVersions = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE IsLatest = TRUE
        ];
        Set<Id> documentIds = new Set<Id>();
        for (ContentVersion cv : contentVersions) {
            documentIds.add(cv.ContentDocumentId);
        }

        List<ContentVersion> results = ContentVersionsSelector.newInstance()
            .selectLatestByContentDocumentIds(documentIds);

        System.assertNotEquals(null, results, 'Should not return null');
        System.assertEquals(
            documentIds.size(),
            results.size(),
            'Should return the same number of records'
        );
    }

    /**
     * @description To validate Content Version details along with Fraud Document details are returned
     * based on passed Store Account Ids.
     **/
    @isTest
    private static void testWhenRelatedToIdPassedThenReturnContentVersionDetails() {
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(RECORD_TYPE_BUSINESS)
            .getRecordTypeId();
        Id storeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get(RECORD_TYPE_STORE)
            .getRecordTypeId();
        List<Account> parentAccounts = new List<Account>{
            new Account(
                Name = BUSINESS_ACCOUNT_NAME,
                RecordTypeId = businessRecordTypeId,
                Segment__c = ACCOUNT_SEGMENT_SMB
            )
        };
        insert parentAccounts;
        List<Account> storeAccounts = new List<Account>{
            new Account(
                Name = STORE_ACCOUNT_NAME,
                ParentId = parentAccounts[0].Id,
                RecordTypeId = storeRecordTypeId,
                BillingStreet = ACCOUNT_BILLING_STREET,
                BillingCity = ACCOUNT_BILLING_CITY,
                BillingPostalCode = ACCOUNT_BILLING_POSTAL_CODE,
                BillingCountry = ACCOUNT_BILLING_COUNTRY,
                BillingState = ACCOUNT_BILLING_STATE,
                Segment__c = ACCOUNT_SEGMENT_SMB
            )
        };
        insert storeAccounts;

        Mx_Fraud_Document__c mxFraudDocument = new Mx_Fraud_Document__c(
            Mx_Country__c = MX_COUNTRY_US,
            Mx_Document_Type__c = DOCUMENT_TYPE_PASSPORT,
            Mx_Document_Verification_Status__c = DOCUMENT_STATUS,
            Mx_Document_Verification_Notes__c = CONTENT_VERSION_TITLE,
            Mx_Store_Id__c = storeAccounts[0].Id
        );
        insert mxFraudDocument;

        ContentVersion newContentVersion = new ContentVersion(
            IsMajorVersion = true,
            PathOnClient = CONTENT_VERSION_PATH_ON_CLIENT,
            Mx_Fraud_Document__c = mxFraudDocument.Id,
            Related_To_Id__c = storeAccounts[0].Id,
            Title = CONTENT_VERSION_TITLE,
            VersionData = Blob.valueOf(CONTENT_VERSION_TITLE)
        );
        insert newContentVersion;

        Test.startTest();
        List<ContentVersion> results = ContentVersionsSelector.newInstance()
            .selectByRelatedStoreIds(new Set<Id>{ storeAccounts[0].Id });
        Test.stopTest();

        System.assertEquals(1, results.size(), ASSERT_MESSAGE_CONTENT_VERSION_NOT_RETURNED);
    }
}