sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>LEM-808, LEM-18931: This field is to indicate the Product Family of a new Campaign Product.</description>
    <inlineHelpText>Indicates the &apos;product family&apos;, or product category, under which the campaign product falls.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ads</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>DashPass</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Promos</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>Storefront</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Weblinks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-625: This field is used to track the Status of the Campaign Product.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/Product_Insights__c.object-meta.xml
<CustomObject>
    <description>LEM-623: Product Insights object that helps track insights against Opportunity, Account or Initiative to capture Merchant Insights for an active DoorDash product</description>
    <label>Product Insights</label>
    <nameField>
        <displayFormat>PDI-{0}</displayFormat>
        <label>Product Insight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Insights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-623: Lookup on Account for the current Insight obtained on the Product</description>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A product insight cannot be associated to a Store Account. Please choose a Business Account and try again.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <description>LEM-623: Captures the level of Interest for a Merchant with whom Product discussions were initiated.</description>
    <inlineHelpText>Indicates the overall Merchant interest level for the campaign product.</inlineHelpText>
    <label>Interest Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested at All</fullName>
            </value>
            <value>
                <fullName>Somewhat Uninterested</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Interested</fullName>
            </value>
            <value>
                <fullName>Very Interested</fullName>
            </value>
            <value>
                <fullName>To Be Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>LEM-623: Field to capture the origin of the Product discussion with a potential Mx.</description>
    <inlineHelpText>Indicates which party initiated the discussion of the campaign product.</inlineHelpText>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mx Initiated</fullName>
            </value>
            <value>
                <fullName>Pitched By DoorDash</fullName>
            </value>
            <value>
                <fullName>VSP Recommendation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>LEM-623: Capture if the Merchant is interested in purchasing the Product under discussion.</description>
    <inlineHelpText>Indicates the Merchant’s interest following the campaign product discussion.</inlineHelpText>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Outcome_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Reason__c</fullName>
    <description>LEM-623: Captures the reason for the Outcome of a discussion with a potential Merchant.</description>
    <inlineHelpText>Indicates the reason for the Outcome.</inlineHelpText>
    <label>Outcome Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aligns with Business Needs</fullName>
            </value>
            <value>
                <fullName>Aligns with Sales/Volume Goals</fullName>
            </value>
            <value>
                <fullName>Better Offering from Competitor</fullName>
            </value>
            <value>
                <fullName>Cost Efficient</fullName>
            </value>
            <value>
                <fullName>DD Operational Concerns</fullName>
            </value>
            <value>
                <fullName>Increased Visibility</fullName>
            </value>
            <value>
                <fullName>Lack of Integration</fullName>
            </value>
            <value>
                <fullName>Mx Operational Concerns</fullName>
            </value>
            <value>
                <fullName>Negative Previous Experience</fullName>
            </value>
            <value>
                <fullName>Not Bought into Value Prop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Price Concerns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-623: Lookup on Campaign Product on Insight</description>
    <label>Solutions</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Product Insight cannot be associated with an inactive Campaign Product. Please choose an active Campaign Product and try again.</errorMessage>
        <filterItems>
            <field>Campaign_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT(Product__r.Product_Family__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/triggerHandlers/ProductInsightsHandlerTest.cls
/**
 * @description Test class for ProductInsightsHandler
 * @author Deloitte
 * @date 06/04/2022
 */
@isTest(SeeAllData=false)
public class ProductInsightsHandlerTest {

    /**
     * @description SuppressWarnings are being used as the Handler is being used to perform
     *              calls to Domain methods and no updates are directly performed using the
     *              handler method.
     *              The suppress warning used helps bypass the PMD Rule error for mandatory
     *              assert statements for unit tests
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsightsAreInsertedThenBeforeInsertIsCalled() {
        //ARRANGE
        Account parentAccount = new Account(Id = fflib_IDGenerator.generate(Account.SObjectType));
        Product_Insights__c[] newInsights = new List<Product_Insights__c>{
            new Product_Insights__c(
                Id = fflib_IDGenerator.generate(Product_Insights__c.SObjectType),
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            ),
            new Product_Insights__c(
                Id = fflib_IDGenerator.generate(Product_Insights__c.SObjectType),
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            )
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IProductInsights insightsMocks = (IProductInsights) mocks.mock(IProductInsights.class);
        mocks.startStubbing();
        mocks.when(insightsMocks.getType()).thenReturn(Schema.Product_Insights__c.SObjectType);
        mocks.stopStubbing();
        Application.Domain.setMock(insightsMocks);

        fflib_SObjectDomain.Test.Database.onInsert(newInsights);
        fflib_SObjectDomain.triggerHandler(ProductInsightsHandler.class);

        //ACT
        ((IProductInsights) mocks.verify(insightsMocks, 1)).autopopulateAccountOnInsights();
        ((IProductInsights) mocks.verify(insightsMocks, 1)).compareRecordsForUniqueCombinations();
    }

    /**
     * @description SuppressWarnings are being used as the Handler is being used to perform
     *              calls to Domain methods and no updates are directly performed using the
     *              handler method.
     *              The suppress warning used helps bypass the PMD Rule error for mandatory
     *              assert statements for unit tests
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenInsightsAreUpdatedThenBeforeUpdateIsCalled() {
        //ARRANGE
        Account parentAccount = new Account(Id = fflib_IDGenerator.generate(Account.SObjectType));
        Id productInsight1 = fflib_IDGenerator.generate(Product_Insights__c.SObjectType);
        Id productInsight2 = fflib_IDGenerator.generate(Product_Insights__c.SObjectType);
        Product_Insights__c[] oldInsights = new List<Product_Insights__c>{
            new Product_Insights__c(
                Id = productInsight1,
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            ),
            new Product_Insights__c(
                Id = productInsight2,
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            )
        };
        Product_Insights__c[] newInsights = new List<Product_Insights__c>{
            new Product_Insights__c(
                Id = productInsight1,
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            ),
            new Product_Insights__c(
                Id = productInsight2,
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested'
            )
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IProductInsights insightsMocks = (IProductInsights) mocks.mock(IProductInsights.class);
        mocks.startStubbing();
        mocks.when(insightsMocks.getType()).thenReturn(Schema.Product_Insights__c.SObjectType);
        mocks.stopStubbing();
        Application.Domain.setMock(insightsMocks);

        fflib_SObjectDomain.Test.Database.onUpdate(newInsights, new Map<Id, SObject>(oldInsights));
        fflib_SObjectDomain.triggerHandler(ProductInsightsHandler.class);

        //ACT
        ((IProductInsights) mocks.verify(insightsMocks, 1)).autopopulateAccountOnInsights();
        ((IProductInsights) mocks.verify(insightsMocks, 1)).compareRecordsForUniqueCombinations();
    }

    @isTest
    private static void testWhenInsightIsInsertedThenTriggerIsCalled() {
        //ARRANGE
        Account parentAccount = new Account(Name = 'Test Account ',Segment__c ='SMB');
        insert parentAccount;

        List<Campaign_Product__c> productRecords = new List<Campaign_Product__c>{
            new Campaign_Product__c(
                Name = 'Test Product 1',
                Product_Family__c = 'Ads',
                Status__c = 'Active'
            ),
            new Campaign_Product__c(
                Name = 'Test Product 2',
                Product_Family__c = 'Ads',
                Status__c = 'Active'
            )
        };
        insert productRecords;

        Product_Insights__c[] newInsights = new List<Product_Insights__c>{
            new Product_Insights__c(
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested',
                Product__c = productRecords[0].Id
            ),
            new Product_Insights__c(
                Account_Name__c = parentAccount.Id,
                Outcome_Reason__c = 'Competitor',
                Interest_Level__c = 'Neutral',
                Origin__c = 'Mx Initiated',
                Outcome__c = 'Interested',
                Product__c = productRecords[1].Id
            )
        };
        insert newInsights;

        System.assertNotEquals(null, newInsights[0].Id, 'The Record Id is null');
    }

    @isTest
    private static void testWhenClassInstantiatesThenCheck() {
        //Constructor call
        List<Product_Insights__c> insightsList = new List<Product_Insights__c>();
        ProductInsightsHandler insightsHandlerObject = new ProductInsightsHandler(insightsList);

        //Inner Class Constructor Call
        ProductInsightsHandler.Constructor objConstructor = new ProductInsightsHandler.Constructor();
        objConstructor.construct(insightsList);
        System.assertNotEquals(
            insightsHandlerObject,
            objConstructor.construct(insightsList),
            'The two constructs should not be similar'
        );
    }
}