sfdx-source/force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-94: This field helps categorise the Mx into Enterprise, Mid-market or SMB.</description>
    <inlineHelpText>Signifies the segment of the Mx. The segment is automatically set based on parent account&apos;s segment</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account/fields/Xref__c.field-meta.xml
<CustomField>
    <fullName>Xref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xref</label>
    <referenceTo>Xref__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>LEM-15222: This custom object represents the plan with in specific timeframe, will hold the selected VSP recommendations and will be associated with the business account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the associated account.</description>
    <inlineHelpText>The account with which the Account Plan is associated.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to indicate whether the Account Plan is Active or Inactive</description>
    <inlineHelpText>Indicates whether the Account Plan is Active or Inactive.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/tests/classes/unit/selectors/AccountPlansSelectorTest.cls
/**
 * @author Deloitte
 * @date 07/08/2024
 * @description Test class for AccountPlansSelector class.
 */
@isTest(seeAllData=false)
private class AccountPlansSelectorTest {
    private static final String ACCOUNT_BILLING_CITY = 'Missoula';
    private static final String ACCOUNT_BILLING_COUNTRY = 'United States';
    private static final String ACCOUNT_BILLING_POSTAL_CODE = '1234';
    private static final String ACCOUNT_BILLING_STATE = 'California';
    private static final String ACCOUNT_BILLING_STREET = '221B Baker Street';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: There is a mismatch in fields list';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: The object type must be Xref__c';
    private static final String BUSINESS_ACCOUNT_NAME = 'Test Business Account';
    private static final String ACTIVE = 'Active';
    private static final String INACTIVE = 'Inactive';
    private static final String ACCOUNT_PLAN_NAME = 'Acc Q1 Netflix';
    private static final String ACCOUNT_SEGMENT_SMB= 'SMB';

    /**
     * @description To test Contructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheckSObjectTypeAndFieldList() {
        AccountPlansSelector accountPlansInstance = new AccountPlansSelector();
        Schema.SObjectType typeOfObject = accountPlansInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = accountPlansInstance.getSObjectFieldList();
        AccountPlansSelector.newInstance();
        System.assertEquals(
            Schema.Account_Plan__c.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Account_Plan__c.Id,
                Account_Plan__c.Name,
                Account_Plan__c.Status__c,
                Account_Plan__c.Account__c
            },
            sObjectFields,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }

    /**
     * @description To test when account ids are passed then active account plans are returned.
     */
    @isTest
    private static void testWhenAccountIdPassedThenActiveAccountPlanRetrieved() {
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account businessAccount = new Account(
            Name = BUSINESS_ACCOUNT_NAME,
            RecordtypeId = businessRecordTypeId,
            BillingStreet = ACCOUNT_BILLING_STREET,
            BillingCity = ACCOUNT_BILLING_CITY,
            BillingState = ACCOUNT_BILLING_STATE,
            BillingPostalCode = ACCOUNT_BILLING_POSTAL_CODE,
            BillingCountry = ACCOUNT_BILLING_COUNTRY,
            Segment__c = ACCOUNT_SEGMENT_SMB
        );
        insert businessAccount;

        Account_Plan__c accountPlan = new Account_Plan__c(
            Name = ACCOUNT_PLAN_NAME,
            Status__c = ACTIVE,
            Account__c = businessAccount.Id
        );
        insert accountPlan;

        AccountPlansSelector accountPlansInstance = new AccountPlansSelector();
        List<Account_Plan__c> activeAccountPlans = accountPlansInstance.selectActiveAccountPlanByAccounts(
            new Set<Id>{ businessAccount.Id }
        );

        System.assertEquals(1, activeAccountPlans.size(), 'Account Plan List size does not match');
    }

    /**
     * @description To test when account ids are passed then inactive account plans are not returned.
     */
    @isTest
    private static void testWhenAccountIdPassedThenInActiveAccountPlanNotReturned() {
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Business')
            .getRecordTypeId();
        Account businessAccount = new Account(
            Name = BUSINESS_ACCOUNT_NAME,
            RecordtypeId = businessRecordTypeId,
            BillingStreet = ACCOUNT_BILLING_STREET,
            BillingCity = ACCOUNT_BILLING_CITY,
            BillingState = ACCOUNT_BILLING_STATE,
            BillingPostalCode = ACCOUNT_BILLING_POSTAL_CODE,
            BillingCountry = ACCOUNT_BILLING_COUNTRY,
            Segment__c = ACCOUNT_SEGMENT_SMB
        );
        insert businessAccount;

        Account_Plan__c accountPlan = new Account_Plan__c(
            Name = ACCOUNT_PLAN_NAME,
            Status__c = INACTIVE,
            Account__c = businessAccount.Id
        );
        insert accountPlan;

        AccountPlansSelector accountPlansInstance = new AccountPlansSelector();
        List<Account_Plan__c> activeAccountPlans = accountPlansInstance.selectActiveAccountPlanByAccounts(
            new Set<Id>{ businessAccount.Id }
        );

        System.assertEquals(0, activeAccountPlans.size(), 'Account Plan List size does not match');
    }
}