sfdx-source/force-app/main/default/objects/Account/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648, LEM-14727: It is used to capture the UUID received by Mulesoft in the payload. </description>
    <inlineHelpText>Displays the SSMO UUID of the Mx if one exists.</inlineHelpText>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Inbound_Ingestion_Log__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Ingestion_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14813: It is used to store the associated inbound ingestion log.</description>
    <label>Inbound Ingestion Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>LEM-17453: It is used to store the SSMO unique Id received by Mulesoft in each payload for this Contact.</description>
    <label>SSMO Transactional Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648: It is used to capture the SSMO UUID received by Mulesoft in the payload .</description>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/Inbound_Ingestion_Log__c.object-meta.xml
<CustomObject>
    <description>LEM-14648: Custom Inbound Ingestion Log object for SSMO Integration.</description>
    <label>Inbound Ingestion Log</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inbound Ingestion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Ingestion Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>LEM-17453: It is used to capture the unique Id received by Mulesoft in each payload.</description>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>LEM-14648: It is used to capture the UUID received by Mulesoft in the payload.</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Inbound_Ingestion_Log__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Ingestion_Log__c</fullName>
    <description>LEM-16814: It is used to store related Inbound Ingestion log Id.</description>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inbound Ingestion Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Lead_Conversion_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Conversion_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14727: It stores the Lead conversion type to be either Manual or Auto.</description>
    <label>Lead Conversion Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/SSMO_UUID__c.field-meta.xml
<CustomField>
    <fullName>SSMO_UUID__c</fullName>
    <description>LEM-14186: It stores the SSMO UUID a unique identifier assigned to Salesforce records.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>This field stores the SSMO UUID a unique identifier assigned to Salesforce records</inlineHelpText>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lead/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <description>LEM-17453: It is stores the SSMO unique Id received by Mulesoft in each payload for this Lead.</description>
    <label>SSMO Transactional Unique ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/SSMOLeadConversionServiceImpl.cls
/**
 * @author Deloitte
 * @date 05/16/2024
 * @description Service implementation class for SSMO Lead conversion related logic.
 */
public inherited sharing class SSMOLeadConversionServiceImpl implements ISSMOLeadConversionService {
    private static final Id BUSINESS_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Business')
        .getRecordTypeId();
    private static final String CONTACT_OBJECT = 'Contact';
    private static final String CONVERTED_LEAD_STATUS = 'Converted';
    private static final String LEAD_BUSINESS_ERROR_MESSAGE = 'Lead conversion failed for Onboarding SSMO event';
    private static final String LEAD_CONVERSION_TYPE_AUTO = 'Auto';
    private static final String LEAD_OBJECT = 'Lead';
    private static final String LOG_DOMAIN = 'Sales';
    private static final String LOG_ERROR_CATEGORY_DML = 'Data Validation';
    private static final String LOG_ERROR_CATEGORY_OTHER = 'Other Salesforce Exception';
    private static final String LOG_SALES_DOMAIN = 'Sales';
    private static final String LOG_SELF_SERVING_FALLOUT_SERVICE = 'selfserviceFalloutService';
    private Map<String, Id> matchingIdentifiersToAccountIds;
    private Map<String, Id> matchingIdentifiersToContactIds;
    private Map<Lead, String> matchingLeadsToIdentifiers;

    /**
     * @description Default constructor to instantiate variables.
     */
    public SSMOLeadConversionServiceImpl() {
        this.matchingIdentifiersToAccountIds = new Map<String, Id>();
        this.matchingIdentifiersToContactIds = new Map<String, Id>();
        this.matchingLeadsToIdentifiers = new Map<Lead, String>();
    }

    /**
     * @description It is used to auto convert Leads received from
     * onboarding SSMO scenario by passed Inbound Ingestion Log Ids.
     * @param ingestionLogIds
     * @param payLoadWrapperByIngestionLogUUIDForContactAndACR
     */
    public void autoConvertLeads(
        Set<Id> ingestionLogIds,
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForContactAndACR
    ) {
        Set<String> uniqueIdentifierIds = new Set<String>();
        if (ingestionLogIds == null || ingestionLogIds.isEmpty()) {
            return;
        }
        for (
            Inbound_Ingestion_Log__c eachInboundIngestionLog : InboundIngestionLogsSelector.newInstance()
                .selectById(ingestionLogIds)
        ) {
            uniqueIdentifierIds.add(eachInboundIngestionLog.UUID__c);
        }
        collectSObjectsByUniqueIdentifiers(
            uniqueIdentifierIds,
            payLoadWrapperByIngestionLogUUIDForContactAndACR
        );
        autoConvertMatchingLeads();
    }

    /**
     * @description It is used to auto convert Leads matching unique identifiers from SSMO.
     */
    private void autoConvertMatchingLeads() {
        fflib_ISObjectUnitOfWork unitOfWork = Application.UNITOFWORK.newInstance();
        List<Database.LeadConvert> leadConverts = new List<Database.LeadConvert>();
        Set<String> leadIds = new Set<String>();
        List<Lead> leads = new List<Lead>();
        if (matchingLeadsToIdentifiers.isEmpty() || matchingLeadsToIdentifiers == null) {
            return;
        }
        for (Lead eachMatchingLead : matchingLeadsToIdentifiers.keySet()) {
            unitOfWork.registerDirty(
                new Lead(
                    Id = eachMatchingLead.Id,
                    Lead_Conversion_Type__c = LEAD_CONVERSION_TYPE_AUTO
                )
            );
            leadIds.add(eachMatchingLead.Id);
            Database.LeadConvert currentLeadConvert = new Database.LeadConvert();
            currentLeadConvert.setLeadId(eachMatchingLead.Id);
            currentLeadConvert.setAccountId(
                matchingIdentifiersToAccountIds.get(
                    matchingLeadsToIdentifiers.get(eachMatchingLead)
                )
            );
            currentLeadConvert.setContactId(
                matchingIdentifiersToContactIds.get(
                    matchingLeadsToIdentifiers.get(eachMatchingLead)
                )
            );
            currentLeadConvert.setConvertedStatus(CONVERTED_LEAD_STATUS);
            currentLeadConvert.setDoNotCreateOpportunity(true);
            currentLeadConvert.setSendNotificationEmail(false);
            currentLeadConvert.setOwnerId(UserInfo.getUserId());
            leadConverts.add(currentLeadConvert);
        }
        leads.addAll(matchingLeadsToIdentifiers.keySet());
        commitWork(unitOfWork, leads, leadIds);
        if (!leadConverts.isEmpty() && !Test.isRunningTest()) {
            try {
                Database.convertLead(leadConverts);
            } catch (Exception ex) {
                IInboundIngestionLoggerEntry loggerEntry = InboundIngestionLoggerService.createInboundIngestionLog(
                    LOG_SELF_SERVING_FALLOUT_SERVICE,
                    LOG_SALES_DOMAIN,
                    leads[0].Inbound_Ingestion_Log__c,
                    leads[0].SSMO_UUID__c,
                    leads[0].Unique_Id__c
                );
                InboundIngestionLoggerService.logException(
                    loggerEntry,
                    ex,
                    LEAD_BUSINESS_ERROR_MESSAGE,
                    '',
                    leadIds,
                    LOG_ERROR_CATEGORY_OTHER
                );
            }
        }
    }

    /**
     * @description A common method to commit unit of work.
     * @param unitOfWork
     * @param leads
     * @param leadIds
     */
    private static void commitWork(
        fflib_ISObjectUnitOfWork unitOfWork,
        List<Lead> leads,
        Set<String> leadIds
    ) {
        try {
            unitOfWork.commitWork();
        } catch (Exception e) {
            IInboundIngestionLoggerEntry loggerEntry = InboundIngestionLoggerService.createInboundIngestionLog(
                LOG_SELF_SERVING_FALLOUT_SERVICE,
                LOG_SALES_DOMAIN,
                leads[0].Inbound_Ingestion_Log__c,
                leads[0].SSMO_UUID__c,
                leads[0].Unique_Id__c
            );
            InboundIngestionLoggerService.logException(
                loggerEntry,
                e,
                LEAD_BUSINESS_ERROR_MESSAGE,
                '',
                leadIds,
                LOG_ERROR_CATEGORY_DML
            );
        }
    }

    /**
     * @description It is used to collect Leads using matching unique identifiers.
     * @param uniqueIdentifierIds
     * @param payLoadWrapperByIngestionLogUUIDForContactAndACR
     */
    private void collectSObjectsByUniqueIdentifiers(
        Set<String> uniqueIdentifierIds,
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForContactAndACR
    ) {
        if (uniqueIdentifierIds == null || uniqueIdentifierIds.isEmpty()) {
            return;
        }
        collectLeadRecords(uniqueIdentifierIds, payLoadWrapperByIngestionLogUUIDForContactAndACR);
        for (
            Account eachAccount : AccountsSelector.newInstance()
                .selectAccountsByUniqueIdentifiersAndRecordType(
                    uniqueIdentifierIds,
                    BUSINESS_RECORD_TYPE_ID
                )
        ) {
            matchingIdentifiersToAccountIds.put(eachAccount.Unique_Identifier__c, eachAccount.Id);
        }
        collectContactRecords(
            uniqueIdentifierIds,
            payLoadWrapperByIngestionLogUUIDForContactAndACR
        );
    }

    /**
     * @description It is used to collect Contacts using matched record Contact Ids or
     * matching passed unique identifiers.
     * @param uniqueIdentifierIds
     * @param payLoadWrapperByIngestionLogUUIDForContactAndACR
     */
    private void collectContactRecords(
        Set<String> uniqueIdentifierIds,
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForContactAndACR
    ) {
        Map<Id, String> matchedContactIdToUniqueId = new Map<Id, String>();
        matchedContactIdToUniqueId = InstantIngestionCheckRecordsService.getExistingSObjectsByMatchedRecordId(
            payLoadWrapperByIngestionLogUUIDForContactAndACR,
            CONTACT_OBJECT
        );
        if (matchedContactIdToUniqueId != null || !matchedContactIdToUniqueId.isEmpty()) {
            for (
                Contact eachContact : ContactsSelector.newInstance()
                    .selectById(matchedContactIdToUniqueId.keySet())
            ) {
                matchingIdentifiersToContactIds.put(
                    matchedContactIdToUniqueId.get(eachContact.Id),
                    eachContact.Id
                );
            }
        }
        for (
            Contact eachContact : ContactsSelector.newInstance()
                .selectContactsByUniqueIdentifier(uniqueIdentifierIds)
        ) {
            matchingIdentifiersToContactIds.put(eachContact.Unique_Identifier__c, eachContact.Id);
        }
    }

    /**
     * @description It is used to collect Leads using matched record Lead Ids or
     * matching passed unique identifiers.
     * @param uniqueIdentifierIds
     * @param payLoadWrapperByIngestionLogUUIDForContactAndACR
     */
    private void collectLeadRecords(
        Set<String> uniqueIdentifierIds,
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForContactAndACR
    ) {
        Map<Id, String> matchedRecordLeadIdToUniqueId = new Map<Id, String>();
        matchedRecordLeadIdToUniqueId = InstantIngestionCheckRecordsService.getExistingSObjectsByMatchedRecordId(
            payLoadWrapperByIngestionLogUUIDForContactAndACR,
            LEAD_OBJECT
        );
        if (matchedRecordLeadIdToUniqueId != null || !matchedRecordLeadIdToUniqueId.isEmpty()) {
            for (
                Lead eachLead : LeadsSelector.newInstance()
                    .selectById(matchedRecordLeadIdToUniqueId.keySet())
            ) {
                if (!eachLead.isConverted) {
                    matchingLeadsToIdentifiers.put(
                        eachLead,
                        matchedRecordLeadIdToUniqueId.get(eachLead.Id)
                    );
                }
            }
        }
        for (
            Lead eachLead : LeadsSelector.newInstance()
                .selectByUniqueIdentifiers(uniqueIdentifierIds)
        ) {
            if (!eachLead.isConverted) {
                matchingLeadsToIdentifiers.put(eachLead, eachLead.SSMO_UUID__c);
            }
        }
    }
}