sfdx-source/force-app/main/default/objects/Account/fields/Xref__c.field-meta.xml
<CustomField>
    <fullName>Xref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xref</label>
    <referenceTo>Xref__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/MX_Order__c/MX_Order__c.object-meta.xml
<CustomObject>
    <description>LEM-13509: Custom Order object for Vendor Integration</description>
    <label>Merchant Order</label>
    <nameField>
        <displayFormat>MX{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/MX_Order__c/fields/Work_Step__c.field-meta.xml
<CustomField>
    <fullName>Work_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14054: It is used to store the Work Step associated with the Mx Order.</description>
    <label>Work Step</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipLabel>Merchant Orders</relationshipLabel>
    <relationshipName>Merchant_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStepDependency__c/WorkStepDependency__c.object-meta.xml
<CustomObject>
    <description>LEM-1061: It stores dependencies between WorkSteps. It is used to control status updates of WorkSteps.</description>
    <label>Work Step Dependency</label>
    <nameField>
        <displayFormat>WSD-{0}</displayFormat>
        <label>Work Step Dependency Number</label>
        <startingNumber>1</startingNumber>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Step Dependencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/WorkStepDependency__c/fields/Dependee_Work_Step__c.field-meta.xml
<CustomField>
    <fullName>Dependee_Work_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1061: It indicates dependee Work Step. It drives status updates on dependent WorkSteps.</description>
    <inlineHelpText>Indicates dependee Work Step</inlineHelpText>
    <label>Work Step Name</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipLabel>Dependent Work Steps</relationshipLabel>
    <relationshipName>DependentWorkSteps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStepDependency__c/fields/Dependent_Work_Step__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Work_Step__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1061: It indicates dependent Work Step. It is used for identifying WorkSteps whose status needs to be controlled.</description>
    <inlineHelpText>Indicates dependent Work Step</inlineHelpText>
    <label>Dependent Work Step</label>
    <referenceTo>WorkStep</referenceTo>
    <relationshipLabel>Work Step Dependencies</relationshipLabel>
    <relationshipName>DependeeWorkStepDependencies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/Xref__c.object-meta.xml
<CustomObject>
    <description>LEM-800: Xref is an object that maintains the mapping of business and store accounts to backend product systems.</description>
    <label>Xref</label>
    <nameField>
        <displayFormat>XR - {0000}</displayFormat>
        <label>Xref Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xrefs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Xref__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-800: Represents the ID of the associated backend record.</description>
    <externalId>true</externalId>
    <inlineHelpText>Represents the ID of the associated backend record</inlineHelpText>
    <label>Store ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Xref__c/fields/Salesforce_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Account_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-800: Represents the name of the business or store account in SFDC.</description>
    <inlineHelpText>Represents the name of the business or store account in SFDC</inlineHelpText>
    <label>Salesforce Account Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Xrefs</relationshipLabel>
    <relationshipName>Xrefs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/services/CriteriaServiceImplTest.cls
/**
 * @author Deloitte
 * @date 04/29/2024
 * @description Test class for CriteriaServiceImpl class.
 */
@isTest(SeeAllData=false)
public class CriteriaServiceImplTest {
    private static final String ASSERT_MESSAGE_RELATED_RECORDS_NOT_RETURNED = 'Unexpected Result: Records not returned.';
    private static final String CONTACT_EMAIL_FIELD = 'Email';
    private static final String CONTACT_EMAIL_FIELD_REFERENCE = 'Contact.Email';
    private static final String MOCK_EXTERNAL_ID_VALUE = 'externalIdMock';
    private static final String XREF_EXTERNAL_ID_FIELD = 'External_ID__c';
    private static final String ID_FIELD = 'Id';

    /**
     * @description To test Decision Maker contact details are returned
     * based on passed Work Order Ids and fields.
     */
    @isTest
    private static void testWhenWorkOrderIdsAndFieldsReceivedThenReturnDecisionMakerContactDetails() {
        Id workOrderId = fflib_IDGenerator.generate(WorkOrder.SObjectType);
        Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
        Id contactId = fflib_IDGenerator.generate(Contact.SObjectType);
        List<SObject> workOrders = new List<SObject>{
            new WorkOrder(Id = workOrderId, AccountId = accountId, ContactId = contactId)
        };
        Set<String> sObjectFields = new Set<String>{ CONTACT_EMAIL_FIELD };
        Set<String> sObjectFieldReference = new Set<String>{ CONTACT_EMAIL_FIELD_REFERENCE };
        List<AccountContactRelation> mockACRs = new List<AccountContactRelation>{
            new AccountContactRelation(AccountId = accountId)
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IAccountContactRelationsSelector mockAccountContactRelationsSelector = (IAccountContactRelationsSelector) mocks.mock(
            IAccountContactRelationsSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockAccountContactRelationsSelector.sObjectType())
            .thenReturn(AccountContactRelation.SObjectType);
        mocks.when(
                mockAccountContactRelationsSelector.selectDecisionMakerContactsByAccountIds(
                    new Set<Id>{ accountId },
                    sObjectFieldReference
                )
            )
            .thenReturn(mockACRs);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockAccountContactRelationsSelector);
        Test.startTest();
        Map<Id, List<SObject>> returnedACR = CriteriaService.collectDecisionMakerContactDetails(
            workOrders,
            sObjectFields
        );
        Test.stopTest();
        System.assertEquals(
            new Map<Id, List<SObject>>{ workOrderId => new List<SObject>{ mockACRs[0].Contact } },
            returnedACR,
            ASSERT_MESSAGE_RELATED_RECORDS_NOT_RETURNED
        );
    }

    /**
     * @description To test Xref details are returned
     * based on passed Work Order Ids and fields.
     */
    @isTest
    private static void testWhenWorkOrderIdsAndFieldsReceivedThenReturnXrefDetails() {
        Id workOrderId = fflib_IDGenerator.generate(WorkOrder.SObjectType);
        Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
        List<SObject> newWorkOrders = new List<SObject>{
            new WorkOrder(Id = workOrderId, AccountId = accountId)
        };
        List<Xref__c> mockXrefs = new List<Xref__c>{
            new Xref__c(
                External_ID__c = MOCK_EXTERNAL_ID_VALUE,
                Salesforce_Account_Name__c = accountId
            )
        };
        Set<String> sObjectFields = new Set<String>{ XREF_EXTERNAL_ID_FIELD };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IXrefsSelector mockXrefsSelector = (IXrefsSelector) mocks.mock(IXrefsSelector.class);
        mocks.startStubbing();
        mocks.when(mockXrefsSelector.sObjectType()).thenReturn(Xref__c.SObjectType);
        mocks.when(
                mockXrefsSelector.selectActiveXrefsBySalesforceAccountName(new Set<Id>{ accountId })
            )
            .thenReturn(mockXrefs);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockXrefsSelector);
        Test.startTest();
        Map<Id, List<SObject>> returnedXrefs = CriteriaService.collectXrefDetails(
            newWorkOrders,
            sObjectFields
        );
        Test.stopTest();
        System.assertEquals(
            new Map<Id, List<SObject>>{ workOrderId => new List<SObject>{ mockXrefs[0] } },
            returnedXrefs,
            ASSERT_MESSAGE_RELATED_RECORDS_NOT_RETURNED
        );
    }

    /**
     * @description To test Dependee Work Step details are returned
     * based on passed Work Step Ids and fields.
     */
    @isTest
    private static void testWhenWorkStepIdsAndFieldsReceivedThenReturnDependeeWorkStepDetails() {
        Id workStepId = fflib_IDGenerator.generate(WorkStep.SObjectType);
        Id dependeeWorkStepId = fflib_IDGenerator.generate(WorkStep.SObjectType);
        List<SObject> newWorkSteps = new List<SObject>{ new WorkStep(Id = workStepId) };
        List<WorkStepDependency__c> mockWorkStepDependencies = new List<WorkStepDependency__c>{
            new WorkStepDependency__c(
                Dependee_Work_Step__c = dependeeWorkStepId,
                Dependent_Work_Step__c = workStepId
            )
        };
        Set<String> sObjectFields = new Set<String>{ ID_FIELD };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWorkStepDependenciesSelector mockWorkStepDependenciesSelector = (IWorkStepDependenciesSelector) mocks.mock(
            IWorkStepDependenciesSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockWorkStepDependenciesSelector.sObjectType())
            .thenReturn(WorkStepDependency__c.SObjectType);
        mocks.when(
                mockWorkStepDependenciesSelector.selectDependenciesByDependentWorkStepsIds(
                    new Set<Id>{ workStepId }
                )
            )
            .thenReturn(mockWorkStepDependencies);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockWorkStepDependenciesSelector);
        Test.startTest();
        Map<Id, List<SObject>> returnedWorkStepDependencies = CriteriaService.collectDependeeWorkSteps(
            newWorkSteps,
            sObjectFields
        );
        Test.stopTest();
        System.assertEquals(
            new Map<Id, List<SObject>>{
                workStepId => new List<SObject>{
                    mockWorkStepDependencies[0].Dependent_Work_Step__r
                }
            },
            returnedWorkStepDependencies,
            ASSERT_MESSAGE_RELATED_RECORDS_NOT_RETURNED
        );
    }

    /**
     * @description To test Merchant order details returned based on passed Work Steps and fields.
     */
    @isTest
    private static void testWhenWorkStepsAndFieldsReceivedThenReturnMxOrderDetails() {
        Id workStepId = fflib_IDGenerator.generate(WorkStep.SObjectType);
        Id mxOrderId = fflib_IDGenerator.generate(MX_Order__c.SObjectType);
        List<SObject> newWorkSteps = new List<SObject>{ new WorkStep(Id = workStepId) };
        List<MX_Order__c> mockMxOrders = new List<MX_Order__c>{
            new MX_Order__c(Id = mxOrderId, Work_Step__c = workStepId)
        };
        Set<String> sObjectFields = new Set<String>{ ID_FIELD };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IMerchantOrdersSelector mockMerchantOrdersSelector = (IMerchantOrdersSelector) mocks.mock(
            IMerchantOrdersSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockMerchantOrdersSelector.sObjectType()).thenReturn(MX_Order__c.SObjectType);
        mocks.when(
                mockMerchantOrdersSelector.selectByWorkStepIds(
                    new Set<Id>{ workStepId },
                    sObjectFields
                )
            )
            .thenReturn(mockMxOrders);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockMerchantOrdersSelector);
        Test.startTest();
        Map<Id, List<SObject>> returnedMxOrders = CriteriaService.collectMxOrders(
            newWorkSteps,
            sObjectFields
        );
        Test.stopTest();
        System.assertEquals(
            new Map<Id, List<SObject>>{ workStepId => mockMxOrders },
            returnedMxOrders,
            ASSERT_MESSAGE_RELATED_RECORDS_NOT_RETURNED
        );
    }
}