sfdx-source/force-app/main/default/objects/AQS_AA_Enablement_IDs__c/AQS_AA_Enablement_IDs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the ID&apos;s  used by the SBAA Enablement unmanaged package. Includes Quote record type ID&apos;s that are referenced by the &quot;Advanced Approvals Status and Record Update&quot; as well as the ID of the logo referenced by the advanced approval email templates</description>
    <label>AQS AA Enablement ID&apos;s</label>
</CustomObject>

sfdx-source/force-app/main/default/objects/AQS_AA_Enablement_IDs__c/fields/AQS_Approval_Email_Logo_ID__c.field-meta.xml
<CustomField>
    <fullName>AQS_Approval_Email_Logo_ID__c</fullName>
    <description>Contains the ID of the image used by VisualForce email templates as part of the SBAA Quote Enablement Package. Update this to the ID of the image that will be displayed as a logo on approval requests and notifications.</description>
    <inlineHelpText>Contains the ID of the image used by VisualForce email templates as part of the SBAA Quote Enablement Package. Update this to the ID of the image that will be displayed as a logo on approval requests and notifications.</inlineHelpText>
    <label>AQS Approval Email Logo ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/AQS_AA_Enablement_IDs__c/fields/AQS_Approved_Quote_RT__c.field-meta.xml
<CustomField>
    <fullName>AQS_Approved_Quote_RT__c</fullName>
    <description>Contains the ID for the Approved record type of the CPQ quote object. Update when installing into new environments.</description>
    <inlineHelpText>Contains the ID for the Approved record type of the CPQ quote object. Update when installing into new environments.</inlineHelpText>
    <label>AQS Approved Quote RT</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/tests/classes/unit/controllers/AQS_AAEnablementHomeControllerTest.cls
/**
 * @author ATG
 * @date 2022-04-20
 * @description This is test class for AQS_AAEnablementHomeController class
 */
//We use See all data = true, because we want to test the email templates that are installed in this org with the Advanced Approvals package.
@isTest
private class AQS_AAEnablementHomeControllerTest {

    /**
	* @description To test AQS_AAEnablementHomeController
	*/
    @istest
    static void testWhenUpdateCustomSettingThenCustomSettingsSet() {
        AQS_AAEnablementHomeController aaHomePage = new AQS_AAEnablementHomeController();
        aaHomePage.updateCustomSetting();

        AQS_AA_Enablement_IDs__c recordTypeCustomSetting = AQS_AA_Enablement_IDs__c.getOrgDefaults();
        System.assert(Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('AQS Approved Quote').getRecordTypeId() == recordTypeCustomSetting.AQS_Approved_Quote_RT__c, 'Email templates record types should be set up correctly');
    }

    @istest
    static void testWhenUpdateEmailLogoIdThenIdSet() {
        AQS_AAEnablementHomeController aaHomePage = new AQS_AAEnablementHomeController();
        //We just need a 18 digit ID, it doesn't matter what type.
        Id emailTemplateId1 = Fake.generateId( EmailTemplate.class );
        aaHomePage.recordTypeSetting.AQS_Approval_Email_Logo_ID__c = emailTemplateId1;
        aaHomePage.updateEmailLogoId();

        AQS_AA_Enablement_IDs__c recordTypeCustomSetting = AQS_AA_Enablement_IDs__c.getOrgDefaults();
        System.assert(recordTypeCustomSetting.AQS_Approval_Email_Logo_ID__c == String.valueOf(emailTemplateId1), 'Email templates Logo Id should be set up correctly');
    }

    @istest
    static void testWhenInvalidEmailLogoIdThenIdSet() {
        AQS_AAEnablementHomeController aaHomePage = new AQS_AAEnablementHomeController();
        //Not a 15 or 18 digit ID
        aaHomePage.recordTypeSetting.AQS_Approval_Email_Logo_ID__c = '001';
        aaHomePage.updateEmailLogoId();

        AQS_AA_Enablement_IDs__c recordTypeCustomSetting = AQS_AA_Enablement_IDs__c.getOrgDefaults();
        System.assert(recordTypeCustomSetting.AQS_Approval_Email_Logo_ID__c == '001', 'Email templates Logo Id should be set up correctly');
    }

    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenCreateTemplatesThenCallService() {
        Id emailTemplateId1 = Fake.generateId( EmailTemplate.class );
        Id emailTemplateId2 = Fake.generateId( EmailTemplate.class );

        List<EmailTemplate> emailTemplateList = new List<EmailTemplate>{
			new EmailTemplate(Id = emailTemplateId1, Name = 'emailTemplateId1'),
			new EmailTemplate(Id = emailTemplateId2, Name = 'emailTemplateId2')
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IEmailTemplateSelector emailTemplateSelectorMock = (IEmailTemplateSelector) mocks.mock(
            IEmailTemplateSelector.class
        );
        fflib_ISObjectUnitOfWork mockUOW = ( fflib_ISObjectUnitOfWork ) mocks.mock( fflib_ISObjectUnitOfWork.class );

        mocks.startStubbing();
        mocks.when(emailTemplateSelectorMock.sObjectType()).thenReturn(EmailTemplate.SObjectType);
        mocks.when(emailTemplateSelectorMock.selectByFolderName('AQS AA Email Templates')).thenReturn(emailTemplateList);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(emailTemplateSelectorMock);
        Application.UNITOFWORK.setMock( mockUOW );

        AQS_AAEnablementHomeController controller = new AQS_AAEnablementHomeController();
        controller.createTemplates();

        ( ( fflib_ISObjectUnitOfWork ) mocks.verify( mockUOW, 1 ) ).commitWork();
        ( ( fflib_ISObjectUnitOfWork ) mocks.verify( mockUOW, 1 ) ).registerNew( fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
                sbaa__EmailTemplate__c.Name => 'emailTemplateId1',
                sbaa__EmailTemplate__c.sbaa__templateID__c => emailTemplateId1
            }
        ) );
        ( ( fflib_ISObjectUnitOfWork ) mocks.verify( mockUOW, 1 ) ).registerNew( fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
                sbaa__EmailTemplate__c.Name => 'emailTemplateId2',
                sbaa__EmailTemplate__c.sbaa__templateID__c => emailTemplateId2
            }
        ) );
    }
}