sfdx-source/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>LEM-15222: This custom object represents the plan with in specific timeframe, will hold the selected VSP recommendations and will be associated with the business account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to indicate whether the Account Plan is Active or Inactive</description>
    <inlineHelpText>Indicates whether the Account Plan is Active or Inactive.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>LEM-15224: This field represents the Category of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisements</fullName>
            </value>
            <value>
                <fullName>Discoverability</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Marketplace Products</fullName>
            </value>
            <value>
                <fullName>Menu Optimizations</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Promos</fullName>
            </value>
            <value>
                <fullName>Selection</fullName>
            </value>
            <value>
                <fullName>Sponsored Listings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/IncrementalSales__c.field-meta.xml
<CustomField>
    <fullName>IncrementalSales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the sales value for the campaign Product.</description>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
s
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Metric__c.field-meta.xml
<CustomField>
    <fullName>Metric__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>LEM-15226: It stores metric value for Lever.</inlineHelpText>
    <label>Metric</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Marketing Revenue</fullName>
            </value>
            <value>
                <fullName>Marketplace GMV</fullName>
            </value>
            <value>
                <fullName>Platform Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Number_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stores__c</fullName>
    <description>LEM-15224: It represents the number of stores.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Number of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>LEM-15224: It represents the points of the solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>LEM-808, LEM-18931: This field is to indicate the Product Family of a new Campaign Product.</description>
    <inlineHelpText>Indicates the &apos;product family&apos;, or product category, under which the campaign product falls.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ads</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>DashPass</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Promos</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>Storefront</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Weblinks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>LEM-15224: It represents the Rank of the Solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-625: This field is used to track the Status of the Campaign Product.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It stores type value for Solution.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/VSP_Code__c.field-meta.xml
<CustomField>
    <fullName>VSP_Code__c</fullName>
    <description>LEM-15224: It represents the VSP Code of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>VSP Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/Recommendation_Business__x.object-meta.xml
<CustomObject>
    <description>LEM-13429: It visualizes recommendation record details from vsp_prediction_by_business table.</description>
    <externalDataSource>Figment_Data_Connector</externalDataSource>
    <externalName>public$vsp_predictions_by_business</externalName>
    <label>Business Recommendation</label>
    <pluralLabel>Business Recommendations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-13429: It stores a reference to Business Account records.</description>
    <externalDeveloperName>business_account_id</externalDeveloperName>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VSP_Recommendations_for_Business</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/incremental_sales__c.field-meta.xml
<CustomField>
    <fullName>incremental_sales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>incremental_sales</externalDeveloperName>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/points__c.field-meta.xml
<CustomField>
    <fullName>points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the points of all the stores directly under the business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>decile</externalDeveloperName>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/rank__c.field-meta.xml
<CustomField>
    <fullName>rank__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It calculates based on the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>rank</externalDeveloperName>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the Recommendation Name.</description>
    <externalDeveloperName>product_name</externalDeveloperName>
    <label>Recommendation</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/controllers/SolutionsControllerTest.cls
/**
 * @author Deloitte
 * @date 06/13/2024
 * @description Test class for SolutionsController class.
 */
@isTest(SeeAllData=false)
private class SolutionsControllerTest {
    private static final String MISMATCH_ASSERT_MESSAGE = 'Unexpected result: Solution Id returned does not match the expected outcome.';
    private static final String METRIC = 'Marketing Revenue';
    private static final String CATEGORY = 'Discoverability';
    private static final String ADS_VALUE = 'Ads';
    private static final String ACTIVE_STATUS = 'Active';
    private static final String TYPE = 'Growth';
    /**
     * @description It is used to test when the Business Account Ids are passed it is returning its associated Solutions
     */
    @isTest
    private static void testWhenBusinessAccountIdPassedThenReturnSolutionsWithPredictions() {
        Id accountId = Fake.generateId(Account.class);
        List<String> businessAccountIdList = new List<String>();
        businessAccountIdList.add(accountId);
        Id accountPlanId = Fake.generateId(Account_Plan__c.class);
        Id businessRecommendationId = Fake.generateId(Recommendation_Business__x.class);
        Id solutionId = Fake.generateId(Campaign_Product__c.class);
		SolutionsController.CreateAccountPlanOrAddLeversInputVariables createLeverInputVariables;
        createLeverInputVariables = new SolutionsController.CreateAccountPlanOrAddLeversInputVariables();
		createLeverInputVariables.businessAccountIds = businessAccountIdList;
		createLeverInputVariables.accountPlanId = accountPlanId;
        List<SolutionsController.CreateAccountPlanOrAddLeversInputVariables> solutionControllerInputlist;
        solutionControllerInputlist =  new List<SolutionsController.CreateAccountPlanOrAddLeversInputVariables>();
        solutionControllerInputlist.add(createLeverInputVariables);
        Recommendation_Business__x businessRecommendation = (Recommendation_Business__x) new Fake(
                Recommendation_Business__x.class
            )
            .setField(Recommendation_Business__x.Id, businessRecommendationId)
            .setField(Recommendation_Business__x.Recommendation__c, ADS_VALUE)
            .setField(Recommendation_Business__x.incremental_sales__c, 123)
            .setField(Recommendation_Business__x.Business_Account__c, accountId)
            .setField(Recommendation_Business__x.Business_Account__r.Id, accountId)
            .setField(Recommendation_Business__x.Rank__c, 2)
            .setParent(
                            'Business_Account__r',
                            new Fake(Account.class)
                            .setField(Account.Id,accountId )
                        )
            .toSObject();

        Campaign_Product__c solution = (Campaign_Product__c) new Fake(Campaign_Product__c.class)
            .setField(Campaign_Product__c.Id, solutionId)
            .setField(Campaign_Product__c.VSP_Code__c, ADS_VALUE)
            .setField(Campaign_Product__c.Type__c, TYPE)
            .setField(Campaign_Product__c.Status__c, ACTIVE_STATUS)
            .setField(Campaign_Product__c.Rank__c, 2)
            .setField(Campaign_Product__c.Points__c, 2)
            .setField(Campaign_Product__c.Metric__c, METRIC)
            .setField(Campaign_Product__c.Category__c, CATEGORY)
            .setField(Campaign_Product__c.Name, ADS_VALUE)
            .setField(Campaign_Product__c.Number_of_Stores__c, 1)
            .setField(Campaign_Product__c.Product_Family__c, ADS_VALUE)
            .setField(Campaign_Product__c.IncrementalSales__c, 123)
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISolutionsSelector mocksSolutionsSelector = (ISolutionsSelector) mocks.mock(
            ISolutionsSelector.class
        );
        IBusinessRecommendationsSelector mocksBusinessRecommendationsSelector = (IBusinessRecommendationsSelector) mocks.mock(
            IBusinessRecommendationsSelector.class
        );

        mocks.startStubbing();
        mocks.when(mocksSolutionsSelector.sObjectType())
            .thenReturn(Schema.Campaign_Product__c.SObjectType);
        mocks.when(mocksBusinessRecommendationsSelector.sObjectType())
            .thenReturn(Schema.Recommendation_Business__x.SObjectType);

        mocks.when(
                mocksBusinessRecommendationsSelector.selectBusinessRecommendationsByBusinessAccountIds(
                    new List<String>{ accountId }
                )
            )
            .thenReturn(new List<Recommendation_Business__x>{ businessRecommendation });
        mocks.when(
                mocksSolutionsSelector.selectActiveSolutionsByVSPCodes()
            )
            .thenReturn(new List<Campaign_Product__c>{ solution });

        mocks.stopStubbing();

        Application.SELECTOR.setMock(mocksSolutionsSelector);
        Application.SELECTOR.setMock(mocksBusinessRecommendationsSelector);
        Test.startTest();
        List<AccountLeverEntry> results = SolutionsController.getSolutionsWithPredictionsByBusinessAccounts(
            solutionControllerInputlist
        );
        Test.stopTest();
        System.assertEquals(solutionId, results[0]?.solutions[0].Id, MISMATCH_ASSERT_MESSAGE);
    }

    /**
     * @description It is used to test when the Business Account Ids are passed it does not return associated Solutions
     */
    @isTest
    private static void testWhenBusinessAccountIdPassedThenReturnSolutionsWithoutPredictions() {
        Id accountId = Fake.generateId(Account.class);
        Id businessRecommendationId = Fake.generateId(Recommendation_Business__x.class);
		Id accountPlanId = Fake.generateId(Account_Plan__c.class);
        List<String> businessAccountIdList = new List<String>();
        businessAccountIdList.add(accountId);
        SolutionsController.CreateAccountPlanOrAddLeversInputVariables createLeverInputVariables;
        createLeverInputVariables = new SolutionsController.CreateAccountPlanOrAddLeversInputVariables();
		createLeverInputVariables.businessAccountIds = businessAccountIdList;
		createLeverInputVariables.accountPlanId = accountPlanId;
        List<SolutionsController.CreateAccountPlanOrAddLeversInputVariables> solutionControllerInputlist;
        solutionControllerInputlist =  new List<SolutionsController.CreateAccountPlanOrAddLeversInputVariables>();
        solutionControllerInputlist.add(createLeverInputVariables);
        Recommendation_Business__x businessRecommendation = (Recommendation_Business__x) new Fake(
                Recommendation_Business__x.class
            )
            .setField(Recommendation_Business__x.Id, businessRecommendationId)
            .setField(Recommendation_Business__x.Recommendation__c, 'ads')
            .setField(Recommendation_Business__x.incremental_sales__c, 123)
            .setField(Recommendation_Business__x.Business_Account__c, accountId)
            .setField(Recommendation_Business__x.Business_Account__r.Id, accountId)
            .setField(Recommendation_Business__x.Rank__c, 2)
            .setParent(
                            'Business_Account__r',
                            new Fake(Account.class)
                            .setField(Account.Id,accountId )
                        )
            .toSObject();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISolutionsSelector mocksSolutionsSelector = (ISolutionsSelector) mocks.mock(
            ISolutionsSelector.class
        );
        IBusinessRecommendationsSelector mocksBusinessRecommendationsSelector = (IBusinessRecommendationsSelector) mocks.mock(
            IBusinessRecommendationsSelector.class
        );

        mocks.startStubbing();
        mocks.when(mocksSolutionsSelector.sObjectType())
            .thenReturn(Schema.Campaign_Product__c.SObjectType);
        mocks.when(mocksBusinessRecommendationsSelector.sObjectType())
            .thenReturn(Schema.Recommendation_Business__x.SObjectType);

        mocks.when(
                mocksBusinessRecommendationsSelector.selectBusinessRecommendationsByBusinessAccountIds(
                    new List<String>{ accountId }
                )
            )
            .thenReturn(new List<Recommendation_Business__x>{ businessRecommendation });
        mocks.when(
                mocksSolutionsSelector.selectActiveSolutionsByVSPCodes()
            )
            .thenReturn(new List<Campaign_Product__c>());

        mocks.stopStubbing();

        Application.SELECTOR.setMock(mocksSolutionsSelector);
        Application.SELECTOR.setMock(mocksBusinessRecommendationsSelector);

        Test.startTest();
        List<AccountLeverEntry> results = SolutionsController.getSolutionsWithPredictionsByBusinessAccounts(
            solutionControllerInputlist
        );
        Test.stopTest();
        System.assertEquals(0, results.size(), MISMATCH_ASSERT_MESSAGE);
    }
}