sfdx-source/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>LEM-15222: This custom object represents the plan with in specific timeframe, will hold the selected VSP recommendations and will be associated with the business account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the associated account.</description>
    <inlineHelpText>The account with which the Account Plan is associated.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to indicate whether the Account Plan is Active or Inactive</description>
    <inlineHelpText>Indicates whether the Account Plan is Active or Inactive.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>LEM-15224: It represents the points of the solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>LEM-15224: It represents the Rank of the Solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-625: This field is used to track the Status of the Campaign Product.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It stores type value for Solution.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/VSP_Code__c.field-meta.xml
<CustomField>
    <fullName>VSP_Code__c</fullName>
    <description>LEM-15224: It represents the VSP Code of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>VSP Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/Lever__c.object-meta.xml
<CustomObject>
    <description>LEM-15226: The object will represent the Growth and Operational Levers which get created after reps choose and select from the raw recommendations.</description>
    <label>Lever</label>
    <nameField>
        <displayFormat>LVR-{0000}</displayFormat>
        <label>Lever Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Levers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-15226: It represents the Account linked to the Lever.</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Lever should be associated to account of type Business. Please select Business Account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store associated Account Plan.</description>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Lever_Points__c.field-meta.xml
<CustomField>
    <fullName>Lever_Points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16469: It stores the Lever Points.</description>
    <label>VSP Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15224 : It represents the points of the related solution record.</description>
    <formula>Solution__r.Points__c</formula>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Predicted_Incremental_Sales__c.field-meta.xml
<CustomField>
    <fullName>Predicted_Incremental_Sales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15224 : It represents the Predicted Incremental Sales of the Lever.</description>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16469: It stores the rank of a Lever.</description>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15226: It is used to store the associated Campaign Product.</description>
    <label>Solution</label>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It represents status of the Lever.</description>
    <inlineHelpText>Indicates the status of this Lever.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected by Merchant</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Opportunity/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15222: It is used to store the Account Plan associated with the opportunity.</description>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/Product_Insights__c.object-meta.xml
<CustomObject>
    <description>LEM-623: Product Insights object that helps track insights against Opportunity, Account or Initiative to capture Merchant Insights for an active DoorDash product</description>
    <label>Product Insights</label>
    <nameField>
        <displayFormat>PDI-{0}</displayFormat>
        <label>Product Insight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Insights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the Associated Account Plan.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Lever__c.field-meta.xml
<CustomField>
    <fullName>Lever__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15224: It represents the Lever linked to the Product Insight record.</description>
    <label>Lever</label>
    <referenceTo>Lever__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/Recommendation_Business__x.object-meta.xml
<CustomObject>
    <description>LEM-13429: It visualizes recommendation record details from vsp_prediction_by_business table.</description>
    <externalDataSource>Figment_Data_Connector</externalDataSource>
    <externalName>public$vsp_predictions_by_business</externalName>
    <label>Business Recommendation</label>
    <pluralLabel>Business Recommendations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-13429: It stores a reference to Business Account records.</description>
    <externalDeveloperName>business_account_id</externalDeveloperName>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VSP_Recommendations_for_Business</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/incremental_sales__c.field-meta.xml
<CustomField>
    <fullName>incremental_sales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>incremental_sales</externalDeveloperName>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/points__c.field-meta.xml
<CustomField>
    <fullName>points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the points of all the stores directly under the business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>decile</externalDeveloperName>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/rank__c.field-meta.xml
<CustomField>
    <fullName>rank__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It calculates based on the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>rank</externalDeveloperName>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the Recommendation Name.</description>
    <externalDeveloperName>product_name</externalDeveloperName>
    <label>Recommendation</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/batchables/LeversDataUpdateBatchTest.cls
/**
 * @author Deloitte
 * @date 07/01/2024
 * @description Test class for LeversDataUpdateBatchTest.
 */
@isTest(SeeAllData=false)
private class LeversDataUpdateBatchTest {
    private static final String ACCOUNT_PLAN_NAME = 'Account Plan';
    private static final String ACTIVE = 'Active';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_PREDICTED_INCREMENTAL_SALES = 'Unexpected Result: Mismatch for Predicted Incremental Sales Uplift $ Value.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_POINTS = 'Unexpected Result: Mismatch for Points Value.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected Result: The object type must be Lever.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_RECORD_LIST = 'Unexpected Result: The Levers were not appropriately fetched.';
    private static final String BUSINESS_ACCOUNT_NAME = 'Business Account';
    private static final String BUSINESS = 'Business';
    private static final String IN_PROGRESS = 'In Progress';
    private static final String SEGMENT_SMB = 'SMB';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: There is a mismatch in fields list.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_NUMBER_OF_SOLUTIONS = 'Unexpected result: The number of solutions returned do not match the expected number of solutions.';
    private static final String METRIC = 'Marketing Revenue';
    private static final String CATEGORY = 'Discoverability';
    private static final String ADS_VALUE = 'Ads';
    private static final String ACTIVE_STATUS = 'Active';
    private static final String TYPE = 'Growth';
    private static final String VSP_CODE_VALUE = 'Test';
    private static final String ACCOUNT_NAME = 'Test Account';
    private static final String ACCOUNT_SEGMENT_SMB = 'SMB';
    private static final String NEUTRAL = 'Neutral';
    private static final String PITCHING = 'Pitching';

   @isTest
    private static void testWhenBusinessAccountIdPassedThenReturnSolutionsWithPredictions() {
        Id accountId = Fake.generateId(Account.class);
        List<String> businessAccountIdList = new List<String>();
        businessAccountIdList.add(accountId);
        Id accountPlanId = Fake.generateId(Account_Plan__c.class);
        Id businessRecommendationId = Fake.generateId(Recommendation_Business__x.class);
        Id solutionId = Fake.generateId(Campaign_Product__c.class);
        Id leverId = Fake.generateId(Lever__c.class);
        Id opportunityId = Fake.generateId(Opportunity.class);
        Id productInsightId = Fake.generateId(Product_Insights__c.class);
        Date currentQuarterStartDate;
        Date currentQuarterEndDate;
        Date todayDate= System.today();
        Integer currentQtr = Decimal.valueOf(todayDate.month()).divide(3.0, 0, System.RoundingMode.UP).intValue();
        Date startOfYear = date.newInstance(system.today().year(), 1, 1);
        if(currentQtr == 1) {
            currentQuarterStartDate = startOfYear;
        }else if(currentQtr == 2) {
            currentQuarterStartDate = startOfYear.addMonths(3);
        }else if(currentQtr == 3) {
            currentQuarterStartDate = startOfYear.addMonths(6);
        }else if(currentQtr == 4) {
            currentQuarterStartDate = startOfYear.addMonths(9);
        }
        currentQuarterEndDate = (currentQuarterStartDate.addMonths(3) - 1);

        Recommendation_Business__x businessRecommendation = (Recommendation_Business__x) new Fake(
                Recommendation_Business__x.class
            )
            .setField(Recommendation_Business__x.Id, businessRecommendationId)
            .setField(Recommendation_Business__x.Recommendation__c, ADS_VALUE)
            .setField(Recommendation_Business__x.incremental_sales__c, 123)
            .setField(Recommendation_Business__x.Business_Account__c, accountId)
            .setField(Recommendation_Business__x.Business_Account__r.Id, accountId)
            .setField(Recommendation_Business__x.Rank__c, 2)
            .setField(Recommendation_Business__x.points__c, 3)
            .setParent(
                            'Business_Account__r',
                            new Fake(Account.class)
                            .setField(Account.Id,accountId )
                        )
            .toSObject();


        Lever__c lever = (Lever__c) new Fake(Lever__c.class)
            .setField(Lever__c.Id, leverId)
            .setField(Lever__c.Status__c, ACTIVE_STATUS)
            .setField(Lever__c.Account__c, accountId)
            .setParent(
                            'Account__r',
                            new Fake(Account.class)
                            .setField(Account.Id,accountId )
             	)
            .setField(Lever__c.Predicted_Incremental_Sales__c, 100)
            .setField(Lever__c.Lever_Points__c, 1)
            .setParent(
                    'Account_Plan__r',
                    new Fake(Account_Plan__c.class)
                    .setField(Account_Plan__c.Id, accountPlanId)
                    .setField(Account_Plan__c.Name, ACCOUNT_PLAN_NAME)
                    .setField(Account_Plan__c.Account__c, accountId)
                    .setParent(
                        'Account__r',
                        new Fake(Account.class)
                        .setField(Account.Id,accountId )
                    	)
                    .setField(Account_Plan__c.Status__c, ACTIVE)
                )
            .setParent(
                'Solution__r',
                new Fake(Campaign_Product__c.class)
                .setField(Campaign_Product__c.Id, solutionId)
                .setField(Campaign_Product__c.VSP_Code__c, ADS_VALUE)
                .setField(Campaign_Product__c.Type__c, TYPE)
                .setField(Campaign_Product__c.Status__c, ACTIVE_STATUS)
                .setField(Campaign_Product__c.Rank__c, 2)
                .setField(Campaign_Product__c.Points__c, 2)
                .setField(Campaign_Product__c.Metric__c, METRIC)
                .setField(Campaign_Product__c.Category__c, CATEGORY)
                .setField(Campaign_Product__c.Name, ADS_VALUE)
                .setField(Campaign_Product__c.Number_of_Stores__c, 1)
                .setField(Campaign_Product__c.Product_Family__c, ADS_VALUE)
                .setField(Campaign_Product__c.IncrementalSales__c, 123)
            	)
                .toSObject();

		Product_Insights__c productInsight = (Product_Insights__c) new Fake(Product_Insights__c.class)
                .setField(Product_Insights__c.Id, productInsightId)
                .setField(Product_Insights__c.Interest_Level__c, NEUTRAL)
            	.setField(Product_Insights__c.Predicted_Sales_Uplift__c, 999)
                .setField(Product_Insights__c.Lever__c, leverId)
                .setParent(
                    'Lever__r',
                    new Fake(Lever__c.class)
                        .setField(Lever__c.Id, leverId)
                        .setField(Lever__c.Account__c, accountId)
						.setParent(
                            'Account__r',
                            new Fake(Account.class)
                            .setField(Account.Id,accountId)
             			)
                    	.setField(Lever__c.Solution__c, solutionId)
                        .setParent(
                        'Solution__r',
                            new Fake(Campaign_Product__c.class)
                            .setField(Campaign_Product__c.Id, solutionId)
                            .setField(Campaign_Product__c.VSP_Code__c, ADS_VALUE)
                            .setField(Campaign_Product__c.Type__c, TYPE)
                            .setField(Campaign_Product__c.Status__c, ACTIVE_STATUS)
                            .setField(Campaign_Product__c.Rank__c, 2)
                            .setField(Campaign_Product__c.Points__c, 2)
                            .setField(Campaign_Product__c.Metric__c, METRIC)
                            .setField(Campaign_Product__c.Category__c, CATEGORY)
                            .setField(Campaign_Product__c.Name, ADS_VALUE)
                            .setField(Campaign_Product__c.Number_of_Stores__c, 1)
                            .setField(Campaign_Product__c.Product_Family__c, ADS_VALUE)
                            .setField(Campaign_Product__c.IncrementalSales__c, 123)
            			)

                )
                .setField(Product_Insights__c.Opportunity__c, opportunityId)
            	.setParent(
                    'Opportunity__r',
                    new Fake(Opportunity.class)
                        .setField(Opportunity.Id, opportunityId)
                        .setField(Opportunity.StageName, PITCHING)
                        .setField(Opportunity.AccountId, accountId)
                    	.setField(Opportunity.IsClosed, False)
                )
                .toSobject();

        List<Lever__c> leversList = new List<Lever__c>{ lever };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISolutionsSelector mocksSolutionsSelector = (ISolutionsSelector) mocks.mock(
            ISolutionsSelector.class
        );
        IBusinessRecommendationsSelector mocksBusinessRecommendationsSelector = (IBusinessRecommendationsSelector) mocks.mock(
            IBusinessRecommendationsSelector.class
        );
        LeversSelector mocksLeversSelector = (LeversSelector) mocks.mock(
            LeversSelector.class
        );
        ProductInsightsSelector mocksProductInsightsSelector = (ProductInsightsSelector) mocks.mock(
            ProductInsightsSelector.class
        );
        mocks.startStubbing();

        mocks.when(mocksSolutionsSelector.sObjectType())
            .thenReturn(Schema.Campaign_Product__c.SObjectType);

        mocks.when(mocksBusinessRecommendationsSelector.sObjectType())
            .thenReturn(Schema.Recommendation_Business__x.SObjectType);

  		mocks.when(mocksLeversSelector.sObjectType())
            .thenReturn(Schema.Lever__c.SObjectType);
        mocks.when(mocksProductInsightsSelector.sObjectType())
            .thenReturn(Schema.Product_Insights__c.SObjectType);

        mocks.when(
                mocksBusinessRecommendationsSelector.selectBusinessRecommendationsByBusinessAccountIds(
                    new List<String>{ accountId }
                )
            )
            .thenReturn(new List<Recommendation_Business__x>{ businessRecommendation });

        mocks.when(
                mocksSolutionsSelector.selectActiveSolutionsByVSPCodes()
            )
            .thenReturn(new List<Campaign_Product__c>());

        mocks.when(
                mocksLeversSelector.selectOpenLeversForCurrentQuarter(currentQuarterStartDate, currentQuarterEndDate)
            )
            .thenReturn(new List<Lever__c>{ lever });

        mocks.when(
            mocksProductInsightsSelector.selectProductInsightsByLeverIdWithOpenOpportunity(new Set<Id>{lever.Id})
            )
            .thenReturn(new List<Product_Insights__c>{ productInsight });

        mocks.stopStubbing();

        Application.SELECTOR.setMock(mocksBusinessRecommendationsSelector);
        Application.SELECTOR.setMock(mocksSolutionsSelector);
        Application.SELECTOR.setMock(mocksLeversSelector);
        Application.SELECTOR.setMock(mocksProductInsightsSelector);

        LeversDataUpdateBatch scheduler = new LeversDataUpdateBatch();
        scheduler.start(null);
        scheduler.execute(null, leversList);
        scheduler.finish(null);

        System.assertEquals(123, lever.Predicted_Incremental_Sales__c, ASSERT_MESSAGE_MISMATCH_IN_PREDICTED_INCREMENTAL_SALES);
        System.assertEquals(3, lever.Lever_Points__c, ASSERT_MESSAGE_MISMATCH_IN_POINTS);
        System.assertEquals(123, productInsight.Predicted_Sales_Uplift__c, ASSERT_MESSAGE_MISMATCH_IN_PREDICTED_INCREMENTAL_SALES);
    }

    @isTest
    static void testWhenBatchIsScheduledThenIncrementalSalesUpliftUpdated() {
        String cronExp = '0 0 1 * * ?';
        Test.startTest();
        String jobId = System.schedule(
            LeversDataUpdateBatchTest.class.getName(),
            cronExp,
            new LeversDataUpdateBatch()
        );
        Test.stopTest();
        CronTrigger cronTriggerRecord = [
            SELECT Id, CronExpression, TimesTriggered, NextFireTime
            FROM CronTrigger
            WHERE Id = :jobId
        ];
        System.assertEquals(
            Time.newInstance(1, 0, 0, 0),
            cronTriggerRecord.NextFireTime.time(),
            'The Batch has not been triggered yet'
        );
    }
}