sfdx-source/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>LEM-15222: This custom object represents the plan with in specific timeframe, will hold the selected VSP recommendations and will be associated with the business account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the associated account.</description>
    <inlineHelpText>The account with which the Account Plan is associated.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to indicate whether the Account Plan is Active or Inactive</description>
    <inlineHelpText>Indicates whether the Account Plan is Active or Inactive.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-625: This field is used to track the Status of the Campaign Product.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/VSP_Code__c.field-meta.xml
<CustomField>
    <fullName>VSP_Code__c</fullName>
    <description>LEM-15224: It represents the VSP Code of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>VSP Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <description>LEM-596,LEM-14667: Initiative object to capture the various initiatives taken against a Mx (Business Account).Renamed to Mx Touchpoint.</description>
    <label>Mx Touchpoint</label>
    <nameField>
        <label>Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mx Touchpoints</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM 596: Relationship to Account on Initiative record</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account selected is not a Business Account. Please select an associated Business Account to save the Initiative.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Initiative__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-624: Lookup on Opportunity to create multiple Initiatives for a given Opportunity</description>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/Lever__c.object-meta.xml
<CustomObject>
    <description>LEM-15226: The object will represent the Growth and Operational Levers which get created after reps choose and select from the raw recommendations.</description>
    <label>Lever</label>
    <nameField>
        <displayFormat>LVR-{0000}</displayFormat>
        <label>Lever Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Levers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-15226: It represents the Account linked to the Lever.</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Lever should be associated to account of type Business. Please select Business Account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Confidence_Level__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Level__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It indicates the confidence level of Lever.</description>
    <inlineHelpText>Indicates the confidence level of Implementing this Lever.</inlineHelpText>
    <label>Confidence Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Certain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It indicates interest level of Lever.</description>
    <inlineHelpText>Indicates the Mx interest level in implementing this Lever.</inlineHelpText>
    <label>Interest Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Evaluated</fullName>
                <default>true</default>
                <label>To Be Evaluated</label>
            </value>
            <value>
                <fullName>Not Interested At All</fullName>
            </value>
            <value>
                <fullName>Somewhat Disinterested</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Interested</fullName>
            </value>
            <value>
                <fullName>Very Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Predicted_Incremental_Sales__c.field-meta.xml
<CustomField>
    <fullName>Predicted_Incremental_Sales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15224 : It represents the Predicted Incremental Sales of the Lever.</description>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
     <fullName>Rejection_Reason__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It indicates to rejection the Solution.</description>
    <inlineHelpText>Indicates why the Merchant rejected the Solution, if applicable.</inlineHelpText>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Better Offering from Competitor</fullName>
            </value>
            <value>
                <fullName>DD Operational Concerns</fullName>
            </value>
            <value>
                <fullName>Lack of Integration</fullName>
            </value>
            <value>
                <fullName>Mx Operational Concerns</fullName>
            </value>
            <value>
                <fullName>Negative Previous Experience</fullName>
            </value>
            <value>
                <fullName>Not Bought into Value Prop</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Price Concerns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15226: It is used to store the associated Campaign Product.</description>
    <label>Solution</label>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/Product_Insights__c.object-meta.xml
<CustomObject>
    <description>LEM-623: Product Insights object that helps track insights against Opportunity, Account or Initiative to capture Merchant Insights for an active DoorDash product</description>
    <label>Product Insights</label>
    <nameField>
        <displayFormat>PDI-{0}</displayFormat>
        <label>Product Insight Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Insights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-623: Lookup on Initiative Object to create Insights against an Initiative taken by DoorDash with an Mx Business Account</description>
    <label>Mx touchpoint</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <description>LEM-623: Captures the level of Interest for a Merchant with whom Product discussions were initiated.</description>
    <inlineHelpText>Indicates the overall Merchant interest level for the campaign product.</inlineHelpText>
    <label>Interest Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested at All</fullName>
            </value>
            <value>
                <fullName>Somewhat Uninterested</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Somewhat Interested</fullName>
            </value>
            <value>
                <fullName>Very Interested</fullName>
            </value>
            <value>
                <fullName>To Be Evaluated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Lever__c.field-meta.xml
<CustomField>
    <fullName>Lever__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15224: It represents the Lever linked to the Product Insight record.</description>
    <label>Lever</label>
    <referenceTo>Lever__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-623: Lookup to Opportunity to create an Insight against an Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Product_Insights__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-623: Lookup on Campaign Product on Insight</description>
    <label>Solutions</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Product Insight cannot be associated with an inactive Campaign Product. Please choose an active Campaign Product and try again.</errorMessage>
        <filterItems>
            <field>Campaign_Product__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Product Insights</relationshipLabel>
    <relationshipName>Product_Insights</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/ProductInsightsSelector.cls
/**
 * @description Selector Class for Product Insights
 * @author Deloitte
 * @date 11/04/2022
 */
public inherited sharing class ProductInsightsSelector extends fflib_SObjectSelector implements IProductInsightsSelector {
    /**
     * @description Default Constructor for the Product Insights Selector Class
     * @return IProductInsightsSelector - Interface of IProductsSelector
     */
    public static IProductInsightsSelector newInstance() {
        return (IProductInsightsSelector) Application.Selector.newInstance(
            Product_Insights__c.SObjectType
        );
    }

    /**
     * @description This method is used for getting fields on Product Insights Object
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Product_Insights__c.Id,
            Product_Insights__c.Name,
            Product_Insights__c.Product__c,
            Product_Insights__c.Product__r.Name,
            Product_Insights__c.Opportunity__c,
            Product_Insights__c.Initiative__c
        };
    }

    /**
     * @description This method is used for getting Object Type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Product_Insights__c.SObjectType;
    }

    /**
     * @description This method is used for getting Product Insights based on Id
     * @param setIds
     * @return list of Insight records
     */
    public List<Product_Insights__c> selectById(Set<Id> setIds) {
        return (List<Product_Insights__c>) selectSObjectsById(setIds);
    }

    /**
     * @description It is used for getting Product Insights and related Lever details by the
     * passed Ids.
     * @param productInsightIds
     * @return List<Product_Insights__c>
     */
    public List<Product_Insights__c> selectProductInsightsAndLeversById(Set<Id> productInsightIds) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Interest_Level__c')
            .selectField('Lever__r')
            .selectField('Lever__r.Interest_Level__c')
            .setCondition('Id IN :productInsightIds');
        return (List<Product_Insights__c>) Database.query(query.toSOQL());
    }

    /**
     * @description Query for all Product Insights records present in the system
     * @param parentIds
     * @return List<Product_Insights__c>
     */
    public List<Product_Insights__c> selectAllInsightsWithLookups(Set<Id> parentIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition(
            'Opportunity__c IN :parentIds OR Initiative__c IN :parentIds OR Product__c IN :parentIds'
        );
        return (List<Product_Insights__c>) Database.query(query.toSOQL());
    }

    /**
     * @description Query for all Product Insights related to passed Opportunity Ids.
     * @param opportunityIds
     * @return List<Product_Insights__c>
     */
    public List<Product_Insights__c> selectProductInsightsByOpportunityIds(Set<Id> opportunityIds) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Lever__c')
            .selectField('Lever__r.Name')
            .selectField('Lever__r.Account__c')
            .selectField('Lever__r.Confidence_Level__c')
            .selectField('Lever__r.Interest_Level__c')
            .selectField('Lever__r.Predicted_Incremental_Sales__c')
            .selectField('Lever__r.Rejection_Reason__c')
            .selectField('Lever__r.Solution__c')
            .selectField('Product__r.name')
            .selectField('Product__r.VSP_Code__c')
            .selectField('Opportunity__c')
            .selectField('Lever__r.Status__c')
            .setCondition('Opportunity__c IN :opportunityIds')
        	.setOrdering('Product__r.name', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Product_Insights__c>) Database.query(query.toSOQL());
    }

    /**
     * @description Query for all Product Insights related to passed Opportunity Ids.
     * @param leverIds
     * @param accountPlanIds
     * @return List<Product_Insights__c>
     */
    public List<Product_Insights__c> selectProductInsightsByLeverIdAndAccPlanId(
        Set<Id> leverIds,
        Set<Id> accountPlanIds
    ) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Lever__c')
            .selectField('Id')
            .selectField('Lever__r.Name')
            .selectField('Lever__r.Account__c')
            .selectField('Lever__r.Confidence_Level__c')
            .selectField('Lever__r.Interest_Level__c')
            .selectField('Lever__r.Predicted_Incremental_Sales__c')
            .selectField('Lever__r.Rejection_Reason__c')
            .selectField('Lever__r.Solution__c')
            .selectField('Lever__r.Status__c')
            .setCondition('Lever__c IN :leverIds AND Lever__r.Account_Plan__c IN :accountPlanIds');
        return (List<Product_Insights__c>) Database.query(query.toSOQL());
    }

    /**
     * @description Query for all Product Insights related to passed Lever Ids.
     * @param leverIds
     * @return List<Product_Insights__c>
     */
    public List<Product_Insights__c> selectProductInsightsByLeverIdWithOpenOpportunity(
        Set<Id> leverIds
    ) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Id')
            .selectField('Predicted_Sales_Uplift__c')
            .selectField('Lever__r.Predicted_Incremental_Sales__c')
            .selectField('Lever__r.Solution__r.VSP_Code__c')
            .selectField('Lever__r.Account__c')
            .setCondition('Lever__c IN :leverIds AND Opportunity__r.IsClosed = false');
        return (List<Product_Insights__c>) Database.query(query.toSOQL());
    }
}