sfdx-source/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>LEM-15222: This custom object represents the plan with in specific timeframe, will hold the selected VSP recommendations and will be associated with the business account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the associated account.</description>
    <inlineHelpText>The account with which the Account Plan is associated.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to indicate whether the Account Plan is Active or Inactive</description>
    <inlineHelpText>Indicates whether the Account Plan is Active or Inactive.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/AccountPlansSelector.cls
/**
 * @author Deloitte
 * @date 07/06/2024
 * @description Selector Class for Account Plans Object.
 */
public inherited sharing class AccountPlansSelector extends fflib_SObjectSelector implements IAccountPlansSelector {
    private static final String ACTIVE = 'Active';
    private static final Integer QUERY_LIMIT = 1;
    /**
     * @description This method is for getting the fields on Account Plan object
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Account_Plan__c.Id,
            Account_Plan__c.Name,
            Account_Plan__c.Status__c,
            Account_Plan__c.Account__c
        };
    }

    /**
     * @description This method is used for getting Object type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Account_Plan__c.SObjectType;
    }

    /**
     * @description This method is used for getting Sobject type Id
     * @param idSet
     * @return List<Account>
     */
    public List<Account_Plan__c> selectById(Set<Id> idSet) {
        return (List<Account_Plan__c>) selectSObjectsById(idSet);
    }

    /**
     * @description This method is used for getting active Account Plans by passing Account Ids.
     * @param accountsWithActiveAccountPlans
     * @return List<Account>
     */
    public List<Account_Plan__c> selectActiveAccountPlanByAccounts(
        Set<Id> accountsWithActiveAccountPlans
    ) {
        fflib_QueryFactory query = newQueryFactory(false)
            .selectField('Account__c')
            .setCondition('Account__c IN :accountsWithActiveAccountPlans AND Status__c = :ACTIVE')
            .setLimit(QUERY_LIMIT);
        return (List<Account_Plan__c>) Database.query(query.toSOQL());
    }

    /**
     * @description default constructor for the AccountPlan Selector class
     * @return IAccountPlansSelector - interface of IAccountPlansSelector
     */
    public static IAccountPlansSelector newInstance() {
        return (IAccountPlansSelector) Application.Selector.newInstance(
            Account_Plan__c.SObjectType
        );
    }
}