sfdx-source/force-app/main/default/objects/Rate_Card__c/Rate_Card__c.object-meta.xml
<CustomObject>
    <description>This is needed to enter Rate Card for Certain Products</description>
    <label>Rate Card</label>
    <nameField>
        <displayFormat>RC-{00}</displayFormat>
        <label>Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Card_Tier__c/Rate_Card_Tier__c.object-meta.xml
<CustomObject>
    <description>This object is set to enter Rate Card Tiers</description>
    <label>Rate Card Tier</label>
    <nameField>
        <displayFormat>RCT-{00}</displayFormat>
        <label>Rate Card Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Card_Tier__c/fields/Fee_Value__c.field-meta.xml
<CustomField>
    <fullName>Fee_Value__c</fullName>
    <description>LEM- 8765 Initial Set up for Rate Card Tiers</description>
    <label>Fee Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Card_Tier__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <description>LEM- 8765 Initial Set up for Rate Card Tiers</description>
    <label>Lower Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Card_Tier__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <description>LEM- 8765 Initial Set up for Rate Card Tiers</description>
    <label>Rate Card</label>
    <referenceTo>Rate_Card__c</referenceTo>
    <relationshipLabel>Rate Card Tiers</relationshipLabel>
    <relationshipName>Rate_Card_Tiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Rate_Card_Tier__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <description>LEM- 8765 Initial Set up for Rate Card Tiers</description>
    <label>Upper Bound</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/RateCardTiersSelector.cls
/**
 * @author DoorDash
 * @date 08/25/2023
 * @description Selector class for Rate_Card_Tier__c object.
 */
public inherited sharing class RateCardTiersSelector extends fflib_SObjectSelector implements IRateCardTiersSelector {
    /**
     * @description Default constructor for the class.
     * @return IRateCardTiersSelector - Returns interface of RateCardTiersSelector
     */
    public static IRateCardTiersSelector newInstance() {
        return (IRateCardTiersSelector) Application.Selector.newInstance(Rate_Card_Tier__c.SObjectType);
    }

    /**
     * @description It is used for getting object type.
     * @return SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Rate_Card_Tier__c.SObjectType;
    }

    /**
     * @description It is for getting the fields of Rate_Card_Tier__c.
     * @return List<Schema.SObjectField> - Rate_Card_Tier__c fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Rate_Card_Tier__c.Id,
            Rate_Card_Tier__c.Lower_Bound__c,
            Rate_Card_Tier__c.Upper_Bound__c,
            Rate_Card_Tier__c.Fee_Value__c,
            Rate_Card_Tier__c.Rate_Card__c
        };
    }
}