sfdx-source/force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/sbaa__Approval__c/fields/Approval_Requested_Reason__c.field-meta.xml
<CustomField>
    <fullName>Approval_Requested_Reason__c</fullName>
    <description>LEM-15260: It is used to store the reason for requesting approvals</description>
    <label>Approval Requested Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/sbaa__Approval__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>LEM-13538: It is used to store the status 'Approve'/'Reject' for Approvals and used in Slack Approval notification.</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/sbaa__Approval__c/fields/AQS_Quote__c.field-meta.xml
<CustomField>
    <fullName>AQS_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote that this approval pertains to</description>
    <inlineHelpText>Quote that this approval pertains to</inlineHelpText>
    <label>AQS Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>AQS_AA_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/fields/Approval_Requested_Reason__c.field-meta.xml
<CustomField>
    <fullName>Approval_Requested_Reason__c</fullName>
    <description>LEM-15260: Field to indicate the reason for requesting approvals</description>
    <inlineHelpText>Indicates the reason for requesting approvals, this field is required when the Quote has to go via approvals</inlineHelpText>
    <label>Approval Requested Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/tests/classes/integration/domains/ApprovalsIntegrationTest.cls
/**
 * @author Deloitte
 * @date 05/02/2024
 * @description Integration Test for Approvals Domain.
 */
@isTest
private class ApprovalsIntegrationTest {
    private static final String APPROVAL_AQS_QUOTE = 'AQS_Quote__c';
    private static final Integer APPROVAL_STEP_ONE = 1;
    private static final Integer APPROVAL_STEP_TWO = 2;
    private static final String APPROVAL_STATUS_APPROVED = 'Approved';
    private static final String APPROVAL_STATUS_REQUESTED = 'Requested';
    private static final String CONSTRUCTOR_ASSERT_MESSAGE = 'Unexpected result: The objects are matching';
    private static final String DATABASE_RECORD_FOUND_ASSERT_MESSAGE = 'Unexpected result: Record are present in database';
    private static final String DATABASE_RECORD_NOT_FOUND_ASSERT_MESSAGE = 'Unexpected result: Record are not present in database';
    private static final String INVALID_ASSERTION = 'Invalid Data';
    private static final String APPROVAL_REQUESTED_REASON = 'Reason to approve the approval';

    /**
     * @description It is used to check whether the callout method is invoked or not.
     */
    @isTest
    private static void testWhenApprovalsInsertedThenStatusUpdated() {
        SBQQ__Quote__c[] quote = new List<SBQQ__Quote__c>{
            new SBQQ__Quote__c(
                Approval_Requested_Reason__c = APPROVAL_REQUESTED_REASON
            )
        };
        insert quote;
        sbaa__Approval__c[] approvals = new List<sbaa__Approval__c>{
            new sbaa__Approval__c(
                sbaa__Status__c = APPROVAL_STATUS_REQUESTED,
                sbaa__RecordField__c = APPROVAL_AQS_QUOTE,
                sbaa__ApprovalStep__c = APPROVAL_STEP_ONE,
                Approval_Status__c = APPROVAL_STATUS_APPROVED,
                AQS_Quote__c = quote[0].Id
            ),
            new sbaa__Approval__c(
                sbaa__Status__c = APPROVAL_STATUS_REQUESTED,
                sbaa__RecordField__c = APPROVAL_AQS_QUOTE,
                sbaa__ApprovalStep__c = APPROVAL_STEP_ONE,
                Approval_Status__c = APPROVAL_STATUS_APPROVED,
                AQS_Quote__c = quote[0].Id
            )
        };
        insert approvals;
        Test.startTest();
        approvals[0].sbaa__ApprovalStep__c = APPROVAL_STEP_TWO;
        update approvals;
        Test.stopTest();
        List<sbaa__Approval__c> approvalRecords = [
            SELECT Id, Name, sbaa__ApprovalStep__c
            FROM sbaa__Approval__c
            WHERE Id = :approvals[0].Id
        ];
        System.assertEquals(
            APPROVAL_STEP_ONE,
            approvalRecords[0].sbaa__ApprovalStep__c,
            INVALID_ASSERTION
        );
    }
}