sfdx-source/force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <description>Holds the integration requests from BAT and sync the data to the heroku and Figment. 
BZAP-18797</description>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>This field will be populated when the COO request sent from product. This status will be updated based coo request status at product.</description>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>approved</fullName>
            </value>
            <value>
                <fullName>ready</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Sfdc_Status__c.field-meta.xml
<CustomField>
    <fullName>Sfdc_Status__c</fullName>
    <description>BZAP-18797 Receive pos integration requests from BAT and process the requests.
Holds the value of status of Integration request</description>
    <label>Sfdc Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/services/IIntegrationRequestsService.cls
/**
 * @author DoorDash
 * @date 06/03/2023
 * @description Service impl class for processing integration requests.
 */
public interface IIntegrationRequestsService {
    /**
     * @description sync child with ir sfdc_status__c and Product_Status__c with the parent integration requests.
     * called from integration request handler
     * @param oldIntReq old integration requests
     * @param newIntReq new int requests.
     */
    void updateParentIntRequest(
        Map<Id, Integration_Request__c> oldIntReq,
        List<Integration_Request__c> newIntReq
    );

    /**
     * @description Publishes events for processing the Integration Requests.
     * @param oldIntReq A map of old Integration_Request__c records.
     * @param newIntReq A list of new Integration_Request__c records.
     * @param retrying Specifies if the method is called from the scheduler.
     */
    void publishEventsForProcessing(
        Map<Id, Integration_Request__c> oldIntReq,
        List<Integration_Request__c> newIntReq,
        Boolean retrying
    );

    /**
     * @description delete old integration request records based on configuration
     */
    void deleteOldRecords();

    /**
     * @description It updates the Integration Requests SFDC Status based on passed Status value.
     * @param integrationRequestIds
     * @param statusToUpdate
     */
    void updateIntegrationRequestsSFDCStatus(Set<Id> integrationRequestIds, String statusToUpdate);
}