sfdx-source/force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <description>Holds the integration requests from BAT and sync the data to the heroku and Figment. 
BZAP-18797</description>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <description>BZAP-18797 Receive pos integration requests from BAT and process the requests.
If the integration type is POS holds the value of type of activations.</description>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS Requests</fullName>
            </value>
            <value>
                <fullName>COO Same Store</fullName>
            </value>
            <value>
                <fullName>Tablet Case Sync</fullName>
            </value>
            <value>
                <fullName>MDS Store Sync</fullName>
            </value>
            <value>
                <fullName>Activation Checklist</fullName>
            </value>
            <value>
                <fullName>Fraud Event</fullName>
            </value>
            <value>
                <fullName>Place It For Me</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Onboarding_Id__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Id__c</fullName>
    <description>BZAP-18797 Receive pos integration requests from BAT and process the requests.
If the integration type is pos holds the value of onboarding Id which is generated in BAT.</description>
    <externalId>true</externalId>
    <label>Onboarding Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/SFDC_Org__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Org__c</fullName>
    <description>BZAP-18797 Receive pos integration requests from BAT and process the requests.
Holds the value of org. whether to process POS integration request in Lemonade or Figment</description>
    <label>SFDC Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lemonade</fullName>
                <default>true</default>
                <label>Lemonade</label>
            </value>
            <value>
                <fullName>Figment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request__c/fields/Sfdc_Status__c.field-meta.xml
<CustomField>
    <fullName>Sfdc_Status__c</fullName>
    <description>BZAP-18797 Receive pos integration requests from BAT and process the requests.
Holds the value of status of Integration request</description>
    <label>Sfdc Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Integration_Request_Processor__e/Integration_Request_Processor__e.object-meta.xml
<CustomObject>
    <description>LEM-25411:Remove POS Process out of Notifier PE.It is important that the Integration Request Processor and Notifier event objects all have the same field shape.</description>
    <label>Integration Request Processor</label>
    <pluralLabel>Integration Request Processors</pluralLabel>
</CustomObject>

sfdx-source/force-app/tests/classes/integration/platformEvents/IntegrationRequestProcessorTest.cls
/**
 * @author BizApps
 * @date 11/26/2024
 * @description Test class for IntegrationRequestProcessor Platform event trigger
 */
@isTest(SeeAllData=false)
public class IntegrationRequestProcessorTest {
    private static final String EVENT_TOPIC_INITIATE_POS_CHILD_WORK_ORDERS_CREATION = 'INITIATE_POS_CHILD_WORK_ORDERS_CREATION';
    private static final String EVENT_BUS_SUBSCRIBER_NAME = 'NotifierEvents';
    private static final String EVENT_BUS_SUBSCRIBER_TYPE = 'ApexTrigger';
    private static final String EVENT_BUS_SUBSCRIBER_TYPE_DOES_NOT_MATCH_ASSERT_MESSAGE = 'Unexpected result: the event bus subscriber Type does not match with ApexTrigger';
    private static final string INTEGRATION_TYPE_POS = 'POS Requests';
    private static final String NOTIFIER_EVENT = 'Integration_Request_Processor__e';
    private static final string ONBOARDING_ID = '222-8888-999-4444';
    private static final String STATUS_PENDING = 'Pending';
    private static final String STORE_ID = '24680';
    private static final string SFDC_ORG_LEMONADE = 'Lemonade';


     /**
      * @description To test IntegrationRequestProcessor events subscription by the trigger handler.
      */
     @isTest
     private static void testWhenWorkOrderProcessorPublishedThenNotifierEventsTriggerListens() {
     	Integration_Request__c irRequest = ServiceIntegrationDataBuilder.createIntegrationRequestInstance(
            STORE_ID
        );
        irRequest.Onboarding_Id__c = ONBOARDING_ID;
        irRequest.SFDC_Org__c = SFDC_ORG_LEMONADE;
        irRequest.Integration_Type__c = INTEGRATION_TYPE_POS;
        irRequest.Sfdc_Status__c = STATUS_PENDING;
        insert irRequest;

         Test.startTest();
         NotifierEventsService.publishBulkEvents(
             new Map<String, List<String>>{
                 EVENT_TOPIC_INITIATE_POS_CHILD_WORK_ORDERS_CREATION => new List<String>{
                     JSON.serialize(new List<String>{ irRequest.ID })
                 }
             }
         );
         Test.stopTest();
         List<EventBusSubscriber> eventBusSubscriberResult = [
             SELECT Name, Type
             FROM EventBusSubscriber
             WHERE Topic = :NOTIFIER_EVENT
         ];
           System.assertEquals(
             EVENT_BUS_SUBSCRIBER_TYPE,
             eventBusSubscriberResult[0].Type,
             EVENT_BUS_SUBSCRIBER_TYPE_DOES_NOT_MATCH_ASSERT_MESSAGE
         );
    }
}