sfdx-source/force-app/main/default/objects/WorkStep/fields/Completed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date_Time__c</fullName>
    <description>LEM-964: Completed Date/Time the work step was first completed.</description>
    <inlineHelpText>Completed Date/Time the work step was first completed</inlineHelpText>
    <label>Completed Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Initial_Owner__c.field-meta.xml
<CustomField>
    <fullName>Initial_Owner__c</fullName>
    <description>LEM-964: First owner of the work step.</description>
    <inlineHelpText>First owner of the work step</inlineHelpText>
    <label>Initial Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Initial_Preparation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Initial_Preparation_Date_Time__c</fullName>
    <description>LEM-793: Indicates the date and time of initial menu preparation.</description>
    <inlineHelpText>Indicates the date and time of initial menu preparation</inlineHelpText>
    <label>Initial Preparation Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Blocked_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Blocked_Date_Time__c</fullName>
    <description>LEM-964: Date/Time timestamp of the last time the work step was blocked.</description>
    <inlineHelpText>Date/Time timestamp of the last time the work step was blocked</inlineHelpText>
    <label>Last Blocked Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Escalation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Escalation_Date_Time__c</fullName>
    <description>LEM-964: Date/Time timestamp of the last time the work step was escalated.</description>
    <inlineHelpText>Date/Time timestamp of the last time the work step was escalated</inlineHelpText>
    <label>Last Escalation Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Prepared_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Prepared_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-793: The last person who prepared the menu.</description>
    <inlineHelpText>The last person who prepared the menu</inlineHelpText>
    <label>Last Prepared By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prepared_Work_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_QA_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_QA_Date_Time__c</fullName>
    <description>LEM-793: Indicates the date and time of last menu QA activity.</description>
    <inlineHelpText>Indicates the date and time of last menu QA activity</inlineHelpText>
    <label>Last QA Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_QAed_By__c.field-meta.xml
<CustomField>
    <fullName>Last_QAed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-793: Person who last QAed the menu.</description>
    <inlineHelpText>Person who last QAed the menu</inlineHelpText>
    <label>Last QAed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>QAed_Work_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Previous_Spent_Days_In_Blocked_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Spent_Days_In_Blocked_Status__c</fullName>
    <defaultValue>0</defaultValue>
    <description>LEM-1489: It is used to store the previous value of Time Spent in blocked (Days) field.</description>
    <label>Previous Spent Days In Blocked Status</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>LEM-964: Start Date/Time the work step was first updated.</description>
    <inlineHelpText>Start Date/Time the work step was first updated</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-977: Indicates the status of the work step.
LEM-1120: Created custom Status field to implement dependency on WorkStep Type field.</description>
    <inlineHelpText>Indicates the status of the work step</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Workable</fullName>
                <default>true</default>
                <label>Not Workable</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - DoorDash to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Mx to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Implemented on the call</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Gone Dark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Time_Spent_In_Blocked_Days_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_In_Blocked_Days_Calculated__c</fullName>
    <description>LEM-964: Number of days the work step remain in Blocked status.
LEM-1489: Changed the data type from number to formula for real-time calculation.</description>
    <formula>IF(
  TEXT(Status__c) = $Label.Work_Step_Status_Blocked,
  ((5 * FLOOR((Today() - DATE(2000, 1, 3)) / 7)
  + MIN(5, MOD(Today() - DATE(2000, 1, 3), 7)))) /*Calculates the number of Working days between the current day and 01/03/2000 - Monday*/
  - ((5 * FLOOR((DATEVALUE(Last_Blocked_Date_Time__c) - DATE(2000, 1, 3)) / 7)
  + MIN(5, MOD(DATEVALUE(Last_Blocked_Date_Time__c) - DATE(2000, 1, 3), 7)))) /*Calculates the number of Working days between the Last Blocked Date and 01/03/2000 - Monday*/
  + Previous_Spent_Days_In_Blocked_Status__c,
  Previous_Spent_Days_In_Blocked_Status__c
)</formula>
    <inlineHelpText>Number of days the work step remain in Blocked status</inlineHelpText>
    <label>Time Spent In Blocked (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/WorkStepsStatusRelatedDatesCalcSrvcImpl.cls
/**
 * @author Deloitte
 * @date 23/05/2022
 * @description Service Implementation class to calculate and update the value of date fields
 * utilized for tracking WorkStep Status changes.
 */
public inherited sharing class WorkStepsStatusRelatedDatesCalcSrvcImpl implements IWorkStepsStatusRelatedDatesCalcService {
    private static final String WORK_STEP_STATUS_NOT_WORKABLE = 'Not Workable';
    private static final String WORK_STEP_STATUS_NOT_STARTED = 'Not Started';
    private static final Set<String> NOT_STARTED_STATUS_VALUES = new Set<String>{
        WORK_STEP_STATUS_NOT_STARTED,
        WORK_STEP_STATUS_NOT_WORKABLE
    };
    private enum Status {
        BLOCKED,
        COMPLETE,
        DEAD,
        ESCALATED,
        IN_PROGRESS,
        NOT_STARTED,
        NOT_WORKABLE,
        QA_COMPLETE,
        READY_FOR_QA
    }
    private static final String WORK_STEP_STATUS_BLOCKED = 'Blocked';
    private static final String WORK_STEP_STATUS_COMPLETE = 'Complete';
    private static final String WORK_STEP_STATUS_COMPLETE_DD_TO_IMPLEMENT_LINK = 'Complete - DoorDash to implement link';
    private static final String WORK_STEP_STATUS_COMPLETE_MX_TO_IMPLEMENT_LINK = 'Complete - Mx to implement link';
    private static final String WORK_STEP_STATUS_COMPLETE_IMPLEMENTED_ON_THE_CALL = 'Complete - Implemented on the call';
    private static final String WORK_STEP_STATUS_DEAD = 'Dead';
    private static final String WORK_STEP_STATUS_ESCALATED = 'Escalated';
    private static final String WORK_STEP_STATUS_IN_PROGRESS = 'In Progress';
    private static final String WORK_STEP_STATUS_QA_COMPLETE = 'QA Complete';
    private static final String WORK_STEP_STATUS_READY_FOR_QA = 'Ready for QA';
    private static final Map<String, Status> STATUSVALUETOENUMVALUES = new Map<String, Status>{
        WORK_STEP_STATUS_BLOCKED => Status.BLOCKED,
        WORK_STEP_STATUS_COMPLETE => Status.COMPLETE,
        WORK_STEP_STATUS_COMPLETE_DD_TO_IMPLEMENT_LINK => Status.COMPLETE,
        WORK_STEP_STATUS_COMPLETE_MX_TO_IMPLEMENT_LINK => Status.COMPLETE,
        WORK_STEP_STATUS_COMPLETE_IMPLEMENTED_ON_THE_CALL => Status.COMPLETE,
        WORK_STEP_STATUS_DEAD => Status.DEAD,
        WORK_STEP_STATUS_ESCALATED => Status.ESCALATED,
        WORK_STEP_STATUS_IN_PROGRESS => Status.IN_PROGRESS,
        WORK_STEP_STATUS_NOT_STARTED => Status.NOT_STARTED,
        WORK_STEP_STATUS_NOT_WORKABLE => Status.NOT_WORKABLE,
        WORK_STEP_STATUS_QA_COMPLETE => Status.QA_COMPLETE,
        WORK_STEP_STATUS_READY_FOR_QA => Status.READY_FOR_QA
    };

    /**
     * @description It is used to calculate and update the value of date fields
     * utilized for tracking WorkStep Status changes.
     * @JIRA# LEM-1489
     * @param newWorkSteps
     * @param oldWorkSteps
     */
    public void updateAssociatedDateTrackingFieldsOnStatusChange(
        List<WorkStep> newWorkSteps,
        Map<Id, WorkStep> oldWorkSteps
    ) {
        if (newWorkSteps == null) {
            return;
        }
        WorkStep oldWorkStep;
        Boolean isWorkStepStarted;
        for (WorkStep eachWorkStep : newWorkSteps) {
            oldWorkStep = oldWorkSteps.get(eachWorkStep.Id);
            updatePreviousSpentDaysInBlockedStatusFieldWhenWorkStepIsUnblocked(
                eachWorkStep,
                oldWorkStep
            );
            isWorkStepStarted = hasUserStartedWorkingOnWorkStep(eachWorkStep, oldWorkStep);
            switch on STATUSVALUETOENUMVALUES.get(eachWorkStep.Status__c) {
                when IN_PROGRESS {
                    if (!isWorkStepStarted) {
                        continue;
                    }
                    updateInitialAuditFields(eachWorkStep, oldWorkStep);
                }
                when COMPLETE {
                    if (isWorkStepStarted) {
                        updateInitialAuditFields(eachWorkStep, oldWorkStep);
                    }
                    eachWorkStep.Completed_Date_Time__c = System.now();
                    updateLastQAedByAndLastQADateTimeFields(eachWorkStep, oldWorkStep);
                }
                when BLOCKED {
                    if (isWorkStepStarted) {
                        updateInitialAuditFields(eachWorkStep, oldWorkStep);
                    }
                    eachWorkStep.Last_Blocked_Date_Time__c = System.now();
                }
                when ESCALATED {
                    if (isWorkStepStarted) {
                        updateInitialAuditFields(eachWorkStep, oldWorkStep);
                    }
                    eachWorkStep.Last_Escalation_Date_Time__c = System.now();
                    updateLastQAedByAndLastQADateTimeFields(eachWorkStep, oldWorkStep);
                }
                when READY_FOR_QA {
                    eachWorkStep.Last_Prepared_By__c = UserInfo.getUserId();
                    if (eachWorkStep.Initial_Preparation_Date_Time__c == null) {
                        eachWorkStep.Initial_Preparation_Date_Time__c = System.now();
                    }
                }
                when QA_COMPLETE {
                    updateLastQAedByAndLastQADateTimeFields(eachWorkStep, oldWorkStep);
                }
                when else {
                    continue;
                }
            }
        }
    }

    /**
     * @description It checks whether the Status is changed from 'Not Started' to any other Status.
     * @JIRA# LEM-1489
     * @param newWorkStep
     * @param oldWorkStep
     * @return Boolean
     */
    private Boolean hasUserStartedWorkingOnWorkStep(WorkStep newWorkStep, WorkStep oldWorkStep) {
        return (NOT_STARTED_STATUS_VALUES.contains(oldWorkStep.Status__c)) &&
            !(NOT_STARTED_STATUS_VALUES.contains(newWorkStep.Status__c));
    }

    /**
     * @description It checks whether the previous Status value is 'Ready for QA'.
     * @JIRA# LEM-1489
     * @param oldWorkStepStatus
     * @return Boolean
     */
    private Boolean isPreviousValueOfStatusReadyForQA(String oldWorkStepStatus) {
        return (oldWorkStepStatus == WORK_STEP_STATUS_READY_FOR_QA);
    }

    /**
     * @description It checks whether the Status is changed from 'Blocked' to any other Status.
     * @JIRA# LEM-1489
     * @param newWorkStep
     * @param oldWorkStep
     * @return Boolean
     */
    private Boolean isWorkStepUnblocked(WorkStep newWorkStep, WorkStep oldWorkStep) {
        return oldWorkStep.Status__c == WORK_STEP_STATUS_BLOCKED &&
            newWorkStep.Status__c != WORK_STEP_STATUS_BLOCKED;
    }

    /**
     * @description It updates the Last QAed By and Last QA Date/Time fields.
     * @JIRA# LEM-1489
     * @param newWorkStep
     * @param oldWorkStep
     */
    private void updateLastQAedByAndLastQADateTimeFields(
        WorkStep newWorkStep,
        WorkStep oldWorkStep
    ) {
        if (!isPreviousValueOfStatusReadyForQA(oldWorkStep.Status__c)) {
            return;
        }
        newWorkStep.Last_QAed_By__c = UserInfo.getUserId();
        newWorkStep.Last_QA_Date_Time__c = System.now();
    }

    /**
     * @description It updates the Previous spent days in blocked status field value with Time spent
     * in blocked days field's previous value when WorkStep is unblocked.
     * @JIRA# LEM-1489
     * @param newWorkStep
     * @param oldWorkStep
     */
    private void updatePreviousSpentDaysInBlockedStatusFieldWhenWorkStepIsUnblocked(
        WorkStep newWorkStep,
        WorkStep oldWorkStep
    ) {
        if (isWorkStepUnblocked(newWorkStep, oldWorkStep)) {
            newWorkStep.Previous_Spent_Days_In_Blocked_Status__c = oldWorkStep.Time_Spent_In_Blocked_Days_Calculated__c;
        }
    }

    /**
     * @description It updates the Start Date/Time and Initial Owner fields
     * when user starts working on the Work Step.
     * @JIRA# LEM-4001
     * @param newWorkStep
     * @param oldWorkStep
     */
    private void updateInitialAuditFields(WorkStep newWorkStep, WorkStep oldWorkStep) {
        if (oldWorkStep.Start_Date_Time__c == null) {
            newWorkStep.Start_Date_Time__c = System.now();
        }
        if (oldWorkStep.Initial_Owner__c == null) {
            newWorkStep.Initial_Owner__c = UserInfo.getName();
        }
    }
}