sfdx-source/force-app/main/default/objects/WorkStep/fields/Completed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date_Time__c</fullName>
    <description>LEM-964: Completed Date/Time the work step was first completed.</description>
    <inlineHelpText>Completed Date/Time the work step was first completed</inlineHelpText>
    <label>Completed Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Initial_Owner__c.field-meta.xml
<CustomField>
    <fullName>Initial_Owner__c</fullName>
    <description>LEM-964: First owner of the work step.</description>
    <inlineHelpText>First owner of the work step</inlineHelpText>
    <label>Initial Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Initial_Preparation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Initial_Preparation_Date_Time__c</fullName>
    <description>LEM-793: Indicates the date and time of initial menu preparation.</description>
    <inlineHelpText>Indicates the date and time of initial menu preparation</inlineHelpText>
    <label>Initial Preparation Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Blocked_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Blocked_Date_Time__c</fullName>
    <description>LEM-964: Date/Time timestamp of the last time the work step was blocked.</description>
    <inlineHelpText>Date/Time timestamp of the last time the work step was blocked</inlineHelpText>
    <label>Last Blocked Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Escalation_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Escalation_Date_Time__c</fullName>
    <description>LEM-964: Date/Time timestamp of the last time the work step was escalated.</description>
    <inlineHelpText>Date/Time timestamp of the last time the work step was escalated</inlineHelpText>
    <label>Last Escalation Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_Prepared_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Prepared_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-793: The last person who prepared the menu.</description>
    <inlineHelpText>The last person who prepared the menu</inlineHelpText>
    <label>Last Prepared By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prepared_Work_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_QA_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_QA_Date_Time__c</fullName>
    <description>LEM-793: Indicates the date and time of last menu QA activity.</description>
    <inlineHelpText>Indicates the date and time of last menu QA activity</inlineHelpText>
    <label>Last QA Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Last_QAed_By__c.field-meta.xml
<CustomField>
    <fullName>Last_QAed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-793: Person who last QAed the menu.</description>
    <inlineHelpText>Person who last QAed the menu</inlineHelpText>
    <label>Last QAed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>QAed_Work_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Previous_Spent_Days_In_Blocked_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Spent_Days_In_Blocked_Status__c</fullName>
    <defaultValue>0</defaultValue>
    <description>LEM-1489: It is used to store the previous value of Time Spent in blocked (Days) field.</description>
    <label>Previous Spent Days In Blocked Status</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>LEM-964: Start Date/Time the work step was first updated.</description>
    <inlineHelpText>Start Date/Time the work step was first updated</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-977: Indicates the status of the work step.
LEM-1120: Created custom Status field to implement dependency on WorkStep Type field.</description>
    <inlineHelpText>Indicates the status of the work step</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Workable</fullName>
                <default>true</default>
                <label>Not Workable</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - DoorDash to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Mx to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Implemented on the call</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Gone Dark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1686: Indicates the overall status of the work plan based on status of the work steps.</description>
    <inlineHelpText>Indicates the overall status of the work plan based on status of the work steps</inlineHelpText>
    <label>Status Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account and Opportunity is a dupe with the same location</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Type is Parent</fullName>
            </value>
            <value>
                <fullName>Alcohol addendum signed, but no alcohol on menu</fullName>
            </value>
            <value>
                <fullName>Appears to be Change of Ownership - Provide Original Store ID</fullName>
            </value>
            <value>
                <fullName>Appears to be Change of Ownership - Update Type</fullName>
            </value>
            <value>
                <fullName>Banking not listed in portal after provisioning</fullName>
            </value>
            <value>
                <fullName>Blurry or poorly cropped menu source</fullName>
            </value>
            <value>
                <fullName>Bulk Activation Failed</fullName>
            </value>
            <value>
                <fullName>Bulk P&amp;P Error</fullName>
            </value>
            <value>
                <fullName>Bulk tool Failure</fullName>
            </value>
            <value>
                <fullName>Business reference not found</fullName>
            </value>
            <value>
                <fullName>Business/Store Already Exists</fullName>
            </value>
            <value>
                <fullName>Business ID mismatch in SFDC and Mint</fullName>
            </value>
            <value>
                <fullName>Business Provisioning Failed - Please refer to Provisioning Errors tab</fullName>
            </value>
            <value>
                <fullName>Catalog / Grocery account</fullName>
            </value>
            <value>
                <fullName>Closed Lost, Mx not interested in Storefront</fullName>
            </value>
            <value>
                <fullName>Contract Format (Must be PDF)</fullName>
            </value>
            <value>
                <fullName>Contract not Signed</fullName>
            </value>
            <value>
                <fullName>Contract Unrelated to Business/Request</fullName>
            </value>
            <value>
                <fullName>COO Same Store Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Provided More Info</fullName>
            </value>
            <value>
                <fullName>DM Email associated to another Business</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t see value in own online ordering</fullName>
            </value>
            <value>
                <fullName>Do not know what Storefront is</fullName>
            </value>
            <value>
                <fullName>Drive Partner</fullName>
            </value>
            <value>
                <fullName>Duplicate Account based on Store ID, Phone, or Address</fullName>
            </value>
            <value>
                <fullName>Duplicate Onboarding Record</fullName>
            </value>
            <value>
                <fullName>Duplicate POS Integration ID - Already in Use</fullName>
            </value>
            <value>
                <fullName>Equipment Never Sent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Time_Spent_In_Blocked_Days_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_In_Blocked_Days_Calculated__c</fullName>
    <description>LEM-964: Number of days the work step remain in Blocked status.
LEM-1489: Changed the data type from number to formula for real-time calculation.</description>
    <formula>IF(
  TEXT(Status__c) = $Label.Work_Step_Status_Blocked,
  ((5 * FLOOR((Today() - DATE(2000, 1, 3)) / 7)
  + MIN(5, MOD(Today() - DATE(2000, 1, 3), 7)))) /*Calculates the number of Working days between the current day and 01/03/2000 - Monday*/
  - ((5 * FLOOR((DATEVALUE(Last_Blocked_Date_Time__c) - DATE(2000, 1, 3)) / 7)
  + MIN(5, MOD(DATEVALUE(Last_Blocked_Date_Time__c) - DATE(2000, 1, 3), 7)))) /*Calculates the number of Working days between the Last Blocked Date and 01/03/2000 - Monday*/
  + Previous_Spent_Days_In_Blocked_Status__c,
  Previous_Spent_Days_In_Blocked_Status__c
)</formula>
    <inlineHelpText>Number of days the work step remain in Blocked status</inlineHelpText>
    <label>Time Spent In Blocked (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/services/WorkStepsStatusRelatedDatesCalcSrvcTest.cls
/**
 * @author Deloitte
 * @date 24/05/2022
 * @description Test class for WorkStepsStatusRelatedDatesCalcSrvcImpl class.
 */
@isTest(seeAllData=false)
private class WorkStepsStatusRelatedDatesCalcSrvcTest {
    private static final String FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE = 'Unexpected result: the field is not updated with expected value';
    private static final String INITIAL_OWNER_NAME = 'Test User';
    private static final Integer PREVIOUS_NUMBER_OF_DAYS_BLOCKED = 0;
    private static final Integer TOTAL_NUMBER_OF_DAYS_BLOCKED = 4;
    private static final String WORK_STEP_STATUS_BLOCKED = 'Blocked';
    private static final String WORK_STEP_STATUS_COMPLETE = 'Complete';
    private static final String WORK_STEP_STATUS_ESCALATED = 'Escalated';
    private static final String WORK_STEP_STATUS_IN_PROGRESS = 'In Progress';
    private static final String WORK_STEP_STATUS_NOT_STARTED = 'Not Started';
    private static final String WORK_STEP_STATUS_NOT_WORKABLE = 'Not Workable';
    private static final String WORK_STEP_STATUS_QA_COMPLETE = 'QA Complete';
    private static final String WORK_STEP_STATUS_READY_FOR_QA = 'Ready for QA';
    private static final String WORK_STEP_STATUS_REASON_OTHER = 'Other';
    private static final String WORK_STEP_TYPE_SETUP_BANKING = 'Setup Banking';

    /**
     * @description To test Start Date/Time and Initial Owner fields are updated
     * when WorkStep status is moved from 'Not Started' to 'In Progress'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusToInProgressThenStartDateAndTimeIsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_IN_PROGRESS
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField = newWorkStep.Start_Date_Time__c;
        Date updatedStartDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Initial Owner field is not updated when Initial Owner field
     * is not null and WorkStep status is moved from 'Not Workable' to 'In Progress'.
     */
    @isTest
    private static void testWhenInitialOwnerIsNotNullThenInitialOwnerFieldIsNotUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
                WORK_STEP_STATUS_NOT_WORKABLE
            )
            .setField(WorkStep.Initial_Owner__c, INITIAL_OWNER_NAME);
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Initial_Owner__c = INITIAL_OWNER_NAME,
            Status__c = WORK_STEP_STATUS_IN_PROGRESS
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField = newWorkStep.Start_Date_Time__c;
        Date updatedStartDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            INITIAL_OWNER_NAME,
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time, Initial Owner and Completed Date/Time fields are
     * updated when WorkStep status is updated from 'Not Started' to 'Complete'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromNotStartedToCompleteThenAuditFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedCompletedDateTime = newWorkStep.Completed_Date_Time__c;
        DateTime updatedStartDateTime = newWorkStep.Start_Date_Time__c;
        Date updatedCompletedDate = Date.newInstance(
            updatedCompletedDateTime.year(),
            updatedCompletedDateTime.month(),
            updatedCompletedDateTime.day()
        );
        Date updatedStartDate = Date.newInstance(
            updatedStartDateTime.year(),
            updatedStartDateTime.month(),
            updatedStartDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedCompletedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time, Initial Owner and Completed Date/Time fields are
     * updated when WorkStep status is updated from 'Not Workable' to 'Complete'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromNotWorkableToCompleteThenAuditFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_WORKABLE
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedCompletedDateTime = newWorkStep.Completed_Date_Time__c;
        DateTime updatedStartDateTime = newWorkStep.Start_Date_Time__c;
        Date updatedCompletedDate = Date.newInstance(
            updatedCompletedDateTime.year(),
            updatedCompletedDateTime.month(),
            updatedCompletedDateTime.day()
        );
        Date updatedStartDate = Date.newInstance(
            updatedStartDateTime.year(),
            updatedStartDateTime.month(),
            updatedStartDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedCompletedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time and Initial Owner fields are not updated when WorkStep
     * status is updated to 'Complete' from status other than Not Workable/Not Started.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromInProgressToCompleteThenInitialAuditFieldsNotUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_IN_PROGRESS
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedCompletedDateTime = newWorkStep.Completed_Date_Time__c;
        Date updatedCompletedDate = Date.newInstance(
            updatedCompletedDateTime.year(),
            updatedCompletedDateTime.month(),
            updatedCompletedDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedCompletedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Start_Date_Time__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Completed Date/Time, Last QAed By, Last QA Date/Time fields are updated
     * when WorkStep status is updated from 'Ready for QA' to 'Complete'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromReadyForQaToCompleteThenQADateFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField;
        dateTimeValueOfField = newWorkStep.Completed_Date_Time__c;
        Date updatedCompletedDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        dateTimeValueOfField = newWorkStep.Last_QA_Date_Time__c;
        Date updatedLastQaDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            System.today(),
            updatedCompletedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            System.today(),
            updatedLastQaDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            UserInfo.getUserId(),
            newWorkStep.Last_QAed_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Last Blocked Date/Time field is updated when WorkStep status
     * is updated to 'Blocked'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusToBlockedThenLastBlockedDateAndTimeIsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_BLOCKED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField = newWorkStep.Last_Blocked_Date_Time__c;
        Date updatedLastBlockedDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastBlockedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time, Last Escalation Date/Time and Initial Owner fields
     * are updated when WorkStep status is updated from 'Not Started' to 'Escalated'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromNotStartedToEscalatedThenAuditFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_ESCALATED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedLastEscalationDateTime = newWorkStep.Last_Escalation_Date_Time__c;
        DateTime updatedStartDateTime = newWorkStep.Start_Date_Time__c;
        Date updatedLastEscalationDate = Date.newInstance(
            updatedLastEscalationDateTime.year(),
            updatedLastEscalationDateTime.month(),
            updatedLastEscalationDateTime.day()
        );
        Date updatedStartDate = Date.newInstance(
            updatedStartDateTime.year(),
            updatedStartDateTime.month(),
            updatedStartDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastEscalationDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Last_QA_Date_Time__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Last_QAed_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time, Last Escalation Date/Time and Initial Owner fields
     * are updated when WorkStep status is updated from 'Not Workable' to 'Escalated'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromNotWorkableToEscalatedThenAuditFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_WORKABLE
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_ESCALATED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedLastEscalationDateTime = newWorkStep.Last_Escalation_Date_Time__c;
        DateTime updatedStartDateTime = newWorkStep.Start_Date_Time__c;
        Date updatedLastEscalationDate = Date.newInstance(
            updatedLastEscalationDateTime.year(),
            updatedLastEscalationDateTime.month(),
            updatedLastEscalationDateTime.day()
        );
        Date updatedStartDate = Date.newInstance(
            updatedStartDateTime.year(),
            updatedStartDateTime.month(),
            updatedStartDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastEscalationDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Last_QA_Date_Time__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Last_QAed_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time and Initial Owner fields are not updated when WorkStep
     * status is updated to 'Escalated' from status other than Not Workable/Not Started.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromInProgressToEscalatedThenInitialAuditFieldsNotUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_IN_PROGRESS
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_ESCALATED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedLastEscalationDateTime = newWorkStep.Last_Escalation_Date_Time__c;
        Date updatedLastEscalationDate = Date.newInstance(
            updatedLastEscalationDateTime.year(),
            updatedLastEscalationDateTime.month(),
            updatedLastEscalationDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastEscalationDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Start_Date_Time__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            null,
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Last Escalation Date/Time, Last QAed By, Last QA Date/Time fields
     * are updated when WorkStep status is updated from 'Ready for QA' to 'Escalated'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromReadyForQaToEscalatedThenQADateFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_ESCALATED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField;
        dateTimeValueOfField = newWorkStep.Last_Escalation_Date_Time__c;
        Date updatedLastEscalationDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        dateTimeValueOfField = newWorkStep.Last_QA_Date_Time__c;
        Date updatedLastQaDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastEscalationDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            System.today(),
            updatedLastQaDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            UserInfo.getUserId(),
            newWorkStep.Last_QAed_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Last Prepared By and Initial Preparation Date/Time fields are updated
     * when WorkStep status is moved to 'Ready for QA'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusToReadyForQaThenInitialPreparationDateTimeAndLastPrepardByFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField = newWorkStep.Initial_Preparation_Date_Time__c;
        Date updatedInitialPreparationDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            System.today(),
            updatedInitialPreparationDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            UserInfo.getUserId(),
            newWorkStep.Last_Prepared_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Initial Preparation Date/Time field is not updated when
     * Initial Preparation Date/Time field is not null and WorkStep status
     * is moved to 'Ready for QA'.
     */
    @isTest
    private static void testWhenInitialPreparationDateTimeFieldIsNotNullThenInitialPreparationDateTimeIsNotUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
                WORK_STEP_STATUS_NOT_STARTED
            )
            .setField(WorkStep.Initial_Preparation_Date_Time__c, System.now().addDays(-1));
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Initial_Preparation_Date_Time__c = System.now().addDays(-1),
            Status__c = WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField = newWorkStep.Initial_Preparation_Date_Time__c;
        Date updatedInitialPreparationDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            true,
            updatedInitialPreparationDate != System.today(),
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            UserInfo.getUserId(),
            newWorkStep.Last_Prepared_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Last QAed By, Last QA Date/Time fields are updated
     * when WorkStep status is updated from 'Ready for QA' to 'QA Complete'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromReadyForQaToQaCompleteThenQADateFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_READY_FOR_QA
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_QA_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime dateTimeValueOfField;
        dateTimeValueOfField = newWorkStep.Last_QA_Date_Time__c;
        Date updatedLastQaDate = Date.newInstance(
            dateTimeValueOfField.year(),
            dateTimeValueOfField.month(),
            dateTimeValueOfField.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastQaDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            UserInfo.getUserId(),
            newWorkStep.Last_QAed_By__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Last QAed By, Last QA Date/Time fields are not updated
     * when WorkStep status is directly updated to 'QA Complete' from 'Not Started'.
     */
    @isTest
    private static void testWhenStatusDirectlyUpdatedToQaCompleteThenQADateFieldsNotUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStep oldMockWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldMockWorkStep.Id, oldMockWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldMockWorkStep.Id,
            Status__c = WORK_STEP_STATUS_QA_COMPLETE
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        System.assertEquals(
            true,
            newWorkStep.Last_QA_Date_Time__c == null,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(
            true,
            newWorkStep.Last_QAed_By__c == null,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test 'Previous spent days in blocked status' Field is updated
     * with 'Time spent in blocked days' previous value when WorkStep status is moved
     * from 'Blocked' to any other status.
     */
    @isTest
    private static void testWhenUnBlockedThenPreviousSpentDaysInBlockedStatusFieldIsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
                WORK_STEP_STATUS_BLOCKED
            )
            .setField(WorkStep.Status_Reason__c, WORK_STEP_STATUS_REASON_OTHER)
            .setField(
                WorkStep.Time_Spent_In_Blocked_Days_Calculated__c,
                TOTAL_NUMBER_OF_DAYS_BLOCKED
            )
            .setField(
                WorkStep.Previous_Spent_Days_In_Blocked_Status__c,
                PREVIOUS_NUMBER_OF_DAYS_BLOCKED
            );
        WorkStep oldMockWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldMockWorkStep.Id, oldMockWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldMockWorkStep.Id,
            Status__c = WORK_STEP_STATUS_NOT_STARTED
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        System.assertEquals(
            TOTAL_NUMBER_OF_DAYS_BLOCKED,
            newWorkStep.Previous_Spent_Days_In_Blocked_Status__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }

    /**
     * @description To test Start Date/Time and Initial Owner fields are updated
     * when WorkStep status is updated from 'Not Workable' to 'Blocked'.
     */
    @isTest
    private static void testWhenUpdateWorkStepStatusFromNotWorkableToBlockedThenAuditFieldsUpdated() {
        Map<Id, WorkStep> oldWorkSteps = new Map<Id, WorkStep>();
        Fake oldWorkStepFakeInstance = MockWorkStepDataBuilder.createWorkStepRecordWithProvidedStatusValue(
            WORK_STEP_STATUS_NOT_WORKABLE
        );
        WorkStep oldWorkStep = MockWorkStepDataBuilder.convertToWorkStepObject(
            oldWorkStepFakeInstance
        );
        oldWorkSteps.put(oldWorkStep.Id, oldWorkStep);
        WorkStep newWorkStep = new WorkStep(
            Id = oldWorkStep.Id,
            Status__c = WORK_STEP_STATUS_BLOCKED,
            Status_Reason__c = WORK_STEP_STATUS_REASON_OTHER
        );
        WorkStepsStatusRelatedDatesCalcService.updateAssociatedDateTrackingFieldsOnStatusChange(
            new List<WorkStep>{ newWorkStep },
            oldWorkSteps
        );
        DateTime updatedLastBlockedDateTime = newWorkStep.Last_Blocked_Date_Time__c;
        DateTime updatedStartDateTime = newWorkStep.Start_Date_Time__c;
        Date updatedLastBlockedDate = Date.newInstance(
            updatedLastBlockedDateTime.year(),
            updatedLastBlockedDateTime.month(),
            updatedLastBlockedDateTime.day()
        );
        Date updatedStartDate = Date.newInstance(
            updatedStartDateTime.year(),
            updatedStartDateTime.month(),
            updatedStartDateTime.day()
        );
        System.assertEquals(
            System.today(),
            updatedLastBlockedDate,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
        System.assertEquals(System.today(), updatedStartDate, FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE);
        System.assertEquals(
            UserInfo.getName(),
            newWorkStep.Initial_Owner__c,
            FIELD_UPDATE_NEGATIVE_ASSERT_MESSAGE
        );
    }
}