sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/Cross_Object_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>LEM-13508: It contains the cross object status mappings.</description>
    <label>Cross Object Status Mapping</label>
    <pluralLabel>Cross Object Status Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <defaultValue>true</defaultValue>
    <description>LEM-13508: It indicates if the record is active or not.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13508: It is used to store the scenario of the status update.</description>
    <label>Process</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/fields/Source_Status__c.field-meta.xml
<CustomField>
    <fullName>Source_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13508: It contains the value for the source status field mapping.</description>
    <label>Source Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/fields/Target_Status__c.field-meta.xml
<CustomField>
    <fullName>Target_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13508: It contains the value for the target status field mapping.</description>
    <label>Target Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Cross_Object_Status_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13508: It represents the type of Mx Order.</description>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStep/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-964: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activate Store</fullName>
            </value>
            <value>
                <fullName>Activations Checklist</fullName>
            </value>
            <value>
                <fullName>Add Marketing</fullName>
            </value>
            <value>
                <fullName>Ads and Promo</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Activate</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Deactivate</fullName>
            </value>
            <value>
                <fullName>Cross Listing - Caviar</fullName>
            </value>
            <value>
                <fullName>Deliver Tablet</fullName>
            </value>
            <value>
                <fullName>Deliver Return Label</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Fee Credit</fullName>
            </value>
            <value>
                <fullName>Grant Portal Access</fullName>
            </value>
            <value>
                <fullName>Implementation Call</fullName>
            </value>
            <value>
                <fullName>Link Implementation</fullName>
            </value>
            <value>
                <fullName>Link Optimization</fullName>
            </value>
            <value>
                <fullName>Menu Updates</fullName>
            </value>
            <value>
                <fullName>Post-Sales - Other</fullName>
            </value>
            <value>
                <fullName>Rate Change</fullName>
            </value>
            <value>
                <fullName>Review &amp; Triage</fullName>
                <default>true</default>
                <label>Review &amp; Triage</label>
            </value>
            <value>
                <fullName>Setup Banking</fullName>
            </value>
            <value>
                <fullName>Setup Business</fullName>
            </value>
            <value>
                <fullName>Setup Catalog</fullName>
            </value>
            <value>
                <fullName>Setup Custom Delivery Radius</fullName>
            </value>
            <value>
                <fullName>Setup Menu</fullName>
            </value>
            <value>
                <fullName>Setup POS</fullName>
            </value>
            <value>
                <fullName>Setup Store</fullName>
            </value>
            <value>
                <fullName>Setup Storefront Page</fullName>
            </value>
            <value>
                <fullName>Sponsored Listing</fullName>
            </value>
            <value>
                <fullName>Complete pre-work</fullName>
            </value>
            <value>
                <fullName>Configure POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/CrossObjectStatusMappingsSelectorTest.cls
/**
 * @author Deloitte
 * @date 05/08/2024
 * @description Test class for CrossObjectStatusMappingsSelector class.
 */
@isTest(SeeAllData=false)
private class CrossObjectStatusMappingsSelectorTest {
    private static final String ASSERT_MESSAGE_OBJECT_MISMATCH = 'Unexpected Error: The object type must be Country Attributes Mapping Metadata';
    private static final String ASSERT_MESSAGE_FIELD_MISMATCH = 'Unexpected Error: Mismatch in field list';
    private static final String ASSERT_MESSAGE_COUNT_MISMATCH = 'Unexpected Error : Mismatch in count of records';
    private static final String DRAFT = 'Draft';
    private static final String NOT_STARTED = 'Not Started';
    private static final String PROCESS = 'Mx Order Status to WorkStep Status';
    private static final String TABLET = 'Tablet';

    /**
     * @description To test Contructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCall() {
        CrossObjectStatusMappingsSelector selectorInstance = (CrossObjectStatusMappingsSelector) CrossObjectStatusMappingsSelector.newInstance();
        Schema.SObjectType typeOfObject = selectorInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = selectorInstance.getSObjectFieldList();
        System.assertEquals(
            Cross_Object_Status_Mapping__mdt.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_OBJECT_MISMATCH
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Cross_Object_Status_Mapping__mdt.Target_Status__c,
                Cross_Object_Status_Mapping__mdt.Source_Status__c,
                Cross_Object_Status_Mapping__mdt.Process__c,
                Cross_Object_Status_Mapping__mdt.Active__c,
                Cross_Object_Status_Mapping__mdt.Type__c
            },
            sObjectFields,
            ASSERT_MESSAGE_FIELD_MISMATCH
        );
    }

    /**
     * @description To test if the Cross Object Status Mapping records related to the passed
     * process name are returned.
     */
    @isTest
    private static void testWhenOrderProcessNamePassedThenReturnOrderStatusToWorkStepStatusMappings() {
        List<Cross_Object_Status_Mapping__mdt> customMetadataMocks = new List<Cross_Object_Status_Mapping__mdt>{
            (Cross_Object_Status_Mapping__mdt) ServiceMockDataBuilder.convertToSObject(
                ServiceMockDataBuilder.createCrossObjectStatusMappingFakeInstance(
                    DRAFT,
                    NOT_STARTED,
                    true,
                    PROCESS,
                    TABLET
                )
            )
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        CrossObjectStatusMappingsSelector mockSelector = (CrossObjectStatusMappingsSelector) mocks.mock(
            CrossObjectStatusMappingsSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockSelector.getSObjectType())
            .thenReturn(Cross_Object_Status_Mapping__mdt.SObjectType);
        mocks.when(mockSelector.selectActiveStatusMappingsByProcessName(PROCESS))
            .thenReturn(customMetadataMocks);
        Application.SELECTOR.setMock(mockSelector);
        Test.startTest();
        List<Cross_Object_Status_Mapping__mdt> crossObjectMappingRecords = CrossObjectStatusMappingsSelector.newInstance()
            .selectActiveStatusMappingsByProcessName(PROCESS);
        Test.stopTest();
        System.assertEquals(
            true,
            !crossObjectMappingRecords.isEmpty(),
            ASSERT_MESSAGE_COUNT_MISMATCH
        );
    }
}