sfdx-source/force-app/main/default/objects/Notifier__e/Notifier__e.object-meta.xml
<CustomObject>
    <description>LEM-955: It allows generic Platform Event schema and the trigger listener to act as dispatcher of the events. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further processing.</description>
    <label>Notifier</label>
    <pluralLabel>Notifiers</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Rate_Change_Request__c/Rate_Change_Request__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <nameField>
        <displayFormat>Change-{0000}</displayFormat>
        <label>Rate Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/Subscription_Rate_Change__c.object-meta.xml
<CustomObject>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Subscription Rate Change</label>
    <nameField>
        <displayFormat>SubscriptionChange-{0000}</displayFormat>
        <label>Subscription Rate Change  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Rate Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Subscription_Rate_Change__c/fields/Rate_Change_Request__c.field-meta.xml
<CustomField>
    <fullName>Rate_Change_Request__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-6457-Active Rate Provisioning</description>
    <label>Rate Change Request</label>
    <referenceTo>Rate_Change_Request__c</referenceTo>
    <relationshipLabel>Subscription Rate Changes</relationshipLabel>
    <relationshipName>Subscription_Rate_Changes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/services/IRateChangeRequestService.cls
/**
 * @author Deloitte
 * @date 09/4/2023
 * @description Interface for RateChangeRequestService.
 */
public interface IRateChangeRequestService {
    /**
     * @description This method is used to complete the Rate Change Request based on Subscription Rate change.
     * @param completedSRCs
     */
    void setRateChangeRequestComplete(List<Subscription_Rate_Change__c> completedSRCs);

    /**
     * @description This method is used to update the Rate Change Request Store Update Flag to true
     * once all the store Accounts are updated in AccountUpdateForActiveRatesBatch.
     * @param rateChangeRequestId
     */
    void setRateChangeRequestStoreUpdatedFlagTrue(Id rateChangeRequestId);

    /**
     * @description Generates Activation Order Creation Event once Rate Change Request Activation Status is set to Ready For Activation.
     * @param rcrIds
     */
    void publishCreateActivationOrdersNotifierEvent(Set<Id> rcrIds);

    /**
     * @description This method is used to handle the published Notifier events.
     * @param notifierEvents list of platform events with payload
     */
    void handleNotifierEvents(List<Notifier__e> notifierEvents);

    /**
     * @description It is used to update Rate Change Requests
     * to cancel status.
     * @param rateChangeRequests List of Rate Change Requests.
     */
    void updateRateChangeRequestToCancelled(List<Rate_Change_Request__c> rateChangeRequests);
}