sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/Inbound_Ingestion_Payload_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>LEM-16349: It is used to store the Mulesoft payload attribute and corresponding Salesforce field mappings.</description>
    <label>Inbound Ingestion Payload Mapping</label>
    <pluralLabel>Inbound Ingestion Payload Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Attribute_Key__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Key__c</fullName>
    <label>Attribute Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SSMO</fullName>
                <default>true</default>
                <label>SSMO</label>
            </value>
            <value>
                <fullName>SSOB</fullName>
            </value>
            <value>
                <fullName>Mx Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Payload_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Payload_Attribute__c</fullName>
    <label>Payload Attribute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Payload_Mapping__mdt/fields/Payload_Type__c.field-meta.xml
<CustomField>
    <fullName>Payload_Type__c</fullName>
    <label>Payload Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/InstantIngestionFieldMappingSelector.cls
/**
 * @author Deloitte
 * @date 08/22/2024
 * @description Selector Class for Instant Ingestor Field Mapping custom metadata.
 */
public inherited sharing class InstantIngestionFieldMappingSelector extends fflib_SObjectSelector implements IInstantIngestionFieldMappingSelector {
    /**
     * @description Default constructor for the class.
     * @return IInstantIngestionFieldMappingSelector - interface of InstantIngestionFieldMappingSelector
     */
    public static IInstantIngestionFieldMappingSelector newInstance() {
        return (IInstantIngestionFieldMappingSelector) Application.Selector.newInstance(
            Inbound_Ingestion_Payload_Mapping__mdt.SObjectType
        );
    }

    /**
     * @description Override default getSObjectType method.
     * @return SObjectType - object type of metadata
     */
    public Schema.SObjectType getSObjectType() {
        return Inbound_Ingestion_Payload_Mapping__mdt.SObjectType;
    }

    /**
     * @description It is used for getting all field values for Inbound_Ingestion_Payload_Mapping__mdt.
     * @return List<Inbound_Ingestion_Payload_Mapping__mdt> - List of metadata records with values
     */
    public List<Inbound_Ingestion_Payload_Mapping__mdt> getAllValues() {
        return Inbound_Ingestion_Payload_Mapping__mdt.getAll().values();
    }

    /**
     * @description It is used for getting the fields of Inbound_Ingestion_Payload_Mapping__mdt.
     * @return List<Schema.SObjectField>- Inbound_Ingestion_Payload_Mapping__mdt fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Inbound_Ingestion_Payload_Mapping__mdt.Integration_Type__c,
            Inbound_Ingestion_Payload_Mapping__mdt.Object__c,
            Inbound_Ingestion_Payload_Mapping__mdt.Default_Value__c,
			Inbound_Ingestion_Payload_Mapping__mdt.Field_Name__c,
			Inbound_Ingestion_Payload_Mapping__mdt.Payload_Attribute__c , 
			Inbound_Ingestion_Payload_Mapping__mdt.Payload_Type__c,
			Inbound_Ingestion_Payload_Mapping__mdt.Attribute_Key__c

        };
    }
}