sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/Contract_Associated_Accounts__c.object-meta.xml
<CustomObject>
    <label>Contract Associated Accounts</label>
    <nameField>
        <displayFormat>CAA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Contract_Associated_Accounts__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-6144: This represents the main Contract record on which the Associated Account Ids are currently stored.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associated Accounts</relationshipLabel>
    <relationshipName>Contract_Associated_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/IContractAssociatedAccountsSelector.cls
/**
 * @author BizApps
 * @description Interface to add Selector class methods
 */
public interface IContractAssociatedAccountsSelector extends fflib_ISObjectSelector {
    /**
     * @description This method is for getting object type
     * @param idSet
     * @return List<Contract_Associated_Accounts__c> - List of Contract_Associated_Accounts__c
     */
    List<Contract_Associated_Accounts__c> selectById(Set<Id> idSet);

    /**
     * @description Retrieves all Contract_Associated_Accounts__c for an inputted Contract
     * @param contractId - Id to filter by in Contract__c field
     * @return List<Contract_Associated_Accounts__c>
    **/
    List<Contract_Associated_Accounts__c> selectByContractId(Id contractId);

    /**
     * @description Retrieves all Contract_Associated_Accounts__c for an inputted Set of Contracts
     * @param contractIds - Set<Id> to filter by in Contract__c field
     * @return List<Contract_Associated_Accounts__c>
    **/
    List<Contract_Associated_Accounts__c> selectByContractIds(Set<Id> contractIds);

    /**
     * @description Retrieves all Contract_Associated_Accounts__c for the contracts that needs to be processed in bacth modeß
     * @return Database.QueryLocator
    **/
    Database.QueryLocator selectByBatchProcessEnabledAndStatus();

     /**
     * @description Retrieves all Contract_Associated_Accounts__c for the contracts that needs to be processed in bacth modeß for an inputted Set of ContractAssociatedAccount IDs
     * @param conAssociatedAccountIds - Set<Id> to filter by Id
     * @return Database.QueryLocator
    **/
    Database.QueryLocator selectByBatchProcessEnabledAndStatusIds(Set<Id> conAssociatedAccountIds);
}