sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/Bat_To_WorkSteps_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This setting used to map Bat status from pos work step status.</description>
    <label>Bat To WorkSteps Status Mapping</label>
    <pluralLabel>Bat To WorkSteps Status Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Bat_Status__c.field-meta.xml
<CustomField>
    <fullName>Bat_Status__c</fullName>
    <description>BZAP-19643 BAT status received from integration request. Target status in integration request is equivalent to this field.</description>
    <label>Bat Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Exclusion_Code__c.field-meta.xml
<CustomField>
    <fullName>Exclusion_Code__c</fullName>
    <description>BZAP-19643 Exclusion will be mapped to the integration request</description>
    <label>Exclusion Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>BZAP-19643 status reason to update on the work step when bat status and exclusion mapping matched</description>
    <label>Status Reason</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Work_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Plan_Status__c</fullName>
    <description>BZAP-19643 update work plan status when the bat status and exclusion code mapped</description>
    <label>Work_Plan Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Work_Step_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Step_Status__c</fullName>
    <description>BZAP-19643 work status to be updated when the bat status and exclusion code matched</description>
    <label>Work Step Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Bat_To_WorkSteps_Status_Mapping__mdt/fields/Work_Step_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Step_Type__c</fullName>
    <description>BZAP-19643 work step type to be mapped and update status reason and status.</description>
    <label>Work Step Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/BatToWorkStepsStatusMappingSelector.cls
/**
 * @author DoorDash
 * @date 03/09/2023
 * @description Selector class for Bat_To_WorkSteps_Status_Mapping__mdt custom metadata.
 */
public inherited sharing class BatToWorkStepsStatusMappingSelector extends fflib_SObjectSelector implements IBatToWorkStepsStatusMappingSelector {
    /**
     * @description Default constructor for the class.
     * @return IBatToWorkStepsStatusMappingSelector - Returns interface of BatToWorkStepsStatusMappingSelector
     */
    public static IBatToWorkStepsStatusMappingSelector newInstance() {
        return (IBatToWorkStepsStatusMappingSelector) Application.Selector.newInstance(
            Bat_To_WorkSteps_Status_Mapping__mdt.SObjectType
        );
    }

    /**
     * @description It is used for getting object type.
     * @return SObjectType - Returns object type of metadata
     */
    public Schema.SObjectType getSObjectType() {
        return Bat_To_WorkSteps_Status_Mapping__mdt.SObjectType;
    }

    /**
     * @description It is for getting the fields of Bat_To_WorkSteps_Status_Mapping__mdt.
     * @return List<Schema.SObjectField> - Bat_To_WorkSteps_Status_Mapping__mdt fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Bat_To_WorkSteps_Status_Mapping__mdt.Bat_Status__c,
            Bat_To_WorkSteps_Status_Mapping__mdt.Exclusion_Code__c,
            Bat_To_WorkSteps_Status_Mapping__mdt.Work_Step_Status__c,
            Bat_To_WorkSteps_Status_Mapping__mdt.Work_Step_Type__c,
            Bat_To_WorkSteps_Status_Mapping__mdt.Status_Reason__c,
            Bat_To_WorkSteps_Status_Mapping__mdt.Work_Plan_Status__c
        };
    }

    /**
     * @description It is for getting all records in Bat_To_WorkSteps_Status_Mapping__mdt.
     * @return List<Bat_To_WorkSteps_Status_Mapping__mdt> - List of metadata records with values
     */
    public List<Bat_To_WorkSteps_Status_Mapping__mdt> getAllValues() {
    	return Bat_To_WorkSteps_Status_Mapping__mdt.getall().values();
    }
}