sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/Activation_Checklist_Validation__mdt.object-meta.xml
<CustomObject>
    <description>LEM-13303: It is used to store the validations and their respective error/success messages and the service classes to be accessed.</description>
    <label>Activation Checklist Validation</label>
    <pluralLabel>Activation Checklist Validations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Activation_Validation_Name__c.field-meta.xml
<CustomField>
    <fullName>Activation_Validation_Name__c</fullName>
    <description>LEM-13305: It is used to store the name of validations required for activation.</description>
    <label>Activation Validation Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDOA</fullName>
                <default>true</default>
                <label>PDOA</label>
            </value>
            <value>
                <fullName>Duplicate Work Orders</fullName>
            </value>
            <value>
                <fullName>MSID</fullName>
            </value>
            <value>
                <fullName>Submarket</fullName>
            </value>
            <value>
                <fullName>Starting Point ID</fullName>
            </value>
            <value>
                <fullName>Commission Rates</fullName>
            </value>
            <value>
                <fullName>Tier Level</fullName>
            </value>
            <value>
                <fullName>Banking Information</fullName>
            </value>
            <value>
                <fullName>Store Is Partner</fullName>
            </value>
            <value>
                <fullName>Business Is Active</fullName>
            </value>
            <value>
                <fullName>Active Menu Count</fullName>
            </value>
            <value>
                <fullName>Business ID</fullName>
            </value>
            <value>
                <fullName>Order Protocol</fullName>
            </value>
            <value>
                <fullName>Offers Pickup/Delivery/Dashpass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-13303: It is used to store the error message of the validation.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-13303: It is used to store if the current validation is active or not.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-13303: It is used to store the object that needs to be validated.</description>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Service_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Class_Name__c</fullName>
    <description>LEM-13303: It is used to the service class where validation is done.</description>
    <label>Service Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Service_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Method_Name__c</fullName>
    <description>LEM-13303: It is used to store service method name where the validation will be done.</description>
    <label>Service Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>LEM-13612: Source of the Activation Checklist Validation.</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Activation_Checklist_Validation__mdt/fields/Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Success_Message__c</fullName>
    <description>LEM-13303: It is used to store the success message for the validation.</description>
    <label>Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/ActivationCheckValidationSelectorTest.cls
/**
 * @author Deloitte
 * @date 04/19/2024
 * @description Test class for ActivationChecklistValidationSelector class.
 */
@isTest(seeAllData=false)
private class ActivationCheckValidationSelectorTest {
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: there is a mismatch in fields list';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: the object type must be Activation Checklist Validation custom metadata';
    private static final String ASSERT_MESSAGE_RECORDS_NOT_FETCHED = 'Unexpected result: custom metadata records not retrieved.';
    private static final String METADATA_ERROR_MESSAGE = 'PDOA is in the future';
    private static final String METADATA_METHOD_NAME = 'validatePDOA';
    private static final String METADATA_NAME = 'PDOA';
    private static final String METADATA_SUCCESS_MESSAGE = 'PDOA is today or in the past';
    private static final Integer RECORD_COUNT_ONE = 1;

    /**
     * @description To test Activation Checklist Validation selector methods.
     */
    @isTest
    private static void testWhenSelectorMethodsCalledThenReturnAppropriateValues() {
        List<Schema.SObjectField> sObjectFieldsMock = new List<Schema.SObjectField>{
            Activation_Checklist_Validation__mdt.Success_Message__c,
            Activation_Checklist_Validation__mdt.Activation_Validation_Name__c,
            Activation_Checklist_Validation__mdt.DeveloperName,
            Activation_Checklist_Validation__mdt.Error_Message__c,
            Activation_Checklist_Validation__mdt.Is_Active__c,
            Activation_Checklist_Validation__mdt.Object_Name__c,
            Activation_Checklist_Validation__mdt.Service_Class_Name__c,
            Activation_Checklist_Validation__mdt.Service_Method_Name__c,
            Activation_Checklist_Validation__mdt.Source__c
        };
        Schema.SObjectType typeOfObject = ActivationChecklistValidationSelector.newInstance()
            .SObjectType();
        ActivationChecklistValidationSelector activationChecklistValidationSelectorInstance = new ActivationChecklistValidationSelector();
        List<Schema.SObjectField> sObjectFields = activationChecklistValidationSelectorInstance.getSObjectFieldList();
        System.assertEquals(
            typeOfObject,
            Activation_Checklist_Validation__mdt.SObjectType,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            sObjectFields,
            sObjectFieldsMock,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }

    /**
     * @description To test Readiness Validation Binding Type selector methods.
     */
    @isTest
    private static void testWhenGetAllActiveValidationsCalledThenReturnActiveRecords() {
        Fake mockFakeActivationChecklistValidation = new Fake(
                Activation_Checklist_Validation__mdt.class
            )
            .setField(
                Activation_Checklist_Validation__mdt.Activation_Validation_Name__c,
                METADATA_NAME
            )
            .setField(Activation_Checklist_Validation__mdt.Is_Active__c, true)
            .setField(Activation_Checklist_Validation__mdt.Error_Message__c, METADATA_ERROR_MESSAGE)
            .setField(
                Activation_Checklist_Validation__mdt.Success_Message__c,
                METADATA_SUCCESS_MESSAGE
            )
            .setField(
                Activation_Checklist_Validation__mdt.Service_Method_Name__c,
                METADATA_METHOD_NAME
            )
            .setFakeId();
        Activation_Checklist_Validation__mdt mockActivationChecklistValidation = (Activation_Checklist_Validation__mdt) ServiceMockDataBuilder.convertToSObject(
            mockFakeActivationChecklistValidation
        );
        List<Activation_Checklist_Validation__mdt> activationChecklistValidations = new List<Activation_Checklist_Validation__mdt>{
            mockActivationChecklistValidation
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ActivationChecklistValidationSelector mockActivationChecklistValidationSelector = (ActivationChecklistValidationSelector) mocks.mock(
            ActivationChecklistValidationSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockActivationChecklistValidationSelector.getSObjectType())
            .thenReturn(Activation_Checklist_Validation__mdt.SObjectType);
        mocks.when(mockActivationChecklistValidationSelector.getAllActiveValidations())
            .thenReturn(activationChecklistValidations);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockActivationChecklistValidationSelector);
        List<Activation_Checklist_Validation__mdt> selectorResult = ActivationChecklistValidationSelector.newInstance()
            .getAllActiveValidations();
        System.assertEquals(true, !selectorResult.isEmpty(), ASSERT_MESSAGE_RECORDS_NOT_FETCHED);
    }
}