sfdx-source/force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>LEM-1337: This object is used to define the relationship Cross Accounts</description>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR - {0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1337: The Account that lookups to one side of the Account Relationship.</description>
    <inlineHelpText>The account from which the relationship is originating.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Relationships cannot be created involving store accounts. Please update the Account and Related Account accordingly.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Related_Accounts_Originating_Relation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>LEM-1337: Captures the date when the Relationship between the Accounts ends</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Inverse_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Relationship_Type__c</fullName>
    <description>LEM-1337: Captures the type of Account from which the Relationship has been created.</description>
    <inlineHelpText>The type of account from which the relationship is originating.</inlineHelpText>
    <label>Inverse Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1337: This looks-up to the Account residing on the other side of the Account Relationship</description>
    <inlineHelpText>The account with which the user is creating a relationship to.</inlineHelpText>
    <label>Related Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account Relationships cannot be created involving store accounts. Please update the Account and Related Account accordingly.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receiving Related Accounts</relationshipLabel>
    <relationshipName>Related_Accounts_Receiving_Relation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the current status of the relationship between the Accounts involved</description>
    <label>Relationship Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the type of Account to which the Relationship is being created.</description>
    <inlineHelpText>The type of account with which the user is creating a relationship to.</inlineHelpText>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Account_Relationships_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Measurement Partner</fullName>
    </customValue>
    <customValue>
        <fullName>AdTech</fullName>
    </customValue>
    <customValue>
        <fullName>POS/MWP Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusive Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Franchise</fullName>
    </customValue>
    <description>LEM-1337: Captures the possible types of Accounts between which relationships can be created</description>
    <masterLabel>Account Relationships Types</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/batchables/AccountRelationshipExpirationBatchTest.cls
/**
 * @author Deloitte
 * @date 19/05/2022
 * @description This is the test class for AccountRelationshipExpirationBatch class
 */
@isTest
public class AccountRelationshipExpirationBatchTest {
    private static final String RELATIONSHIP_STATUS_ACTIVE = 'Active';
    @IsTest
    static void testWhenAccountRelationshipsWithPastEndDateExistsThenAccountRelationshipStatusIsChangedToInactive() {
        //ARRANGE
        Account account1 = (Account) new Fake(Account.class)
            .setField(Account.Name, 'Test Account 1 - Batch')
            .setFakeId()
            .toSObject();

        Account account2 = (Account) new Fake(Account.class)
            .setField(Account.Name, 'Test Account 2 - Batch')
            .setFakeId()
            .toSObject();

        Account_Relationship__c relationshipWithPastEndDate = (Account_Relationship__c) new Fake(
                Account_Relationship__c.class
            )
            .setField(Account_Relationship__c.Relationship_Type__c, 'Agency')
            .setField(Account_Relationship__c.Inverse_Relationship_Type__c, 'Agency')
            .setField(Account_Relationship__c.Relationship_Status__c, 'Active')
            .setField(Account_Relationship__c.End_Date__c, System.today().addDays(-1))
            .setField(Account_Relationship__c.Account__c, account1.Id)
            .setField(Account_Relationship__c.Related_Account__c, account2.Id)
            .setFakeId()
            .toSObject();

        List<Account_Relationship__c> relationshipRecords = new List<Account_Relationship__c>{
            relationshipWithPastEndDate
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUnitOfWork = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );

        Application.UNITOFWORK.setMock(mockUnitOfWork);

        //ACT
        AccountRelationshipExpirationBatch batch = new AccountRelationshipExpirationBatch();
        batch.execute(null, relationshipRecords);

        //ASSERT
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUnitOfWork, 1)).commitWork();
        System.assertEquals(
            'Inactive',
            relationshipRecords[0].Relationship_Status__c,
            'Status is not updated as expected'
        );
    }
}