sfdx-source/force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>LEM-1337: This object is used to define the relationship Cross Accounts</description>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR - {0000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>LEM-1337: Captures the date when the Relationship between the Accounts ends</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Inverse_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Relationship_Type__c</fullName>
    <description>LEM-1337: Captures the type of Account from which the Relationship has been created.</description>
    <inlineHelpText>The type of account from which the relationship is originating.</inlineHelpText>
    <label>Inverse Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the current status of the relationship between the Accounts involved</description>
    <label>Relationship Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-1337: Captures the type of Account to which the Relationship is being created.</description>
    <inlineHelpText>The type of account with which the user is creating a relationship to.</inlineHelpText>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Relationships_Types</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Account_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>LEM-1337: Captures the Date when the relationship between the Accounts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Account_Relationships_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Measurement Partner</fullName>
    </customValue>
    <customValue>
        <fullName>AdTech</fullName>
    </customValue>
    <customValue>
        <fullName>POS/MWP Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Supplier</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Exclusive Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Franchise</fullName>
    </customValue>
    <description>LEM-1337: Captures the possible types of Accounts between which relationships can be created</description>
    <masterLabel>Account Relationships Types</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/triggerHandlers/AccountRelationshipsHandler.cls
/**
 * @author Deloitte
 * @date 25/05/2022
 * @description Account Relationship Object Trigger Handler
 */
public class AccountRelationshipsHandler extends ApplicationDomainHandler {
    /**
     * @description Constructor to instantiate List of Account Relationships
     * @param sObjectList - Account Relationship Record List
     */
    public AccountRelationshipsHandler(List<Account_Relationship__c> sObjectList) {
        super(sObjectList);
        setContextBypass(Account_Relationship__c.SobjectType, AccountRelationshipsHandler.class);
    }

    /**
     * @description Constructor Class implements fflib_SObjectDomain.IConstructable class
     */
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        /**
         * @description This method implements construct method of fflibSObjectDomain.IConstructable
         * @param sObjectList
         * @return AccountRelationshipsHandler
         */
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new AccountRelationshipsHandler(sObjectList);
        }
    }

    /**
     * @description Called to perform Default operations on the Account Relationship
     */
    public override void onApplyDefaults() {
        AccountRelationships.newInstance((List<Account_Relationship__c>) getRecords())
            .defaultOperationsOnInsertion();
    }

    /**
     * @description Called to perform after insert processing
     */
    public override void onAfterInsert() {
        AccountRelationships.newInstance((List<Account_Relationship__c>) getRecords())
            .generateReciprocalRelationship();
    }

    /**
     * @description Called to perform Before Update Processing
     * @param existing
     */
    public override void onBeforeUpdate(Map<Id, SObject> existing) {
        List<Account_Relationship__c> changedRelationships = new List<Account_Relationship__c>(
            (List<Account_Relationship__c>) getChangedRecords(
                new Set<SObjectField>{
                    Account_Relationship__c.Relationship_Type__c,
                    Account_Relationship__c.Inverse_Relationship_Type__c
                }
            )
        );
        AccountRelationships.newInstance(changedRelationships).defaultOperationsOnInsertion();
    }

    /**
     * @description Called to perform after update processing
     * @param existing
     */
    public override void onAfterUpdate(Map<Id, SObject> existing) {
        List<Account_Relationship__c> changedRelationships = new List<Account_Relationship__c>(
            (List<Account_Relationship__c>) getChangedRecords(
                new Set<SObjectField>{
                    Account_Relationship__c.Start_Date__c,
                    Account_Relationship__c.End_Date__c,
                    Account_Relationship__c.Relationship_Type__c,
                    Account_Relationship__c.Inverse_Relationship_Type__c,
                    Account_Relationship__c.Relationship_Status__c
                }
            )
        );
        if (changedRelationships.size() == 0) {
            changedRelationships = null;
        }
        if (changedRelationships != null) {
            AccountRelationships.newInstance(changedRelationships)
                .updateReciprocalRelationships((Map<Id, Account_Relationship__c>) existing);
        }
    }

    /**
     * @description Called to perform after delete processing
     */
    public override void onAfterDelete() {
        AccountRelationships.newInstance(existingRecords.values()).deleteReciprocalRelationships();
    }
}