sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>LEM-15224: This field represents the Category of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertisements</fullName>
            </value>
            <value>
                <fullName>Discoverability</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Marketplace Products</fullName>
            </value>
            <value>
                <fullName>Menu Optimizations</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Promos</fullName>
            </value>
            <value>
                <fullName>Selection</fullName>
            </value>
            <value>
                <fullName>Sponsored Listings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/IncrementalSales__c.field-meta.xml
<CustomField>
    <fullName>IncrementalSales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the sales value for the campaign Product.</description>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
s
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Metric__c.field-meta.xml
<CustomField>
    <fullName>Metric__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>LEM-15226: It stores metric value for Lever.</inlineHelpText>
    <label>Metric</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Marketing Revenue</fullName>
            </value>
            <value>
                <fullName>Marketplace GMV</fullName>
            </value>
            <value>
                <fullName>Platform Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Number_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stores__c</fullName>
    <description>LEM-15224: It represents the number of stores.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Number of Stores</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>LEM-15224: It represents the points of the solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>LEM-808, LEM-18931: This field is to indicate the Product Family of a new Campaign Product.</description>
    <inlineHelpText>Indicates the &apos;product family&apos;, or product category, under which the campaign product falls.</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ads</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>DashPass</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Promos</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>Storefront</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Weblinks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>LEM-15224: It represents the Rank of the Solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-625: This field is used to track the Status of the Campaign Product.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15226: It stores type value for Solution.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Tip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/VSP_Code__c.field-meta.xml
<CustomField>
    <fullName>VSP_Code__c</fullName>
    <description>LEM-15224: It represents the VSP Code of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>VSP Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/SolutionsSelectorTest.cls
/**
 * @author Deloitte
 * @date 06/12/2024
 * @description Test class for SolutionsSelector class.
 */
@isTest(SeeAllData=false)
private class SolutionsSelectorTest {
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: There is a mismatch in fields list.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: The object type must be Event.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_NUMBER_OF_SOLUTIONS = 'Unexpected result: The number of solutions returned do not match the expected number of solutions.';
    private static final String METRIC = 'Marketing Revenue';
    private static final String CATEGORY = 'Discoverability';
    private static final String ADS_VALUE = 'Ads';
    private static final String ACTIVE_STATUS = 'Active';
    private static final String INACTIVE_STATUS = 'Inactive';
    private static final String TYPE = 'Growth';
    private static final String VSP_CODE_VALUE = 'Test';

    /**
     * @description To test contructor instantiation.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheckSObjectTypeAndFieldList() {
        SolutionsSelector solutionsSelectorInstance = new SolutionsSelector();
        Schema.SObjectType typeOfObject = solutionsSelectorInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = solutionsSelectorInstance.getSObjectFieldList();
        SolutionsSelector.newInstance();
        System.assertEquals(
            Schema.Campaign_Product__c.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Campaign_Product__c.Id,
                Campaign_Product__c.VSP_Code__c,
                Campaign_Product__c.Type__c,
                Campaign_Product__c.Status__c,
                Campaign_Product__c.Rank__c,
                Campaign_Product__c.Points__c,
                Campaign_Product__c.Metric__c,
                Campaign_Product__c.Category__c,
                Campaign_Product__c.Name,
                Campaign_Product__c.Number_of_Stores__c,
                Campaign_Product__c.Product_Family__c,
                Campaign_Product__c.IncrementalSales__c
            },
            sObjectFields,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }

    /**
     * @description To test when account ids passed then return the soltuions.
     */
    @isTest
    private static void testWhenAccountIdsPassedThenReturnSolutions() {
        Campaign_Product__c solution = new Campaign_Product__c();
        solution.VSP_Code__c = ADS_VALUE;
        solution.Type__c = TYPE;
        solution.Status__c = ACTIVE_STATUS;
        solution.Rank__c = 2;
        solution.Points__c = 2;
        solution.Metric__c = METRIC;
        solution.Category__c = CATEGORY;
        solution.Name = ADS_VALUE;
        solution.Number_of_Stores__c = 1;
        solution.Product_Family__c = ADS_VALUE;
        solution.IncrementalSales__c = 123;
        insert solution;
        Test.startTest();
        List<Campaign_Product__c> results = SolutionsSelector.newInstance()
            .selectActiveSolutionsByVSPCodes();
        Test.stopTest();
        System.assertEquals(1, results.size(), ASSERT_MESSAGE_MISMATCH_IN_NUMBER_OF_SOLUTIONS);
    }
    /**
     * @description To test when account ids passed then do not return the soltuions.
     */
    @isTest
    private static void testWhenAccountIdsPassedThenDoNotReturnSolutions() {
        Campaign_Product__c solution = new Campaign_Product__c();
        solution.VSP_Code__c = ADS_VALUE;
        solution.Type__c = TYPE;
        solution.Status__c = INACTIVE_STATUS;
        solution.Rank__c = 2;
        solution.Points__c = 2;
        solution.Metric__c = METRIC;
        solution.Category__c = CATEGORY;
        solution.Name = ADS_VALUE;
        solution.Number_of_Stores__c = 1;
        solution.Product_Family__c = ADS_VALUE;
        solution.IncrementalSales__c = 123;
        insert solution;
        Test.startTest();
        List<Campaign_Product__c> results = SolutionsSelector.newInstance()
            .selectActiveSolutionsByVSPCodes();
        Test.stopTest();
        System.assertEquals(0, results.size(), ASSERT_MESSAGE_MISMATCH_IN_NUMBER_OF_SOLUTIONS);
    }
}