sfdx-source/force-app/main/default/objects/Campaign_Product__c/Campaign_Product__c.object-meta.xml
<CustomObject>
    <description>LEM-625: This object is to store the products available for reps to pitch or gather Mx insights on so that they can be easily updated and related back to other objects.</description>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Adjusted_Incr_Sales_Uplift__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Incr_Sales_Uplift__c</fullName>
    <label>Adjusted Incr. Sales Uplift $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/IncrementalSales__c.field-meta.xml
<CustomField>
    <fullName>IncrementalSales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15222: It is used to store the sales value for the campaign Product.</description>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
s
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>LEM-15224: It represents the points of the solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>LEM-15224: It represents the Rank of the Solution record.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Campaign_Product__c/fields/VSP_Code__c.field-meta.xml
<CustomField>
    <fullName>VSP_Code__c</fullName>
    <description>LEM-15224: It represents the VSP Code of the Solution.</description>
    <complianceGroup>GDPR</complianceGroup>
    <label>VSP Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/Lever__c.object-meta.xml
<CustomObject>
    <description>LEM-15226: The object will represent the Growth and Operational Levers which get created after reps choose and select from the raw recommendations.</description>
    <label>Lever</label>
    <nameField>
        <displayFormat>LVR-{0000}</displayFormat>
        <label>Lever Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Levers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Adjusted_Incr_Sales_Uplift__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Incr_Sales_Uplift__c</fullName>
    <description>LEM-17006: It will This field will display a number value. It will take the value from the “Incremental Sales Uplift $”, divide that number by the number of days in the quarter, and multiply by the number of days remaining in the quarter.</description>
    <formula>( Predicted_Incremental_Sales__c /(((IF(
MONTH(Today()) &lt; 4,
(ADDMONTHS(DATE( YEAR(Today()), 01, 01),3)-1),
IF(
MONTH(Today()) &lt; 7,
(ADDMONTHS(DATE( YEAR(Today()), 04, 01),3)-1),
IF(
MONTH(Today()) &lt; 10,
(ADDMONTHS(DATE( YEAR(Today()), 07, 01),3)-1),
(ADDMONTHS(DATE( YEAR(Today()), 10, 01),3)-1)
))))) - IF(
MONTH(Today()) &lt; 4,
DATE( YEAR(Today()), 01, 01),
IF(
MONTH(Today()) &lt; 7,
DATE( YEAR(Today()), 04, 01),
IF(
MONTH(Today()) &lt; 10,
DATE( YEAR(Today()), 07, 01),
DATE( YEAR(Today()), 10, 01)
)))+1))*(IF(
MONTH(Today()) &lt; 4,
(ADDMONTHS(DATE( YEAR(Today()), 01, 01),3)),
IF(
MONTH(Today()) &lt; 7,
(ADDMONTHS(DATE( YEAR(Today()), 04, 01),3)),
IF(
MONTH(Today()) &lt; 10,
(ADDMONTHS(DATE( YEAR(Today()), 07, 01),3)),
(ADDMONTHS(DATE( YEAR(Today()), 10, 01),3))
)))-Today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjusted Incr. Sales Uplift $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15224 : It represents the points of the related solution record.</description>
    <formula>Solution__r.Points__c</formula>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-16469: It stores the rank of a Lever.</description>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Lever__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15226: It is used to store the associated Campaign Product.</description>
    <label>Solution</label>
    <referenceTo>Campaign_Product__c</referenceTo>
    <relationshipLabel>Levers</relationshipLabel>
    <relationshipName>Levers</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/Recommendation_Business__x.object-meta.xml
<CustomObject>
    <description>LEM-13429: It visualizes recommendation record details from vsp_prediction_by_business table.</description>
    <externalDataSource>Figment_Data_Connector</externalDataSource>
    <externalName>public$vsp_predictions_by_business</externalName>
    <label>Business Recommendation</label>
    <pluralLabel>Business Recommendations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-13429: It stores a reference to Business Account records.</description>
    <externalDeveloperName>business_account_id</externalDeveloperName>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VSP_Recommendations_for_Business</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/incremental_sales__c.field-meta.xml
<CustomField>
    <fullName>incremental_sales__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>incremental_sales</externalDeveloperName>
    <label>Predicted Incremental Sales Uplift $</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/points__c.field-meta.xml
<CustomField>
    <fullName>points__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the sum of the points of all the stores directly under the business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>decile</externalDeveloperName>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/rank__c.field-meta.xml
<CustomField>
    <fullName>rank__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It calculates based on the sum of the Predicted Incremental Sales Uplift in $ of all the stores directly under the Business Account to which the VSP Recommendation applies.</description>
    <externalDeveloperName>rank</externalDeveloperName>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Recommendation_Business__x/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13429: It displays the Recommendation Name.</description>
    <externalDeveloperName>product_name</externalDeveloperName>
    <label>Recommendation</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/force-app/main/default/classes/controllers/SolutionsController.cls
/**
 * @author Deloitte
 * @date 06/13/2024
 * @description This is the controller class for Solutions.
 */
public with sharing class SolutionsController {
    /**
     * @description It is used to get solutions associated to the bussiness Accounts.
     * @param createAccountPlanOrAddLeversInputVariables
     * @return List<AccountLeverEntry>
     */
    @InvocableMethod(
        label='Solutions with Predictions'
        description='Get List of Solutions with VSP Predictions'
    )
    public static List<AccountLeverEntry> getSolutionsWithPredictionsByBusinessAccounts(
        List<CreateAccountPlanOrAddLeversInputVariables> createAccountPlanOrAddLeversInputVariables
    ) {
        List<String> businessAccountIds = createAccountPlanOrAddLeversInputVariables.get(0)
            .businessAccountIds;
        String accountPlanId = createAccountPlanOrAddLeversInputVariables.get(0).accountPlanId;
        List<AccountLeverEntry> solutionsToBeReturned = new List<AccountLeverEntry>();
        List<String> vspCodes = new List<String>();
        Map<Id, Map<String, Recommendation_Business__x>> vspRecByProductNameByAccountId = new Map<Id, Map<String, Recommendation_Business__x>>();

        for (
            Recommendation_Business__x eachBusinessRecommendation : BusinessRecommendationsSelector.newInstance()
                .selectBusinessRecommendationsByBusinessAccountIds(businessAccountIds)
        ) {
            vspCodes.add(eachBusinessRecommendation.Recommendation__c);
            if (
                !vspRecByProductNameByAccountId.containsKey(
                    eachBusinessRecommendation.Business_Account__r.Id
                )
            ) {
                vspRecByProductNameByAccountId.put(
                    eachBusinessRecommendation.Business_Account__r.Id,
                    new Map<String, Recommendation_Business__x>()
                );
            }
            vspRecByProductNameByAccountId.get(eachBusinessRecommendation.Business_Account__r.Id)
                .put(eachBusinessRecommendation.Recommendation__c, eachBusinessRecommendation);
        }
        solutionsToBeReturned = getAssociatedSolutions(
            vspCodes,
            vspRecByProductNameByAccountId,
            businessAccountIds,
            accountPlanId
        );
        return solutionsToBeReturned;
    }
    /**
     * @description It is used to get associated solutions to business account.
     * @param vspCodes
     * @param vspRecByProductNameByAccountId
     * @param businessAccountIds
     * @param accountPlanId
     * @return List<AccountLeverEntry>
     */
    private static List<AccountLeverEntry> getAssociatedSolutions(
        List<String> vspCodes,
        Map<Id, Map<String, Recommendation_Business__x>> vspRecByProductNameByAccountId,
        List<String> businessAccountIds,
        String accountPlanId
    ) {
        Set<String> accountPlanWithLeversAndSolutionsSet = new Set<String>();
        List<AccountLeverEntry> solutionsToBeReturned = new List<AccountLeverEntry>();
        List<Campaign_Product__c> solutions = SolutionsSelector.newInstance()
            .selectActiveSolutionsByVSPCodes();
        if (accountPlanId != null) {
            for (
                Lever__c eachLever : LeversSelector.newInstance()
                    .selectOpenLeversByAccountPlanId(new Set<Id>{ accountPlanId })
            ) {
                accountPlanWithLeversAndSolutionsSet.add(eachLever.Solution__r.Name);
            }
        }
        if (!solutions.isEmpty()) {
            //for (String eachAccountId : businessAccountIds) {
            Date currentQuarterStartDate;
            Date currentQuarterEndDate;
            Date todayDate = System.today();
            currentQuarterStartDate = getCurrentQuarter(todayDate);
            currentQuarterEndDate = (currentQuarterStartDate.addMonths(3) - 1);
            Integer totalNumberOfDaysInTheCurrentQuarter = currentQuarterStartDate.daysBetween(
                currentQuarterStartDate.addMonths(3)
            );
            Integer remainingNumberOfDaysInTheCurrentQuarter = todayDate.daysBetween(
                currentQuarterStartDate.addMonths(3)
            );
            Id eachAccountId = businessAccountIds[0];
            AccountLeverEntry accountLevers = new AccountLeverEntry();
            accountLevers.solutions = new List<Campaign_Product__c>();
            for (Campaign_Product__c eachSolution : solutions) {
                if (
                    accountPlanWithLeversAndSolutionsSet.size() > 0 &&
                    accountPlanWithLeversAndSolutionsSet.contains(eachSolution.Name)
                ) {
                    continue;
                }
                if (
                    vspRecByProductNameByAccountId.containsKey(eachAccountId) &&
                    vspRecByProductNameByAccountId.get(eachAccountId)
                        .containsKey(eachSolution.VSP_Code__c)
                ) {
                    eachSolution.IncrementalSales__c = vspRecByProductNameByAccountId.get(
                            eachAccountId
                        )
                        .get(eachSolution.VSP_Code__c)
                        .incremental_sales__c;
                    eachSolution.Adjusted_Incr_Sales_Uplift__c = ((eachSolution.IncrementalSales__c /
                        totalNumberOfDaysInTheCurrentQuarter) *
                        remainingNumberOfDaysInTheCurrentQuarter)
                        .setScale(2);
                    eachSolution.Points__c = vspRecByProductNameByAccountId.get(eachAccountId)
                        .get(eachSolution.VSP_Code__c)
                        .Points__c;
                    eachSolution.Rank__c = vspRecByProductNameByAccountId.get(eachAccountId)
                        .get(eachSolution.VSP_Code__c)
                        .Rank__c;
                }
                accountLevers.solutions.add(eachSolution);
            }
            solutionsToBeReturned.add(accountLevers);
            //}
        }
        return solutionsToBeReturned;
    }

    /**
     * @description It is used to get current quarter of the year.
     * @param todayDate
     * @return Date
     */
    private static Date getCurrentQuarter(Date todayDate) {
        Date currentQuarterStartDate;
        Integer currentQtr = Decimal.valueOf(todayDate.month())
            .divide(3.0, 0, System.RoundingMode.UP)
            .intValue();
        Date startOfYear = date.newInstance(system.today().year(), 1, 1);
        if (currentQtr == 1) {
            currentQuarterStartDate = startOfYear;
        } else if (currentQtr == 2) {
            currentQuarterStartDate = startOfYear.addMonths(3);
        } else if (currentQtr == 3) {
            currentQuarterStartDate = startOfYear.addMonths(6);
        } else if (currentQtr == 4) {
            currentQuarterStartDate = startOfYear.addMonths(9);
        }
        return currentQuarterStartDate;
    }

    /**
     * @description It is used to get business account Id and AccountPlanId (Create Account Plan & Add Levers Flows)
     * @param businessAccountIds
     * @param accountPlanId
     */
    public class CreateAccountPlanOrAddLeversInputVariables {
        @InvocableVariable
        public List<String> businessAccountIds;

        @InvocableVariable
        public String accountPlanId;
    }
}