sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/RESSMO_UI_Input__mdt.object-meta.xml
<CustomObject>
    <description>LEM-16420 Store fields to display on RESSMO UI.</description>
    <label>RESSMO UI Input</label>
    <pluralLabel>RESSMO UI Inputs</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>Applicable_For__c</fullName>
    <description>Used to Select if metadata needs to display on Quote or Contract Screen for RESSMO</description>
    <label>Applicable For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
                <default>true</default>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>Store the API Name of field displayed on RESSMO UI Screen on Contract and Quote</description>
    <label>Field API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Input_Type__c.field-meta.xml
<CustomField>
    <fullName>Input_Type__c</fullName>
    <description>Store the Type of Input if Input is Generic and is not used from Record Edit Form to be displayed on RESSMO UI Screen on Contract and Quote</description>
    <label>Input Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Input_UI_Label__c.field-meta.xml
<CustomField>
    <fullName>Input_UI_Label__c</fullName>
    <description>Store the Label of Input if Input is Generic and is not used from Record Edit Form to be displayed on RESSMO UI Screen on Contract and Quote</description>
    <label>Input UI Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Store the Object API Name if Input is used from Record Edit Form to be displayed on RESSMO UI Screen on Contract and Quote</description>
    <label>Object API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Stores the order of the field in which the input needs to be displayed</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>Store the picklist values in this field by ; Seperated</description>
    <inlineHelpText>Yes;No</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <description>Section on UI under which details needs to be rendered.</description>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Photoshoot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Input type Simple / Generic Input /Address / [FieldSpecific] /Empty Block to determine input behaviour</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/UI_Validation_Message__c.field-meta.xml
<CustomField>
    <fullName>UI_Validation_Message__c</fullName>
    <label>UI Validation Message</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/RESSMO_UI_Input__mdt/fields/Validation__c.field-meta.xml
<CustomField>
    <fullName>Validation__c</fullName>
    <label>Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Required on UI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/RESSMOUIInputsSelectorTest.cls
/**
 * @description       : Test Class for RESSMOUIInputsSelector
 * @author            : SamikshaDD
 * @group             : Aethereus
 * @last modified on  : 10-07-2024
 * @last modified by  : Soumya Dash
**/
@isTest
public with sharing class RESSMOUIInputsSelectorTest {

    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: there is a mismatch in fields list.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: the object type must be RESSMOUIInput custom metadata';
    private static final String ASSERT_MESSAGE_APPLICABLE_FIELD_CONTRACT = 'The "Applicable_For__c" field should be "Contract"';
    private static final String ASSERT_MESSAGE_APPLICABLE_FIELD_QUOTE = 'The "Applicable_For__c" field should be "Quote"';
    private static final String APPLICABLE_FOR_CONTRACT = 'Contract';
    private static final String ASSERT_MESSAGE_COUNT_NOT_MATCHING = 'assert count not matching';

    /**
    * @description test When RESSMO UI Inputs Selector Instantiates Then Call
    * @author SamikshaDD | 07-29-2024
    **/
    @isTest
    private static void testWhenRESSMOUIInputsSelectorInstantiatesThenCall() {
        List<Schema.SObjectField> sObjectFieldsMock = new List<Schema.SObjectField>{
            RESSMO_UI_Input__mdt.Label,
            RESSMO_UI_Input__mdt.MasterLabel,
            RESSMO_UI_Input__mdt.DeveloperName,
            RESSMO_UI_Input__mdt.Applicable_For__c,
            RESSMO_UI_Input__mdt.Field_API_Name__c,
            RESSMO_UI_Input__mdt.Input_Type__c,
            RESSMO_UI_Input__mdt.Input_UI_Label__c,
            RESSMO_UI_Input__mdt.Object_API_Name__c,
            RESSMO_UI_Input__mdt.Order__c,
            RESSMO_UI_Input__mdt.Validation__c,
            RESSMO_UI_Input__mdt.Section__c,
            RESSMO_UI_Input__mdt.Type__c,
            RESSMO_UI_Input__mdt.UI_Validation_Message__c,
            RESSMO_UI_Input__mdt.Picklist_Values__c
        };

        RESSMOUIInputsSelector ressmoUIInputsSelectorInstance = new RESSMOUIInputsSelector();
        Schema.SObjectType typeOfObject = ressmoUIInputsSelectorInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = ressmoUIInputsSelectorInstance.getSObjectFieldList();
        RESSMOUIInputsSelector.newInstance();

        Assert.areEqual(
            RESSMO_UI_Input__mdt.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        Assert.areEqual(
            sObjectFieldsMock,
            sObjectFields,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }


    /**
    * @description test When RESSMO Ui Inputs Of Contract Then Return
    * @author SamikshaDD | 07-29-2024
    **/
    @isTest
    public static void testWhenRESSMOUiInputsOfContractThenReturn(){

        RESSMO_UI_Input__mdt ressmoUiInputContract = new RESSMO_UI_Input__mdt(
            MasterLabel = 'Test Contract Mapping',
            Applicable_For__c = 'Contract',
            Is_Active__c = true
        );

        List<RESSMO_UI_Input__mdt> ressmoUiInputContractList = RESSMOUIInputsSelector.newInstance().selectRessmoUiInputsOfContract();
        Assert.areEqual(ressmoUiInputContract.Applicable_For__c, ressmoUiInputContractList[0].Applicable_For__c, ASSERT_MESSAGE_APPLICABLE_FIELD_CONTRACT);
    }


    /**
    * @description test When RESSMO Ui Inputs Of Quote Then Return
    * @author SamikshaDD | 07-29-2024
    **/
    @isTest
    public static void testWhenRESSMOUiInputsOfQuoteThenReturn(){

        RESSMO_UI_Input__mdt ressmoUiInputContract = new RESSMO_UI_Input__mdt(
            MasterLabel = 'Test Contract Mapping',
            Applicable_For__c = 'Quote',
            Is_Active__c = true
        );

        List<RESSMO_UI_Input__mdt> ressmoUiInputContractList = RESSMOUIInputsSelector.newInstance().selectRessmoUiInputsOfQuote();
        Assert.areEqual(ressmoUiInputContract.Applicable_For__c, ressmoUiInputContractList[0].Applicable_For__c, ASSERT_MESSAGE_APPLICABLE_FIELD_QUOTE);
    }

    @isTest
    public static void testWhenRESSMOAndOIATTributesThenReturnALLRecords(){

        List<RESSMO_UI_Input__mdt> ressmoUiInputContractList = RESSMOUIInputsSelector.newInstance().selectAllREESMOUIInputContract();
        Assert.areEqual([SELECT Id from RESSMO_UI_Input__mdt WHERE Applicable_For__c =:APPLICABLE_FOR_CONTRACT  AND Is_Active__c = true].size(), ressmoUiInputContractList.size(),ASSERT_MESSAGE_COUNT_NOT_MATCHING );
    }


}