sfdx-source/force-app/main/default/objects/WorkOrder/fields/HasWorkPlansGenerated__c.field-meta.xml
<CustomField>
    <fullName>HasWorkPlansGenerated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-1956: It indicates whether Work Plans are generated on parent Work Order.</description>
    <label>HasWorkPlansGenerated</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Provisioning_Status__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Status__c</fullName>
    <description>LEM-2083: It indicates the Provisioning Status of stores and business. In addition to that, it has the following purposes:
1. It is updated on child Work Orders by provisioning integration and parent Work Orders by apex based roll-up logic.
2. Drives logic for Work Plans and Work Steps creation.
3. Indicates the readiness of the stores for provisioning in the backend databases.</description>
    <label>Provisioning Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Readiness Check</fullName>
            </value>
            <value>
                <fullName>Readiness Check Failed</fullName>
            </value>
            <value>
                <fullName>Readiness Check Complete</fullName>
            </value>
            <value>
                <fullName>Ready for Provisioning</fullName>
            </value>
            <value>
                <fullName>Provisioning Complete</fullName>
            </value>
            <value>
                <fullName>Provisioning Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/batchables/WorkOrdersProvisioningStatusCOOBatch.cls
/**
 * @author DoorDash
 * @date 11/29/2022
 * @description Batch class that updates the Provisioning status on COO Work Orders to Ready for Provisioning the day before the PDOA date.
 */
public with sharing class WorkOrdersProvisioningStatusCOOBatch implements Database.Batchable<SObject>, Schedulable {
    @testvisible
    private static final String PROVISIONING_STATUS_READY_FOR_PROVISIONING = 'Ready for Provisioning';
    /**
     * @description It queries all WorkOrders where PDOA date is in future
     * @JIRA# LEM-3648
     * @param batchableContext
     * @return Database.QueryLocator
     */
    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        return WorkOrdersSelector.newInstance().selectCOOWorkOrdersBasedOnPDOADate();
    }

    /**
     * @description It updates WorkOrder provisioning status according to PDOA dates.
     * @JIRA# LEM-3648
     * @param batchableContext
     * @param workOrders
     */
    public void execute(Database.BatchableContext batchableContext, List<WorkOrder> workOrders) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        for (WorkOrder eachWorkOrder : workOrders) {
            eachWorkOrder.Provisioning_Status__c = PROVISIONING_STATUS_READY_FOR_PROVISIONING;
            eachWorkOrder.HasWorkPlansGenerated__c = true;
            uow.registerDirty(eachWorkOrder);
        }
        try {
            uow.commitWork();
        } catch (Exception ex) {
            Logger.publish(LogEntry.newExceptionLog(ex, LogEntry.SeverityLevel.HIGH));
        }
    }

    /**
     * @description Finish method of this batch.
     * Suppressed Warnings since finish method is required to be implemented
     * but no logic is required to be processed in it.
     * @JIRA# LEM-3648
     * @param batchableContext
     */
    @SuppressWarnings('PMD.EmptyStatementBlock')
    public void finish(Database.BatchableContext batchableContext) {
    }

    /**
     * @description Execute method to schedule this batch.
     * @param schedulableContext
     */
    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(new WorkOrdersProvisioningStatusCOOBatch());
    }
}