sfdx-source/force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-813: Opportunity linked to the onboarding event.</description>
    <inlineHelpText>Opportunity linked to the onboarding event</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-813: Onboarding event type.</description>
    <inlineHelpText>Onboarding event type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Order_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Work_Order_Name__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-982: It indicates Work Order name generated from a combination of Work Order number, Account name, Work Order type, Account billing country, Work Order PDOA original.</description>
    <formula>WorkOrderNumber + &apos; - &apos; + Account.Name + &apos; - &apos; + TEXT(Type__c) +
IF(
  ISBLANK(Account.BillingCountry),
  &apos;&apos;,
  &apos; - &apos; + Account.BillingCountry
) +
IF(
  ISBLANK(Proposed_Date_of_Activation_Original__c),
  &apos;&apos;,
  &apos; - &apos; + TEXT(MONTH(Proposed_Date_of_Activation_Original__c)) + &apos;/&apos; + TEXT(DAY(Proposed_Date_of_Activation_Original__c)) + &apos;/&apos; + TEXT(YEAR(Proposed_Date_of_Activation_Original__c))
)</formula>
    <label>Work Order Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Work_Order_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketplace</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Sales</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Ads &amp; Promos</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Order type values.</description>
    <masterLabel>Work Order Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/controllers/DisplayWorkOrdersControllerTest.cls
/**
 * @author Deloitte
 * @date 15/03/2022
 * @description This is a test class for DisplayWorkOrdersRelatedList.
 */
@isTest(SeeAllData=false)
private class DisplayWorkOrdersControllerTest {
    /**
     * @description To test the retrieved fields when get fields method is called.
     */
    @isTest
    private static void testWhenRetriveFieldsFromFieldSetThenReturnDefaultFieldsAndTheirAttributesInJsonFormat() {
        String jsonData = DisplayWorkOrdersController.getFields();
        List<DynamicColumn> dynamicColumn = (List<DynamicColumn>) JSON.deserialize(
            jsonData,
            List<DynamicColumn>.class
        );
        System.assertEquals(
            'workOrderNumberHyperlink',
            dynamicColumn[0].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'url',
            dynamicColumn[0].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'WorkOrderNumber',
            dynamicColumn[0].typeAttributes.label.fieldName,
            'Unexpected Error: Field Name is not matching'
        );
        System.assertEquals(
            'Work Order Number',
            dynamicColumn[0].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'workOrderNameHyperlink',
            dynamicColumn[1].fieldName,
            'Unexpected Error:Field Name is not matching'
        );
        System.assertEquals(
            'url',
            dynamicColumn[1].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Work_Order_Name__c',
            dynamicColumn[1].typeAttributes.label.fieldName,
            'Unexpected Error: Field Name is not matching'
        );
        System.assertEquals(
            'Work Order Name',
            dynamicColumn[1].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[2].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Status',
            dynamicColumn[2].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[3].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Type',
            dynamicColumn[3].label,
            'Unexpected Error: Field Label is not matching'
        );
        System.assertEquals(
            'string',
            dynamicColumn[4].type,
            'Unexpected Error: Field Type__c is not matching'
        );
        System.assertEquals(
            'Proposed Date of Activation',
            dynamicColumn[4].label,
            'Unexpected Error: Field Label is not matching'
        );
    }

    /**
     * @description To test if unique records are retrieved when get parent work orders method is called.
     */
    @IsTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenGetWorkOrdersRecordsByStoreAccountAndOpportunityThenReturnUniqueParentWorkOrderRecords() {
        Id businessId = Fake.generateId(Account.class);
        Id storeId = Fake.generateId(Account.class);
        Id oppId = Fake.generateId(Opportunity.class);

        WorkOrder[] parentWorkOrders = new List<WorkOrder>{
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Drive',
                Status = 'Planning',
                AccountId = businessId,
                Opportunity__c = oppId
            ),
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Marketplace',
                Status = 'Planning',
                AccountId = businessId,
                Opportunity__c = oppId
            )
        };

        WorkOrder[] childWorkOrders = new List<WorkOrder>{
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Drive',
                Status = 'Planning',
                AccountId = storeId,
                ParentWorkOrder = parentWorkOrders[0],
                Opportunity__c = oppId
            ),
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Drive',
                Status = 'Planning',
                AccountId = storeId,
                ParentWorkOrder = parentWorkOrders[0],
                Opportunity__c = oppId
            ),
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Marketplace',
                Status = 'Planning',
                AccountId = storeId,
                ParentWorkOrder = parentWorkOrders[1],
                Opportunity__c = oppId
            ),
            new WorkOrder(
                Id = Fake.generateId(WorkOrder.class),
                Type__c = 'Marketplace',
                Status = 'Planning',
                AccountId = storeId,
                ParentWorkOrder = parentWorkOrders[1],
                Opportunity__c = oppId
            )
        };

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IWorkOrdersSelector selectorMock = (IWorkOrdersSelector) mocks.mock(
            IWorkOrdersSelector.class
        );
        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(WorkOrder.SObjectType);
        mocks.when(selectorMock.selectWorkOrdersByAccountId(storeId)).thenReturn(childWorkOrders);
        mocks.when(selectorMock.selectWorkOrdersByOpportunityId(oppId)).thenReturn(parentWorkOrders);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(selectorMock);
        List<WorkOrder> uniqueWorkOrders = DisplayWorkOrdersController.getWorkOrderDetails(
            storeId
        );
        List<WorkOrder> uniqueWorkOrdersForOpp = DisplayWorkOrdersController.getWorkOrderDetails(
            oppId
        );
        System.assertEquals(2, uniqueWorkOrders.size(), 'The list size does not match');
        System.assertEquals(
            parentWorkOrders[0].Id,
            uniqueWorkOrders[0].Id,
            'The work order id does not match'
        );
        System.assertEquals(
            parentWorkOrders[1].Id,
            uniqueWorkOrders[1].Id,
            'The work order id does not match'
        );
        System.assertEquals(2, uniqueWorkOrdersForOpp.size(), 'The list size does not match');
        System.assertEquals(
            parentWorkOrders[0].Id,
            uniqueWorkOrdersForOpp[0].Id,
            'The work order id does not match'
        );
        System.assertEquals(
            parentWorkOrders[1].Id,
            uniqueWorkOrdersForOpp[1].Id,
            'The work order id does not match'
        );
    }
}