sfdx-source/force-app/main/default/objects/Business_Vertical__c/Business_Vertical__c.object-meta.xml
<CustomObject>
    <description>LEM-11076: It is used to capture the Vertical, UI Type and Product as a singular Business Vertical Id.</description>
    <label>Business Vertical</label>
    <nameField>
        <label>Business Vertical</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>LEM-11076: It indicates if the Business Vertical Record is Active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Business_Vertical_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_Vertical_ID__c</fullName>
    <description>LEM-11076: This field is to capture the unique vertical ID of the business vertical</description>
    <externalId>true</externalId>
    <label>Business Vertical ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>LEM-11076: This field is to capture the description of the vertical.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Menu_UI_Type__c.field-meta.xml
<CustomField>
    <fullName>Menu_UI_Type__c</fullName>
    <description>LEM-11076: This field is to capture the menu type of the vertical.</description>
    <label>Menu UI Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Menu_UI</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Primary_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vertical__c</fullName>
    <description>LEM-11076: This field is to capture the primary vertical value of this business vertical.</description>
    <label>Primary Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>LEM-11076: This field is to capture the product related to the business vertical.</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Vertical__c/fields/Vertical_Name__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Name__c</fullName>
    <description>LEM-11076: This field is to capture the vertical name.</description>
    <label>Vertical Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Menu_UI.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <description>LEM-2082 Captures the UI associated with the Business.</description>
    <masterLabel>Menu UI</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/globalValueSets/Vertical.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alcohol</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Catering</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience</fullName>
    </customValue>
    <customValue>
        <fullName>CPG</fullName>
    </customValue>
    <customValue>
        <fullName>Dashmart</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Express Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Floral</fullName>
    </customValue>
    <customValue>
        <fullName>Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Government/NonProfit</fullName>
    </customValue>
    <customValue>
        <fullName>Grocery</fullName>
    </customValue>
    <customValue>
        <fullName>Health &amp; Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Hemp &amp; Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Home Chef</fullName>
    </customValue>
    <customValue>
        <fullName>Home Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Home Improvement</fullName>
    </customValue>
    <customValue>
        <fullName>Hot &amp; Prepared</fullName>
    </customValue>
    <customValue>
        <fullName>Misc.</fullName>
    </customValue>
    <customValue>
        <fullName>Nationwide Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Rx</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
        <isActive>false</isActive>
        <label>Pharmacy</label>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
        <isActive>false</isActive>
        <label>Cannabis</label>
    </customValue>
    <description>LEM-280: This picklist value set is created to define the verticals and sub-verticals associated with store and business accounts.</description>
    <masterLabel>Vertical</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/tests/classes/unit/triggerHandlers/BusinessVerticalsHandlerTest.cls
/**
 * @description This is test class for BusinessVerticalHandler class
 * @author Deloitte
 * @date 11/11/2023
 */
@isTest(SeeAllData=false)
public class BusinessVerticalsHandlerTest {
    /**
     * @description Test BusinessVerticalHandler class on Business Vertical Insertion
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    public static void testWhenBusinessVerticalCreatedThenCall() {
        List<Business_Vertical__c> businessVerticalList = new List<Business_Vertical__c>{
            new Business_Vertical__c(
                Active__c = true,
                Description__c = 'for Unit Testing',
                Menu_UI_Type__c = 'Retail',
                Primary_Vertical__c = 'Baby',
                Product__c = 'Drive',
                Vertical_Name__c = 'Grocery',
                Business_Vertical_ID__c = '12'
            ),
            new Business_Vertical__c(
                Active__c = true,
                Description__c = 'for Unit Testing 2',
                Menu_UI_Type__c = 'Retail',
                Primary_Vertical__c = 'Alcohol',
                Product__c = 'Drive',
                Vertical_Name__c = 'Alcohol',
                Business_Vertical_ID__c = '13'
            )
        };
        fflib_SObjectDomain.Test.Database.onInsert(businessVerticalList);

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IBusinessVerticals businessVerticalsMock = (IBusinessVerticals) mocks.mock(IBusinessVerticals.class);
        mocks.startStubbing();
        mocks.when(businessVerticalsMock.getType()).thenReturn(Business_Vertical__c.SObjectType);
        mocks.stopStubbing();
        Application.DOMAIN.setMock(businessVerticalsMock);

        fflib_SObjectDomain.triggerHandler(BusinessVerticalsHandler.class);
        ((IBusinessVerticals) mocks.verify(businessVerticalsMock, 1)).assignNameOnInsertOrNameUpdate();
    }

    @isTest
    public static void testWhenBusinessVerticalIsInsertedThenNameIsUpdated() {
        List<Business_Vertical__c> businessVerticalList = new List<Business_Vertical__c>{
            new Business_Vertical__c(
                Active__c = true,
                Description__c = 'for Unit Testing',
                Menu_UI_Type__c = 'Retail',
                Primary_Vertical__c = 'Baby',
                Product__c = 'Drive',
                Vertical_Name__c = 'Grocery',
                Business_Vertical_ID__c = '12'
            )
        };
        insert businessVerticalList;

        List<Business_Vertical__c> insertedBusinessVerticalRecord = [
            SELECT Id, Name, Vertical_Name__c, Business_Vertical_ID__c
            FROM Business_Vertical__c
        ];

        Id bizVertRecord = insertedBusinessVerticalRecord[0].id;
		insertedBusinessVerticalRecord[0].Business_Vertical_ID__c = '';
        update insertedBusinessVerticalRecord[0];
        
  		List<Business_Vertical__c> updatedBusinessVerticalRecord = [
            SELECT Id, Name, Vertical_Name__c, Business_Vertical_ID__c
            FROM Business_Vertical__c where id =:bizVertRecord
        ];

        System.assertNotEquals(
            businessVerticalList[0].Vertical_Name__c + ' ' + '(' +
            businessVerticalList[0].Business_Vertical_ID__c + ')',
            updatedBusinessVerticalRecord[0].Name,
            'The Business Vertical Name has not been assigned correctly'
        );
    }
}