sfdx-source/force-app/main/default/objects/Product2/fields/Applicable_Segment__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Segment__c</fullName>
    <description>LEM-13394: It is used to store applicable account segment values to filter out products on Quote Line Editor.</description>
    <label>Applicable Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/Quote_Line_Drawer_Attributes__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1486 To display the attributes on the quote configurator</description>
    <label>Quote Line Drawer Attributes</label>
    <pluralLabel>Quote Line Drawer Attributes</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Applicable_Segment__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Segment__c</fullName>
    <description>LEM-13441: This field captures the account segment value for which this attribute is applicable.</description>
    <label>Applicable Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
                <default>true</default>
                <label>Enterprise</label>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Eligible_for_Product__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6458- True if this attribute should show for this product when sold standalone</description>
    <label>Eligible for Product</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Eligible_Packages__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Packages__c</fullName>
    <description>LEM-6458: Packages Name to which this attribute applies to</description>
    <label>Eligible Packages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Quote_Line_Drawer_Products__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Drawer_Products__c</fullName>
    <label>Quote Line Drawer Products</label>
    <referenceTo>Quote_Line_Drawer_Products__mdt</referenceTo>
    <relationshipLabel>Quote Line Drawer Attributes</relationshipLabel>
    <relationshipName>Quote_Line_Drawer_Attributes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Required_for_Segment__c.field-meta.xml
<CustomField>
    <fullName>Required_for_Segment__c</fullName>
    <description>LEM-13441: This field captures the account segment value for which this attribute is required.</description>
    <label>Required For Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
                <default>true</default>
                <label>Enterprise</label>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Products__mdt/Quote_Line_Drawer_Products__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1486 This for displaying attributes on Quote configurator</description>
    <label>Quote Line Drawer Products</label>
    <pluralLabel>Quote Line Drawer Products</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Products__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/tests/classes/unit/controllers/DisplayQuoteLineAttributesControllerTest.cls
/**
 * @author DoorDash
 * @date 24/06/2022
 * @description Test class for DisplayQuoteLineAttributesController class.
 * Suppressed Warnings since mock verify method does not require system assert statements.
 */
@isTest
public with sharing class DisplayQuoteLineAttributesControllerTest {
    private static final String PARENT_PRODUCT_CODE = '10012';
    private static final Integer DELIVERY_PRODUCT_LINE_NUMBER = 2;
    private static final String PARENT_PRODUCT_NAME = 'Large Order Fulfillment (LOF)';
    private static final String DELIVERY_PRODUCT_NAME = 'Delivery';

    @IsTest
    public static void testWhenProductCodeThenGetQuoteLineAttributes() {
        map<String, List<String>> optionalFields;
        map<String, List<String>> requiredFields;
        map<String, List<String>> activePrices;
        Id parentQLEProdId = fflib_IDGenerator.generate(
            Quote_Line_Drawer_Products__mdt.SObjectType
        );

        List<Quote_Line_Drawer_Attributes__mdt> qleAttributeList = new List<Quote_Line_Drawer_Attributes__mdt>{
            (Quote_Line_Drawer_Attributes__mdt) new Fake(Quote_Line_Drawer_Attributes__mdt.class)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Active__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c, null)
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_For_Product__c, false)
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c, 'Test_API_Name__c')
                .setField(Quote_Line_Drawer_Attributes__mdt.MasterLabel, 'Test_Label')
                .setField(Quote_Line_Drawer_Attributes__mdt.DeveloperName, 'Test_DeveName')
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_Label__c, 'Test_fieldLabel')
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
                    parentQLEProdId
                )
                .setParent(
                    'Quote_Line_Drawer_Products__r',
                    new Fake(Quote_Line_Drawer_Products__mdt.class)
                        .setField(Quote_Line_Drawer_Products__mdt.Id, parentQLEProdId)
                        .setField(Quote_Line_Drawer_Products__mdt.Is_Active__c, true)
                        .setField(Quote_Line_Drawer_Products__mdt.Product_Code__c, '11111')
                )
                .toSObject(),
            (Quote_Line_Drawer_Attributes__mdt) new Fake(Quote_Line_Drawer_Attributes__mdt.class)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Active__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Required__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_Packages__c, 'Package1')
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_For_Product__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c, 'Test_API_Name__c2')
                .setField(Quote_Line_Drawer_Attributes__mdt.MasterLabel, 'Test_Label2')
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_Label__c, 'Test_FieldDeveName_2')
                .setField(Quote_Line_Drawer_Attributes__mdt.DeveloperName, 'Test_DeveName2')
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
                    parentQLEProdId
                )
                .setParent(
                    'Quote_Line_Drawer_Products__r',
                    new Fake(Quote_Line_Drawer_Products__mdt.class)
                        .setField(Quote_Line_Drawer_Products__mdt.Id, parentQLEProdId)
                        .setField(Quote_Line_Drawer_Products__mdt.Is_Active__c, true)
                        .setField(Quote_Line_Drawer_Products__mdt.Product_Code__c, '11111')
                )
                .toSObject()
        };
        DisplayQuoteLineAttributesController.quoteAccountSegment = 'Enterprise';

        DisplayQuoteLineAttributesController.QuoteLineAttributesWrapper wrapVar = new DisplayQuoteLineAttributesController.QuoteLineAttributesWrapper(
            optionalFields,
            requiredFields,
            activePrices
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IQuoteLineDrawAttributesSelector qleAttributesMock = (IQuoteLineDrawAttributesSelector) mocks.mock(
            IQuoteLineDrawAttributesSelector.class
        );
        mocks.startStubbing();
        mocks.when(qleAttributesMock.sObjectType())
            .thenReturn(Quote_Line_Drawer_Attributes__mdt.SObjectType);
        mocks.when(qleAttributesMock.selectQLAttributesByProductCode('11111'))
            .thenReturn(qleAttributeList);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(qleAttributesMock);
        Test.startTest();
        wrapVar = DisplayQuoteLineAttributesController.getQLProductsWithAttributes(
            '11111',
            '',
            'Enterprise'
        );
        Test.stopTest();

        System.assertEquals(
            wrapVar.requiredFields != null,
            true,
            'This product has QLE attributes'
        );
        System.assertEquals(
            wrapVar.requiredFields.values().size() > 0,
            true,
            'This product has required QLE attributes'
        );
        System.assertEquals(
            wrapVar.optionalFields.values().size() > 0,
            false,
            'This product has optional QLE attributes'
        );
    }

    @IsTest
    public static void testWhenProductPackageThenGetQuoteLineAttributes() {
        map<String, List<String>> optionalFields;
        map<String, List<String>> requiredFields;
        map<String, List<String>> activePrices;
        Id parentQLEProdId = fflib_IDGenerator.generate(
            Quote_Line_Drawer_Products__mdt.SObjectType
        );

        List<Quote_Line_Drawer_Attributes__mdt> qleAttributeList = new List<Quote_Line_Drawer_Attributes__mdt>{
            (Quote_Line_Drawer_Attributes__mdt) new Fake(Quote_Line_Drawer_Attributes__mdt.class)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Active__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c, null)
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Eligible_Packages__c,
                    'Package1; Package2'
                )
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_For_Product__c, false)
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c, 'Test_API_Name__c')
                .setField(Quote_Line_Drawer_Attributes__mdt.MasterLabel, 'Test_Label')
                .setField(Quote_Line_Drawer_Attributes__mdt.DeveloperName, 'Test_DeveName')
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_Label__c, 'Test_fieldLabel')
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
                    parentQLEProdId
                )
                .setParent(
                    'Quote_Line_Drawer_Products__r',
                    new Fake(Quote_Line_Drawer_Products__mdt.class)
                        .setField(Quote_Line_Drawer_Products__mdt.Id, parentQLEProdId)
                        .setField(Quote_Line_Drawer_Products__mdt.Is_Active__c, true)
                        .setField(Quote_Line_Drawer_Products__mdt.Product_Code__c, '11111')
                )
                .toSObject(),
            (Quote_Line_Drawer_Attributes__mdt) new Fake(Quote_Line_Drawer_Attributes__mdt.class)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Active__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Required__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_Packages__c, 'Package1')
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_For_Product__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c, 'Test_API_Name__c2')
                .setField(Quote_Line_Drawer_Attributes__mdt.MasterLabel, 'Test_Label2')
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_Label__c, 'Test_FieldDeveName_2')
                .setField(Quote_Line_Drawer_Attributes__mdt.DeveloperName, 'Test_DeveName2')
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
                    parentQLEProdId
                )
                .setParent(
                    'Quote_Line_Drawer_Products__r',
                    new Fake(Quote_Line_Drawer_Products__mdt.class)
                        .setField(Quote_Line_Drawer_Products__mdt.Id, parentQLEProdId)
                        .setField(Quote_Line_Drawer_Products__mdt.Is_Active__c, true)
                        .setField(Quote_Line_Drawer_Products__mdt.Product_Code__c, '11111')
                )
                .toSObject(),
            (Quote_Line_Drawer_Attributes__mdt) new Fake(Quote_Line_Drawer_Attributes__mdt.class)
                .setField(Quote_Line_Drawer_Attributes__mdt.Is_Active__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c, 'Enterprise')
                .setField(Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c, null)
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Eligible_Packages__c,
                    'Package1; Package2'
                )
                .setField(Quote_Line_Drawer_Attributes__mdt.Eligible_For_Product__c, true)
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c, 'Active_Fee__c')
                .setField(Quote_Line_Drawer_Attributes__mdt.MasterLabel, 'Test_Label3')
                .setField(Quote_Line_Drawer_Attributes__mdt.Field_Label__c, 'Test_FieldDeveName_3')
                .setField(Quote_Line_Drawer_Attributes__mdt.DeveloperName, 'Test_DeveName3')
                .setField(
                    Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
                    parentQLEProdId
                )
                .setParent(
                    'Quote_Line_Drawer_Products__r',
                    new Fake(Quote_Line_Drawer_Products__mdt.class)
                        .setField(Quote_Line_Drawer_Products__mdt.Id, parentQLEProdId)
                        .setField(Quote_Line_Drawer_Products__mdt.Is_Active__c, true)
                        .setField(Quote_Line_Drawer_Products__mdt.Product_Code__c, '11111')
                )
                .toSObject()
        };
        DisplayQuoteLineAttributesController.quoteAccountSegment = 'Enterprise';
        DisplayQuoteLineAttributesController.QuoteLineAttributesWrapper wrapVar = new DisplayQuoteLineAttributesController.QuoteLineAttributesWrapper(
            optionalFields,
            requiredFields,
            activePrices
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IQuoteLineDrawAttributesSelector qleAttributesMock = (IQuoteLineDrawAttributesSelector) mocks.mock(
            IQuoteLineDrawAttributesSelector.class
        );
        mocks.startStubbing();
        mocks.when(qleAttributesMock.sObjectType())
            .thenReturn(Quote_Line_Drawer_Attributes__mdt.SObjectType);
        mocks.when(qleAttributesMock.selectQLAttributesByProductCode('11111'))
            .thenReturn(qleAttributeList);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(qleAttributesMock);
        Test.startTest();
        wrapVar = DisplayQuoteLineAttributesController.getQLProductsWithAttributes(
            '11111',
            'Package1',
            'Enterprise'
        );
        Test.stopTest();

        List<String> requiredfieldList = wrapVar.requiredFields.get('11111Package1');

        System.assertEquals(
            wrapVar.requiredFields != null,
            true,
            'This product has QLE attributes'
        );
        System.assertEquals(
            wrapVar.requiredFields.values().size() > 0,
            true,
            'This product has required QLE attributes'
        );
        System.assertEquals(
            requiredfieldList.size() > 0,
            true,
            'This product has required QLE attributes'
        );
        System.assertEquals(
            wrapVar.optionalFields.values().size() > 0,
            true,
            'This product has optional QLE attributes'
        );
        System.assertEquals(
            wrapVar.activePrices.values().size() > 0,
            true,
            'This product has active price QLE attributes'
        );
    }

    @IsTest
    public static void testWhenParentProductNotNullThenInsertParentProduct() {
        Id quoteId = fflib_IDGenerator.generate(SBQQ__Quote__c.SObjectType);
        Id productId1 = Fake.generateId(Product2.class);
        Id groupId = Fake.generateId(SBQQ__QuoteLineGroup__c.class);
        Id quoteLineId1 = Fake.generateId(SBQQ__QuoteLine__c.class);
        Id quoteLineId2 = Fake.generateId(SBQQ__QuoteLine__c.class);
        set<string> productCode = new Set<string>();
        List<Product2> productList = new List<Product2>();

        Product2 product1 = (Product2) new Fake(Product2.class)
            .setField(Product2.Id, productId1)
            .setfield(Product2.Name, PARENT_PRODUCT_NAME)
            .setfield(Product2.ProductCode, PARENT_PRODUCT_CODE)
            .toSObject();
        productList.add(product1);

        SBQQ__QuoteLine__c quoteLine1 = (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineId1)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Quote__c, quoteId)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Product__c, productId1)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Number__c, 1)
            .setfield(SBQQ__QuoteLine__c.SBQQ__ProductName__c, PARENT_PRODUCT_NAME)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Group__c, groupId)
            .toSObject();

        SBQQ__QuoteLine__c quoteLine2 = (SBQQ__QuoteLine__c) new Fake(SBQQ__QuoteLine__c.class)
            .setField(SBQQ__QuoteLine__c.Id, quoteLineId2)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Quote__c, quoteId)
            .setfield(SBQQ__QuoteLine__c.SBQQ__Product__c, productId1)
            .setfield(
                SBQQ__QuoteLine__c.SBQQ__ProductOption__c,
                Fake.generateId(SBQQ__ProductOption__c.class)
            )
            .setfield(SBQQ__QuoteLine__c.SBQQ__Number__c, DELIVERY_PRODUCT_LINE_NUMBER)
            .setfield(SBQQ__QuoteLine__c.SBQQ__RequiredBy__c, null)
            .setfield(SBQQ__QuoteLine__c.SBQQ__ProductName__c, DELIVERY_PRODUCT_NAME)
            .toSObject();

        List<SBQQ__Quoteline__c> listOfQuoteline = new List<SBQQ__Quoteline__c>();
        listOfQuoteline.add(quoteLine1);
        listOfQuoteline.add(quoteLine2);
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork) mocks.mock(
            fflib_ISObjectUnitOfWork.class
        );
        Application.UNITOFWORK.setMock(mockUOW);

        IProductsSelector productsSelectorMock = (IProductsSelector) mocks.mock(
            IProductsSelector.class
        );
        mocks.startStubbing();
        mocks.when(productsSelectorMock.sObjectType()).thenReturn(Product2.SObjectType);
        mocks.when(
                productsSelectorMock.selectProductByProductName(
                    new Set<String>{ PARENT_PRODUCT_NAME }
                )
            )
            .thenReturn(productList);
        mocks.stopStubbing();
        Application.Selector.setMock(productsSelectorMock);
        DisplayQuoteLineAttributesController.insertParentProduct(
            quoteId,
            PARENT_PRODUCT_NAME,
            quoteLine2.Id,
            DELIVERY_PRODUCT_LINE_NUMBER,
            quoteLine2.SBQQ__RequiredBy__c,
            quoteLine1.SBQQ__Group__c
        );
        ((fflib_ISObjectUnitOfWork) mocks.verify(mockUOW, 2)).commitWork();
        List<Product2> quoteLinesReturned = productsSelectorMock.selectProductByProductName(
            new Set<String>{ PARENT_PRODUCT_NAME }
        );
        System.assertEquals(1, quoteLinesReturned.size(), 'Product Not Available');
    }
}