sfdx-source/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>LEM-81: This object is used to store log records which part of logging framework.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Log__c/fields/Class_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Method_Name__c</fullName>
    <description>LEM-81: This field is used to store method name of the class which created the log.</description>
    <label>Class Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>LEM-81: This field is used to store name of the class which created log.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>LEM-81: This field is used to store Source of the error.</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/tests/classes/unit/controllers/LogControllerTest.cls
/**
 * @description This is a test class created to handle exception in case of any exception scenarios in lightning component.
 * @author Deloitte
 * @date 04/03/2022
 */
@isTest(SeeAllData=false)
private class LogControllerTest {
    private static final String COMPONENT_NAME = 'Test Aura Component';
    private static final String ERROR_MESSAGE = 'Exception occurred in Aura Component';
    private static final String METHOD_NAME = 'Test AuraEnabled Method';
    private static final String DESCRIBE_NAME = 'Payment Account';
    private static final String SOBJECT_NAME =  'Payment_Account__c';
    /**
     * @description This method is used to create log when an exception occur in aura components
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenErrorOccurredInLWCThenCreateLog() {
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        Application.UNITOFWORK.setMock(uowMock);

        LogController.createLog(COMPONENT_NAME, METHOD_NAME, ERROR_MESSAGE);
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock, 1)).commitWork();
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock, 1))
            .registerNew(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object>{
                        Log__c.Class_Method_Name__c => METHOD_NAME,
                        Log__c.Class_Name__c => COMPONENT_NAME,
                        Log__c.Quiddity__c => String.valueOf(Request.getCurrent().getQuiddity())
                    }
                )
            );
    }
}