sfdx-source/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>LEM-81: This object is used to store log records which part of logging framework.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Log__c/fields/Franchise_Parent_Account_Id_18__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Parent_Account_Id_18__c</fullName>
    <description>LEM-11497: It stores the 18 digit Id of the franchise parent Account of store for which store association failed.</description>
    <label>Franchise Parent Account Id 18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Parent_Account_Id_18__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Id_18__c</fullName>
    <description>LEM-10033: It stores the 18 digit Id of the parent Account of store for which store association failed.</description>
    <label>Parent Account Id 18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Recipient_Ids_To_Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Ids_To_Send_Notification__c</fullName>
    <description>LEM-11497: It stores the list of Owner Ids to send a Log&apos;s email notification. It currently considers Parent Account Owner, Franchise Parent Account Owner and Parent Work Order Owner for the email notification.</description>
    <label>Recipient Ids To Send Notification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-10033: It indicates whether to notify the parent Account Owner on Log creation.</description>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/services/LogsEmailNotificationServiceImplTest.cls
/**
 * @author Deloitte
 * @date 01/23/2024
 * @description Test class for LogsEmailNotificationServiceImpl class.
 */
@isTest(SeeAllData=false)
private class LogsEmailNotificationServiceImplTest {
    /**
     * @description To test triggering of email flow when eligible Log records found.
     * TODO: Update verify statements to verify flow interview call.
     */
    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
    private static void testWhenEligibleLogsSentThenEmailNotificationFlowTriggered() {
        Schema.SObjectField parentField = Log__c.Parent_Account_Id_18__c;
        Id parentAccountId = fflib_IDGenerator.generate(Account.SObjectType);
        Id recepientId = fflib_IDGenerator.generate(User.SObjectType);
        Log__c mockLog = new Log__c(
            Id = fflib_IDGenerator.generate(Log__c.SObjectType),
            Send_Notification__c = true,
            Parent_Account_Id_18__c = parentAccountId,
            Franchise_Parent_Account_Id_18__c = null,
            Recipient_Ids_To_Send_Notification__c = recepientId,
            CreatedDate = System.today() + 1
        );
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        LogsSelector mockLogsSelector = (LogsSelector) mocks.mock(LogsSelector.class);
        mocks.startStubbing();
        mocks.when(mockLogsSelector.sObjectType()).thenReturn(Log__c.SObjectType);
        mocks.when(
                mockLogsSelector.selectLogsEligibleToSendNotification(
                    parentField,
                    new Set<Id>{ parentAccountId },
                    Log__c.Franchise_Parent_Account_Id_18__c
                )
            )
            .thenReturn(new List<Log__c>{ mockLog });
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockLogsSelector);
        LogsEmailNotificationService.initiateEmailNotificationsProcessor(
            parentField,
            new Set<Id>{ parentAccountId }
        );
    }
}