sfdx-source/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>LEM-81: This object is used to store log records which part of logging framework.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Log__c/fields/Franchise_Parent_Account_Id_18__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Parent_Account_Id_18__c</fullName>
    <description>LEM-11497: It stores the 18 digit Id of the franchise parent Account of store for which store association failed.</description>
    <label>Franchise Parent Account Id 18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Parent_Account_Id_18__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Id_18__c</fullName>
    <description>LEM-10033: It stores the 18 digit Id of the parent Account of store for which store association failed.</description>
    <label>Parent Account Id 18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Recipient_Ids_To_Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Ids_To_Send_Notification__c</fullName>
    <description>LEM-11497: It stores the list of Owner Ids to send a Log&apos;s email notification. It currently considers Parent Account Owner, Franchise Parent Account Owner and Parent Work Order Owner for the email notification.</description>
    <label>Recipient Ids To Send Notification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Log__c/fields/Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-10033: It indicates whether to notify the parent Account Owner on Log creation.</description>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/LogsSelector.cls
/**
 * @author Deloitte
 * @date 01/11//2024
 * @description Selector class for Log object.
 */
public inherited sharing class LogsSelector extends fflib_SObjectSelector implements ILogsSelector {
    /**
     * @description Default constructor for the class.
     * @return ILogsSelector
     */
    public static ILogsSelector newInstance() {
        return (ILogsSelector) Application.Selector.newInstance(Log__c.SObjectType);
    }

    /**
     * @description Overriding default getSObjectType method.
     * @return SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Log__c.SObjectType;
    }

    /**
     * @description It is used to get the fields of Log__c object.
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{ Log__c.Id };
    }

    /**
     * @description It is used for querying Log__c records which satisfies the criteria to
     * send notification.
     * @param parentField
     * @param parentIds
     * @param secondaryParentFieldToExclude
     * @return List<Log__c>
     */
    public List<Log__c> selectLogsEligibleToSendNotification(
        Schema.SObjectField parentField,
        Set<Id> parentIds,
        Schema.SObjectField secondaryParentFieldToExclude
    ) {
        fflib_QueryFactory logQuery = newQueryFactory()
            .selectField('Franchise_Parent_Account_Id_18__c')
            .selectField('Parent_Account_Id_18__c')
            .selectField('Recipient_Ids_To_Send_Notification__c')
            .selectField('Send_Notification__c')
            .setCondition(
                'Send_Notification__c = TRUE' +
                ' AND Recipient_Ids_To_Send_Notification__c != null' +
                ' AND CreatedDate >= LAST_N_DAYS:5' +
                ' AND ' +
                String.valueOf(parentField) +
                ' IN :parentIds'
            );
        if (secondaryParentFieldToExclude != null) {
            logQuery.setCondition(
                logQuery.getCondition() +
                ' AND ' +
                String.valueOf(secondaryParentFieldToExclude) +
                ' = null'
            );
        }
        return (List<Log__c>) Database.query(logQuery.toSOQL());
    }
}