sfdx-source/force-app/main/default/objects/Business_Friendly_Mapping__mdt/Business_Friendly_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Created this Custom meta data for transforming the Integration related error messages to the business friendly error message.</description>
    <label>Business Friendly Mapping</label>
    <pluralLabel>Business Friendly Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Business_Friendly_Mapping__mdt/fields/Integration_Key_String__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key_String__c</fullName>
    <label>Integration Key String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Friendly_Mapping__mdt/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Xref Provisioning</fullName>
                <default>true</default>
                <label>Xref Provisioning</label>
            </value>
            <value>
                <fullName>Test Type</fullName>
            </value>
            <value>
                <fullName>Business Reference Provisioning</fullName>
            </value>
            <value>
                <fullName>Tablet Case Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Business_Friendly_Mapping__mdt/fields/Message_Category__c.field-meta.xml
<CustomField>
    <fullName>Message_Category__c</fullName>
    <label>Message Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking Validations</fullName>
                <default>true</default>
                <label>Banking Validations</label>
            </value>
            <value>
                <fullName>Test Category</fullName>
            </value>
            <value>
                <fullName>Services Missing</fullName>
            </value>
            <value>
                <fullName>Timeout</fullName>
            </value>
            <value>
                <fullName>Decision Maker Or Store Duplicate</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Phone Number</fullName>
            </value>
            <value>
                <fullName>Missing Data - Currency</fullName>
            </value>
            <value>
                <fullName>Missing Data - TaxId</fullName>
            </value>
            <value>
                <fullName>Missing Data - Billing Contact Name</fullName>
            </value>
            <value>
                <fullName>Missing Data - Decision Maker</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Entity Type</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Routing Number</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Transit Number</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Account Number</fullName>
            </value>
            <value>
                <fullName>Invalid COO</fullName>
            </value>
            <value>
                <fullName>Geo Coverage Issue</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>System Issue</fullName>
            </value>
            <value>
                <fullName>POS - Duplicate</fullName>
            </value>
            <value>
                <fullName>Global Do Not Activate</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Postal Code</fullName>
            </value>
            <value>
                <fullName>FullSend Create</fullName>
            </value>
            <value>
                <fullName>Amendment &amp; Bulk</fullName>
            </value>
            <value>
                <fullName>Invalid Data - Tax Strategy</fullName>
            </value>
            <value>
                <fullName>Error - Create Tax Strategy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/Status_Reason_And_Details_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>LEM-9964: It stores the SObject’s Type, Status and Status Reason mappings for integration failures.</description>
    <label>Status Reason And Details Mapping</label>
    <pluralLabel>Status Reason And Details Mappings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/fields/Business_Friendly_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Business_Friendly_Mapping__c</fullName>
    <description>LEM-9964: It is used to associate the Status Reason and Details Mappings to a Business Friendly Mapping.</description>
    <label>Business Friendly Mapping</label>
    <referenceTo>Business_Friendly_Mapping__mdt</referenceTo>
    <relationshipLabel>Status Reason And Details Mappings</relationshipLabel>
    <relationshipName>Status_Reason_And_Details_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/fields/Quick_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Quick_Action_Name__c</fullName>
    <description>Created this field to map the quick action which was created for having the resolution steps/guided flow for fixing this particular error with work step.</description>
    <label>Quick Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-9964: It stores the Status values of SObjects(currently used for WorkStep).</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Workable</fullName>
                <default>true</default>
                <label>Not Workable</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - DoorDash to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Mx to implement link</fullName>
            </value>
            <value>
                <fullName>Complete - Implemented on the call</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>LEM-9964: It stores the Status Reason values of SObjects(currently used for WorkStep).</description>
    <label>Status_Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appears to be Change of Ownership - Provide Original Store ID</fullName>
            </value>
            <value>
                <fullName>Business reference not found</fullName>
            </value>
            <value>
                <fullName>Invalid Address</fullName>
            </value>
            <value>
                <fullName>Invalid Store Phone</fullName>
            </value>
            <value>
                <fullName>Manual Store Creation Needed</fullName>
            </value>
            <value>
                <fullName>Mx requested Order Protocol change</fullName>
            </value>
            <value>
                <fullName>Needs Coverage Extension - Location is out of Starting Point</fullName>
            </value>
            <value>
                <fullName>Not in Coverage - Location is out of Starting Point</fullName>
            </value>
            <value>
                <fullName>Store Provisioning Failed - Please refer to Provisioning Errors tab</fullName>
            </value>
            <value>
                <fullName>Submarket is not live and Launch Date is TBD</fullName>
            </value>
            <value>
                <fullName>Unidentified Provisioning Error</fullName>
            </value>
            <value>
                <fullName>VB does not pass QC</fullName>
            </value>
            <value>
                <fullName>Invalid payment account details</fullName>
            </value>
            <value>
                <fullName>Missing Billing Contact Name</fullName>
            </value>
            <value>
                <fullName>Invalid POS details</fullName>
            </value>
            <value>
                <fullName>Missing Decision Maker contact info on Store</fullName>
            </value>
            <value>
                <fullName>Services set incorrectly</fullName>
            </value>
            <value>
                <fullName>System error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Duplicate POS Integration ID - Already in Use</fullName>
            </value>
            <value>
                <fullName>Invalid POS Integration ID</fullName>
            </value>
            <value>
                <fullName>Missing Store hours</fullName>
            </value>
            <value>
                <fullName>No menu source found</fullName>
            </value>
            <value>
                <fullName>Missing POS Integration ID</fullName>
            </value>
            <value>
                <fullName>Invalid Routing Number</fullName>
            </value>
            <value>
                <fullName>Invalid Account Number</fullName>
            </value>
            <value>
                <fullName>Invalid EIN</fullName>
            </value>
            <value>
                <fullName>Missing Menu Link</fullName>
            </value>
            <value>
                <fullName>Missing Account Number</fullName>
            </value>
            <value>
                <fullName>Invalid Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Status_Reason_And_Details_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-9964: It stores the Type values of SObjects(currently used for WorkStep).</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activate Store</fullName>
            </value>
            <value>
                <fullName>Activations Outreach</fullName>
            </value>
            <value>
                <fullName>Activations Checklist</fullName>
            </value>
            <value>
                <fullName>Add Marketing</fullName>
            </value>
            <value>
                <fullName>Ads and Promo</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Activate</fullName>
            </value>
            <value>
                <fullName>Ads and Promo - Deactivate</fullName>
            </value>
            <value>
                <fullName>Cross Listing - Caviar</fullName>
            </value>
            <value>
                <fullName>Deliver Tablet</fullName>
            </value>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Fee Credit</fullName>
            </value>
            <value>
                <fullName>Grant Portal Access</fullName>
            </value>
            <value>
                <fullName>Implementation Call</fullName>
            </value>
            <value>
                <fullName>Link Implementation</fullName>
            </value>
            <value>
                <fullName>Link Optimization</fullName>
            </value>
            <value>
                <fullName>Menu Updates</fullName>
            </value>
            <value>
                <fullName>Post-Sales - Other</fullName>
            </value>
            <value>
                <fullName>Rate Change</fullName>
            </value>
            <value>
                <fullName>Review &amp; Triage</fullName>
                <default>true</default>
                <label>Review &amp; Triage</label>
            </value>
            <value>
                <fullName>Setup Banking</fullName>
            </value>
            <value>
                <fullName>Setup Business</fullName>
            </value>
            <value>
                <fullName>Setup Catalog</fullName>
            </value>
            <value>
                <fullName>Setup Custom Delivery Radius</fullName>
            </value>
            <value>
                <fullName>Setup Menu</fullName>
            </value>
            <value>
                <fullName>Setup POS</fullName>
            </value>
            <value>
                <fullName>Setup Store</fullName>
            </value>
            <value>
                <fullName>Setup Storefront Page</fullName>
            </value>
            <value>
                <fullName>Sponsored Listing</fullName>
            </value>
            <value>
                <fullName>Complete pre-work</fullName>
            </value>
            <value>
                <fullName>Configure POS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/StatusReasonAndDetailsMappingsSelectTest.cls
/**
 * @author Deloitte
 * @date 10/16/2023
 * @description Test class for StatusReasonAndDetailsMappingsSelector class.
 * Suppressed Warnings since mock verify method does not require system assert statements.
 */
@isTest(SeeAllData=false)
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
private class StatusReasonAndDetailsMappingsSelectTest {
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: there is a mismatch in fields list.';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: the object type must be Nintex To Work Order Mapping custom metadata';
    private static final String ASSERT_MESSAGE_NO_STATUS_REASON_MAPPINGS_RETURNED = 'Unexpected result: selector call failed to return all Status Reason to Detail Mappings';

    /**
     * @description To test standard methods in StatusReasonAndDetailsMappingsSelector.
     */
    @isTest
    private static void testWhenStandardSelectorMethodsCalledThenReturnAppropriateValues() {
        List<Schema.SObjectField> sObjectFieldsMock = new List<Schema.SObjectField>{
            Status_Reason_And_Details_Mapping__mdt.Business_Friendly_Mapping__c,
            Status_Reason_And_Details_Mapping__mdt.MasterLabel,
            Status_Reason_And_Details_Mapping__mdt.DeveloperName,
            Status_Reason_And_Details_Mapping__mdt.Status__c,
            Status_Reason_And_Details_Mapping__mdt.Status_Reason__c,
            Status_Reason_And_Details_Mapping__mdt.Type__c,
            Status_Reason_And_Details_Mapping__mdt.Quick_Action_Name__c
        };
        StatusReasonAndDetailsMappingsSelector statusReasonAndDetailsMappings = new StatusReasonAndDetailsMappingsSelector();
        Schema.SObjectType typeOfObject = statusReasonAndDetailsMappings.SObjectType();
        List<Schema.SObjectField> sObjectFields = statusReasonAndDetailsMappings.getSObjectFieldList();
        System.assertEquals(
            typeOfObject,
            Status_Reason_And_Details_Mapping__mdt.SObjectType,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            sObjectFields,
            sObjectFieldsMock,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }

    /**
     * @description To test selection of all Status Reason And Detail Mappings.
     */
    @isTest
    private static void testWhenGetAllMappingsCalledThenAllCustomMetadataRecordsReturned() {
        Id businessFriendlyMappingId = fflib_IDGenerator.generate(
            Business_Friendly_Mapping__mdt.SObjectType
        );

        Status_Reason_And_Details_Mapping__mdt statusReasonAndDetailsMappings = (Status_Reason_And_Details_Mapping__mdt) new Fake(
                Status_Reason_And_Details_Mapping__mdt.class
            )
            .setField(Status_Reason_And_Details_Mapping__mdt.Status__c, 'Blocked')
            .setField(Status_Reason_And_Details_Mapping__mdt.Status_Reason__c, 'Invalid Address')
            .setField(Status_Reason_And_Details_Mapping__mdt.Type__c, 'Setup Store')
            .setField(
                Status_Reason_And_Details_Mapping__mdt.Business_Friendly_Mapping__c,
                businessFriendlyMappingId
            )
            .setParent(
                'Business_Friendly_Mapping__r',
                new Fake(Business_Friendly_Mapping__mdt.class)
                    .setField(Business_Friendly_Mapping__mdt.id, businessFriendlyMappingId)
                    .setField(
                        Business_Friendly_Mapping__mdt.Integration_Key_String__c,
                        'required key [accountCurrency] not found'
                    )
                    .setField(
                        Business_Friendly_Mapping__mdt.Integration_Type__c,
                        'Xref Provisioning'
                    )
                    .setField(
                        Business_Friendly_Mapping__mdt.Message_Category__c,
                        'Missing Data - Currency'
                    )
                    .setField(Business_Friendly_Mapping__mdt.Order__c, 40)
                    .setField(Business_Friendly_Mapping__mdt.Active__c, true)
            )
            .setFakeId()
            .toSObject();
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        StatusReasonAndDetailsMappingsSelector mockStatusReasonAndDetailsMappingsSelector = (StatusReasonAndDetailsMappingsSelector) mocks.mock(
            StatusReasonAndDetailsMappingsSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockStatusReasonAndDetailsMappingsSelector.sObjectType())
            .thenReturn(Status_Reason_And_Details_Mapping__mdt.SObjectType);
        mocks.when(mockStatusReasonAndDetailsMappingsSelector.getAllMappings())
            .thenReturn(
                new List<Status_Reason_And_Details_Mapping__mdt>{ statusReasonAndDetailsMappings }
            );
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockStatusReasonAndDetailsMappingsSelector);
        List<Status_Reason_And_Details_Mapping__mdt> queryResult = StatusReasonAndDetailsMappingsSelector.newInstance()
            .getAllMappings();
        System.assertEquals(
            'Blocked',
            queryResult[0].Status__c,
            ASSERT_MESSAGE_NO_STATUS_REASON_MAPPINGS_RETURNED
        );
        System.assertEquals(
            'Invalid Address',
            queryResult[0].Status_Reason__c,
            ASSERT_MESSAGE_NO_STATUS_REASON_MAPPINGS_RETURNED
        );
    }
}