sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/Stores_List_View_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1158: This configuration will be used for storesOnWorkPlan LWC to store sequence, section name, object name &amp; list of fields to be displayed in &quot;Onboarding Details&quot; on Work Plan</description>
    <label>Onboarding Details Configuration</label>
    <pluralLabel>Onboarding Details Configurations</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Applicable_Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Account_Record_Type__c</fullName>
    <description>LEM-2516: It indicates the record type of Account for which the section is applicable on onboarding details.</description>
    <label>Applicable Account Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
                <default>true</default>
                <label>Business</label>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/FieldSet_Name__c.field-meta.xml
<CustomField>
    <fullName>FieldSet_Name__c</fullName>
    <description>LEM-1397: Indicates the fields set name which will be used to display the fields on UI.</description>
    <label>FieldSet Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-4892: It indicates whether Onboarding Details Configuration is active. The system only picks the active configurations for Onboarding Details.</description>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1158: Indicates the object name.</description>
    <label>Object Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <description>LEM-1158: Indicates the section name of the section.</description>
    <label>Section Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Section_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Section_Sequence__c</fullName>
    <description>LEM-1397: Indicates the sequence of the section to allow sorting of the section.</description>
    <label>Section Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Show_Section_Header__c.field-meta.xml
<CustomField>
    <fullName>Show_Section_Header__c</fullName>
    <defaultValue>true</defaultValue>
    <description>LEM-2198: It indicates whether section header will be visible on the onboarding details.</description>
    <label>Show Section Header</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-1158: Indicates the type of WorkPlan on which section should be visible.</description>
    <inlineHelpText>Indicates WorkPlan Type</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Stores_List_View_Configuration__mdt/fields/Types_To_Exclude__c.field-meta.xml
<CustomField>
    <fullName>Types_To_Exclude__c</fullName>
    <description>LEM-3096: It indicates the types of Work Plan on which the section should not be visible.</description>
    <inlineHelpText>Indicates WorkPlan types to exclude.</inlineHelpText>
    <label>Types To Exclude</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkPlan/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>LEM-1874: It indicates type of Work Plan. It is used to identify the existing Work Plans on Work Order.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Plan_Type</valueSetName>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/globalValueSets/Work_Plan_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Activations</fullName>
    </customValue>
    <customValue>
        <fullName>Ads and Promo - Activate</fullName>
    </customValue>
    <customValue>
        <fullName>Ads and Promo - Deactivate</fullName>
    </customValue>
    <customValue>
        <fullName>Catalog</fullName>
    </customValue>
    <customValue>
        <fullName>Caviar - Cross Listing</fullName>
    </customValue>
    <customValue>
        <fullName>Central Activations</fullName>
    </customValue>
    <customValue>
        <fullName>COO Same Store</fullName>
    </customValue>
    <customValue>
        <fullName>Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Grant Portal Access</fullName>
    </customValue>
    <customValue>
        <fullName>Menu</fullName>
    </customValue>
    <customValue>
        <fullName>Menu Updates</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Rate Change</fullName>
    </customValue>
    <customValue>
        <fullName>Setup Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsored Listing</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront</fullName>
    </customValue>
    <customValue>
        <fullName>Storefront Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Return</fullName>
    </customValue>
    <customValue>
        <fullName>Central Activations Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Vendor Photoshoot</fullName>
    </customValue>
    <customValue>
        <fullName>Photo Linking</fullName>
    </customValue>
    <customValue>
        <fullName>Photo QA</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Kit</fullName>
    </customValue>
    <customValue>
        <fullName>Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Promos</fullName>
    </customValue>
    <description>LEM-1874: It is set of Work Plan type values.</description>
    <masterLabel>Work Plan Type</masterLabel>
</GlobalValueSet>

sfdx-source/force-app/main/default/classes/selectors/StoresListViewConfigurationsSelector.cls
/**
 * @author Deloitte
 * @date 29/04/2022
 * @description Selector class for Stores_List_View_Configuration__mdt custom metadata.
 */
public inherited sharing class StoresListViewConfigurationsSelector extends fflib_SObjectSelector implements IStoresListViewConfigurationsSelector {
    private static final String TYPE_ALL = '%All%';
    /**
     * @description default constructor for the class.
     * @return IStoresListViewConfigurationsSelector - interface of IStoresListViewConfigurationsSelector
     */
    public static IStoresListViewConfigurationsSelector newInstance() {
        return (IStoresListViewConfigurationsSelector) Application.Selector.newInstance(
            Stores_List_View_Configuration__mdt.SObjectType
        );
    }

    /**
     * @description It is used for getting Object type.
     * @return SObjectType - object type of metadata
     */
    public Schema.SObjectType getSObjectType() {
        return Stores_List_View_Configuration__mdt.SObjectType;
    }

    /**
     * @description It is for getting the fields on Stores_List_View_Configuration__mdt.
     * @return List<Schema.SObjectField>- Stores_List_View_Configuration__mdt fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Stores_List_View_Configuration__mdt.Applicable_Account_Record_Type__c,
            Stores_List_View_Configuration__mdt.DeveloperName,
            Stores_List_View_Configuration__mdt.FieldSet_Name__c,
            Stores_List_View_Configuration__mdt.Is_Active__c,
            Stores_List_View_Configuration__mdt.Object_Name__c,
            Stores_List_View_Configuration__mdt.Section_Name__c,
            Stores_List_View_Configuration__mdt.Section_Sequence__c,
            Stores_List_View_Configuration__mdt.Show_Section_Header__c,
            Stores_List_View_Configuration__mdt.Type__c,
            Stores_List_View_Configuration__mdt.Types_To_Exclude__c
        };
    }

    /**
     * @description It is for getting all field values on basis of Work Plan type
     * and Account record type for Stores_List_View_Configuration__mdt.
     * Salesforce truncates 255 charaters for long text area hence quering records.
     * Suppressed warnings since typeMatcher variable is used to set the condition of dynamic SOQL.
     * @JIRA# LEM-1158 and LEM-2516
     * @param type - Type of WorkPlan
     * @param accountRecordType - Account record type
     * @return List<Stores_List_View_Configuration__mdt> - List of metadata records with values
     */
    @SuppressWarnings('PMD.UnusedLocalVariable')
    public List<Stores_List_View_Configuration__mdt> selectByWorkPlanTypeAndAccountRecordType(
        String type,
        String accountRecordType
    ) {
        String typeMatcher = '%' + type + '%';
        fflib_QueryFactory query = newQueryFactory()
            .setCondition(
                'Is_Active__c = true AND ' +
                '(Type__c LIKE :typeMatcher OR Type__c LIKE :TYPE_ALL) AND ' +
                'Applicable_Account_Record_Type__c = :accountRecordType'
            )
            .setOrdering('Section_Sequence__c', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Stores_List_View_Configuration__mdt>) Database.query(query.toSOQL());
    }
}