sfdx-source/force-app/main/default/objects/WorkPlanTemplateEntry/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BZAP-19551</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStepDependencyTemplate__c/WorkStepDependencyTemplate__c.object-meta.xml
<CustomObject>
    <description>LEM-1061: It stores template of dependencies between WorkSteps.
It is used for creating actual dependency records after creation of WorkSteps.</description>
    <label>Work Step Dependency Template</label>
    <nameField>
        <displayFormat>WSDT-{0}</displayFormat>
        <label>Work Step Dependency Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Step Dependency Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/WorkStepDependencyTemplate__c/fields/Dependee_Work_Plan_Template_Entry__c.field-meta.xml
<CustomField>
    <fullName>Dependee_Work_Plan_Template_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1061: It indicates dependee WorkPlanTemplateEntry. It is used for populating dependee WorkStep in actual dependency record.</description>
    <inlineHelpText>Indicates dependee WorkPlanTemplateEntry</inlineHelpText>
    <label>Dependee Work Plan Template Entry</label>
    <referenceTo>WorkPlanTemplateEntry</referenceTo>
    <relationshipLabel>Dependent Work Step Templates</relationshipLabel>
    <relationshipName>DependentWorkStepTemplates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStepDependencyTemplate__c/fields/Dependent_Work_Plan_Template_Entry__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Work_Plan_Template_Entry__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-1061: It indicates dependee WorkPlanTemplateEntry. It is used for populating dependent WorkStep in actual dependency record.</description>
    <inlineHelpText>Indicates dependent WorkPlanTemplateEntry</inlineHelpText>
    <label>Dependent Work Plan Template Entry</label>
    <referenceTo>WorkPlanTemplateEntry</referenceTo>
    <relationshipLabel>Dependee Work Step Dependency Templates</relationshipLabel>
    <relationshipName>DependeeWorkStepDependencyTemplates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkStepDependencyTemplate__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-1061: It indicates whether dependency between WorkSteps is applicable.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/WorkStepDependencyTemplatesSelectorTest.cls
/**
 * @author Deloitte
 * @date 05/05/2022
 * @description Test class for WorkStepDependencyTemplatesSelector class.
 */
@isTest
private class WorkStepDependencyTemplatesSelectorTest {
    private static final String ASSERT_MESSAGE_INCORRECT_OBJECT_TYPE = 'Unexpected result: the object type must beWorkStepDependencyTemplate';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_SOBJECT_FIELDS = 'Unexpected result: there is a mismatch in fields list';
    private static final String ASSERT_MESSAGE_NO_WORK_STEP_DEPENDENCY_RECORDS = 'Unexpected result: query returned no dependee WorkStep';
    private static final String WORK_PLAN_TEMPLATE_NAME_ONBOARDING = 'Onboarding';
    private static final String WORK_PLAN_TEMPLATE_NAME_SETUP_BANKING = 'Setup Banking';
    private static final String WORK_STEP_TEMPLATE_NAME_REVIEW_TRIAGE = 'Review & Triage';
    private static final String WORK_STEP_TEMPLATE_NAME_SETUP_BANKING = 'SETUP_BANKING';

    /**
     * @description To test instantiation and return of correct sobjectType and sobject fields list.
     */
    @isTest
    private static void testWhenClassInstantiatesThenCheckSObjectTypeAndFieldList() {
        WorkStepDependencyTemplatesSelector workStepDependencyTemplatesSelectorInstance = new WorkStepDependencyTemplatesSelector();
        Schema.SObjectType typeOfObject = workStepDependencyTemplatesSelectorInstance.getSObjectType();
        List<Schema.SObjectField> sObjectFields = workStepDependencyTemplatesSelectorInstance.getSObjectFieldList();
        System.assertEquals(
            Schema.WorkStepDependencyTemplate__c.SObjectType,
            typeOfObject,
            ASSERT_MESSAGE_INCORRECT_OBJECT_TYPE
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                WorkStepDependencyTemplate__c.Id,
                WorkStepDependencyTemplate__c.Dependee_Work_Plan_Template_Entry__c,
                WorkStepDependencyTemplate__c.Dependent_Work_Plan_Template_Entry__c,
                WorkStepDependencyTemplate__c.Is_Active__c
            },
            sObjectFields,
            ASSERT_MESSAGE_MISMATCH_IN_SOBJECT_FIELDS
        );
    }

    /**
     * @description To test query on WorkPlanTemplate by passed set of Ids
     * returns WorkPlanTemplates with WorkPlanTemplateEntries.
     */
    @isTest
    private static void testWhenSelectDependeeWorkStepDependencyTemplatesIsCalledThenWorkStepDependencyTemplatesReturned() {
        WorkPlanTemplate onboardingWorkPlanTemplate = new WorkPlanTemplate(
            Name = WORK_PLAN_TEMPLATE_NAME_ONBOARDING
        );
        WorkPlanTemplate setupBankingWorkPlanTemplate = new WorkPlanTemplate(
            Name = WORK_PLAN_TEMPLATE_NAME_SETUP_BANKING
        );
        insert new List<WorkPlanTemplate>{
            onboardingWorkPlanTemplate,
            setupBankingWorkPlanTemplate
        };
        WorkStepTemplate reviewTriageWorkStepTemplate = new WorkStepTemplate(
            Name = WORK_STEP_TEMPLATE_NAME_REVIEW_TRIAGE,
            IsActive = true
        );
        WorkStepTemplate setupBankingWorkStepTemplate = new WorkStepTemplate(
            Name = WORK_PLAN_TEMPLATE_NAME_SETUP_BANKING,
            IsActive = true
        );
        insert new List<WorkStepTemplate>{
            reviewTriageWorkStepTemplate,
            setupBankingWorkStepTemplate
        };
        WorkPlanTemplateEntry onboardingWorkPlanTemplateEntry = new WorkPlanTemplateEntry(
            WorkPlanTemplateId = onboardingWorkPlanTemplate.Id,
            WorkStepTemplateId = reviewTriageWorkStepTemplate.Id,
            Active__c = true
        );
        WorkPlanTemplateEntry setupBankingWorkPlanTemplateEntry = new WorkPlanTemplateEntry(
            WorkPlanTemplateId = setupBankingWorkPlanTemplate.Id,
            WorkStepTemplateId = setupBankingWorkStepTemplate.Id,
            Active__c = true
        );
        insert new List<WorkPlanTemplateEntry>{
            onboardingWorkPlanTemplateEntry,
            setupBankingWorkPlanTemplateEntry
        };
        WorkStepDependencyTemplate__c workStepDepenencyTemplate = new WorkStepDependencyTemplate__c(
            Dependee_Work_Plan_Template_Entry__c = onboardingWorkPlanTemplateEntry.Id,
            Dependent_Work_Plan_Template_Entry__c = setupBankingWorkPlanTemplateEntry.Id,
            Is_Active__c = true
        );
        insert workStepDepenencyTemplate;
        Test.startTest();
        List<WorkStepDependencyTemplate__c> workStepDependencyTemplatesResult = WorkStepDependencyTemplatesSelector.newInstance()
            .selectDependeeWorkStepDependencyTemplates(
                new Set<Id>{ setupBankingWorkPlanTemplateEntry.Id }
            );
        Test.stopTest();
        System.assertEquals(
            onboardingWorkPlanTemplateEntry.Id,
            workStepDependencyTemplatesResult[0].Dependee_Work_Plan_Template_Entry__c,
            ASSERT_MESSAGE_NO_WORK_STEP_DEPENDENCY_RECORDS
        );
    }
}