sfdx-source/force-app/main/default/objects/ReadinessValidation_SobjectType_Binding__mdt/ReadinessValidation_SobjectType_Binding__mdt.object-meta.xml
<CustomObject>
    <description>LEM-2976: It is a junction custom metadata between Sobject Type Sub-Type Mapping and Store Readiness Validation Rule custom metadata.</description>
    <label>ReadinessValidation SobjectType Binding</label>
    <pluralLabel>ReadinessValidation SobjectType Bindings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/ReadinessValidation_SobjectType_Binding__mdt/fields/Sobject_Type_Sub_Type_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type_Sub_Type_Mapping__c</fullName>
    <description>LEM-2976: It indicates the Sobject Type Sub-Type Mapping custom metadata record.</description>
    <label>Sobject Type Sub-Type Mapping</label>
    <referenceTo>Sobject_Type_Sub_Type_Mapping__mdt</referenceTo>
    <relationshipLabel>Readiness Validation Sobject Type Bindings</relationshipLabel>
    <relationshipName>ReadinessValidationSobjectTypeBindings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/force-app/main/default/objects/ReadinessValidation_SobjectType_Binding__mdt/fields/Store_Readiness_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Store_Readiness_Validation_Rule__c</fullName>
    <description>LEM-2976: It indicates Store Readiness Validation Rule custom metadata record.</description>
    <label>Store Readiness Validation Rule</label>
    <referenceTo>Store_Readiness_Validation_Rule__mdt</referenceTo>
    <relationshipLabel>Readiness Validation Sobject Type Bindings</relationshipLabel>
    <relationshipName>ReadinessValidationSobjectTypeBindings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/ReadinessValidationBindingsSelectTest.cls
/**
 * @author Deloitte
 * @date 09/12/2022
 * @description Test class for ReadinessValidationTypeBindingsSelector class.
 */
@isTest(SeeAllData=false)
private class ReadinessValidationBindingsSelectTest {
    private static final String ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST = 'Unexpected result: there is a mismatch in fields list';
    private static final String ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE = 'Unexpected result: the object type must be ReadinessValidation SobjectType Binding custom metadata';

    /**
     * @description To test Readiness Validation Binding Type selector methods.
     */
    @isTest
    private static void testWhenSelectorMethodsCalledThenReturnAppropriateValues() {
        List<Schema.SObjectField> sObjectFieldsMock = new List<Schema.SObjectField>{
            ReadinessValidation_SobjectType_Binding__mdt.Sobject_Type_Sub_Type_Mapping__c,
            ReadinessValidation_SobjectType_Binding__mdt.Store_Readiness_Validation_Rule__c
        };
        Schema.SObjectType typeOfObject = ReadinessValidationTypeBindingsSelector.newInstance()
            .SObjectType();
        ReadinessValidationTypeBindingsSelector readinessValidationTypeBindingsInstance = new ReadinessValidationTypeBindingsSelector();
        List<Schema.SObjectField> sObjectFields = readinessValidationTypeBindingsInstance.getSObjectFieldList();
        System.assertEquals(
            typeOfObject,
            ReadinessValidation_SobjectType_Binding__mdt.SObjectType,
            ASSERT_MESSAGE_MISMATCH_IN_OBJECT_TYPE
        );
        System.assertEquals(
            sObjectFields,
            sObjectFieldsMock,
            ASSERT_MESSAGE_MISMATCH_IN_FIELDS_LIST
        );
    }
}