sfdx-source/force-app/main/default/objects/Brief__c/Brief__c.object-meta.xml
<CustomObject>
    <description>LEM-2983: Object to capture a brief of the Campaigns specific to the Merchant.</description>
    <label>Brief</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Briefs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Brief__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>LEM-2983: Captures the Account with which the current Brief is associated to.</description>
    <label>ZAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Briefs</relationshipLabel>
    <relationshipName>Briefs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Brief_Relationship__c/Quote_Brief_Relationship__c.object-meta.xml
<CustomObject>
    <description>LEM-2983: Junction object between Quote and Brief.</description>
    <label>Quote Brief Relationship</label>
    <nameField>
        <displayFormat>BQR-{000000}</displayFormat>
        <label>Brief Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Brief Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Quote_Brief_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>LEM-5456: It is used to store the Account Id on the related Quote.</description>
    <formula>CASESAFEID(Quote__r.SBQQ__Account__c)</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Brief_Relationship__c/fields/Brief__c.field-meta.xml
<CustomField>
    <fullName>Brief__c</fullName>
    <description>LEM-2983: Captures the Brief related to the Quote Brief Relationship.</description>
    <label>Brief</label>
    <referenceTo>Brief__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote_Brief_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Brief_Relationship__c/fields/Campaign_of_Brief__c.field-meta.xml
<CustomField>
    <fullName>Campaign_of_Brief__c</fullName>
    <description>LEM-2982: Captures the campaign of the Brief with which the current Quote Relationship is associated.</description>
    <label>Campaign of Brief</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Brief_Relationship__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Brief Relationships</relationshipLabel>
    <relationshipName>Quote_Brief_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/selectors/QuoteBriefRelationshipsSelectorTest.cls
/**
 * @author Deloitte
 * @date 12/23/20222
 * @description Test class for Quote Brief RelationshipsSelector.
 */
@isTest(SeeAllData=false)
private class QuoteBriefRelationshipsSelectorTest {
    /**
     * @description It is used to test the instantiation of QuoteBriefRelationshipsSelector class.
     */
    @isTest
    private static void testWhenQuoteBriefRelationshipsExistThenQueryBasedOnQuoteAndCampaign() {
        QuoteBriefRelationshipsSelector relationshipsSelectorInstance = new QuoteBriefRelationshipsSelector();
        QuoteBriefRelationshipsSelector.newInstance();

        Schema.SObjectType typeOfObj = relationshipsSelectorInstance.getSObjectType();
        List<Schema.SObjectField> fieldList = relationshipsSelectorInstance.getSObjectFieldList();

        System.assertEquals(
            Schema.Quote_Brief_Relationship__c.SObjectType,
            typeOfObj,
            'The object type must be Quote Brief Relationship'
        );
        System.assertEquals(
            new List<Schema.SObjectField>{
                Quote_Brief_Relationship__c.Id,
                Quote_Brief_Relationship__c.Brief__c,
                Quote_Brief_Relationship__c.Campaign_of_Brief__c,
                Quote_Brief_Relationship__c.Quote__c,
                Quote_Brief_Relationship__c.Account__c
            },
            fieldList,
            'Mismatch in field list'
        );
    }
}