sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/Email_Outbound_Events_Binding__mdt.object-meta.xml
<CustomObject>
    <description>LEM-13778: It is used to store mapping of factory classes.</description>
    <label>Email Outbound Events Binding</label>
    <pluralLabel>Email Outbound Events Bindings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used factory class name that should be called based on the topic.</description>
    <label>Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Scope_Size__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used to store the execution scope size based on the processing payload size.</description>
    <label>Scope Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used to store the name of the topic.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/ApplicationEmailOutboundFactoryTest.cls
/**
 * @author Deloitte
 * @date 05/09/2024
 * @description Unit tests for ApplicationEmailOutboundFactory class
 */
@IsTest(IsParallel=true)
private class ApplicationEmailOutboundFactoryTest {
    private static final String ASSERT_MESSAGE_SCOPE_SIZE = 'Expected a retriveval size of 200';
    private static final String EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION = 'EMAIL_OUTBOUND_INTEGRATION';
    private static final String SERVICE_CLASS_NAME = 'IntegrationOutboundService';
    private Map<String, Email_Outbound_Events_Binding__mdt> implementationsByEventTopic;
    private Map<String, Object> mockImplementationsByEventTopic;

    @IsTest
    private static void testWhenCallingEmailOutboundFactoryThenReturnRegisteredImplementationsAndMocks() {
        Email_Outbound_Events_Binding__mdt[] bindings = new List<Email_Outbound_Events_Binding__mdt>{
            new Email_Outbound_Events_Binding__mdt(
                Class_Name__c = SERVICE_CLASS_NAME,
                Scope_Size__c = 200,
                Topic__c = EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION
            )
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IHandleEmailOutboundIntegrationsEvents handleEmailOutboundEventsMock = (IHandleEmailOutboundIntegrationsEvents) mocks.mock(
            IHandleEmailOutboundIntegrationsEvents.class
        );

        IEmailOutboundEventBindingSelector selectorMock = (IEmailOutboundEventBindingSelector) mocks.mock(
            IEmailOutboundEventBindingSelector.class
        );

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType())
            .thenReturn(Email_Outbound_Events_Binding__mdt.SObjectType);
        mocks.when(selectorMock.getAllValues()).thenReturn(bindings);
        mocks.stopStubbing();

        Application.SELECTOR.setMock(selectorMock);
        Application.EMAIL_OUTBOUND_INTEGRATION_EVENT.setMock(
            EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION,
            handleEmailOutboundEventsMock
        );

        EMAIL_OUTBOUND.setMock(
            EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION,
            handleEmailOutboundEventsMock
        );
        EMAIL_OUTBOUND.newInstance(EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION);
        EMAIL_OUTBOUND.retrieveScopeSize(EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION);
        System.assert(
            EMAIL_OUTBOUND.retrieveScopeSize(EVENT_TOPIC_EMAIL_OUTBOUND_INTEGRATION) == 200,
            ASSERT_MESSAGE_SCOPE_SIZE
        );
    }

    // Configure and create the EmailOutboundFactory for this Application
    public static final ApplicationEmailOutboundFactory EMAIL_OUTBOUND = new ApplicationEmailOutboundFactory();
}