sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/Email_Outbound_Events_Binding__mdt.object-meta.xml
<CustomObject>
    <description>LEM-13778: It is used to store mapping of factory classes.</description>
    <label>Email Outbound Events Binding</label>
    <pluralLabel>Email Outbound Events Bindings</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used factory class name that should be called based on the topic.</description>
    <label>Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Scope_Size__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used to store the execution scope size based on the processing payload size.</description>
    <label>Scope Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Email_Outbound_Events_Binding__mdt/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-13778: It is used to store the name of the topic.</description>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/EmailOutboundEventBindingSelector.cls
/**
 * @author Deloitte
 * @date 05/09/2024
 * @description Selector class to query Email outbound integration binding.
 */
public inherited sharing class EmailOutboundEventBindingSelector extends fflib_SObjectSelector implements IEmailOutboundEventBindingSelector {
    /**
     * @description default constructor for the class
     * @return IEmailOutboundEventBindingSelector - interface of IEmailOutboundEventBindingSelector
     */
    public static IEmailOutboundEventBindingSelector newInstance() {
        return (IEmailOutboundEventBindingSelector) Application.Selector.newInstance(
            Email_Outbound_Events_Binding__mdt.SObjectType
        );
    }

    /**
     * @description override default getSObjectType method
     * @return SObjectType - object type of metadata
     */
    public Schema.SObjectType getSObjectType() {
        return Email_Outbound_Events_Binding__mdt.SObjectType;
    }

    /**
     * @description This method is for getting all field values for Email_Outbound_Events_Binding__mdt
     * @return List<Email_Outbound_Events_Binding__mdt> - List of metadata records with values
     */
    public List<Email_Outbound_Events_Binding__mdt> getAllValues() {
        return Email_Outbound_Events_Binding__mdt.getAll().values();
    }

    /**
     * @description This method is for getting the fields of Email_Outbound_Events_Binding__mdt
     * @return List<Schema.SObjectField>- Email_Outbound_Events_Binding__mdt fields
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Email_Outbound_Events_Binding__mdt.Topic__c,
            Email_Outbound_Events_Binding__mdt.Class_Name__c,
            Email_Outbound_Events_Binding__mdt.Scope_Size__c
        };
    }
}