sfdx-source/force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Payment Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing street</inlineHelpText>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Bill_To_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Company_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-2029: Refers to the billing entity of the MX</description>
    <inlineHelpText>Refers to the billing entity of the MX</inlineHelpText>
    <label>Bill To Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Billing_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Email__c</fullName>
    <description>LEM-1285: Formula field to get the Email from Contact lookup field</description>
    <formula>Billing_Contact_Name__r.Email</formula>
    <label>Billing Contact Email</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing city</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Country_Code_Alpha_2__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_Alpha_2__c</fullName>
    <description>LEM-1285: Given a country, calculates the Alpha-2 ISO Code. Currently used for Netsuite integration.</description>
    <formula>Case( Country__c ,
&apos;United States&apos;, &apos;US&apos;,
&apos;Canada&apos;, &apos;CA&apos;,
&apos;Australia&apos;, &apos;AU&apos;,
&apos;New Zealand&apos;, &apos;NZ&apos;,
&apos;Japan&apos;, &apos;JP&apos;,
&apos;Germany&apos;, &apos;DE&apos;,
NULL)</formula>
    <label>Country Code (Alpha-2)</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures the NetSuite record ID of the related Customer account in NetSuite.</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/NetSuite_Sync_Response__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync_Response__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures the response code from NetSuite for the latest sync</inlineHelpText>
    <label>NetSuite Sync Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing postal code</inlineHelpText>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>LEM-1371: Payment Account Object setup</description>
    <inlineHelpText>Captures billing state</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Payment_Account__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

sfdx-source/force-app/main/default/classes/services/NetsuiteIntegratorRestletServiceImpl.cls
/**
 * @author DoorDash
 * @date   10/12/2022
 * @description This is the service interface implementation for Sync with Netsuite implementation
 */
public class NetsuiteIntegratorRestletServiceImpl implements INetsuiteIntegrator {
    private static final string VALIDATION_ERROR_RECORD_TYPE =System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_RECORD_TYPE;
    private static final string VALIDATION_ERROR_BILLING_CONTACT_EMAIL =System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_BILLING_CONTACT_EMAIL;
    private static final string VALIDATION_ERROR_NET_SUITE_SYNC_PROCESSES =System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_NET_SUITE_SYNC_PROCESSES;
    private static final string VALIDATION_ERROR_COUNTRY_CODE_ALPHA2 = System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_COUNTRY_CODE_ALPHA2;
	private static final string VALIDATION_ERROR_ADDRESS = System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_ADDRESS;
    private static final string VALIDATION_ERROR_BILL_TO_COMPANY_NAME = System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_BILL_TO_COMPANY_NAME;
    private static final string VALIDATION_ERROR_CURRENCY =System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_CURRENCY;
    private static final String ALLOW_SYNC_WITH_NETSUITE = System.Label.SYNC_WITH_NETSUITE_CUSTOM_PERMISSION;
    private static final String VALIDATION_PERMISSION_ISSUE = System.Label.PAYMENT_ACCOUNT_VALIDATION_ERROR_PERMISSION_SET;
    private static final String SUCCESS_MESSAGE = System.Label.SYNC_WITH_NETSUITE_SUCCESS_MESSAGE;
    private static final String RECORD_TYPE='Invoice';
    private static final String DESCRIBE_NAME = 'Payment Account';
    private static final String SOBJECT_NAME = 'Payment_Account__c';
    private static final String ERROR_KEY = 'error';
    private static final String ID_KEY = 'id';
    private static final String SUCCESS_KEY = 'success';
    private static final String MESSAGE_KEY = 'message';
    private static final Integer SUCCESS_STATUS_CODE = 200;
    private static final String STATUS_KEY='status';
    private static final Id STORE_RECORD_TYPE_ID;
    static {
        STORE_RECORD_TYPE_ID = Schema.SObjectType.Payment_Account__c.getRecordTypeInfosByDeveloperName()
            .get(RECORD_TYPE)
            .getRecordTypeId();
    }
    Map<String, Object> deserializedResponse = new Map<String,Object>();
    @TestVisible
    private List<String> validationErrors;
    /**
     * @description Call Netsuite Restlet API.
     * @param recordId
     * @return Map<String, Object>
    */
    public Map<String, Object> syncWithNetsuite(String recordId){
        Map<String, Object> deserializedResponse;
        Payment_Account__c paymentAccountRecord = new Payment_Account__c(
        	Id = recordId
        );
        HttpRequest request = OAuth1RequestGenerator.generateRequest(
        	DESCRIBE_NAME,
            recordId,
            SOBJECT_NAME
        );
        HttpResponse response = (new Http()).send(request);
        LogEntry entry = new LogEntry(DESCRIBE_NAME, response.getBody(), LogEntry.SeverityLevel.LOW)
            .withCallout(response.getStatus(),String.valueOf(response.getStatusCode()) , request.getEndpoint());
        entry.recordId = recordId;
        entry.className =  NetsuiteIntegratorRestletServiceImpl.class.getName();
        Logger.publish(entry);
        deserializedResponse = getDeserializedResponse(response);
        if(response.getStatusCode() == SUCCESS_STATUS_CODE){
           paymentAccountRecord.NetSuite_ID__c =String.valueOf( deserializedResponse?.get(ID_KEY));
           paymentAccountRecord.NetSuite_Sync_Response__c = null;
        }else{
           paymentAccountRecord.NetSuite_Sync_Response__c = String.valueOf( deserializedResponse?.get(MESSAGE_KEY));
        }

        PaymentAccountsService.updatePaymentAccountWithSyncWithNetsuiteResponse (paymentAccountRecord);
        return deserializedResponse;
     }
    /**
     * @description returns Map of Payment Record Id with Readiness Message for netSuiteIntegration with synchronous call.
     * @param paymentAccountId
     * @return List<String>
    */
    public List<String> performReadinessCheckValidations(Id paymentAccountId){
        validationErrors= new List<String>();
        Payment_Account__c paymentAccount = PaymentAccountsSelector.newInstance().selectById(new Set<Id>{paymentAccountId}).get(0);
            if(!FeatureManagementService.newInstance()
               .checkPermission(ALLOW_SYNC_WITH_NETSUITE)){
               validationErrors.add(VALIDATION_PERMISSION_ISSUE);
               return validationErrors;
            }
            if(paymentAccount.recordTypeId != STORE_RECORD_TYPE_ID){
                validationErrors.add(VALIDATION_ERROR_RECORD_TYPE);
                return validationErrors;
            }
            if(String.isNotBlank(paymentAccount.NetSuite_ID__c)){
                validationErrors.add(VALIDATION_ERROR_NET_SUITE_SYNC_PROCESSES);
                return validationErrors;
            }
            validateBillingContactEmail(paymentAccount);
            validateBillToCompanyName(paymentAccount);
            validateCurrency(paymentAccount);
            validateAddress(paymentAccount);
            validateCountryAlpha2(paymentAccount);
        	return validationErrors;
     }

    /**
     * @description validate Billing Contact Email field in Payment_Account__c object.
     * @param paymentAccount
    */
	  @TestVisible
    private void validateBillingContactEmail(Payment_Account__c paymentAccount){
        if(String.isBlank(paymentAccount.Billing_Contact_Email__c)){
        	validationErrors.add(VALIDATION_ERROR_BILLING_CONTACT_EMAIL);
        }
    }

    /**
     * @description validate Billing Company Name field in Payment_Account__c object.
     * @param paymentAccount
    */
    @TestVisible
    private void validateBillToCompanyName(Payment_Account__c paymentAccount){
        if(String.isBlank(paymentAccount.Bill_To_Company_Name__c)){
           validationErrors.add(VALIDATION_ERROR_BILL_TO_COMPANY_NAME);
        }
    }

    /**
     * @description validate Country Alpha2 field in Payment_Account__c object.
     * @param paymentAccount
    */
    @TestVisible
    private void validateCountryAlpha2(Payment_Account__c paymentAccount){
        if(String.isBlank(paymentAccount.Country_Code_Alpha_2__c)){
        	validationErrors.add(VALIDATION_ERROR_COUNTRY_CODE_ALPHA2);
        }
    }

    /**
     * @description validate Address(Address_Line_1, State, City, Postal code) field in Payment_Account__c object.
     * @param paymentAccount
    */
    @TestVisible
    private void validateAddress(Payment_Account__c paymentAccount){
        if(String.isBlank(paymentAccount.Address_Line_1__c)
           || String.isBlank(paymentAccount.State__c )
           || String.isBlank(paymentAccount.City__c )
           || String.isBlank(paymentAccount.Postal_Code__c )){
        	validationErrors.add(VALIDATION_ERROR_ADDRESS);
        }
    }
    /**
     * @description validate Country Alpha2 field in Payment_Account__c object.
     * @param paymentAccount
    */
    @TestVisible
    private void validateCurrency(Payment_Account__c paymentAccount){
        if(String.isBlank(paymentAccount.CurrencyIsoCode )){
        	validationErrors.add(VALIDATION_ERROR_CURRENCY);
        }
    }
    /**
     * @description Deserialize HttpResponse in Key and Value format
     * @param response
     * @return Map<String, Object>
    */

  	@testvisible
    private Map<String, Object> getDeserializedResponse(HttpResponse response){
    Map<String, Object> deserializedResponse = new Map<String, Object>();
    if(response.getStatusCode() == SUCCESS_STATUS_CODE){

         deserializedResponse.put(STATUS_KEY, SUCCESS_KEY);
         deserializedResponse.put(ID_KEY, String.valueOf(((Map<String, Object>) JSON.deserializeUntyped(response.getBody()))?.get(ID_KEY)));
         deserializedResponse.put(MESSAGE_KEY,SUCCESS_MESSAGE);

    }else{
         deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
		 deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped( JSON.serialize(deserializedResponse.get(ERROR_KEY)));
		 deserializedResponse = (Map<String, Object>) JSON.deserializeUntyped(String.valueOf(deserializedResponse.get(MESSAGE_KEY)));
		 deserializedResponse.put(STATUS_KEY, ERROR_KEY);

    }
    return deserializedResponse;
  }

}