sfdx-source/force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>LEM-564: A brand is a concept – a name, term, design, symbol, or any other feature that identifies one seller&apos;s goods or services as distinct from those of other sellers. The brand may have one or more brands underneath it (this will be represented as a brand relationship). Brands are owned by Businesses.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Contract_Brand_Association__c/Contract_Brand_Association__c.object-meta.xml
<CustomObject>
    <description>LEM-3618: Initial Setup of Brand to Contract Relationship object</description>
    <label>Contract Brand Association</label>
    <nameField>
        <displayFormat>CBA-{0}</displayFormat>
        <label>Contract Brand Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Brand Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Contract_Brand_Association__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>LEM-3618: Initial Setup of Brand to Contract Relationship object</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Contract Brand Associations</relationshipLabel>
    <relationshipName>Contract_Brand_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Brand_Association__c/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <description>LEM-5399: It is used to store the Brand Id of the brand related to the association.</description>
    <formula>CASESAFEID(Brand__r.Id)</formula>
    <label>Brand Id</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Brand_Association__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>LEM-3618: Initial Setup of Brand to Contract Relationship object</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Brand Associations</relationshipLabel>
    <relationshipName>Contract_Brand_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contract_Brand_Association__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-3618: Initial Setup of Brand to Contract Relationship object</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/ContractBrandAssociationsSelector.cls
/**
 * @author Deloitte
 * @date 03/24/2023
 * @description Selector class for Contract Brand Association object.
 */
public inherited sharing class ContractBrandAssociationsSelector extends fflib_SObjectSelector implements IContractBrandAssociationsSelector {
    /**
     * @description default constructor for the Contract Brand Association Selector class
     * @return IContractBrandAssociationsSelector - interface of IContractBrandAssociationsSelector
     */
    public static IContractBrandAssociationsSelector newInstance() {
        return (IContractBrandAssociationsSelector) Application.Selector.newInstance(
            Contract_Brand_Association__c.SObjectType
        );
    }

    /**
     * @description This method is for getting the fields on Contract Brand Association object
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Contract_Brand_Association__c.Id,
            Contract_Brand_Association__c.Brand__c,
            Contract_Brand_Association__c.Brand_Id__c,
            Contract_Brand_Association__c.Contract__c,
            Contract_Brand_Association__c.Status__c
        };
    }

    /**
     * @description This method is used for getting Object type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Contract_Brand_Association__c.SObjectType;
    }

    /**
     * @description This method is used for getting records by id.
     * @param contractBrandAssociationIds
     * @return List<Contract_Brand_Association__c>
     */
    public List<Contract_Brand_Association__c> selectById(Set<Id> contractBrandAssociationIds) {
        return (List<Contract_Brand_Association__c>) selectSObjectsById(
            contractBrandAssociationIds
        );
    }

    /**
     * @description This method is used for getting records by id.
     * @param contractIds
     * @return List<Contract_Brand_Association__c>
     */
    public List<Contract_Brand_Association__c> selectByContracts(Set<String> contractIds) {
        fflib_QueryFactory associationsQuery = newQueryFactory()
            .selectField('Brand__r.Name')
            .selectField('Brand__r.Id')
            .setCondition('Contract__c IN :contractIds')
            .setOrdering('Brand__r.Name', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Contract_Brand_Association__c>) Database.query(associationsQuery.toSOQL());
    }

     /**
     * @description LEM-12963 Retrieves a list of Contract_Brand_Association__c records based on the provided contract Id and Brand Id.
     * @param contractId The Id of the contract.
     * @param brandAsscIds The Id of the Brand .
     * @return A list of Contract_Brand_Association__c records that match the given contract Id and Brand Association Id.
     */
    public List<Contract_Brand_Association__c> selectByContractAndBrandAsscs(Id contractId, Set<Id> brandAsscIds) {
        return (List<Contract_Brand_Association__c>) Database.query(
            newQueryFactory()
                .setCondition('Contract__c  = :contractId AND Brand__c IN :brandAsscIds')
                .toSOQL()
        );
    }
}