sfdx-source/force-app/main/default/objects/Contact/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-23682: It stores Account Name value to display in Create Opportunity Contact Roles from Stores Flow.</description>
    <formula>Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13790: It indicates active or inactive status of the SMB contact.</description>
    <complianceGroup>GDPR</complianceGroup>
    <inlineHelpText>Indicates whether the status of the SMB contact</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/Readiness_Check_Failure__c.object-meta.xml
<CustomObject>
    <description>LEM-1684: It stores validation rules evaluated successfully for a store Account related to a Work Order during readiness check. Onboarding and activations persona&apos;s user will take corrective actions to resolve the failures captured in this object in order to make a store ready for provisioning.</description>
    <label>Readiness Check Failure</label>
    <nameField>
        <displayFormat>RCF-{0}</displayFormat>
        <label>Readiness Check Failure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readiness Check Failures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the store Account that needs correction to resolve the failure.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Readiness Check Failures</relationshipLabel>
    <relationshipName>Readiness_Check_Failures</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>LEM-1684: It indicates the error message to be displayed to onboarding and activations persona&apos;s user for corrections on the store related to the failure record.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>LEM-1684: It indicates the field name where the failure occurred.</description>
    <label>Field Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>LEM-1684: It indicates the object name where the failure occurred.</description>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-1684: It indicates the parent of work order related to the readiness check failure record.</description>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Readiness Check Corrections</relationshipLabel>
    <relationshipName>Readiness_Check_Corrections</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Readiness_Check_Failure__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>LEM-13135 </description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; + AccountId , Account.Name , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/WorkOrder/fields/Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Work_Order__c</fullName>
    <description>LEM-16014: It indicates Id of Parent Work Order.</description>
    <formula>CASESAFEID(ParentWorkOrderId)</formula>
    <label>Parent Work Order</label>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/tests/classes/unit/controllers/DisplayRelatedReadinessCheckCntrTest.cls
/*
*@author Deloitte
*@date 26 June 2024
*@description Test class for DisplayRelatedReadinessCheckController.
*/

@isTest(SeeAllData=false)
public class DisplayRelatedReadinessCheckCntrTest{
    private static final String ERROR_MESSAGE = 'Unexpected Error: Values do not match.';
    private static final String COLUMNS_TO_DISPLAY_STATIC_CONFIG = 'RelatedReadinessCheckColumnsViewOrder';


    /*
    *@description-To test the retrieved field values when getFields method is called.
    */
    @isTest
    private static void testWhenGetFieldsMethodCalledThenReturnColumnsWithCorrectFieldsAndAttributes() {
        String jsonData = DisplayRelatedReadinessCheckController.getFields();
        List<DynamicColumn> dynamicColumns = (List<DynamicColumn>) JSON.deserialize(jsonData,List<DynamicColumn>.class);
        String columnsToDisplay = StaticConfigurationsSelector.newInstance().getInstanceValue(COLUMNS_TO_DISPLAY_STATIC_CONFIG).Configuration_Value__c;
        for (DynamicColumn eachDynamicColumn : dynamicColumns) {
            System.assertEquals(true,columnsToDisplay.contains(eachDynamicColumn.label),ERROR_MESSAGE);
        }
    }

    /*
    *@description To test if Readiness_Check_Failure__c details are retrieved when getReadinessCheckFailureDetails method is called.
    */
    @isTest
    private static void testWhenGetReadinessCheckRecordsThenReturnParentWorkOrder() {
        Id parentWorkOrderId = Fake.generateId(WorkOrder.class);
        Readiness_Check_Failure__c[] newReadinessFailureRecords = new List<Readiness_Check_Failure__c>{
            new Readiness_Check_Failure__c(
                Id = Fake.generateId(Readiness_Check_Failure__c.class),
                Account_Name__c = Fake.generateId(Account.class),
                Field_Name__c = 'Phone',
                Error_Message__c ='Please ensure Tax ID is populated.',
                Status__c='Active',
                Object_Name__c='Account',
                Parent_Work_Order__c=parentWorkOrderId
            ),
            new Readiness_Check_Failure__c(
                Id = Fake.generateId(Readiness_Check_Failure__c.class),
                Account_Name__c = Fake.generateId(Account.class),
                Field_Name__c = 'Phone',
                Error_Message__c ='Please ensure the Contact with Decision Maker role is created on the store account.',
                Status__c='Active',
                Object_Name__c='Contact',
                Parent_Work_Order__c=parentWorkOrderId
            )
        };
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IReadinessCheckFailuresSelector selectorMock = (IReadinessCheckFailuresSelector) mocks.mock(IReadinessCheckFailuresSelector.class);
        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Readiness_Check_Failure__c.SObjectType);
        mocks.when(selectorMock.selectByParentWorkOrderIds((Set<Id>) fflib_Match.anyObject())).thenReturn(newReadinessFailureRecords);
        mocks.stopStubbing();
        Application.SELECTOR.setMock(selectorMock);
        List<Readiness_Check_Failure__c> relatedReadinessCheckRecords = DisplayRelatedReadinessCheckController.getReadinessCheckFailureDetails(parentWorkOrderId);
        List<Readiness_Check_Failure__c> relatedReadinessCheckUpdatedRecords = DisplayRelatedReadinessCheckController.getReadinessCheckFailureUpdatedDetails(parentWorkOrderId);
        System.assertEquals(2, relatedReadinessCheckRecords.size(), ERROR_MESSAGE);
        System.assertEquals(relatedReadinessCheckRecords[0].Object_Name__c, 'Account', ERROR_MESSAGE);
        System.assertEquals(relatedReadinessCheckUpdatedRecords[1].Object_Name__c, 'Contact', ERROR_MESSAGE);
    }
}