sfdx-source/force-app/main/default/objects/Contact/fields/Address_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Address_Rejection_Reason__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the address rejection reasons.</description>
    <label>Address Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bad Address</fullName>
            </value>
            <value>
                <fullName>Incomplete Address</fullName>
            </value>
            <value>
                <fullName>Technical Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Address_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It stores Account status in order to validate entity address.</description>
    <label>Address Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Alcohol_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Alcohol_Eligibility__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It signifies whether Mx’s location is eligible for alcohol sales and/or deliveries.</description>
    <label>Alcohol Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wet</fullName>
            </value>
            <value>
                <fullName>Moist</fullName>
            </value>
            <value>
                <fullName>Dry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Business_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It represents the Business Id that was provisioned during the SSMO process.</description>
    <label>Business Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14818: It is used to Store the Company Name received in payload on SSMO fallout.</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Hours_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Hours_of_Operation__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14822: It indicates the hours during which the restaurant is open.</description>
    <label>Hours of Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <description>LEM-14822: It represents the Store Id that was provisioned during the SSMO process.</description>
    <label>Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Submarket__c.field-meta.xml
<CustomField>
    <fullName>Submarket__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14822: It represents the sub-market of the Contact and would be populated by Mulesoft.</description>
    <label>Submarket</label>
    <referenceTo>Submarket__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Contact/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>LEM-14648: It is used to capture the SSMO UUID received by Mulesoft in the payload .</description>
    <label>SSMO UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Submarket__c/Submarket__c.object-meta.xml
<CustomObject>
    <description>LEM-1850: Table to handle submarket pricing data from Figment</description>
    <label>Submarket</label>
    <nameField>
        <label>Submarket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submarkets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/tests/classes/unit/services/SSMOContactCreationServiceImplTest copy.cls
/**
* @author Deloitte
* @date 05/20/2024
* @description This is  the test class for SSMO Contact Creation
*/
@isTest(seeAllData=false)
private class SSMOContactCreationServiceImplTest {
    private static final String STATIC_RESOURCE_TEST_JSON = 'SSMO_Contact_Ingestion_Mock_Payload';


     /**
     * @description It is used verify contact creation scenario when no matched records are
     * present in the payload
     * */
    @isTest
    private static void testWhenNoMatchingRecordThenCreateContactFromPayload() {

        StaticResource sr = fetchStaticResource();
        Blob blobJSON = sr.Body;
        String payloadString = blobJSON.toString();
        SSMOFalloutWrapper parsedPayloads = (SSMOFalloutWrapper)System.JSON.deserialize(payloadString,SSMOFalloutWrapper.class);
        Contact contactToInsert = new Contact();


        Contact contactsTobeInserted = SSMOContactCreationService.insertContactSSMO(parsedPayloads,contactToInsert);

        System.assertEquals(parsedPayloads.storeName, contactsTobeInserted.Company__c, 'False');
        System.assertEquals(parsedPayloads.ownerFirstName, contactsTobeInserted.FirstName, 'False');
        System.assertEquals(parsedPayloads.ownerLastName, contactsTobeInserted.LastName, 'False');
        System.assertEquals(parsedPayloads.ownerPhone, contactsTobeInserted.MobilePhone, 'False');
        System.assertEquals(parsedPayloads.email, contactsTobeInserted.Email, 'False');
	}

     /**
     * @description It is used verify contact updation scenario when matched records are
     * present in the payload
     * */
    @isTest
    private static void testWhenMatchingContactFoundThenUpdateContactFromPayload() {
        Id subMarketIdMock = fflib_IDGenerator.generate(Submarket__c.SObjectType);
        StaticResource sr = fetchStaticResource();
        Blob blobJSON = sr.Body;
        String payloadString = blobJSON.toString();
        SSMOFalloutWrapper parsedPayloads = (SSMOFalloutWrapper)System.JSON.deserialize(payloadString,SSMOFalloutWrapper.class);
        Contact testInsertContactSSMO = new Contact();

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISubmarketsSelector mockSubmarketsSelector = (ISubmarketsSelector) mocks.mock(
            ISubmarketsSelector.class
        );
        mocks.startStubbing();
        mocks.when(mockSubmarketsSelector.sObjectType()).thenReturn(Submarket__c.SObjectType);
        mocks.when(
                mockSubmarketsSelector.getSubmarketById('9094')
            )
            .thenReturn(new List<Submarket__c>{new Submarket__c(Id = subMarketIdMock)});
        mocks.stopStubbing();
        Application.SELECTOR.setMock(mockSubmarketsSelector);


       Contact contactsTobeUpdated = SSMOContactCreationService.updateContactSSMO(parsedPayloads,testInsertContactSSMO);
       System.assertEquals(parsedPayloads.sourceUniqueId, contactsTobeUpdated.Unique_Identifier__c, 'False');
       System.assertEquals(subMarketIdMock, contactsTobeUpdated.Submarket__c, 'False');
       System.assertEquals(parsedPayloads.addressVerificationInfo ?.alcoholRules ?.alcoholAllowanceCategory, contactsTobeUpdated.Alcohol_Eligibility__c, 'False');
       System.assertEquals(parsedPayloads.addressVerificationInfo ?.addressVerificationStatus, contactsTobeUpdated.Address_Verification_Status__c, 'False');
       System.assertEquals(parsedPayloads.addressVerificationInfo ?.rejectedReason, contactsTobeUpdated.Address_Rejection_Reason__c , 'False');
    }
   	/**
     * @description It is used verify contact updation with new submarket creation scenario when matched records are
     * present in the payload
     * */
    @isTest
    private static void testWhenContactPresentThenUpdateContactWithNewSubmarket() {
        StaticResource sr = fetchStaticResource();
        Blob blobJSON = sr.Body;
        String payloadString = blobJSON.toString();
        SSMOFalloutWrapper parsedPayloads = (SSMOFalloutWrapper)System.JSON.deserialize(payloadString,SSMOFalloutWrapper.class);
        Contact testInsertContactSSMO = new Contact();

       Contact contactsTobeUpdated = SSMOContactCreationService.updateContactSSMO(parsedPayloads,testInsertContactSSMO);
       System.assertEquals(parsedPayloads.sourceUniqueId, contactsTobeUpdated.Unique_Identifier__c, 'False');
       System.assertEquals(String.valueOf(parsedPayloads.businessId), contactsTobeUpdated.Business_Id__c, 'False');
       System.assertEquals(parsedPayloads.storeHours, contactsTobeUpdated.Hours_of_Operation__c, 'False');
       System.assertEquals(String.valueof(parsedPayloads.storeId), contactsTobeUpdated.Store_Id__c , 'False');
    }

    /**
     * @description To query static resources
     * @return StaticResource
     * */
    private static StaticResource fetchStaticResource() {

        StaticResource stresource = [
            SELECT Body
            FROM StaticResource
            WHERE Name = :STATIC_RESOURCE_TEST_JSON
        ];
        return stresource;
    }
}