sfdx-source/force-app/main/default/objects/Contact/fields/Inbound_Ingestion_Log__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Ingestion_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-14813: It is used to store the associated inbound ingestion log.</description>
    <label>Inbound Ingestion Log</label>
    <referenceTo>Inbound_Ingestion_Log__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Inbound_Ingestion_Log__c/Inbound_Ingestion_Log__c.object-meta.xml
<CustomObject>
    <description>LEM-14648: Custom Inbound Ingestion Log object for SSMO Integration.</description>
    <label>Inbound Ingestion Log</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Inbound Ingestion Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Ingestion Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Instant_Ingestor__e/Instant_Ingestor__e.object-meta.xml
<CustomObject>
    <description>LEM-14648: It allows SSMO specific Platform Event schema and the trigger listener to act as dispatcher of the events. It passes topic and corresponding payload to the trigger listener which identifies service corresponding to the passed topic and passes payload to the service layer for further records processing.
It is important that the PreSalesTransaction, PostSalesTransaction, and Instant_Ingestor event objects all have the same field shape.</description>
    <label>Instant Ingestor</label>
    <pluralLabel>Instant Ingestors</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/classes/services/IInstantIngestionOnboardingService.cls
/**
 * @author Deloitte
 * @date 05/11/2024
 * @description Interface of service class for InstantIngestionOnboardingService related logic.
 */
public interface IInstantIngestionOnboardingService {
    /**
     * @description It is used to initiate InstantIngestion records creation when instant ingestor event is fired.
     * @param instantIngestorEvents
     */
    void handleInstantIngestorEvents(List<Instant_Ingestor__e> instantIngestorEvents);

    /**
     * @description It is used to initiate account, xref and business reference creation.
     * @param payLoadWrapperByIngestionLogUUID
     * @param sourceByUUID
     */
    void payloadDistributorForAccountsAndXrefsBizRefs(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUID,
        Map<String, String> sourceByUUID
    );

    /**
     * @description It is used to initiate Contact and ACR creation.
     * @param payLoadWrapperByIngestionLogUUIDForContactAndACR
     * @param sourceByUUID
     */
    void payloadDistributorForContactsAndACRs(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForContactAndACR,
        Map<String, String> sourceByUUID
    );

    /**
     * @description This method is responsible for distributing the payload for RESSMO accounts and Xrefs BizRefs.
     *
     * @param payLoadWrapperByIngestionLogUUID The payload to be distributed.
     */
    void payloadDistributorForRESSMOAccountsAndXrefsBizRefs(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUID
    );

    /**
     * @description Update the Quote to Contract Signed and Mx Onboarding link to success
     * @author VenkateshDD | 08-05-2024
     * @param payLoadWrapperByIngestionLogUUID
     **/
    void updateQuoteToContractSignedAndMxOnboardingLinkToSuccess(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUID
    );

    /**
     * @description It is used to initiate the creation of Opportunities by the received payload.
     * @param payLoadWrapperByIngestionLogUUIDForOpportunityAndOCR
     * @param sourceByUUID
     * @param inboundIngestionLogByUUID
     */
    void payloadDistributorForOpportunities(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForOpportunityAndOCR,
        Map<String, String> sourceByUUID,
        Map<String, Inbound_Ingestion_Log__c> inboundIngestionLogByUUID
    );

    /**
     * @description It is used to initiate the creation of Quote and Quote Lines by the received payload.
     * @param payLoadWrapperByIngestionLogUUIDForQuoteAndQuoteLines
     */
    void payloadDistributorForQuotesAndQuoteLines(
        Map<String, InstantIngestionPayloadParser> payLoadWrapperByIngestionLogUUIDForQuoteAndQuoteLines
    );
}