sfdx-source/force-app/main/default/objects/Generic_Log__c/Generic_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used to capture logs in JSON format of all types like apex errors, spike detection, api response etc, which will eventually make into Scalyr and get purged</description>
    <label>Generic Log</label>
    <nameField>
        <displayFormat>GL-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GenericLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Generic_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Generic_Log_Event__e/Generic_Log_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event to insert Generic Log data</description>
    <label>Generic Log Event</label>
    <pluralLabel>Generic Log Events</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Generic_Log_Event__e/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Field to capture generated JSON log message</description>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/classes/triggerHandlers/GenericLogEventsHandler.cls
/**
 * @description GeericLog Event Object Trigger Handler
 */
public with sharing class GenericLogEventsHandler extends ApplicationDomainHandler {
    /**
     * @description Constructor Method
     * @param sObjectList - Provisioning Events Record List
     */
    public GenericLogEventsHandler(List<Generic_Log_Event__e> sObjectList) {
        super(sObjectList);
        setContextBypass(Generic_Log_Event__e.SObjectType, GenericLogEventsHandler.class);
    }

    /**
     * @description Called to perform after insert processing
     */
    public override void onAfterInsert() {

        fflib_ISobjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Generic_Log_Event__e> genericLogEventsToProcess = new List<Generic_Log_Event__e>();

        for (Integer counter = 0; counter < this.records.size(); counter++) {
            Generic_Log_Event__e genericLogEvent = (Generic_Log_Event__e) this.records[counter];

            genericLogEventsToProcess.add(genericLogEvent);
            EventBus.TriggerContext.currentContext().setResumeCheckpoint(genericLogEvent.replayId);
        }

        for (Generic_Log_Event__e event : genericLogEventsToProcess) {
            uow.registerNew(new Generic_Log__c(Log_Details__c = event.Log_Details__c));
        }

        uow.commitWork();

    }

    /**
     * @description Constructor class implements fflib_SObjectDomain class
     */
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        /**
         * @description This method implements construct method of fflib_SObjectDomain.IConstructable
         * @param sObjectList - List of SObjects
         * @return GenericLogEventsHandler
         */
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new GenericLogEventsHandler(sObjectList);
        }
    }
}