sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/Quote_Line_Drawer_Attributes__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1486 To display the attributes on the quote configurator</description>
    <label>Quote Line Drawer Attributes</label>
    <pluralLabel>Quote Line Drawer Attributes</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Applicable_Segment__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Segment__c</fullName>
    <description>LEM-13441: This field captures the account segment value for which this attribute is applicable.</description>
    <label>Applicable Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
                <default>true</default>
                <label>Enterprise</label>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Eligible_for_Product__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LEM-6458- True if this attribute should show for this product when sold standalone</description>
    <label>Eligible for Product</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Eligible_Packages__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Packages__c</fullName>
    <description>LEM-6458: Packages Name to which this attribute applies to</description>
    <label>Eligible Packages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Quote_Line_Drawer_Products__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Drawer_Products__c</fullName>
    <label>Quote Line Drawer Products</label>
    <referenceTo>Quote_Line_Drawer_Products__mdt</referenceTo>
    <relationshipLabel>Quote Line Drawer Attributes</relationshipLabel>
    <relationshipName>Quote_Line_Drawer_Attributes</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Attributes__mdt/fields/Required_for_Segment__c.field-meta.xml
<CustomField>
    <fullName>Required_for_Segment__c</fullName>
    <description>LEM-13441: This field captures the account segment value for which this attribute is required.</description>
    <label>Required For Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
                <default>true</default>
                <label>Enterprise</label>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Products__mdt/Quote_Line_Drawer_Products__mdt.object-meta.xml
<CustomObject>
    <description>LEM-1486 This for displaying attributes on Quote configurator</description>
    <label>Quote Line Drawer Products</label>
    <pluralLabel>Quote Line Drawer Products</pluralLabel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Quote_Line_Drawer_Products__mdt/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/QuoteLineDrawAttributesSelector.cls
/**
 * @author Doordash
 * @date 06/30/2022
 * @description Selector class for Quote Line Drawer Attributes Mapping
 */
public inherited sharing class QuoteLineDrawAttributesSelector extends fflib_SObjectSelector implements IQuoteLineDrawAttributesSelector {
    /**
     * @description Default constructor for the Quote Line Drawer Attributes selector class
     * @return IQuoteLineDrawAttributesSelector - interface of IQuoteLineDrawAttributesSelector
     */
    public static IQuoteLineDrawAttributesSelector newInstance() {
        return (IQuoteLineDrawAttributesSelector) Application.Selector.newInstance(
            Quote_Line_Drawer_Attributes__mdt.SObjectType
        );
    }
    /**
     * @description It is used for getting Object type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Quote_Line_Drawer_Attributes__mdt.SObjectType;
    }

    /**
     * @description It is for getting the fields on Quote_Line_Drawer_Attributes__mdt Metadata
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Quote_Line_Drawer_Attributes__mdt.Id,
            Quote_Line_Drawer_Attributes__mdt.Is_Active__c,
            Quote_Line_Drawer_Attributes__mdt.Field_API_Name__c,
            Quote_Line_Drawer_Attributes__mdt.Field_Label__c,
            Quote_Line_Drawer_Attributes__mdt.Required_for_Segment__c,
            Quote_Line_Drawer_Attributes__mdt.Applicable_Segment__c,
            Quote_Line_Drawer_Attributes__mdt.Quote_Line_Drawer_Products__c,
            Quote_Line_Drawer_Attributes__mdt.Eligible_Packages__c,
            Quote_Line_Drawer_Attributes__mdt.Eligible_for_Product__c,
            Quote_Line_Drawer_Attributes__mdt.Is_Required__c
        };
    }

    /**
     * @description This method is for getting Quote Line Attributes for a particular product
     * @JIRA# LEM-6458
     * @param prodCode
     * @return List<Quote_Line_Drawer_Attributes__mdt>
     */
    public List<Quote_Line_Drawer_Attributes__mdt> selectQLAttributesByProductCode(
        String prodCode
    ) {
        fflib_QueryFactory quoteLineAttributeQuery = newQueryFactory(false)
            .selectField('Eligible_Packages__c')
            .selectField('Eligible_for_Product__c')
            .selectField('Field_API_Name__c')
            .selectField('Required_for_Segment__c')
            .selectField('Applicable_Segment__c')
            .selectField('Is_Required__c')
            .selectField('Quote_Line_Drawer_Products__r.Is_Active__c')
            .selectField('Quote_Line_Drawer_Products__r.Product_Code__c')
            .setCondition(
                'Is_Active__c = true ' +
                    'AND Quote_Line_Drawer_Products__r.Is_Active__c = true ' +
                    'AND Quote_Line_Drawer_Products__r.Product_Code__c = :prodCode'
            );
        return (List<Quote_Line_Drawer_Attributes__mdt>) Database.query(
            quoteLineAttributeQuery.toSOQL()
        );
    }
}