sfdx-source/force-app/main/default/objects/ContentVersion/fields/Mx_Document_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15838: It indicates the document verification status. The default value is &quot;Pending Review&quot;.</description>
    <label>Mx Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Mx_Fraud_Document__c.field-meta.xml
<CustomField>
    <fullName>Mx_Fraud_Document__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15836 : It associates the content version to Merchant Fraud Document record.</description>
    <label>Mx Fraud Document</label>
    <referenceTo>Mx_Fraud_Document__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/ContentVersion/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores Store Id of the document.</description>
    <label>Related To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/Mx_Fraud_Document__c.object-meta.xml
<CustomObject>
    <description>LEM-15836: It is used to store all required documents and validation details for fraud verification purposes.</description>
    <label>Mx Fraud Document</label>
    <nameField>
        <displayFormat>MX-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Fraud Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores all document type and dependent on country code. This is not a restricted picklist so it allows user to insert new value.</description>
    <label>Mx Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mx_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ABN Document</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>DBA (Doing Business As)</fullName>
            </value>
            <value>
                <fullName>EIN Verification Letter (147C)</fullName>
            </value>
            <value>
                <fullName>Food License</fullName>
            </value>
            <value>
                <fullName>Form SS-4</fullName>
            </value>
            <value>
                <fullName>HST/GST Document</fullName>
            </value>
            <value>
                <fullName>NZBN Document</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Photo Identification Back</fullName>
            </value>
            <value>
                <fullName>Photo Identification Front</fullName>
            </value>
            <value>
                <fullName>W9 with Schedule C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Notes__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Notes__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the Document Verification Notes or Comments.</description>
    <label>Mx Document Verification Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the document verification status. The default value is &quot;Pending Review&quot;.</description>
    <label>Mx Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Mx_Store_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>LEM-15836: It associates the Mx Fraud Document to the Store Account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mx Fraud Documents</relationshipLabel>
    <relationshipName>Mx_Fraud_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/ContentVersionsSelector.cls
/**
 * @author DoorDash
 * @description Selector class for the ContentVersion object.
 **/
public inherited sharing class ContentVersionsSelector extends fflib_SObjectSelector implements IContentVersionsSelector {
    /**
     * @description default constructor for the ContentVersion Selector class
     * @return IContentVersionsSelector - interface of IContentVersionsSelector
     */
    public static IContentVersionsSelector newInstance() {
        return (IContentVersionsSelector) Application.Selector.newInstance(
            ContentVersion.SObjectType
        );
    }

    /**
     * @description This method is used for getting Object type
     * @return Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return ContentVersion.SObjectType;
    }

    /**
     * @description This method is for getting the fields on ContentVersion object
     * @return List of Schema.SObjectField
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            ContentVersion.Id,
            ContentVersion.CreatedById,
            ContentVersion.CreatedDate,
            ContentVersion.FileType,
            ContentVersion.LastModifiedDate,
            ContentVersion.LastModifiedById,
            ContentVersion.ContentDocumentId,
            ContentVersion.Description,
            ContentVersion.IsLatest,
            ContentVersion.Title,
            ContentVersion.VersionNumber,
            ContentVersion.VersionData
        };
    }

    /**
     * @description Returns a List of ContentVersions by their IDs
     * @param idSet - Set of ContentVersion IDs
     * @return List<ContentVersion>
     */
    public List<ContentVersion> selectById(Set<Id> idSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN: idSet');
        return (List<ContentVersion>) Database.query(query.toSOQL());
    }

    /**
     * @description Returns a List of ContentVersions by ContentDocumentId
     * @param documentIds - ContentDocumentIds
     * @return List<ContentVersion>
     **/
    public List<ContentVersion> selectByContentDocumentIds(Set<Id> documentIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('ContentDocumentId IN :documentIds');
        query.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ContentVersion>) Database.query(query.toSOQL());
    }

    /**
     * @description Returns a List of the latest ContentVersions by ContentDocumentId
     * @param documentIds - ContentDocumentIds
     * @return List<ContentVersion>
     **/
    public List<ContentVersion> selectLatestByContentDocumentIds(Set<Id> documentIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('ContentDocumentId IN :documentIds');
        query.setCondition('IsLatest = true');
        return (List<ContentVersion>) Database.query(query.toSOQL());
    }

    /**
     * @description It queries Content Versions along with Fraud Document details
     * based on passed Store Account Ids.
     * @JIRA# LEM-16642
     * @param relatedStoreIds
     * @return List<ContentVersion>
     */
    public List<ContentVersion> selectByRelatedStoreIds(Set<Id> relatedStoreIds) {
        fflib_QueryFactory query = newQueryFactory()
            .selectField('Related_To_Id__c')
            .selectField('Title')
            .selectField('VersionNumber')
            .selectField('Mx_Fraud_Document__r.CreatedDate')
            .selectField('Mx_Fraud_Document__r.LastModifiedDate')
            .selectField('Mx_Fraud_Document__r.Mx_Document_Type__c')
            .selectField('Mx_Fraud_Document__r.Mx_Document_Verification_Status__c')
            .selectField('Mx_Fraud_Document__r.Mx_Document_Verification_Notes__c')
            .selectField('Mx_Fraud_Document__r.Mx_Store_Id__c')
            .setCondition(
                'Related_To_Id__c IN :relatedStoreIds AND Mx_Fraud_Document__r.Mx_Store_Id__c IN :relatedStoreIds'
            )
            .setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<ContentVersion>) Database.query(query.toSOQL());
    }
}