sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/Mx_Tag_Association__c.object-meta.xml
<CustomObject>
    <description>LEM-14102: It is a junction object between Mx Tag and other objects.</description>
    <label>Mx Tag Association</label>
    <nameField>
        <displayFormat>[TAG-{0000}]</displayFormat>
        <label>Mx Tag Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Tags Association</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Tag_Association__c/fields/MxTagAssociation_Status__c.field-meta.xml
<CustomField>
    <fullName>MxTagAssociation_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-14987: It is used to represent the status of the the Mx Tag Association.</description>
    <inlineHelpText>Indicates the status of the the Mx Tag Association.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/classes/triggerHandlers/MxTagAssociationsHandler.cls
/**
 * @author Deloitte
 * @date 04-26-2024
 * @description Mx_Tag_Association__c Object Trigger Handler
 */
public class MxTagAssociationsHandler extends ApplicationDomainHandler {
    /**
     * @description Constructor Method
     * @param sObjectList - Mx_Tag_Association__c Record List
     */
    public MxTagAssociationsHandler(List<Mx_Tag_Association__c> sObjectList) {
        super(sObjectList);
        setContextBypass(Mx_Tag_Association__c.SObjectType, MxTagAssociationsHandler.class);
    }

    /**
     * @description Constructor class implements fflib_SObjectDomain class
     */
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        /**
         * @description This method implements construct method of fflib_SObjectDomain.IConstructable
         * @param sObjectList - List of SObjects
         * @return MxTagAssociationsHandler
         */
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new MxTagAssociationsHandler(sObjectList);
        }
    }

    /**
     * @description Called to perform before insert processing
     */
    public override void onBeforeInsert() {
        MxTagAssociations.newInstance(this.records).updateStartAndEndDate();
    }

    /**
     * @description Called to perform before update processing
     * @param existing - The map of old requests
     */
    public override void onBeforeUpdate(Map<Id, SObject> existing) {
        MxTagAssociations.newInstance(
                new List<Mx_Tag_Association__c>(
                    (List<Mx_Tag_Association__c>) getChangedRecords(
                        new Set<SObjectField>{ Mx_Tag_Association__c.MxTagAssociation_Status__c }
                    )
                )
            )
            .updateStartAndEndDate();
    }

    /**
     * @description Called to perform after insert processing
     */

    public override void onAfterInsert() {
        MxTagAssociations.newInstance(this.records)
            .assignOpportunityLookUpOnInsertOrUpdateWhenAccountLookupIsPresent();
        MxTagAssociations.newInstance(this.records).createMxTagAssociationsOnParentAccount();
    }
    /**
     * @description Called to perform on after update processing
     * @param existingRecords - The map of old requests
     */
    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        MxTagAssociations.newInstance(this.records)
            .updateOpportunityLookUpOnMxTagAssociationUpdate(existingRecords);
        MxTagAssociations.newInstance(this.records)
            .assignOpportunityLookUpOnInsertOrUpdateWhenAccountLookupIsPresent();
    }

    /**
     * @description Called to perform on after delete processing
     */
    public override void onAfterDelete() {
        MxTagAssociations.newInstance(existingRecords.values())
            .updateOpportunityLookUpOnMxTagAssociationDelete();
        OpportunitiesService.concatenateMxTagsOnSObjects(existingRecords.values());
    }
}