sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/Mx_Fraud_Document__c.object-meta.xml
<CustomObject>
    <description>LEM-15836: It is used to store all required documents and validation details for fraud verification purposes.</description>
    <label>Mx Fraud Document</label>
    <nameField>
        <displayFormat>MX-{YY}{MM}{DD}{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mx Fraud Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Document_Title__c.field-meta.xml
<CustomField>
    <fullName>Document_Title__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the Content Version&apos;s document title uploaded for fraud verification.</description>
    <label>Document Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It is used to store the current version of the associated Content version document.</description>
    <label>Document Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Country__c.field-meta.xml
<CustomField>
    <fullName>Mx_Country__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It indicates the Store&apos;s Country code Information to store the document. This is controlling field for document type.</description>
    <label>Mx Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Type__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores all document type and dependent on country code. This is not a restricted picklist so it allows user to insert new value.</description>
    <label>Mx Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mx_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ABN Document</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>DBA (Doing Business As)</fullName>
            </value>
            <value>
                <fullName>EIN Verification Letter (147C)</fullName>
            </value>
            <value>
                <fullName>Food License</fullName>
            </value>
            <value>
                <fullName>Form SS-4</fullName>
            </value>
            <value>
                <fullName>HST/GST Document</fullName>
            </value>
            <value>
                <fullName>NZBN Document</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Photo Identification Back</fullName>
            </value>
            <value>
                <fullName>Photo Identification Front</fullName>
            </value>
            <value>
                <fullName>W9 with Schedule C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Notes__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Notes__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the Document Verification Notes or Comments.</description>
    <label>Mx Document Verification Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Document_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Mx_Document_Verification_Status__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the document verification status. The default value is &quot;Pending Review&quot;.</description>
    <label>Mx Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Review</fullName>
                <default>true</default>
                <label>Pending Review</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Mx_Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Mx_Store_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>LEM-15836: It associates the Mx Fraud Document to the Store Account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mx Fraud Documents</relationshipLabel>
    <relationshipName>Mx_Fraud_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>LEM-15836: It stores the Store Id (External Id) based on Content Version associated.</description>
    <label>Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Mx_Fraud_Document__c/fields/Work_Plan__c.field-meta.xml
<CustomField>
    <fullName>Work_Plan__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LEM-15836: It associates the Mx Fraud Document to the Work Plan record.</description>
    <label>Work Plan</label>
    <referenceTo>WorkPlan</referenceTo>
    <relationshipLabel>Mx Fraud Documents</relationshipLabel>
    <relationshipName>Mx_Fraud_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/classes/selectors/MxFraudDocumentsSelector.cls
/**
 * @author Deloitte
 * @date 07/05/2024
 * @description Selector class for Mx Fraud Documents object.
 */
public inherited sharing class MxFraudDocumentsSelector extends fflib_SObjectSelector implements IMxFraudDocumentsSelector {
    /**
     * @description It returns the instance of IMxFraudDocumentsSelector interface.
     * @return IMxFraudDocumentsSelector
     */
    public static IMxFraudDocumentsSelector newInstance() {
        return (IMxFraudDocumentsSelector) Application.Selector.newInstance(
            Mx_Fraud_Document__c.SObjectType
        );
    }

    /**
     * @description Overriding default getSObjectType method.
     * @JIRA# LEM-15836
     * @return SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Mx_Fraud_Document__c.SObjectType;
    }

    /**
     * @description It is used for getting the fields on Mx Fraud Document.
     * @JIRA# LEM-15836
     * @return List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Mx_Fraud_Document__c.Id,
            Mx_Fraud_Document__c.CreatedDate,
            Mx_Fraud_Document__c.Document_Title__c,
            Mx_Fraud_Document__c.Document_Version__c,
            Mx_Fraud_Document__c.LastModifiedDate,
            Mx_Fraud_Document__c.Mx_Country__c,
            Mx_Fraud_Document__c.Mx_Document_Type__c,
            Mx_Fraud_Document__c.Mx_Document_Verification_Notes__c,
            Mx_Fraud_Document__c.Mx_Document_Verification_Status__c,
            Mx_Fraud_Document__c.Mx_Store_Id__c,
            Mx_Fraud_Document__c.Name,
            Mx_Fraud_Document__c.Store_Id__c,
            Mx_Fraud_Document__c.Work_Plan__c
        };
    }

    /**
     * @description It returns Mx Fraud Documents based on passed Store Account Ids.
     * @JIRA# LEM-15836
     * @param storeAccountIds
     * @return List<Mx_Fraud_Document__c>
     */
    public List<Mx_Fraud_Document__c> selectByStoreAccountIds(Set<Id> storeAccountIds) {
        // LEM-18563 - Bypassed CRUD check for this query only during Trigger execution.
        if (Trigger.isExecuting) {
            ignoreCRUD();
        }
        fflib_QueryFactory mxFraudDocumentsQuery = newQueryFactory()
            .setCondition('Mx_Store_Id__c IN :storeAccountIds');
        return (List<Mx_Fraud_Document__c>) Database.query(mxFraudDocumentsQuery.toSOQL());
    }
}